### ISSUE TITLE
Wrong IRC colors in ZKL

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1]
ZKL seems to display wrong colors in responce to mIRC-style caret-notation formatting.

For instance, ^C04 becomes blueish, while it should be red or dark-red.

This is in particular significant in relation to Github IRC service messages, which lose a lot of readability this way.

**Comment by abma** [comment]
@Anarchid 

uhm...?

**Comment by Anarchid** [comment]
Webhook tesitng. Sorry.
