### ISSUE TITLE
Url tag on forum broken for certain links

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1009]
http://test.zero-k.info/Forum/Thread/22244?postID=154978 -- proof

Urls without http or https before them lead to the url http://test.zero-k.info/Forum/Thread/[link], which then errors out with the following message:

The parameters dictionary contains a null entry for parameter 'id' of non-nullable type 'System.Int32' for method 'System.Web.Mvc.ActionResult Thread(Int32, System.Nullable`1[System.Int32])' in 'ZeroKWeb.Controllers.ForumController'. An optional parameter must be a reference type, a nullable type, or be declared as an optional parameter.
Parameter name: parameters

**Comment by Licho1** [comment]
tested, fixed
