### ISSUE TITLE
(forum) linking to posts on maps  & replays always goes to first post

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1011]
"Link to this post" does work in forum, but does not work in comments on maps and replays.
It always goes to first page.

replays:
This link http://zero-k.info/Battles/Detail/259883#94467 should go to the first post on page 2.
(Kyubey: "cough wrecks contain 40% of the units metal cost cough")

maps:
This link http://zero-k.info/Maps/Detail/21387#50455 should go to  page 3, to some post by Googlefrog.
(gf:  "How about trololo hour? A single hour.")

Firefox

**Comment by CrazyEddieTK** [comment]
Same happens in Chrome.
