### ISSUE TITLE
(forum) quote not working when quoted text contains > <

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1012]
http://zero-k.info/PostHistory/Index/155920
broken tag

http://zero-k.info/Forum/Thread/20993?postID=155921#155921
contains text, but text is invisible

http://zero-k.info/Forum/Thread/20993?postID=155922#155922
broken tag

**Comment by Licho1** [comment]
works for me now with stuff like [quote] > asdas < blah > <asdas >asda</> [/quote]
