### ISSUE TITLE
newbies cannot exit own game

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#1013]
seems like every new player has springie lvl 1 ... you need springie lvl 2 to exit I think. remove exit for bigger games might be okay. But they should be able to exit own game or?

**Comment by knorker** [comment]
new accounts start with lvl 0

**Comment by Jamanno** [comment]
sorry, I meant springiee level.

**Comment by sprunk** [comment]
in your own room you are level 3
