### ISSUE TITLE
seperate elo from host

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#1014]
imagine serious host will work out.

Everyone can dump his elo on all welcome and play serious... ––– bad idea

Inflect elo for host types. Is this hard to invent on database?

**Comment by CrazyEddieTK** [comment]
Even better:

a) do not count non-serious host games for elo, and
b) do not balance the not-serious host

Let the !balance command assign teams randomly in not-serious. If people want to play games where the sides are balanced, let them come to the serious room and abide by the serious rules (whatever those are).

**Comment by Jamanno** [comment]
The balance is needed for all welcome... despite it won't be 95 % because of elo dumping. There are possibilities when all high elo players are balanced into one team which would be very bad.
The idea was I wouldn't care on serious host to have a serious game when I know it is not really balanced because some players will lower their elo on purpose on all welcome

**Comment by Jamanno** [comment]
So? 
Serious host makes really no sense when you do have seperate elo. If not I do not see a reason why 1 vs 1 should have seperated elo

**Comment by Licho1** [comment]
hosts gone
