### ISSUE TITLE
springiee helper lines for infolog

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#1016]
!infolog
gives short information about where to find infolog etc.

**Comment by db81** [comment]
As far as I know ZKL has a button already to open infolog. SWL has a button that puts the infolog on springpaste and gives you the link. I think that's the direction we should be going, instead of adding even more text !commands.

**Comment by sprunk** [comment]
Settings -> Game Diagnostic Log

Having a !command won't help because newbies won't know about the command.
