### ISSUE TITLE
Non-ASCII characters get relayed as question marks from game to springie battle chat

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K-Infrastructure#1020]
Spring and Springie apparently use different unicode standards. Almost certain it's UTF8 vs UTF16. Anyway chat between ZK in game and Springie is not compatible once you have got out of English charset. Other chars get back and forth as "?" signs. Since it's impractical to fix it on spring side, Springie side should rather be fixed.

**Comment by db81** [comment]
You're talking about question marks in battleroom relay messages. This is done by Springie, nothing to do with ZKL.
