### ISSUE TITLE
Admin subforum

### ISSUE THREAD

**Issue by wagonrepairer** [ZeroK-RTS/Zero-K-Infrastructure#1026]
Make a subforum for admins.

**Comment by sprunk** [comment]
a

**Comment by DeinFreund** [comment]
One for freunds as well please.

**Comment by knorker** [comment]
use the clans system instead. it is not needed for anything else. make clan "admins" with password, all join, tada.

**Comment by Licho1** [comment]
I don't think we need an admin subforum.
