### ISSUE TITLE
battle with two wieners

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1031]
http://zero-k.info/Battles/Detail/412933
website shows both team as winners. Replay shows north team as winner.

http://zero-k.info/Battles/Detail/413080
website shows both team as winners, (did not look replay)

**Comment by sprangg** [comment]
Rafal[ZK] had an observation that this happens when one player in losing team never connects.

**Comment by vladmihaisima** [comment]
And more:
http://zero-k.info/Battles/Detail/430182
Team 1 is winner.
