### ISSUE TITLE
bigger webms do not fit forum layout

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#1035]
when you upload random webm to some hoster, forum tries to display full size and cuts video dimensions on forum width.
Would be nice to see something like that:
<video width="320" height="240">
anyone knows how to get those before, something like that? 
http://stackoverflow.com/questions/6856852/html5-video-height-and-width-through-javascript

**Comment by mojjj** [comment]
if you make the surrounding container have attribute 
maxwidth=100%
the video is made fit into the outer box from the forum.

is this the desired behaviour you mean?

when i originally wrote the webm replacer, i had this implemented. someone removed it obviously. some larger videos are not displayed completely for me.
