### ISSUE TITLE
New website font cannot be made bold

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1040]
One of the words on this screenshot has `[b]` tags around it. The cancelable upvote "+1" has a `font-weight:bold` style rule. The effect is identical for me on a Mac: doodley-squat.
![screen shot 2016-05-13 at 14 15 29](https://cloud.githubusercontent.com/assets/3822768/15246426/6cf1d830-1915-11e6-8bb4-0eaf42e873d6.png)

**Comment by db81** [comment]
Works for me:
![open-sans-semi-bold](https://cloud.githubusercontent.com/assets/2241548/15246609/88916d80-1951-11e6-88e5-a07aef1bafff.png)

**Comment by Anarchid** [comment]
What's your os/browser? Mine was Mac/Chrome, so maybe this is os-specific.

The `font-family: os, sans-serif` is suggestive enough, i guess.

**Comment by Skasi** [comment]
Also works for me, looks exactly like for db81.

**Comment by ashdnazg** [comment]
win7 chrome here, everything is bold.

**Comment by Licho1** [comment]
I picked "heavier" font for better readability.We can switch to regular. Goal is to have identical font in zkl and site.

**Comment by db81** [comment]
It's fine to have different fonts for UI components and for textual content. If ZKL is still a browser that opens zero-k.info we can change the font for forum posts and wiki pages while keeping the UI font consistent.

**Comment by KingRaptor** [comment]
Also fails to distinguish bold and non-bold on my Chrome + Win7.

Given that this is a moderately serious defect, I'm in favor of reverting the offending commit if someone doesn't have a fix.

**Comment by Licho1** [comment]
Do not revert the commit jesus. Its a big change in other areas too. Just change the font!! It exsists as semi-bold, bold and standard weight. Put in standard weight.

**Comment by KingRaptor** [comment]
83ee33135edc064574027369abb8478408d5c56d (can be seen on [test.zero-k.info](http://test.zero-k.info))

Bold works again. Not sure if like font appearance.
e normal font feels kinda "thin"...

**Comment by Licho1** [comment]
Please also do the same change to ZKL. Goal is to have identical font in both places.

**Comment by Licho1** [comment]
fixed by KR
