### ISSUE TITLE
Campaign progress broken

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1044]
http://zero-k.info/Campaign

Planets do not get tagged as done after passing the relevant mission.

**Comment by KingRaptor** [comment]
ZKL's infolog parser appears to be non-functional when playing missions.

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/71f5da9922f7b7f9082d3f297b422013694f4504/Shared/LobbyClient/Spring.cs#L386
```C#
private void ParseInfolog(string text, bool isCrash)
{
    Trace.TraceWarning("Parsing infolog");
```

says nothing in ZKL compiled from master.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
