### ISSUE TITLE
[Test site] XP Bar broken

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1049]
![testsite](https://cloud.githubusercontent.com/assets/7841201/15436712/2f85f6bc-1e78-11e6-9a79-d0e51028d2c1.PNG)

**Comment by db81** [comment]
Browser, OS? Looks fine here (Firefox on linux).

**Comment by ArchShaman** [comment]
Firefox (Latest?) on windows 7 64bit

**Comment by KingRaptor** [comment]
My level 0 smurf has a sliced bar at the filled/unfilled intersection (which also happens to be the zero point), but on my normal account it's fine.

Chrome 50.0.2661.102 m on Win7 32 bit

**Comment by ArchShaman** [comment]
Took a look at it today, seems fixed on my end.

**Comment by KingRaptor** [comment]
No longer getting it either. Closing!
