### ISSUE TITLE
Youtube embedding doesn't work with HTTPS URLs.

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1052]
```http://www.youtube.com/watch?v=eNtT9JS2jxM``` causes a youtube video to be embedded in forum posts or wiki, but ```https://www.youtube.com/watch?v=eNtT9JS2jxM``` results in a regular link.

**Comment by knorker** [comment]
links of this format do not work either:
https://youtu.be/hzPpWInAiOg
(that is the format you get using rightclick on youtube-player  -> "copy video url")

a video or youtube tag or something would be better than automatically embedding every yt link.
