### ISSUE TITLE
(forum/wiki) Wiki-page links do not appear in mouse-over-preview

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1053]
![zk_wikipagenotpreview](https://cloud.githubusercontent.com/assets/3044855/15574901/48a6ca5e-2350-11e6-99e6-b2362563d91b.png)

http://zero-k.info/Forum/Thread/22522?postID=158359#158359

**Comment by Licho1** [comment]
seems to be working or i dont understand.

**Comment by knorker** [comment]
See http://zero-k.info/Forum/Thread/22522?postID=158359#158359
The post text is "Thank you for following the TestingSchedule." with "TestingSchedule" being a link to http://zero-k.info/Wiki/TestingSchedule wiki page.
The link does not appear in mouse-over-preview of topic list.
"Thank you for following the _____."

**Comment by Licho1** [comment]
Oh the previews are only meant for threads/wiki posts linked from main page. They werent supposed to work in general posts elsewhere though i suppose they might work there.
