### ISSUE TITLE
(wiki/forum) "loading" icon after using preview-function

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1056]
After using the preview-function and closing the preview-function, some useless "loading" animation sometimes stays in middle of screen:
![zkpreview_not_going_away](https://cloud.githubusercontent.com/assets/3044855/15575223/feb33d2c-2351-11e6-820d-e4b42e87d206.png)

Mildly related for long pages (wiki) the preview-function is annoying to use because:
- it always previews whole page, not just edited wikipage-section
- the preview is smaller than actual forum/wiki, resulting in horinzontal scrollbar at bottom and different formating (line breaks etc)
- the scrolling and automatic reloading is annoying

Firefox.

**Comment by Licho1** [comment]
fixed by disabling preview refresh

**Comment by knorker** [comment]
this still (or again) happens
Firefox

**Comment by db81** [comment]
Yeah still not fixed.

**Comment by Licho1** [comment]
fixed now
