### ISSUE TITLE
(lobby/website) when watching replays or playing missions: "lobby program is not running" / "must be logged in" 

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1057]
These messages randomly appear when trying to watch replays:
- "lobby program is not running" (when clicking "watch replay now" in lobby)
-  "must be logged in"

1) start lobby
2) do not log in
3) find a replay (forum, battles list etc)
4) click "watch replay now"
5) lobby says "Must be logged in" 
(Why would log-in be nessecary?)

In fact it is not nessecary to be logged in to watch replays: just have to wildly click around the lobby and eventually the replay will launch. Seems that check can be removed...

**Comment by KingRaptor** [comment]
The 'watch replay' (and 'play mission') commands appear to be piped through the ZK lobby server (e.g. see [this](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/Controllers/LobbyController.cs#L19) -> [this](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyServer/ZkLobbyServer.cs#L182)). I can't say how easy it'd be to change this while retaining the one-click replay watching functionality.

**Comment by knorker** [comment]
yes, play mission has the same problem:

clicking "play now" on mission-overview http://zero-k.info/Missions = "Your lobby program is not running"
clicking "play now" on a mission-page http://zero-k.info/Missions/Detail/140 = it works.

**Comment by knorker** [comment]
> have to wildly click around the lobby and eventually the replay will launch.

since last lobby update that does not work anymore.
can not watch replays at all.

**Comment by Licho1** [comment]
fixed

**Comment by Licho1** [comment]
Its needed because without ZKL connection, site cannot talk to zkl and send it command to download demo properly.

**Comment by knorker** [comment]
it sometimes downloaded and played the demo correctly in past. (i have been unable to log in since some months)

**Comment by Licho1** [comment]
In the past browser was wired and urls were monitored for. This turned to be unreliable, due to different escaping of different browser versions, so instead commands are passed through lobby connection now.

Also click monitoring did not work with external browser obviously.
