### ISSUE TITLE
(lobby/browser)  zkLobby does not display images in forum

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1059]
As posted by @DeinFreund in http://zero-k.info/Forum/Thread/20328?postID=158371#158371

zkLobby does not display images in forum

**Comment by DeinFreund** [comment]
I think this is a problem of internet explorer, not the lobby.

**Comment by knorker** [comment]
I think zkl uses internet explorer. end result is bug in any way.
maybe post system info / IE version, usual blabla..

**Comment by DeinFreund** [comment]
Win 7 x64 SP 1, came with IE 8 preinstalled (which remains the currently installed version)

**Comment by Licho1** [comment]
Issue of outdated IE core. Not possible to fix easilly (shot of switching to chromium)

**Comment by knorker** [comment]
detect it and show info/warning to update?

**Comment by Licho1** [comment]
What is your OS version?

**Comment by knorker** [comment]
win 7 64bit

**Comment by Licho1** [comment]
wow.. erm..thats unexpected.. any chance you got something weird installed in/with IE? With default untouched unupdated IE it seems to work there.
