### ISSUE TITLE
forum handles long words badly

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1060]
http://i.imgur.com/UP7qFcD.png

http://zero-k.info/Forum/Thread/22539

**Comment by Skasi** [comment]
There's a bigger issue in than that trying to post long titles leads to error message. http://i.imgur.com/KDvCPbT.png

This would require a maximum length option for the input field. Can be done via an HTML attribute iirc.

The lack of line breaks can be fixed via CSS:
word-wrap: break-word;

This will also be needed for the "posted thread" section. http://i.imgur.com/Abyfcyj.png
word-wrap: break-word;
on top of that something to limit the width to the parent element's borders is necessary:
max-width: 668px;
in combination with
box-sizing: border-box;
is pretty close, but not exactly as it should look. Still needs some fine tuning.
