### ISSUE TITLE
Springies don't host new stables or test versions

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1061]
This is a pretty dire bug. Why even have gameside development.

**Comment by db81** [comment]
#1045

**Comment by db81** [comment]
Restarting springies didn't seem to fix it. After restarting site they still hosted the old version at first but then updated after a delay. So maybe infra only discovers new mods on startup or something in that vein.

**Comment by db81** [comment]
After the updating loop fix restarting springies makes them update.

**Comment by Licho1** [comment]
should be fixed in test/master

**Comment by db81** [comment]
I just tested with test springies and not only did they not pick up a new zk:test version, they didn't even rehost from the last version they had, which worked before.

To clarify, test springie was down for some time so when I started it, it was using some old zk version, then it picked up the new version (as it always did on start before the fix), but didn't rehost to it without !rehost. Then I pushed a new zk:test version but it never saw it.

**Comment by Licho1** [comment]
you tested on test server or live server? Change is not deployed.

**Comment by db81** [comment]
On test.zero-k.info, the one with ZKLS port 8202, springie from ```projekty/test.zero-k.info/springie/```

**Comment by Licho1** [comment]
fixed in master, !mod zk:test works.
