### ISSUE TITLE
Disable !resign for the first 8 minutes.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1066]
The !resign command should not be available within the first 8 minutes of the game starting. This may as well be done in Springie time for simplicity. If you pause the game for 8 minutes then I guess you get to resign at frame 0.

**Comment by Aquanim** [comment]
I feel like there are legitimate causes to resign before 8 minutes in some games... that's actually quite a while.

A scorcher rush on Red Comet can functionally end a game in under two minutes (as a generous estimate).

I agree that there is an issue here but I am unsure that this is the best solution. A shorter duration (possibly based on game size) or some other approach should be at least considered.

**Comment by Anarchid** [comment]
Period of no resign should be equal to period of rating mercy.

**Comment by GoogleFrog** [comment]
The 8 minutes would be more like 4 ingame minutes once everyone loads and the game starts. I think it is ok for rare rush cases to not be covered by resign voting. If you resign in the first minute but the rest of your team does not then there is the risk that they will keep on playing.

**Comment by Licho1** [comment]
springie knows when game actually starts.

**Comment by GoogleFrog** [comment]
What did you do? Eight ingame minutes is far too long.

**Comment by Licho1** [comment]
It's tied to elo timer, which is atm 60s so its 60s

**Comment by GoogleFrog** [comment]
Good.
