### ISSUE TITLE
ZKL cannot download dev engines

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1069]
This seems recent, I've seen at least two occurrences of first time players saying they can't download the engine. I haven't checked whether it reliably fails on a clean install.

ZKL log courtesy of LoneRanger: http://pastebin.com/1VPkwcEL

**Comment by Aquanim** [comment]
I can replicate this by moving the engine files away and restarting ZKL.

**Comment by ashdnazg** [comment]
@Aquanim did you check if the same happens when you move the 100.0 dir?

**Comment by KingRaptor** [comment]
Fixed in b9d204eee3af802c5cf02e39de5854a633a778e1, but see #1070

**Comment by Aquanim** [comment]
Bit late now I suppose, but 100.0 and 101.0 were both downloadable.

**Comment by db81** [comment]
Did anyone even try to bring this up with whoever maintains spring buildbot (@abma)? It would be easier to just get them to restore the zip option, instead of jumping through hoops.

**Comment by KingRaptor** [comment]
I didn't ask because if I were Spring dev my response would be "we already have a perfectly good .7z, everyone and their mom can use that format these days, we're not using more disk space on the server just because ZK can't make changes."
