### ISSUE TITLE
Can't post lists in forum

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1073]
> The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.ForumPostWords_dbo.Words_WordID". The conflict occurred in database "zero-k", table "dbo.Words", column 'WordID'.
> The statement has been terminated.

**Comment by DeinFreund** [comment]
Here's what I'm trying to put in my post: http://hastebin.com/imepubusas.md

If I paste anything more than the first 3 lines I get the cited error. But if I change the numbers after the names I can sometimes succeed at posting the first 2 entries of the list.

**Comment by Licho1** [comment]
Interesting, it seems some issue with search indexer.

**Comment by Licho1** [comment]
I am unable to replicate, it seems someone else inserted some new same words at the same time as you posted it. It should work.
