### ISSUE TITLE
(wiki) voting on wiki-pages makes no sense, disable

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1074]
It is possible to upvote/down avatar-wiki pages.
Since (ideally) a page is the resulting work of several peoplers, it makes no sense to up/down vote only the first editor.

**Comment by Skasi** [comment]
Voting does make sense - it helps ensure quality of wiki articles and allows people to mark pages that misinform, have bad formatting, etc. Similarly, users will be able to highlight well-written articles.

That said, wiki pages and their votes should not be linked to a user.

**Comment by knorker** [comment]
content of page changes, votes do not. even if peoplers always were to update their votes (which is unrealistic to expect) then votes of inactive peoplers would stay. useless confusion feature.

**Comment by Licho1** [comment]
external wiki used now
