### ISSUE TITLE
[Forum] Tooltips don't handle apostrophes or line breaks

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#1075]
Bit of a minor issue (since it's kinda abusing the tooltip system), but using tooltips as footnotes becomes really awkward to write without possessives or contractions, and not being able to line break somewhat limits their usefulness.

**Comment by sprunk** [comment]
Line breaks are possible (use \n)

**Comment by Licho1** [comment]
Which tooltips? User and forum post tooltips are ok.

**Comment by dvr333** [comment]
Forum tooltips, that is [tooltip] tags.

**Comment by Licho1** [comment]
I dont recall adding that tag...

**Comment by Licho1** [comment]
Oh it is <br/> you can add simple html into that place.
