### ISSUE TITLE
[Forum] Player @ Tags break on apostrophes

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#1076]
When using @ tags for players (and probably also battles and maps) doing "@PlayerName's" doesn't work, requiring spacing out the apostrophe, which is really awkward.

**Comment by knorker** [comment]
Not just apostrophes. Other special chars following playername fail too.
Examples:

"I wish I was pro like @PlayerName....."
All the ... points will not show.

"I wish I was pro like @PlayerName!"
The ! does not show.

"Why can I not be pro like @PlayerName?"
The ? does not show.

**Comment by knorker** [comment]
until fix the trick is to add some empty bbcode between playername and apostrophe:
  playername[i][/i]'s

**Comment by Licho1** [comment]
fixed
