### ISSUE TITLE
ZKL installer makes user accept old Code of Conduct before installing

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1080]
By "old" I mean the verbose one before GoogleFrog slimmed it down. Also the checkbox has the wrong grammar ("I accept these code of conduct").

Why does installer have the CoC in the first place to begin with?

**Comment by Licho1** [comment]
No idea ... i reused something started by xponen it can be removed.

**Comment by Licho1** [comment]
fixed
