### ISSUE TITLE
Offline skirmisher should be brought back

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#1086]
Possibly added as a SIngleplayer tab or such and with an improved interface. I am sure some potential players occasionally want to be able to play without being logged in.

**Comment by KingRaptor** [comment]
b04749ce096b135079a0f73d2d580ddcc4435536 suggests it'll be brought back once its code is cleaned up.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
