### ISSUE TITLE
Game won't start

### ISSUE THREAD

**Issue by ParzivalX** [ZeroK-RTS/Zero-K-Infrastructure#1088]
On new zero-k lobby games will not start. I can press start button, ZKL freezes, crashes, and has to be killed. Since there is no game there is no error log (That I can Find).

**Comment by Skasi** [comment]
I am pretty sure 99% of crashes that happen are Steam-related. I haven't had more than perhaps a single crash (if any) in 1000+ hours of ZKL usage with Steam closed.

**Comment by ParzivalX** [comment]
update: I tried with steam off. It was autohost CAI room. No one else experienced the same problem. The problem happens always regardless of modoptions, players, AIs, and maps.

**Comment by db81** [comment]
springweblobby/swl-website#55 seems to suggest it's not endemic to ZKL and is probably a spring problem, so at least look at the infolog.

**Comment by ParzivalX** [comment]
Actually, it most likely is a ZKL thing because ZK now plays fine on SWL.

**Comment by db81** [comment]
I think there's a button in settings that lets you open ZeroKErrors.log or whatever it's called. Pastebin or attach here.

**Comment by db81** [comment]
@ParzivalX no luck getting the log?

**Comment by ParzivalX** [comment]
Zero K now mysteriously works. I don't know why.

Protip, let web lobby try to start ZK for a few hours, that seems to help.

**Comment by db81** [comment]
I would guess it's the latest round of hotfixes (#1104), except there's nothing relevant there.
