### ISSUE TITLE
[Lobby] Lobby has rather large minimum size

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#1090]
While I get that the lobby is for playing, so it should generally be front and center, the minimum size it can be resized to (1280x1024) is pretty much the size of my second monitor, meaning that if I'm sitting and chatting, I basically have to just have it background to everything else, rather than having it small in a corner.

Vertical resizing is more important for this than horizontal. Something like ~~640x960~~ 960x640 minimum resolution would be fine.

**Comment by db81** [comment]
I think the minimum size should be at least 1024x768 to avoid things like http://zero-k.info/Forum/Post/160360#160360.

**Comment by dvr333** [comment]
You mean at most 1024x768, because it's currently 1280x1024.

Also, I got my dimensions mixed up in the first comment, I should have said 960x640 would be fine.

**Comment by db81** [comment]
Apparently even if you can resize it to 1280, it will cut off half of the UI because nothing scales: http://zero-k.info/Forum/Post/160384#160384

**Comment by Anarchid** [comment]
I have a pillbox style screen on my laptop and i am unable to even chat, because the buttons are cut off.

Maximize/minimize does nothing.

**Comment by Licho1** [comment]
changed to 1024x700
