### ISSUE TITLE
ZKL should remember lobbyclient fullscreen state

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1091]
(and windowed resolution/position as well)

**Comment by Licho1** [comment]
this was removed intentionally .. fullscreen giant buttons seems to be the wanted "standard" way

**Comment by KingRaptor** [comment]
But if someone decides they want the "non-standard" windowed way they presumably want it to stay that way at next run.

**Comment by Skasi** [comment]
Yes, definitely. I'm annoyed at having to leave fullscreen again everytime I start ZKL.
