### ISSUE TITLE
ZKL popup windows hidden behind lobby

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#1093]
Lobby error messages such as "Account 'Honki' does not exist yet, do you want to create it? [Yes] [No]"  are hidden behind the fullscreen lobby and can not be reached easily. This can cause a lot of confusion because the lobby does not respond to any input.

**Comment by KingRaptor** [comment]
Note: I couldn't reproduce this issue when testing it using the existing infra code, so I can't be sure it's fixed.

If anyone is interested in testing compiled version or after next hotfix release, some error messages I need to make sure pop up in the right place:
- "Do you want to set low settings?" (launch a game on Springie, end process spring.exe)
- Datadir selection (Settings -> General -> Content data folder: enter a directory that doesn't exist (NOT BLANK))
- Reset settings prompt (Settings -> Reset ingame)

**Comment by KingRaptor** [comment]
http://wishmesh.com/2012/12/c-net-messagebox-is-hidden-behind-the-form/

Having a hard time debugging this...
