### ISSUE TITLE
ZKL doesn't remember password after first change

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#1094]
Sooo I used to have my account name and password stored and remembered just nice (eg. Username: Skasi, Password: Honk). Then I went to SETTINGS and changed some things (eg. Username: Skasi, Password: Honk1). Now when I want to login obviously ZKL tells me my password is incorrect and I input the correct password. The problem is that this password is not stored. ZKL keeps remembering my wrong password and even going to SETTINGS and changing everything back (eg. Username: Skasi, Password: Honk) does not solve the problem.

**Comment by knorker** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/966
