### ISSUE TITLE
(lobby) lobby does not show version number anymore

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1095]
version number used to be in window's title bar.
now can not find. will be annoying for bug reports. unsure for players if they have most up-to-date version.

/edit
visible in window title when turning off fullscreen

**Comment by KingRaptor** [comment]
(my original plan was to add an About button in top right, but I don't have an icon)

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
