### ISSUE TITLE
(lobby) no progress bars for downloads

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1096]
Just says "starting replay xgvxcvx.sdf" but nothing about progress of files download.

**Comment by dvr333** [comment]
Download progress could be done unintrusively with a small progress bar (i.e. not stretching the whole width of the lobby, probably no wider than the player list and only about 7 player names tall) window for all the downloads. 

As a side thing, having the "X" replaced with the total download percentage tells everyone how close others are to completion, which would help a lot with starting larger games.
