### ISSUE TITLE
(lobby) after update the player-name field was empty but a password was entered

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1098]
![zk_after_update_password_filled_in_no_username](https://cloud.githubusercontent.com/assets/3044855/16704685/d5e12e22-457a-11e6-8c44-36b6a31366c3.png)

**Comment by Licho1** [comment]
this is due to password saving bug which did not overwrite full password. It should not happen in latest zkl
