### ISSUE TITLE
(lobby) Adv. Settings -> Edit keybinds does not work

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1099]
flashes a window that instantly disappears

**Comment by KingRaptor** [comment]
It opens `zk_keys.lua` using the default text editor, which then presumably runs into #1093.

**Comment by knorker** [comment]
The other buttons that open textfiles all work. (for ex edit LUPS setting, engine settings etc)
Only this one does not work.

**Comment by knorker** [comment]
Maybe it does not up with the "default text editor" but with the "default program"
Which for .lua files me is the Lua runtime thing.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
