### ISSUE TITLE
(github wiki)"ZK Infrastructure zero k.info Website Development" page on google.code is gone

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1103]
No idea if there was anything important:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/wiki/ZK-Infrastructure----zero-k.info-Website-Development

" old document is on https://code.google.com/p/zero-k/wiki/Developing#Modifying_infrastructure/tools "

it's gone lol

**Comment by KingRaptor** [comment]
It's [on avatarwiki](http://zero-k.info/Wiki/Developing) for now.

(made a note to self to port to MediaWiki)
