### ISSUE TITLE
(lobby)  [ArgumentException: Invalid salt Parameter name: salt]

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1107]
Server Error in '/' Application.

Invalid salt
Parameter name: salt 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.ArgumentException: Invalid salt
Parameter name: salt

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  

Stack Trace: 

[ArgumentException: Invalid salt
Parameter name: salt]
   BCrypt.Net.BCrypt.HashPassword(String input, String salt) +621
   ZkData.Account.AccountVerify(ZkDataContext db, String login, String passwordHash) +336
   ZkData.AuthServiceClient.VerifyAccountHashed(String login, String passwordHash) +104
   ZeroKWeb.MvcApplication.MvcApplication_PostAuthenticateRequest(Object sender, EventArgs e) +471
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

  

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.1069.1

**Comment by db81** [comment]
Same as #601?

**Comment by knorker** [comment]
no idea.
I do not understand the post https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/601#issuecomment-94978006 or why #601 was closed

**Comment by Licho1** [comment]
Unable to replicate it should happen only in isolated accounts with no pw (imports from old uberserver).
Such need to be fixed account by account.
