### ISSUE TITLE
Lobby full screen messes up spring full screen upon alt+tab

### ISSUE THREAD

**Issue by Flipstip** [ZeroK-RTS/Zero-K-Infrastructure#1110]
I did:
use lobby in full screen mode
start game (spring in fullscreen mode)
alt+tab from spring.exe to something else (not sure if it has to be zk-lobby)
alt+tab back
→ spring.exe window is shifted downwards: on the top of the screen the windows behind it are visible
(a zone as big as the top bar of a window, presumably the part that zk-lobby wants to hide in full-screen mode)
the bottom of the spring.exe window is "below" the screen: scrolling by moving the cursor near the edge doesn't work anymore (since the cursor can only move to the bottom of the screen).

**Comment by Flipstip** [comment]
btw specs:
Spring 102.0
Build Environment: boost-105500, GNU libstdc++ version 20130531
Compiler Version:  gcc-4.8.1
Operating System:  Microsoft Windows
Microsoft Home Premium Edition, 64-bit (build 9200)
Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz; 16273MB RAM, 18705MB pagefile

I can reproduce and get infolog if needed.

**Comment by Flipstip** [comment]
It only seems to happen when alt+tabbing during loading of spring.

**Comment by Licho1** [comment]
fixed
