### ISSUE TITLE
After migration mediawiki does not work 

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1123]
[4a9aa572] 2016-07-27 14:59:40: Fatal exception of type MWException

DB is migrated with identical account

**Comment by KingRaptor** [comment]
https://www.mediawiki.org/wiki/Topic:Rlsy8eezuik84hb9

I just changed [$wgMainCacheType](https://www.mediawiki.org/wiki/Manual:%24wgMainCacheType) to `CACHE_ANYTHING` so now it works, but if performance issues are involved we might want to relook at this.
