### ISSUE TITLE
Send battle type

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1126]
BattleAdded should contain parameters which tell the lobby program what type of game is supported. This information would then be used to provide a more informative tooltip and to disable irrelevant parts of the UI. For example:
 * If a battle disallows bots then the "Add AI" button would be removed or inactive.
 * If a battle autobalances then the UI could make it clear that selecting your team is impossible.
 * If a battle is limited to two teams then adding extra teams would not be possible.

Here are some new keys. Perhaps think of more:
 * autobalance: bool
 * allowBots: bool
 * teamLimit: number

See https://github.com/Spring-Chobby/Chobby/issues/201

**Comment by Licho1** [comment]
Server now sends game type (in master).  

Game type determines rules:

custom = anything goes, team count limited by map (server going to send slot names too)
teams = restricted maps, no mod options, no team selection, no bots
1v1 = restricted maps, no mod options, no team selection, no bots
chickens = restricted maps, no mod options, no team selection, forced bots (initially bot is added based on map chicken or cai), owner can add/remove bots at will but bots needed to start
planetwars = fully managed, not possible to open new such games from client
mission = fully managed, all humans forced into commshare team 
ffa = restricted maps, no mod options, no team selection, no bots. Slots based on map.

**Comment by Licho1** [comment]
i guess that we can add those flags too - like autobalance, allow bots etc.. keeping open until fully resolved

**Comment by Licho1** [comment]
Closing for now. Battle type works. Will include named slots instead of ally numbers in the future.
