### ISSUE TITLE
Implement server side friends.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1129]
Server side friends are required if we are going to not send all data to all clients. Players want to know when their friends come online so will be sent the full status of all their friends.

See https://github.com/Spring-Chobby/Chobby/commit/13a57061ce47a802906f7de2b06e158599917462#diff-cae57afcf4581091bde85cf54367ddb9R62

**Comment by Licho1** [comment]
wokring on it, it will be generalized "player to player relation" value (none/friend/ignore)

**Comment by gajop** [comment]
Although you probably shouldn't, you can ignore friends
doesn't matter as far as Chobby is concerned though, as long as it's implementable through the API
Chobby doesn't even really care if you make the friendship relation one-sided, although I'd suggest you don't

**Comment by Licho1** [comment]
implemented in master
