### ISSUE TITLE
Where are the mission

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1142]
I want a zip full of missions and startscripts so I can implement local mission launching through Chobby.

**Comment by KingRaptor** [comment]
You want all the currently featured ones I take it?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by KingRaptor** [comment]
Due to #1144 I don't care run my mission fetcher code again, so [here's](https://www.dropbox.com/s/sb6qsda221rn1f3/missionExport.zip?dl=0) just one mission for now.

**Comment by Licho1** [comment]
Missions exist at 
http://zero-k.info/Missions/File?name=140
etc number is the ID of mission which is diplayed in its url.
