### ISSUE TITLE
zkl doesnt start (win 8.1)

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K-Infrastructure#1150]
errorlog says this: 

FATAL: System.InvalidOperationException: Der Threadausnahmemodus kann nicht mehr geändert werden, sobald Steuerelemente in dem Thread erstellt wurden.
   bei System.Windows.Forms.NativeWindow.SetUnhandledExceptionModeInternal(UnhandledExceptionMode mode, Boolean threadScope)
   bei System.Windows.Forms.Application.SetUnhandledExceptionMode(UnhandledExceptionMode mode, Boolean threadScope)
   bei System.Windows.Forms.Application.SetUnhandledExceptionMode(UnhandledExceptionMode mode)
   bei ZeroKLobby.Program.Main(String[] args)

"you cannot change the thread-exception-mode after control elements in the thread have been created."

**Comment by Licho1** [comment]
fixed in master
