### ISSUE TITLE
Can't close ZKL when not logged in

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1170]
The close button doesn't do anything, have to kill it for it to close.

Maybe this error is related: http://hastebin.com/vurisehile.avrasm

**Comment by Licho1** [comment]
odd it works for me, how did it get into disconnected state?

**Comment by DeinFreund** [comment]
I enabled ForgetName and ForgetPassword to stop it from autologin without being able to choose an account.
