### ISSUE TITLE
Springiee error after battle ending

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1171]
> [18:44]  * Nightwatch Poll: Resign team 1? [END:SUCCESS]
> [18:44]  * Nightwatch Team 1 resigned
> [18:44]  * Nightwatch System.NullReferenceException: Object reference not set to an instance of an object.
> [18:44]  * Nightwatch    at ZeroKWeb.SpringieInterface.BattleResultHandler.SubmitSpringBattleResult(SpringBattleContext result, ZkLobbyServer server)

Times in CEST, 2016-09-05

**Comment by Licho1** [comment]
added full debug dump on battle result exception

**Comment by DeinFreund** [comment]
Same error again
http://hastebin.com/ojodotolof.tex
