### ISSUE TITLE
Cannot run custom engine

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#1176]
Nightwatch Host downloading the engine
Nightwatch Host engine download failed

This is what I'm running locally:
~/spring-static/spring_\{develop\}103.0.1-96-g5ac4b4c_minimal-portable-linux64-static/spring
Which is the latest engine at the time of this writing.

**Comment by Licho1** [comment]
To play a custom engine we need to upload it to main site.
I have added this version to the list. If you need other version, ask any admin
