### ISSUE TITLE
[Lobby] ZKL cannot join game on Linux Mint 64-bit

### ISSUE THREAD

**Issue by lagerspetz** [ZeroK-RTS/Zero-K-Infrastructure#1186]
Cannot join a game with ZKL.
The lobby shows me the games, and I select one, click spectate, and click rejoin. This is what I get:
![cannot-join-game](https://cloud.githubusercontent.com/assets/1171264/18395163/058b2502-76c6-11e6-9d30-1392d4703036.png)

The log is attached. At the end of the log I also close ZKL.
[zkl-log-cannotjoin.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/464415/zkl-log-cannotjoin.txt)

**Comment by lagerspetz** [comment]
I just noticed that in zk/engine/103.0, all of the spring binaries are missing the exec permission. So I did chmod 755 spring* and the game now runs properly.
Perhaps the archive that ZKL downloads has the wrong permissions on the spring binaries?

**Comment by Licho1** [comment]
chmod u+x is now being executed in test version of zkl, fixed
