### ISSUE TITLE
[Lobby] ZKL does not show chat announcements on Linux Mint 64-bit (same color as background?)

### ISSUE THREAD

**Issue by lagerspetz** [ZeroK-RTS/Zero-K-Infrastructure#1187]
The issue is best described by the invisible chat annoucement text in the following picture:
![cannot-see-chat-announcements](https://cloud.githubusercontent.com/assets/1171264/18395191/27f52c14-76c6-11e6-81a9-b91c397e2d59.png)
I also could not find any settings to change that:
![misplaced-popup-text](https://cloud.githubusercontent.com/assets/1171264/18395214/4b5ab1a6-76c6-11e6-8b2f-ab2254069bb6.png)

**Comment by Licho1** [comment]
this should be fixed now
