### ISSUE TITLE
[Lobby] ZKL shows popup and button text lower than it should on Linux Mint 64-bit

### ISSUE THREAD

**Issue by lagerspetz** [ZeroK-RTS/Zero-K-Infrastructure#1188]
The popup tooltip text for the top buttons (Settings at the top right in this picture), as well as the OK button in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1186 looks lower than it should be:
![misplaced-popup-text](https://cloud.githubusercontent.com/assets/1171264/18395241/7356dbd0-76c6-11e6-891d-48e3222a09a0.png)
This issue is purely visual and does not affect functionality of the lobby.

**Comment by Licho1** [comment]
This is a wontfix, i dont have mint, it works on ubuntu and we are moving to chobby
