### ISSUE TITLE
Nightwatch offline on spring lobby server

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#1189]
as requested by @Anarchid i've changed Nightwatch's password at the spring lobbyserver. now its offline :-|

**Comment by Licho1** [comment]
sigh kingraptor or anarchid please make sure pw in db matches the one on lobbyserver .. i have no idea how it was changed in the past..

**Comment by Licho1** [comment]
fixed by anarchid matching passwords, link now works it seems
