### ISSUE TITLE
MM Server Interface Requirements

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1197]
The matchmaker interface needs the following commands:
 * AreYouReady. We already have a command of this name. The AreYouReady command should be limited to asking players whether they are ready for the match found for them.
 * AreYouReadyUpdate. The server should respond to AreYouReady. This will prompt the UI to stop displaying the accept button. AreYouReadyUpdate should also contain information such as how many other players are ready.
 * AreYouReadyResult. This tells the lobby the result of the attempt the create a battle. The includes whether the battle succeeded or failed. It can send some text with the reason. It could also tell players whether they are blocked from queuing.

MatchMakerStatus should send its information in a readable form. It should at least send the number of the players in the queue as a key.

**Comment by GoogleFrog** [comment]
When AreYouReady is sent the players should also be removed from the queue. Their queue preference should be remembered by the server and reapplied if the appropriate AreYouReadyResult occurs (someone else rejected).

**Comment by Licho1** [comment]
areyou ready changed in 869b7e9c7b1a58cd9af8437f5e28c457874f027a
