### ISSUE TITLE
Start MM battle early

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1198]
If everyone has responded that they are ready for a MM battle the battle should start. Waiting around for an extra 25 seconds is boring and gives the impression that the server is malfunctioning.

**Comment by Licho1** [comment]
It can fail early too

**Comment by GoogleFrog** [comment]
Yes, that can be handled with AreYouReadyResult. However remember that two partially failed battles can potentially be merged together after the 30s are up. The matchmaker should check whether a merge is possible at each time someone rejects the match. If no merge is possible then AreYouReadyResult should be sent to say that it failed by rejection.
