### ISSUE TITLE
RequestJoin for battles without being in the battleroom

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1203]
I forget whether it was possible to rejoin battles without being in the battleroom for the battle. This can be used for spectating and rejoining dropped battles. The ticket is a reminder to implement it if it is not already implemented.

**Comment by Licho1** [comment]
You can send  RequestConnectSpring message to rejoin battle. However for consistency purposes it is atm only possible after you join the room.
