### ISSUE TITLE
Make rank progression nicer

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1205]
Rank progression should have players gain a new rank image at levels 5, 10, 20, 35, 50, 75 and 100.

**Comment by DeinFreund** [comment]
The highest currently occupied ELO bracket is exclusive to two active players, which fits the hard-to-achieve 99th percentile role. 

High XP ranks will never be that rare, but multiple posters have proposed limiting them to the top 10-50. How about going with 10, 20, 35, 50, 75, 100, 125 instead?

Anyway I think either of these systems would be easier to grasp than the logarithmic formula, so if you think the level 5 levelup achievement is needed, just go with that.

**Comment by Licho1** [comment]
We could go fibonacci way - sum of previous two levels with seed 5,10
5, 10, 15, 25, 40, 65, 105

**Comment by GoogleFrog** [comment]
My progression fits for a variety of reasons. The numbers 50, 75 and 100 are common milestones. The current rank icons have a visual grouping of 3, 2, 2, 1:
 * The first three ranks are just upside down Vs.
 * The next two ranks are upside down Vs with a U at the bottom.
 * The next two rank share a small star with a U at the bottom.
 * The final rank is just a large star.

My progression reflects this similarity with a gap of 15 for the two ranks in the second group and a gap of 25 for the two ranks in the third group. It also has the side effect that you gain a small star at level 50 and a large star at level 100.

The low end rank progression of 5, 10 and 20 is to allow people to easily distinguish between a new player and really new player. This distinction is important when discussing many topics such as technical help or game advice. Someone with level 5 has managed to run ZK.

**Comment by Licho1** [comment]
Ok lets use your progression then..
