### ISSUE TITLE
Matchmaker ban should send OnMatchMakerStatus

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1207]
OnMatchMakerStatus should be sent when you receive a ban message. This should tell the client that they are not in the match and not in matchmaking. OnMatchMakerStatus could send RemainingBanTime as a parameter

**Comment by Licho1** [comment]
When you are banned you are by definition not in queue.. message of status with enabled=false always precedes ban.

**Comment by GoogleFrog** [comment]
I don't have the infolog but if I recall correctly I sent MatchMakerQueueRequest and only received a Say containing text about being banned in return. What are the commands that tell me when I am banned and unbanned? Newly connected clients need to know whether they are banned, told when it will expire and sent a message from the server when it does expire.

**Comment by Licho1** [comment]
i can add it.. however do they need to know? You can be banned form battle room as well and you learn it if you join it. Its not smart to disable gui elements without explaining why so it makes sense to leave it active and just send the message. Does chobby display the messagebox response?

**Comment by GoogleFrog** [comment]
Chobby doesn't do anything with Say of Target 5 because there were some irrelevant messages coming through this channel.

**Comment by Licho1** [comment]
By all means DO show messages !!!! 
Those are the most important, like response to being banned in lobby server or from battle..
If there are irrelevant messages, report bug! There should not be any. It also sends exceptions there too so maybe you were sending invalid data to server in the past.
