### ISSUE TITLE
website commanders not in sync with ingame coms?

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#1209]
are they?

**Comment by Licho1** [comment]
Why woudln't they?

**Comment by mojjj** [comment]
they are. i will screenshot this evening.

**Comment by mojjj** [comment]
http://imgur.com/a/x2X7u

reopen...

**Comment by KingRaptor** [comment]
Have a startscript or replay file? I want to check if the data server sends is malformed, or if ZK isn't reading it correctly.

**Comment by mojjj** [comment]
the screenshot above is from http://zero-k.info/Battles/Detail/430308

the commander in question once had 2 laserbeams (whereby i think one was green kudos-laser) before the ingame commander upgrade change (level 3: 1 laserbeam, 2 nanolathes). i did nothing to the com, the 2 slots were suddenly empty, i ignored this for a some time and then adjusted the commander setup via website (but with no effect on the ingame preset built)

**Comment by KingRaptor** [comment]
[Decoded base64 of comm configs](http://pastebin.com/yXTAgxQn)

My guess: the level 3 modules are not given in the order game code expects (it puts the weapon after the modules, due to the slot ID order in SQL). I'll make the site fix order of modules before it writes to startscript.

(It also occurs to me that the system may break if the weapon slot is left empty. At least few people are likely to do that.)

**Comment by KingRaptor** [comment]
Fixed in master. Thanks for the report with pictures and everything, it helped me find the issue in short order :+1:

**Comment by mojjj** [comment]
thx for fixing this :D

**Comment by mojjj** [comment]
might be broken again? see http://zero-k.info/Forum/Thread/24349

**Comment by darloth** [comment]
Still certainly broken as of last week - you can't select, say, Personal Cloak on the Guardian chassis, despite that being a valid option ingame.  There are others, that's just the one that comes to mind.

**Comment by sprunk** [comment]
>you can't select, say, Personal Cloak on the Guardian chassis, despite that being a valid option ingame

This ticket is about configs not being correctly sent to ingame. Outdated module list is a separate issue (related #1749).

**Comment by KingRaptor** [comment]
6bf5dd5e03b16bf5af32bcb4c1cbfbe49bb87970 should fix the issue in the thread mojjj linked, once deployed.

**Comment by KingRaptor** [comment]
Fix deployed! Reopen if issue found to persist.

**Comment by mojjj** [comment]
thax for the efforts!
