### ISSUE TITLE
Able to reject and accept a match

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1211]
You are currently able to reject and accept a match if you send both commands to the server. I sent accept and then I sent reject. The result was that I entered the game when my 1v1 partner clicked accept. I was also banned from matchmaking for five minutes.

My UI has it that clicking accept removes the accept button and says "you accepted". At any point you can click reject to send a reject message to the server and close the popup box. This is required in case your house starts burning down.

**Comment by Licho1** [comment]
Once you accept you should imo not be able to reject again. Thats the bug. Accepting might trigger instant creation of battle
