### ISSUE TITLE
[Lobby] Matchmaker doesn't save previous choice for gametype

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#1214]
While I'm sure the current matchmaker setup is very much placeholder, since it doesn't save the teams/1v1 preferences, it's easy to forget to reset them, which caused me to get banned from the matchmaker for 5 minutes when I canceled to correct my preferences.

**Comment by Licho1** [comment]
Correcting preferences does not lead to a ban, only if it happens at time when invitation is active.

**Comment by sprunk** [comment]
Fixed by https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/9ed118816158fc7252e3a2075bdf24c6dc15d716 by the way
