### ISSUE TITLE
Remove match maker refusal ban

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#1215]
I don't understand the logic behind a 5 minute temp ban from the matchmaker for refusing a match. AFAICT you don't get to see who you will be fighting (and you shouldn't), so it's not like dodging is even a thing. 

The only reasons someone would cancel and then return shortly after would be to change their matchmaking preferences or because they needed to deal with something and didn't want to fool the matchmaker into thinking they were currently available. Neither of these seem ban worthy.

**Comment by GoogleFrog** [comment]
He made some good points. Keep the ban in the code because it can be applied in other circumstances. Remove it from simple rejection.

**Comment by sprunk** [comment]
* without the ban you can come back and forth to spam the popup for others which then gets failed 3/4.
 * it's possible to queue against your own smurf to farm Elo by cycling the MM. Short ban prevents the cycling (mostly applicable if we grow).
 * if you need to handle something IRL you don't care about the 5 minutes.
 * preferences should be saved by the lobby, so not a problem here either.

**Comment by dvr333** [comment]
@sprunk Point 1 is more someone being wantonly cruel, in which case the solution seems to be applying the ban if someone enters queue and exits match X times in Y minutes, not just once. Point 2 could probably just be solved by ensuring no players with matching IPs get matchmade (if the problem only comes up when we grow that will have no effect on regular matchmaking). The other two points don't really support keeping the ban.

**Comment by sprunk** [comment]
Why not punish the first offence? That still leaves room for some free trolling. Meanwhile honest players don't get screwed up at all. If the first ban length is <= the overhead of starting a game (loading Spring, startpos picking phase) you might as well accept if you have a short IRL problem. For longer problems the ban will expire before you're done.

**Comment by dvr333** [comment]
Why assume someone leaving is trolling and not an honest mistake or issue? If it is trolling it will be a frequent enough issue to automate something to deal with the player without punishing everyone just to be sure.

**Comment by sprunk** [comment]
Give an example of an "honest mistake" that actually punishes the player given a 1-5 minute MM ban.

**Comment by db81** [comment]
Make sure to at least never call it a "ban", the message should be something along "You can enter the queue in N minutes." Call it a "cancellation timeout" or something, make it shorter.

**Comment by dvr333** [comment]
As I mentioned in the lobby chat: hitting "stop" right as a match happens because you didn't realize it (either to change match settings or because you got unlucky on timing and now want to play that newly available opponent). Granted that's more of a ZKL failure, but that demonstrates how sensitive it is.

**Comment by Licho1** [comment]
It should be called rest time or something instead of ban. Otherwise what sprung said is true. Regarding GUI, yes GUI should remember preferences.
