### ISSUE TITLE
MM: handle decline workarounds

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1221]
You can "decline" MM without consequences by accepting and killing Spring. You can also resign in the first minute because that doesn't change Elo.

**Comment by Licho1** [comment]
Are there any reasonable solution to this?

**Comment by GoogleFrog** [comment]
Make elo loss always occur from the point that the server tell the clients to connect to the battle. Apply a penalty if you don't connect (don't do that now, it is a possible solution for future uptime. Currently not connecting is likely to be a bug and elo loss mostly coveres the dodging case).

**Comment by Licho1** [comment]
If we apply elo loss we also apply elo gain and this allows gaming the system using fake accounts and fast games.

**Comment by GoogleFrog** [comment]
Gaming the system in this way will take forever because new accounts have 1100 elo with malus taken into account. Also inflated elo will really just hurt the perpetrator because they will lose all the games they play. I feel like we can just punish these cases if its a problem.

**Comment by sprunk** [comment]
If there are more people using the system then you are more likely to get matched with them than with your smurf. Decline causes a long wait (ideally it would escalate above 30s if declined multiple times in a row) and accepting means you play with real people so hax gets nullified.

**Comment by Licho1** [comment]
MM elo now applies instantly, so quitting gives elo penalty.
