### ISSUE TITLE
Elo gap algo looks wrong

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1228]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyServer/MatchMaker.cs#L436

Potential player compares with min/max so the gap can grow arbitrarily large.

Eg. battle starts with 2600 elo godde, he has a 400 elo gap. In queue there's someone at 2200, 1800, 1400, 1000.

2600 matches 2200 (gap 400) so min becomes 2200. 1800 matches the new min so min becomes 1800 etc. so at the end 2600 plays together with 1000 for a total of 1600 gap between them.

**Comment by DeinFreund** [comment]
Lulz http://zero-k.info/Forum/NewPost?threadID=22962&forumPostID=164195

Fixed by 994923c6c5ef0264f0291b0e3d20a0a87a5fd976 cc9538d60e885df56fe6fce02ef3a70cf1a4dac7
