### ISSUE TITLE
lobby consumes chat history

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K-Infrastructure#1231]
if you log into zkl, the offline chat history is no longer available for other lobbies. this seems to be an issue with zkl alone, if you log into weblobby first and then into zkl you will have the history in both lobby chats. tested with zkl and weblobby only.

this is somewhat of a big deal in the current situation because some people cannot read the zkl chat at all. (which is fixed in the next release i think?)

**Comment by Licho1** [comment]
unable to replicate, please give full reproduction steps if possible.
