### ISSUE TITLE
Ladder fluctuations

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1249]
There has been criticism about the new ELO constant leading to fluctuations which won't allow for a stable top 10 list. This was to be expected because the higher sensitivity reacts aggressively to "bad days" (which is where its predictive power is also better)

Instead of displaying up to date values the ladders could average ELO values over a longer period of time. Either by updating it only monthly and averaging the values over each day, or by using a smooth average aka x*elo + (1-x) * old_elo.

**Comment by Licho1** [comment]
I think added more complexity to it is not a proper solution.. instead i just reverted K to 32

**Comment by DeinFreund** [comment]
Why that? It makes the system less predictive and will only reduce the ladder fluctuations by a bit.

If the ladders are supposed to be "constant" a different approach is needed for them.

**Comment by Licho1** [comment]
It will increase spread a bit and "seriousness" of each game. It feels bad to lose 50 elo points at once.
