### ISSUE TITLE
Matchmaker queue size update

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1256]
Is only broadcasted when somebody joins a queue, but not if somebody leaves a queue.

**Comment by Licho1** [comment]
It's broadcasted every 30s. It seemed to be not as useful to do full updates when someone leaves or clicks "not ready"

**Comment by DeinFreund** [comment]
Maybe don't do any extra updates just because of single people joining/leaving? Seems a bit inconsistent to do it only on join but not on leave and might be a bit confusing to leave but not see the number decrease.

**Comment by GoogleFrog** [comment]
I think this is solved by https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1260
