### ISSUE TITLE
ChangeUserStatus Error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1259]
ChangeUserStatus sent an error back which caused me to disconnect. The infolog shows that it worked but then stopped working.
[ChangeUserStatus.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/484098/ChangeUserStatus.txt)

**Comment by Licho1** [comment]
According to logs you were not logged in. You disconnected and received welcome message but didn't send login.

Chobby didnt detect reconnect properly, except for showing some message about being offline.

In this state most commands don't work;
