### ISSUE TITLE
MM undeserved ban

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1266]
If the match is killed before you can Accept then you are banned from matchmaking. Example:
 * Players A and B matched together.
 * A clicks reject.
 * Battle is killed.
 * B failed to click accept in time so is banned also.

**Comment by Licho1** [comment]
That is correct behavior, both were AFK or rejected and AFK counts as reject (same as closing lobby program), program should not make any distinction here.

Penalty is for being AFK in queue basically.

**Comment by sprunk** [comment]
What happens if there are just 2 people in the queue and someone rejects in 1s? Will the other guy have 30s to accept/reject still or will he be counted as afk if he didn't do something in 1s?

**Comment by GoogleFrog** [comment]
If the battle is killed then the remaining players should have the result sent to them with no ban.
