### ISSUE TITLE
ELO values are (temporarily) wrong

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1272]
Transferring the old values from 1v1/Teams to new casual/competitive ratings causes them to be completely off for at least the rest of the year. This change is similar in error to a complete ELO reset, which is causing a lot of confusion/discontent. I would suggest recalculating the values using the new filters and past games, which should be a lot more accurate than the old 1v1 values(many players had no 1v1 rating). 

I could provide the approximate ELO values if that'd simplify things.

**Comment by Licho1** [comment]
What do you mean? How can they be off?

**Comment by DeinFreund** [comment]
They are currently the old 1v1 ELO, which is far off from small 
teams ELO.

**Comment by Licho1** [comment]
So you mean reset competetive elo.. we could recalc it from the new mm games - fresh start.

**Comment by DeinFreund** [comment]
I would suggest recalculating it from the existing game database. Using old 1v1-4v4 games to infer it.

This should give a good approximation.

**Comment by Licho1** [comment]
It's a bragging elo imo it should reflect what it affects it now. If now its based on MM games then perhaps only mm games should be counted.

**Comment by Licho1** [comment]
Decision has been made to reset mm elos once .. not sure when need to get agreement from tohers.
