### ISSUE TITLE
lobby asks on startup to change to chobby

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#1279]
how dare you. chobby is completely broken on my linux. https://github.com/Spring-Chobby/Chobby/issues/350

stop bugging me.

**Comment by Anarchid** [comment]
Actually read the rest of the ticket. There's a reason i used quotes when saying "everything broken", it fixes on another start.

If the failure mode is different for you, make a separate ticket!

**Comment by Licho1** [comment]
Duplicate? Issue with chobby posted on chobby.

**Comment by knorker** [comment]
chobby is the savior.
