### ISSUE TITLE
(chesti) site block does not work with firefox porno mode

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#1287]
zero-k.info site/forum block does not function when enabling porno mode of firefox

**Comment by Licho1** [comment]
Not able to fix that...

**Comment by KingRaptor** [comment]
I can log in to site fine with a private window of Firefox 47.0 and 47.0.1 fine. Posting also works, at least on test.zero-k.info.

**Comment by knorker** [comment]
> I can log in to site fine with a private window of Firefox 47.0 and 47.0.1. 

me too

**Comment by Licho1** [comment]
Report is that the ban does not work. If firefox uses proxy, its natural it wont work..

**Comment by db81** [comment]
It would need an IP ban to work.

**Comment by Licho1** [comment]
It does have IP ban

**Comment by Licho1** [comment]
Oh I understand now, someone added a separate forum block improperly .. site block works.. why do we even have bazilion punishments... spectator talk ban.. really??

**Comment by knorker** [comment]
>  why do we even have bazilion punishments... spectator talk ban.. really?? 

so that some kids can feel important on the internet

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/52cbec2034bc459f7fdedad40aa7374fe4fa3466

**Comment by knorker** [comment]
almost

**Comment by sprunk** [comment]
unfeatured https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/52cbec2034bc459f7fdedad40aa7374fe4fa3466
featured the newer version instead https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/dc0c128d1fb649b330725a45aff8a9e4dfe88c46

**Comment by knorker** [comment]
site block not working. poor mapfeaturers still have to manually censor forum posts.

**Comment by knorker** [comment]
for the time being it might be best to disable registration of new accounts completly:
In the last 14 days 315 new accounts were registered but only ~5 of those reached level > 0
The rest did not play a single match or never even logged in.

pro: site block works
con: nothing
