### ISSUE TITLE
Improve game host's ability to set teams

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1289]
Recently we had huge trouble organizing the tournament because !team was missing. While it is obsolete for all but custom game mode, it is still an invaluable command for setting up custom matches. Please readd it.

Thank you.

**Comment by Licho1** [comment]
You mean that people aren't able to join given team?

**Comment by ArchShaman** [comment]
I mean forcing another player to a team. It's good for tournaments. (EG we had trouble setting up anarchid+hoko vs blackdutchie + sigero in first round)

**Comment by Licho1** [comment]
Why was it hard? Was it hard because they didnt know which team to join or becase their lobbies made it hard?

**Comment by ArchShaman** [comment]
Lobbies.

**Comment by Licho1** [comment]
Which lobbies, chobby?

**Comment by ArchShaman** [comment]
Yes

**Comment by Licho1** [comment]
we could improve that and optionally add drag and drop for admins/hosts

**Comment by ArchShaman** [comment]
That'd be a great improvement.

**Comment by Licho1** [comment]
Please recreate in chobby repo.
