### ISSUE TITLE
Map discovery (autoregistrator) is broken again 

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1292]
- No new maps are discovered by AR since at least half a week
- Some game and menu modules are erroneously identified as map modules: 
http://zero-k.info/Maps/Detail/53271
http://zero-k.info/Maps/Detail/53273
- This is possibly related to unitsync in the newer (dev) engines losing some of the old deprecated functions (iirc that was `GetMapInfo`, which also served to break ZKME and is an issue in SWL (workarounded by downoading 103.0).

**Comment by db81** [comment]
If it's unitsync, just use 103.0 unitsync as a quick fix.

**Comment by Licho1** [comment]
It's certainly unitsync.

**Comment by Licho1** [comment]
should be fixed now
