### ISSUE TITLE
Party support

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1295]
Discuss party support. Here are some ideas:
- Parties are sets of players.
- A player can be added to a party by any member of the party inviting the player. The player then gets a lobby server message asking them to accept or decline the invitation. Lone players are, formally, parties of one.
- A player can leave a party at any time by sending the appropriate message to the lobby server.
- Players can be part of at most one party. Responding 'accept' to a party invitation causes the lobby server to remove the player from their current party.

Parties should be implemented with dedicated server protocol, nothing that uses strings which are expected to appear in popups. Each party would have a partyID and an associated list of players. The following are probably sufficient for the above party system:
- InviteToParty(userName)
- LeaveParty(partyID)
- PartyInviteResponse(accepted)
- OnPartyInvite(partyID, listOfUsers)
- OnJoinParty(userName, partyID)
- OnPartyStatus(partyID, listOfUsers)
- OnPartyDisband(partyID)
- OnLeaveParty(userName, partyID)

A party is visible to a user if they are in the party or have a friend in the party. OnPartyStatus, OnJoinParty and OnLeaveParty are self-explanatory and should be sent to everyone who can see the party. OnPartyDisband is only sent to people who can see the party and is sent when someone leaves a two person party. OnPartyDisband should also be sent to players for which the party is going to become invisible (this is simply when their last friend leaves). OnPartyDisband indicates that the partyID can be reused.

**Comment by Licho1** [comment]
I think  we also need "RequestInvite" 
Also friend in the context of party visibility means two sided friendship.

**Comment by Licho1** [comment]
Also to be similar to games like overwatch, party chat could be overlayed over chat in all places, including ingame.. in those games you can simply chat at any time and party members have green font. It's very convenient. 
In practice it would be a bit more complicated because we have many chat channels (instead of just one chat window like those games).

**Comment by GoogleFrog** [comment]
Friends can still be your one sided stalker definition. You can see the parties that include someone who you have designated a friend (or stalkiee, really).

Sure, add RequestInvite. It makes me think that this may need some inbuilt spam protection.

I wouldn't bother with chat channels. Party chat can be a simple autocreated lobby chat channel.

**Comment by Licho1** [comment]
I was thinking that maybe we dont need request invite if instead it sends party invite and accepting just merges the parties together (under the acceptee party).

**Comment by Licho1** [comment]
Do we really need "friend" visibility of parties? Does any other game have this?
It seems a bit of waste (also code complexity waste) to push updates about party status to friends ..

**Comment by sprunk** [comment]
>Does any other game have this?

DotA 2

Works well there, most of people I have as friends there are simply people who are reliable teammates for partying.
