### ISSUE TITLE
Matchmaker parties

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1296]
Parties should be able to queue in the matchmaker. I'll assume there is some concept of parties, perhaps this https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1295

I believe that the server protocol requires no modification to support parties in the matchmaker. The only changes will be to the matchmaker logic. Here are some ideas:
- Any player in a party can send a matchmaker request. This request is equivalent to all players in the party sending an identical request. Requests to join queues with a matchmaker limit lower than the party size are filtered out.
- If the party changes then all players in the party are removed from matchmaking. This also applies to any player who left or joined the party.

Each player is independently run through the matchmaker algorithm, with the following changes:
- The elo of a player is the average elo of the players in their party. This applies to all elo queries by the matchmaker and battle balance system.
- Players from the same party must always be balanced to the same team when matched into a battle.
- The matchmaker currently considers a single player, A, and builds sets of people to play in a battle with A. Parties add restrictions.
  - If A is in a party then the the matchmaker initializes the battle set to contain A's party.
  - For A to select B, all members of B's party must be able to fit in the battle set and fit on the same team. 
  - If B is selected then B's party is automatically selected as well.

Fitting on a team is not as trivial as it sounds and queues may require extra data attached to them to take it into account. For example if A is in a party of 2 and selects B, from a party of 3, then A cannot select C from another party of 3. This is because, while there are 8 players, there is no way to put them on teams obeying their party structure.

Discuss failure cases and improvements.

**Comment by Licho1** [comment]
Matchmaker will treaty whole party as a single "player" just with bigger "size".  "Player" will get min and max elo instead of just one elo for purpose of constructing team.

**Comment by GoogleFrog** [comment]
Can you define what that means for the algorithm?

**Comment by Licho1** [comment]
Actually I think average is better.
When proposing battles, MM will treat entire party (or valid subset of thereof - for example those who were ready) as a single player, with elo = average elo of party.

Party members will thereof  be guaranteed to be in the same spring battle and elo spread will count party average. This is needed anyway, because people with wildly different elo can join the same party.

Separate function will make sure they are balanced ingame together too.

**Comment by DeinFreund** [comment]
Keep in mind that parties will make balancing harder. If the party provides most of the high/low skill players in a match it will have much worse balance than the same match without a party(Where the low/high skill players would be split up).
