### ISSUE TITLE
ChannelUserAdded recieved without User

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1298]
ChannelUserAdded can be sent without User. To reproduce I had Test123 leave and join the server while watching zk with Test1234. Test1234 ChannelUserAdded but no User so Test123  looked like they were offline. If Test123 joins a battle then Test1234 receives User.

**Comment by DeinFreund** [comment]
I'm still getting these..

**Comment by DeinFreund** [comment]
Seems fixed now
