### ISSUE TITLE
New server behaviour should reduce to old

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1299]
The new server behaviour makes zk look empty and puts me at risk of missing discussions. Basically, if we're just thinking about the current situation, the changes are a regression. This can be solved by making the server behave like it used to in low player count situations.
 * The chat history in zk should still be sent. Perhaps require that people subscribe.
 * The first 100 players should be shown in zk. Simply pick a random 100 players from the channel and send them upon connection. If someone connects and there are still less than 100 players then send them to everyone else.

**Comment by Licho1** [comment]
Chat sending is 1000 lines by default. 
1000 people join, each gets 1000 lines ,each line possibly 1000 bytes. 
I don't think its smart to burn 1GB on such convenience..  we can change limits though.

**Comment by Licho1** [comment]
Regarding visibliy, we hae to test this. If all are visible (even if its renamed channel) then we wont test anything. So I think it should be tested and then turned off (or 100 players made visible or something similar). But we do have to test.

**Comment by knorker** [comment]
What makes zeroK look empty too is the "Top 50 Competitive" ladder.
It is supposed to be Top-50 but after one month of matchmaker it has still not filled.
It contains total newbs who played first (and only) match with seconds duration...looks bad to list that as as competive. A Top-10 list would be less embarrassing.

**Comment by DeinFreund** [comment]
Instead of X random people, could we always show the X highest ranked? Istrolid does it that way and even with 100+ people online this allows regular players to find each other easily. These players are also the most likely to be chatting/able to help out.
