### ISSUE TITLE
ZKLS ping allergy

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1302]
`[WARNING] :61 [IN] Say {"IsEmote":false,"Place":5,"Ring":false,"Target":"DeinSchlumpf","Text":"[50 46.126.50.111:25402 DeinSchlumpf] error processing line Ping{} : System.Exception: Invalid json type PlasmaShared.CommandJsonSerializer : Ping\r\n  at PlasmaShared.CommandJsonSerializer.DeserializeLine(String line)\r\n  at ZkLobbyServer.ClientConnection<OnCommandReceived>d__10.MoveNext()","User":"DeinSchlumpf"}`

Might be nicer if it didn't spew randomly formatted exceptions at the client.

**Comment by db81** [comment]
Eh it's fine I think, the client isn't supposed to send ping.

**Comment by DeinFreund** [comment]
Just an enhancement, otherwise some regex lobby could break. Just catch the exception and send some general "Invalid Command(cmd name)" response.

Not really a problem though.

**Comment by Licho1** [comment]
its just an exception message it can happen with unexpected things too.. it should not break properly written parsing.. or you could break it with chat too..
