### ISSUE TITLE
Option to search for players

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1307]
There should be an easy way for players to find each other and send a friend request so they can see each other in the lobby.

The easiest way would probably be adding an Add Friend button on the site (which already has good user search), but there should also be a way to do it in-game.

**Comment by GoogleFrog** [comment]
Apparently the protocol already supports friending other people under any circumstance. All we need to do is provide people somewhere to type names.

**Comment by DeinFreund** [comment]
Adding it on site as well would be nice.

**Comment by Licho1** [comment]
Not needed with steam? 
Reopen if you disagree
