### ISSUE TITLE
(ZKL) not displaying all players in room

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1309]
Heard this from multiple zkl users, but can't be completely sure it's lobby related.

**Comment by let4be** [comment]
I see people joining the room(counter increases), but I don't see who joins(ZKL)
I need to leave the room and join again to update the in-room player list

**Comment by Licho1** [comment]
What room and what lobby?

**Comment by let4be** [comment]
ZKL, any custom room

**Comment by Licho1** [comment]
by room you mean chat or battle?

**Comment by let4be** [comment]
battle room

**Comment by Licho1** [comment]
Unable to replicate this issue. When I join the room both icon and playerlist updates. If you have further details/instructions please post them.

**Comment by let4be** [comment]
right, screw this dying lobby...
who cares

**Comment by let4be** [comment]
I said not when YOU join the room but when OTHERS do. Player list is not being updated

**Comment by Licho1** [comment]
oh .. "player list" now you are being specific..
yes player list count is not updated instantly, its bunched every couple of seconds to avoid n^2 issues. 
This is a feature.

**Comment by let4be** [comment]
Player list _inside_ battle room. And the delay, if there is such a thing is infinity. I never see it updated when new player joins my room _unless_ I rejoin the room myself

**Comment by Licho1** [comment]
I am unable to replicate it with zkl, it works for me. When i open battle and other people join it i see it instantly .. very odd..

**Comment by let4be** [comment]
Thanks, I will test as I get to PC

**Comment by let4be** [comment]
seems to work fine!
