### ISSUE TITLE
PM's are not echoed to user

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1314]
If this is a new protocol feature it's not supported by either SWL, ZKL nor Chobby.

**Comment by DeinFreund** [comment]
Sending test from choppy:

![1](https://i.imgur.com/hX229GW.png)
![2](https://i.imgur.com/dzEhriY.png)

**Comment by Licho1** [comment]
Its fixed. Not deployed

Dne 28. 10. 2016 0:56 napsal uživatel "DeinFreund" <notifications@github.com
