### ISSUE TITLE
Ban message not displayed for site bans

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1316]
Doesn't fix knorke, but may remove some confusion to actually tell peoplers they are banned instead of showing exceptions.

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/366f73ec17157c902aafbe7d62fc4144493cc5cd/Zero-K.info/Global.asax.cs#L142
Calling `penalty.AccountByAccountID.Name` fails. (Trace: http://paste.springfiles.com/view/9d90f3ea)

**Comment by knorker** [comment]
when ban system fails easier to just change passwords
