### ISSUE TITLE
Chat doubleup

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1318]
The ingame chat that Springie echos to the battle room is echoed ingame. Springie should not send the echoed chat back ingame.

**Comment by GoogleFrog** [comment]
[f=-000001] <4hundred> you want me to say it twice? <- ingame chat
[f=-000001] > <4hundred>you want me to say it twice? <- grey chat sent from springie

**Comment by Licho1** [comment]
This is fixed already, requires stable.

**Comment by DeinFreund** [comment]
Chat is still doubled, can't do commands like !cheats ingame because they toggle twice.
