### ISSUE TITLE
!poll kick should be able to kick non currently present players

### ISSUE THREAD

**Issue by let4be** [ZeroK-RTS/Zero-K-Infrastructure#1320]
It's possible to circumvent kicking by temporary leaving the room and rejoining after the vote finishes

**Comment by db81** [comment]
I guess it can just add the person to the temp ban list even if they're not present when the vote passes.

**Comment by let4be** [comment]
Arbitrary string that exists in the zk's user database
sounds legit

**Comment by Licho1** [comment]
huh it still works for ingame stuff

**Comment by DeinFreund** [comment]
It already allows to kick an arbitrary string

**Comment by Licho1** [comment]
this is already working
