### ISSUE TITLE
MissionEditor: allow to export to .sdd

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#1322]
currently it seems the MissionEditor can only export to a .sdz?!

it would be nice if it could directly update a .sdd folder so git + rapid could be easily used.

https://github.com/spring/RapidTools/issues/48

**Comment by Licho1** [comment]
@KingRaptor  can you go online? We need feature trailer video to cut it

**Comment by silentwings** [comment]
<3
