### ISSUE TITLE
ZKLS forgets to send User {}

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1323]
Seemingly at random ZKLS may decide not to send any User {} messages on login other than for yourself. If you sit there connecting and disconnecting it forgets about half the time.

http://pastebin.com/XwQnFdgB

**Comment by Licho1** [comment]
Were you connected to the same account using two different lobby instances?

**Comment by db81** [comment]
No, that's with a single lobby.

**Comment by Licho1** [comment]
How did you disconnect? Is it possible your previous session "timed out" or was otherwise uncleanly cut?

**Comment by db81** [comment]
Yeah I looked into it and the way it closes the socket is not *quite* right. So maybe it thinks it's second client (but then half the time it doesn't?). Why not send User {} to a second client anyway?
