### ISSUE TITLE
Forum @playername style inconsistent?

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#1326]
i left the faction, so my name is no longer purple. a reference on myself from the past still is purple. is this intended behaviour?

compare:
http://zero-k.info/Forum/Thread/23099?postID=165482#165482
http://zero-k.info/Forum/Thread/23099?postID=165483#165483

**Comment by Licho1** [comment]
This is intended/cache.
