### ISSUE TITLE
Wrapper feature: Delete springsettings.cfg

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1328]
I need to be able to have chobby do a once-off delete of springsettings.cfg prior to starting spring. This would then recopy the springsettings from the appropriate folder inside zkMenu.

**Comment by Licho1** [comment]
How do you suggest we make it? 
We could add some "version" field into some config file and wrapper auto deletes it if version differs from local

**Comment by GoogleFrog** [comment]
Could put settings version in chobby modinfo. I don't want to delete settings on every update.

**Comment by Licho1** [comment]
Version in modinfo sounds good but I think it should be related to game and not to chobby don't you think?

**Comment by GoogleFrog** [comment]
It should be chobby related because both can cause old settings to be bad and chobby is higher and more relevant here than game. If game causes a reset to be required then I'll just release chobby too.
