### ISSUE TITLE
Wrapper protocol: download engine

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1330]
Chobby should be able to tell the wrapper to download an engine. This can be used to make chobby download an engine update and then prompt the user for restart, saving them time.

**Comment by Licho1** [comment]
Ok so you want "request new engine download" and "engine download done" events, correct?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by Licho1** [comment]
already implemented
