### ISSUE TITLE
Unranked status for inactive/new players

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1332]
Wrong Elo values are causing confusion, which is why I'd suggest showing Elo only for active people who have played a minimum amount of MM games. This would also fix the problem with long time players who deny to play MM and complain about their Elo being unjustified -> Don't show a rating if we don't have a representative one.

(Asking mostly for opinions, should be able to implement it myself)

**Comment by db81** [comment]
That's probably a good setup to have, at least right before release.

**Comment by Licho1** [comment]
Its already implemented, it shows no rating for low weight. We should just adjust it to reduce weight of people who are inactive.

**Comment by Licho1** [comment]
This is already done if its displayed somewhere where it shoudlnt be, tell me exactly where.
