### ISSUE TITLE
Remove casual Elo

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1333]
I would suggest getting rid of casual Elo and replacing it by readonly MM elo. Averaged among all players and games, it's more accurate to balance big games by small teams elo, even if there are individuals who never play a single small teams game.

Additionally, this will save a lot of confusion that's inherently caused by having a "hidden rating".

While for many (less active) players, the current casual Elo may be more accurate than their current competitive one, this is only because of the "wrong" initialization with 1v1/Teams values and will change over time. We could probably derive better initial values from the existing two ratings.

**Comment by Licho1** [comment]
Problem is people scream if you touch their clusterfuck elo thingie.

**Comment by DeinFreund** [comment]
Then just initialize the MM ratings with clusterfuck elo. Even the old clusterfuck elo was pretty much only affected by small team games, the big games being much smaller weight and much more random results in them hardly having an impact.

**Comment by Licho1** [comment]
I dont understand what is the request of this ticket.

**Comment by DeinFreund** [comment]
Removing casual elo.. All games would be balanced by MM elo. Casual games wouldn't affect elo.

**Comment by Licho1** [comment]
This makes no sense, this would make casual games heavily unbalanced.

**Comment by sprunk** [comment]
For balanced games people should use MM?

**Comment by DeinFreund** [comment]
Big teams are already balanced by small teams Elo, just by how the weighting works out. The small team games are now being fought in MM, which leaves mostly big games for casual Elo. Elo currently doesn't work to predict Big Teams.

So we could either just balance big teams randomly, which will result in similar quality games as having a dedicated Big Teams Elo. Or we could continue doing like we used to and use Small Teams Elo to balance big teams. This means balancing big team games with MM elo.

I have already done the experiment of ignoring all >4v4 games and it doesn't impact the predictiveness of Elo, even for the big games.

**Comment by DeinFreund** [comment]
It's important to think independent of the current casual values, as they are still 99% the old values and will take a year or more to actually lose their predictiveness from the new system.

**Comment by Licho1** [comment]
There are two elos .. MM and everything else. MM is used to balance MM games, everything else ELO to everything else.

**Comment by DeinFreund** [comment]
The problem is that everything else elo is not only unneeded but also inaccurate. If we used MM elo for everything else it would be more accurate. What do we need the everything else elo for? To give people a magic random number?

I haven't done the statistics to back this yet, mostly because MM hasn't been around for long. But if you want I can do that.

**Comment by Licho1** [comment]
Everything else elo is balancing elo, which should not be very public. But I guess we could track this elo in every game and then it will be most accurate elo ever.

**Comment by sprunk** [comment]
No autobalance is needed for rooms at all, let room host control teams manually. If someone wants autobalance -> use MM.

**Comment by DeinFreund** [comment]
I don't understand the need for a second balancing elo.. 

> this would make casual games heavily unbalanced.

is just not the case. Also then games would already now be heavily unbalanced, because elo is only a tiny bit better than random balance for big teams.

**Comment by Licho1** [comment]
What do you mean.. there is just one balancing elo.. and one bragging elo ..
And no I dont think random is tiny bit better than elo.. you probably aren't around to remember times before elo.. it was pretty horrible, people insta quitting etc., Don't forgot not all team games are 8v8, you also get 2v2, 3v3 on non-mm hosts.

**Comment by sprunk** [comment]
>you also get 2v2, 3v3 on non-mm hosts.

If anything changes then people will just move to play 2v2 in the MM (which we want, MM works better when more people use it, and the people get better quality games too).

**Comment by Aquanim** [comment]
If you replace casual Elo with readonly MM elo I am very sure some players will tank their MM elo to get easy casual games.

**Comment by Licho1** [comment]
read only? You mean write only? All I did is that "casual" elo is calculated from all games not just non-mm games.

**Comment by DeinFreund** [comment]
Hm, this way works as well.
