### ISSUE TITLE
Ring notifies the issuing player in PM

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1334]
Any method that sends rings (startvote when someone is not done downloading, manual !ring) seems to cause *two* players to receive PM notifications: the player who was to be ringed (proper case) and also the player who initiated the action. Icing on the cake is that the originating player receives the PM worded as "Targetplayer wants your attention".

**Comment by Licho1** [comment]
Well since its just a say with "ring" flag it should be client's task to ignore self-rings. It gets every say it sends.
