### ISSUE TITLE
Wrapper: Launch replay.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1343]
The wrapper should have a command to launch a given replay file. Chobby will make sure that the appropriate game and map are downloaded. It should also send a request to the wrapper to download the engine prior to sending the "launch replay" command, however, the wrapper should probably be able to download the required engine itself.

The wrapper needs to be able to receive a springsettings to use. If it uses the springsettings present in the base folder then it will launch spring with the wrong settings, namely fullscreen mode. I am unsure how to solve this. Perhaps there is a cmdline way to override settings.

**Comment by mojjj** [comment]
https://github.com/Spring-Chobby/Chobby/issues/385

**Comment by Licho1** [comment]
The settings change requirements is holding this back. No idea how to arrange that. Any ideas?

**Comment by GoogleFrog** [comment]
I can change springsettings using Spring.SetConfigInt and then tell the wrapper to start the game. However this will cause chobby to go fullscreen and it may block the game.

**Comment by GoogleFrog** [comment]
I can write a settings file to a subdirectory.

**Comment by GoogleFrog** [comment]
I could send you a table of the settings to apply and wrapper could write that to settings file. Implement this without doing the settings and see how we go.

**Comment by Licho1** [comment]
Table as function param sounds good will probably do that.

**Comment by Licho1** [comment]
fixed by c22f4db336445ec24fbde8e0b67dddfb3ecfe83b

**Comment by mojjj** [comment]
so can chobby now download replays with older engines and start them?

**Comment by Licho1** [comment]
No, not really.
