### ISSUE TITLE
No link in the Zero-K side to the corresponding Spring Files map page

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1346]
I suspect there are maps that could benefit from a link to the Spring Files side because it seems the map details the Zero-K website provides can be incomplete.

**Comment by sprunk** [comment]
Examples?

**Comment by Sgathec** [comment]
My map, "Folsom Dam Core".
http://zero-k.info/Maps/Detail/50479
http://springfiles.com/spring/spring-maps/folsomdamcore

**Comment by sprunk** [comment]
Sorry, I meant examples of details from ZK infra. (I can't access zk-info at the moment to compare.)

ZK should start to provide any relevant info but as far as I remember most of what is available on SpringFiles over ZK is not relevant to ZK.

**Comment by Sgathec** [comment]
On the Zero-K map page for Folsom Dam Core, in the description field all one can see is "Folsom Dam Core v 0.95 ".

In the Spring Files side there are multiple lines under subheaders "Description", "Acknowledgement" and "License".

**Comment by sprunk** [comment]
As far as I can tell that info is not a part of the map archive itself but a SF content thing, like ZK comments under maps. So the equivalent thing to do would be to just make a comment.

**Comment by Sgathec** [comment]
No, the Spring Files text I talked about is not a part of it.

Writing descriptions/comments like that would result in duplicate content. One could forgo writing a proper description onto the Spring files page, but I find that inappropriate as Spring Files is used as well.

**Comment by Licho1** [comment]
Not very interested in making it. Atm you could use comments to add useful info, or add a PR.
