### ISSUE TITLE
Commands execute twice if said in game

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1347]
Affects:
- Cheats
- Most poll commands
- Hostsay /nocost
- Hostsay /godmode
- Hostsay /globallos
- more?
![screen00122](https://cloud.githubusercontent.com/assets/7841201/20929195/5206b4e6-bb86-11e6-965f-03f4ba384733.png)

Replication:

1. create game room
2. start game against bots or whatever.
3. Type !cheats in game. It executes twice.
4. Type !poll Spec NullAI -- it executes twice. (two successful polls because you're the only one in the game)

**Comment by sprunk** [comment]
Related #1318
