### ISSUE TITLE
200+ character usernames are allowed

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1348]
![2](https://cloud.githubusercontent.com/assets/7841201/20933122/506de894-bb94-11e6-9469-21dcc55b0e15.png)
http://zero-k.info/Users/Detail/392660

**Comment by db81** [comment]
Relatedly, we should make logins case-insensitive already, it's bound to cause trouble.

**Comment by ArchShaman** [comment]
![3](https://cloud.githubusercontent.com/assets/7841201/20974029/240d38bc-bc58-11e6-9da2-ed28ce856ed6.PNG)
![4](https://cloud.githubusercontent.com/assets/7841201/20974048/2d924d00-bc58-11e6-83a7-cac157e190ad.PNG)

Really long usernames break stuff.

**Comment by Licho1** [comment]
You could have tested this on test.zero-k.info..
Regarding case sensitivity there are too many collisions to solve, needs manual work.

**Comment by Licho1** [comment]
fixed by kr
