### ISSUE TITLE
Temp files for startscript are not cleaned up after games

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1350]
Games were unable to be started on zkls because 
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/LobbyClient/DedicatedServer.cs#L286 failed to acquire new temp files for startscripts. 

```
System.IO.IOException: The file exists. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.__Error.WinIOError() at System.IO.Path.InternalGetTempFileName(Boolean checkHost) at System.IO.Path.GetTempFileName() at LobbyClient.DedicatedServer.StartDedicated(String script)
```

Apparently cleaning up the temporary files fixed the issue. This should be done automatically to avoid future server downtimes.

**Comment by KingRaptor** [comment]
I don't know whether it's the startscript files specifically that are not being cleaned up, but this needs to be looked into regardless.

**Comment by abma** [comment]
maybe you hit this nice windows feature:

https://msdn.microsoft.com/en-us/library/system.io.path.gettempfilename%28VS.80%29.aspx

"The GetTempFileName method will raise an IOException if it is used to create more than 65535 files without deleting previous temporary files."

:)

**Comment by Licho1** [comment]
Temp is not being cleaned, you need to clean files manually after they are used. Windows does not do that.
