### ISSUE TITLE
Can join other faction's channels

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1351]
https://github.com/ZeroK-RTS/Chobby/issues/59

**Comment by KingRaptor** [comment]
[It already blocks joining undeleted factions](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/64a608c327f8ac765eb0eef388003a8d1260ab95/ZkLobbyServer/ChannelManager.cs#L75). 

I couldn't join either `#Hegemony` or `#Rising` channels (case-sensitive) in chobby:

```
[f=-000001] LuaMenuServerMessage, <JoinChannelResponse {"ChannelName":"Hegemony","Reason":"you don't have permission to join this channel","Success":false}
```

Guess I'll close this if no-one else mentions being able to reproduce.

**Comment by KingRaptor** [comment]
Ah, I see a careful reading of the code line would have revealed the problem. Well, fixed :)
