### ISSUE TITLE
Can't upload mutators?

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1352]
I uploaded a mutator earlier today to Springfiles, but it doesn't seem to want to show up in Springiee. Has there been some sort of mistake? Am I doing it wrong?

**Comment by Licho1** [comment]
Uploading mutators to springfiles does nothing.. What exactly do you want to achieve?

**Comment by ArchShaman** [comment]
Use !game <mutatorname> to host it. Like to test code in live situations. I at one point or time was able to do this in the past. (See: !game Zero-K IGNORE TEST / Zero-K Chicken Madness)

**Comment by Licho1** [comment]
In the past ZKL used to unitsync and submit data about it. I'm not sure if ZKL still has this function enabled, probably not. Without metadata server is ignorant about it and wont let you host it.
Only maps are downloaded from springfiles.

**Comment by ArchShaman** [comment]
I checked ZKL and it doesn't have this function. It said couldn't find resource... asking again later. Or something like that.

Sad.

**Comment by Licho1** [comment]
we need to think about how we want to add new stuff like mutators to ecosystem.. should there be upload site? For whom? Will there be review? Should it use steamworkshop?

**Comment by ArchShaman** [comment]
Steam workshop seems like a cool idea. I'd personally like to see mutators allowed. However quality control should also be a thing. For the moment I see mutators as useful for sciencing (that balance mod someone was doing) or testing code. What I personally wouldn't like to see are mods like " all players named Firepluk get 5,000m instantly" or silly unbalanced stuff like that.

**Comment by ArchShaman** [comment]
Seems that maps are affected too. Tried to upload a map and that didn't work either.

**Comment by Licho1** [comment]
Maps should be working.

**Comment by ArchShaman** [comment]
How can I check if it uploaded?

Thanks for the information so far, it's appreciated. :)

**Comment by Licho1** [comment]
Check that its in map list on the server. Make sure yo also check you want to see non-downloadable etc maps.
Then use !map exactname to force switch some game into your map and it might become downloadable.

**Comment by ArchShaman** [comment]
Okay will try it. Thanks.

**Comment by Licho1** [comment]
Need more information.
If its a game mutator, use !forcegame
if its a map, report with link if it does not auto register in ZK

**Comment by Licho1** [comment]
map to register mods and games is now available. Also zk now has basic steam workshop support
