### ISSUE TITLE
Reimplement !resetoptions

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1357]
Currently SetModOptions sends a table of changes relative to the previous state, with one exception. !resetoptions causes the server to send an empty table which lobbies are supposed to interpret as 'reset options to default'. This is inconsistent so I'd prefer it to send a diff every time or use a different command name to signal a reset.

**Comment by Licho1** [comment]
It sends table relative to default state. This is how it's even stored internally in springie autohosts. When proposing !setoptions change client must send all keys different from default. If he misses some they will be reset to default.
