### ISSUE TITLE
Wrapper doesn't download mission maps

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1358]
The wrapper does not download maps required for missions (yes, I checked without 'dev' set). To reproduce simply delete isisDelta_v02 from your maps folder. Chobby will start without the wrapper downloading the map. Then the map will be downloaded by chobby due to a change I just made.

**Comment by Licho1** [comment]
It does work. 
You changed it's data. 
It does make sure it exists on the first start. 
It does not assume player will remove the map while keeping mission and mission metadata intact. 
Running checks for that would be expensive.

**Comment by GoogleFrog** [comment]
I had this report from a new user. TODO: test first start.

**Comment by Licho1** [comment]
i tested on start and it worked.
