### ISSUE TITLE
User page allows you to nuke the site/lobby server

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1361]
Dem troublesome queries killed everything I think. Chobby self update is dead in the water. Zero-K.info is nonresponsive.

**Comment by Licho1** [comment]
Please explain what you mean, i dont understand this ticket.

**Comment by Aquanim** [comment]
I believe the meaning is that a large number of persons (or one with multiple browser tabs) giving http://zero-k.info/Users sorting requests is an effective and easy-to-execute denial of service attack against the website and game server.

**Comment by KingRaptor** [comment]
34b7a3a721d24342fef87c215d0259b7b0e2318a removed the expensive queries. I also intend to purge unused accounts from DB (no battles; no forum posts; no logins in past year).

**Comment by ArchShaman** [comment]
Can you delete my test accounts as well except TEST and resign? (EG: the extremely-long-named one)

**Comment by KingRaptor** [comment]
```C#
            var db = new ZkDataContext();
            var accs = db.Accounts.Where(x => x.SpringBattles.Count == 0 && x.ForumPosts.Count == 0).ToList();
            accs = accs.Where(x=> x.LastLogin.AddMonths(12) < DateTime.UtcNow).ToList();
            Console.WriteLine("{0} / {1}", accs.Count, db.Accounts.Count());
            db.Accounts.DeleteAllOnSubmit(accs);
            db.SaveChanges();
```
This didn't complete running on server even after several hours >:(

**Comment by Licho1** [comment]
Well this will force the server to do some insane stuff..
This is the way to do it:
delete from accounts where not exists (select * from SpringBattlePlayers where AccountID = accounts.accountid) and not exists (select * from ForumPosts where AuthorAccountID = accounts.accountid)

**Comment by Licho1** [comment]
The proper cleanup command is:
`insert into @todel (accountid) select accountid from accounts where not exists (select * from SpringBattlePlayers where AccountID = accounts.accountid) and not exists (select * from ForumPosts where AuthorAccountID = accounts.accountid ) and not exists (select * from PollVotes where accountid = accounts.accountid) and not exists (select * from missionscores where accountid = accounts.accountid) and not exists (select * from ratings where accountid = accounts.accountid) and not exists (select * from mapratings where accountid = accounts.accountid)  and not exists (select * from contributions where accountid = accounts.accountid)  and not exists (select * from forumthreads where forumthreads.CreatedAccountID = accounts.accountid or LastPostAccountID = accounts.accountid) and not exists (select * from resources where resources.TaggedByAccountID = accounts.accountid) and not exists (select * from springbattles where springbattles.HostAccountID = accounts.accountid) and MissionRunCount = 0 and LastLogin < '20160101'
select count(*) from @todel
delete from ForumThreadLastReads where accountid in (select accountid from @todel)
delete from ForumLastReads where accountid in (select accountid from @todel)
delete from AccountBattleAwards where accountid in (select accountid from @todel)
delete from commanders where accountid in (select accountid from @todel)
delete from AbuseReports where accountid in (select accountid from @todel) or ReporterAccountID in (select accountid from @todel)
delete from accounts where accountid in (select accountid from @todel)
`

And it freed whooping 1088 accounts.. lol
