### ISSUE TITLE
Command/Ability to remove other player's bots

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1362]
It is hard to convince others to kick the bot host, which is also overkill just for removing a few bots. There should be a way to clear all or a player's bots from the battleroom. 

Bots should also be cleared when switching battle type.

**Comment by Licho1** [comment]
battle founders, admins and bot owners can remove it. What else would you want?

**Comment by DeinFreund** [comment]
Yup, that's perfect.
