### ISSUE TITLE
Redesign initial MM elo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1365]
I want to remove the MM elo malus that makes new players look like they have 1100 elo. The uncertainty parameter would still exist to make elo change more rapidly when you begin playing. I think this is desirable both for the current playerbase and a larger one.

Here are some reasons that 1100 may be inaccurate or not required:
 * Players do not necessarily start playing ZK in MM. Currently we have custom rooms and messing about in singleplayer. In the future I expect more options for messing around in singleplayer.
 * A few difficult matches at the start of their MM playing is to be expected in order to properly rank players.
 * If we have an influx of players then it doesn't matter what the starting elo is, they will mostly play each other anyway.

Regardless of the above, the malus is bad because it makes it hard for new players to find games. The average MM elo of players who have worked of their malus is going to be 1500 at best and probably much higher because low elo players are less likely to MM.

This redesign should include a MM elo reset.

**Comment by Licho1** [comment]
I would like to change how its calculated instead of dropping malus completely. It should be used to pick nubs for nubs at first and later non nubs if there is no match.

Probably we should track min elo and max elo for each player, with interval changing over time and use this .. Battles min elo would be max of min elos of players.

**Comment by GoogleFrog** [comment]
It sounds like you want the idea in the OP with the condition that MM is more likely to match new players with new players. Adding width is a very complicated proposal. Why not simply spend the first round of matchmaking (for 30 seconds) matching people into two groups depending on whether they are new or not. After the first round they are able to be matched to anyone. This seems to implement the same behaviour without massive complication.

**Comment by Licho1** [comment]
There isnt "first round" of matchmaking.. when it tries to offer people games is it first round or not?

**Comment by GoogleFrog** [comment]
There is a first round for each players search based on how long they have spent searching. In the first round it could only match games (and send offers) with players which are in the same set as themselves. The sets are the set of new players and the set of not new players.

**Comment by GoogleFrog** [comment]
It does not reduce the set of matches. The first round matches you only with players that have the same newPlayer attribute as you do. The second and subsequent rounds match you with anyone.

**Comment by Licho1** [comment]
There is no first and no second, I still dont understand. Every player is included in every check, even if they are not in queue.

**Comment by sprunk** [comment]
>There is no first and no second, I still dont understand.

The way I understand the idea is something like this:
```
AddPlayerToQueue(player P, queue Q) {
    P.first = true;
    Q.insert(P);
}

Every30Seconds (queue Q) {
    queue nubs, pros;
    for (player P in Q) {
        if (P.first) {
            if (P.isNub) {
                nubs.insert(P);
            } else {
                pros.insert(P);
            }
        } else { // able to match anyone
            nubs.insert(P);
            pros.insert(P);
        }
        P.first = false;
    }
    TryMakeGameFromPeople (nubs);
    TryMakeGameFromPeople (pros);
}
```

**Comment by Licho1** [comment]
Thats not how it works, because you have to check all players to offer insta join. So it actually checks all people all the time (and limited subset too for which it might make some sense, but issue is with invites, not with this subset).

**Comment by GoogleFrog** [comment]
There is a first and second round because each check is done from the point of view of a player in the MM queue.

**Comment by Licho1** [comment]
Which means that they might invite nub initially but not later when its not "first" check. Which leads to inconsistency and decreasing options which is bad

**Comment by GoogleFrog** [comment]
There are no decreasing options.
 * Every player has the state "new" or "not new"
 * On the first round of checking the player only considers players of the same state.
 * On subsequent rounds of checking the player considers all other players.

I don't know what you think I am saying.

**Comment by Licho1** [comment]
All players in lobby are subjects to these checks, not just people who clicked to join queue. Every 30s ALL players, even not in queue are checked. 
What counts as new/not new? 

Or you want to duplicate entire check and run it always 2x? Once with weight and once without? 

And what about "holes" .. the difference between 1100 and 1500 is huge, and treating someone as either 1100 or 1500 might exclude some game in middle. So interval check seems to me superior.

**Comment by GoogleFrog** [comment]
> All players in lobby are subjects to these checks, not just people who clicked to join queue. Every 30s ALL players, even not in queue are checked.

Define "checked"? As far as I know everyone in a MM queue has a search width based on how long they have spent searching for a game. Every "check" in the MM system is asymmetrical, it singles out a player and checks all other players to see if a game can be created. These checks are initialized by people who are in the queue. I'm not saying that effective elo be changed to 1100 for one of these checks, there is no weighting. My idea is simply to replace "all other players" with the set of players which match the "new/not new" tag of the player initializing the check for the first check that the player initializes.

I don't even want the "new/not new" tag. All I want is for everyone to start at 1500 and remove malus. I am just suggesting "new/not new" because it seems vastly simpler than interval checking and so more understandable/maintainable.

From this comment:
> I would like to change how its calculated instead of dropping malus completely. It should be used to pick nubs for nubs at first and later non nubs if there is no match.

Instead of using a complicated interval calculation which is likely to create incorrect behaviour without us realizing it, just do exactly what your sentence says. For the first 30s (or minute, whatever) after a player joins the MM queue they only search for games among new/not new players. After this time they search for games with everyone. The instant "1v1 available" messages should be unaffected. If an old player has searched for 2 minutes and finds a game against a non-queuing new player then the new player will receive the "1v1 available" notification.

**Comment by Licho1** [comment]
Sigh, I clearly suck at explaining this..
Well look at code, look at how many times is ProposeBattles called and how instant battle start works. 

Making it work with "new/not new" is imo much more complex and bug prone than changing "CanBeAdded" function to incorporate intervals.

But go ahead, if you think it's easy just make a PR, we can push it to test and check for inconsistencies (like instant battle start invitation not resolving to actual battle). 

When I do look at this im going to instead add intervals which seems much simpler.

**Comment by GoogleFrog** [comment]
At this point do whatever you think is simpler. I just wanted to stop you from wasting time and having unmaintainable code. In the end, the time will be spent on whatever you think it best.

All I want is for new players to be matched as if they have 1500 elo, at least after a minute or two in the queue. If you want to have an inteval of potential elos ranging from (1100, 1100) when they enter to (1100, 1500) after a bit of waiting, and you think it's simple to implement, then it's fine by me.
