### ISSUE TITLE
Don't let test languish unreleased

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1366]
Release infrastructure as often as possible to prevent the occurrence of multiple breaking changes. When was the last release? When can we expect the already-added MM search change?

**Comment by KingRaptor** [comment]
Infra updates are infrequent because they require taking server down (briefly) and there is still no good mechanism for player notifications ahead of time. (Does Chobby support channel topics?)

Last infra release was 3 days ago and contains all changes from master as of time of writing.

**Comment by GoogleFrog** [comment]
Ah, that is fine.

**Comment by Licho1** [comment]
For announcements it's good idea to have either topic, or server message which stays on screen until player acknowledges it! 
Then it can be made very frequent, even daily if needed.
