### ISSUE TITLE
Wrapper Isolation

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1367]
Chobby should run isolated by default. I am not sure if it does. I think chobby was isolated at some point but then it was removed.
 * The wrapper should make chobby launch isolated.
 * There could be some way for chobby to set whether subsequent launches are isolated. This can possibly be done by chobby alone by deleting/creating isolated.txt but would be better done with a proper wrapper interface command.

**Comment by Licho1** [comment]
Wrapper does set isolation mode, it tells engine that the root of isolation is the place where chobby.exe is.
I cannot imagine a reason to make non-isolated start.
Perhaps setting up isolation path might be interesting option to add. Closing until explained why its needed and what is needed.

**Comment by GoogleFrog** [comment]
Feedback tag.

**Comment by GoogleFrog** [comment]
It does seem to be isolated.
