### ISSUE TITLE
Wrapper offline error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1368]
If you run the wrapper with no internet then you see nothing, then this error.

![errornointernet](https://cloud.githubusercontent.com/assets/1318249/21575034/dbd1a4ac-cf53-11e6-89ec-19a18d0a1353.png)

Chobby then starts about 20 seconds later. The error is very poor. It should say something more like "no internet connection, starting in offline mode".

**Comment by Licho1** [comment]
Wrapper is going to have two modes .. offline (all startup checks and downloads disabled, just API provided for the lobby), and standard online mode.

Offline mode will be triggered by the presence of the file steamfolder.txt in the local folder, which will also cause it to extract steam ID from running steam and signal to steam that the app is running.

Steam itself can then run game in fully offline mode.

Question is, do we, under such conditons, want a third mode which is non-steam, offline mode?

**Comment by GoogleFrog** [comment]
This isn't a ticket about deciding upon which modes are required, it's just an error report. There are going to be occasions when the non-steam wrapper is launched while there is no internet connection. If this occurs then chobby should run as well as it can without the internet and without displaying misleading errors.

**Comment by Licho1** [comment]
Ok.. though I'm not sure there are going to be situations when non-steam wrapper is launched at all..

**Comment by Licho1** [comment]
fixed
