### ISSUE TITLE
Free up user names

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1373]
Old usernames can be freed up by renaming users from Name to OldUser<nonsense>Name. Here are some decent criteria for the process:
 * Most recent login or forum post occurred in 2014 or earlier.
 * Less than 10 games played.

**Comment by Licho1** [comment]
this is going to free 33366 account names, which is pretty good.

**Comment by GoogleFrog** [comment]
How many account names are there in total?

**Comment by Licho1** [comment]
About 70 000

**Comment by KingRaptor** [comment]
While we're at it I'd like to rename all accounts with case-sensitivity conflicts as DeinFreund suggested (non-oldest accounts get _1, _2, _3, etc. appended to end of name) and then make name collision check on registration case insensitive.

**Comment by Licho1** [comment]
Renaming accounts is more disruptive it will affect existing players... what is the exact rule?
Regarding old accounts i will just rename "nickname" to "nickname#old#accountid"

**Comment by db81** [comment]
We can use latest logged in instead of oldest to resolve case-sensitivity.

**Comment by DeinFreund** [comment]
We could also just disallow "duplicate"(matching an existing name ignoring case) registrations from now on. As long as duplicate names are only a problem to humans reading them this should be the easiest solution.

**Comment by Licho1** [comment]
Yeah thats probably the best thing to do .. case conflicts are only issue for humans.
