### ISSUE TITLE
Wrapper should send chobby a username suggestion

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1374]
When using Steam, the wrapper should send chobby a suggested username. This username would tell chobby to show a cutdown login screen which just confirms the login. Ideally the wrapper would pass a valid ZKS name by ripping out unsupported symbols beforehand. Otherwise I'd like a list of allowed symbols.

**Comment by Licho1** [comment]
done
