### ISSUE TITLE
Casual elo must not be visible

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1376]
But it is still shown on the ladders. 

How about replacing the casual ladder by highest level players that are actively playing? Besides being "hidden", casual elo is known for not being a very accurate nor precise measurement of skill (There are too many variables in Teams/FFA).

Imo this would make more sense than trying to make a "competitive" ladder (skill based) for an explicitly non-competitive game mode. One might say that this ladder would be very static and thus boring, but how much more variation is there in actual skill? Besides random fluctuations due to how elo works, Godde and Randy will remain at the top for the foreseeable future.

The way for newbies to get a ladder place remains the award category.

Give southern98 some credit for having played over 5000 games without ever touching competitive pvp :)

**Comment by Licho1** [comment]
There has been a huge outcry when casual elo got removed. Sorry I'm not going to put myself on firing line again :-)
