### ISSUE TITLE
The zk server died, now I am sad

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1377]
Still resolvable, but doesn't even respond to pings anymore. Problem of the hoster?

Or is it Windows Updates again?

**Comment by Aquanim** [comment]
Seems to be up again now.

**Comment by DeinFreund** [comment]
Cause?

**Comment by Licho1** [comment]
Server wasn't down for months, afaik just frog in the pipeline or something.
