### ISSUE TITLE
Split 2v2, 3v3 and 4v4 queues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1381]
I hear from Dancer and NCG that many people would use MM but that they are terrified of 2v2. Technically we can split these queues so may as well test it out. The UI could make it clear that people should queue for many things, I am unsure how though.

**Comment by GoogleFrog** [comment]
Unfortunately I don't have the ability to edit the UI that most players are using. I think SWL etc.. usage is seriously hurting any attempt to get MM used at the moment. With this in mind the 3v3 and 4v4 queues should not be split.

**Comment by GoogleFrog** [comment]
Here is a PR https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/1382

I went with split 3v3 and 4v4 for simplicity.

**Comment by db81** [comment]
SWL does try to make it clear that you queue for many things:
![swl_queue_select](https://cloud.githubusercontent.com/assets/2241548/21962142/0fe5e6be-db6a-11e6-83c0-3e1d08b6f3f4.png)

**Comment by Licho1** [comment]
done by gf pr
