### ISSUE TITLE
Chili Share Widget consumes H key

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1383]
This is in conflict with Integral Menu which uses H for its hotkeys (e.g. ZH for Strider Hub). Both widgets are default, so they should not conflict.

The use of hotkey by Chili Share Widget is also unconfigurable, so i can't even disable this behaviour.

**Comment by sprunk** [comment]
wrong repo https://github.com/ZeroK-RTS/Zero-K/issues/1828
