### ISSUE TITLE
Consider new punishment: No hosting rights / Can't join battle with player X in it.

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#1384]

**Comment by sprunk** [comment]
= lobby ban

**Comment by Licho1** [comment]
There is already bazilion of punishments, we need less not more imo..

**Comment by ArchShaman** [comment]
If cannot join battle with player X won't be implemented as a player punishment can I ask for a blacklist instead? The use case would be in event a player does not wish player X to join their games, they could put player X on the blacklist and chobby/whatever would automatically kick player X from a game.

**Comment by sprunk** [comment]
Make a passworded room to prevent unwanted people.

**Comment by ArchShaman** [comment]
Passworded room blocks everyone though. Why block everyone when it's desired to only block 1 person? That and handing out passwords is work and doesn't achieve the desired affect. I feel it would be an easy thing to implement in Chobby. Just scan battle playerlist for player X, issue kick if host. Maybe it would be even better to implement ban lists on hosts and automatically add the banlist on host creation? A !ban command for hosts would go a long way I feel towards providing players solutions for dealing with undesirables rather than relying on a 5min ban/passwording a room.

**Comment by sprunk** [comment]
>A !ban command for hosts would go a long way I feel towards providing players solutions for dealing with undesirables rather than relying on a 5min ban/passwording a room.

You can have people banned by making a report.

**Comment by ArchShaman** [comment]
I've made several reports today about a certain player harassing me and kicking me from my own game using smurfs. These were not responded to.

**Comment by sprunk** [comment]
>These were not responded to.

That is a problem with the admin team and not rooms.

>using smurfs

None of the methods you propose help against smurf takeover.

>One should not have to rely on admin action to take care of undesired elements.

The admins decide who is undesired in public rooms.

**Comment by ArchShaman** [comment]
Then how about kick immunity for hosts?

**Comment by sprunk** [comment]
Sounds fine.

**Comment by sprunk** [comment]
#1385

**Comment by ArchShaman** [comment]
Great. That's a step towards solving the issue. Thanks.
