### ISSUE TITLE
Party invite response technicalities

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1393]
When should the party invite window be destroyed?
 * Timeout after 60s destroys.
 * What if the user who sent the invite leave the party? Goes offline?
 * What if my party status changes?

On the UI side of things, what if the composition of the party to join changes. Say this happens:
 * Receive an invite, party you are being invited to contains players X and Y. They are shown on the invite UI.
 * 10 seconds later player Z joins the party. Your invite UI should update.

This means the player needs to see the partyID that they are to join (if such a partyID exists). However, what do you do if the players in the party leave the party and join different ones?

**Comment by Licho1** [comment]
You join the original inviter. 
That means if the player leaves meanwhile you will join a party where he is now, If party is disbanded you will form a new party with the player.
If player leaves completely, nothing will happen.

Your protocol suggestion didn't include any other messages so I think its fine.. 
Those are all edge cases (player leaving game meanwhile)
