### ISSUE TITLE
Install HTTPS to website

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1398]
This is now required due to new google policy:

Quote from email:

Beginning in January 2017, Chrome (version 56 and later) will mark pages that collect passwords or credit card details as “Not Secure” unless the pages are served over HTTPS.

The following URLs include input fields for passwords or credit card details that will trigger the new Chrome warning. Review these examples to see where these warnings will appear, and so you can take action to help protect users’ data. The list is not exhaustive.

http://zero-k.info/Battles/Detail/443813

http://zero-k.info/Battles/Detail/443822

http://zero-k.info/Battles/Detail/443894

We should investigate this CA:
https://letsencrypt.org/
to check it works on android and more obscure browser, if it does i can install it's certificate.

**Comment by Anarchid** [comment]
https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394/7

XP and Android 2.3 are screwed. But android 2.3 doesn't support Spring's certificate either, and is probably by now rarer than Gentoo.

**Comment by Licho1** [comment]
Completely walling off windows xp .. i dont know..

**Comment by Anarchid** [comment]
> Windows XP SP3 - Requires some extra work to support. Does not support SNI, and is also problematic regarding supported ciphers. Certificates issued prior to March 25 2016 were not trusted by Chrome, IE, and Safari on XP SP3. However, certificates issued after that date can work with XP SP3166 if you manually configure ciphers.

Doesn't seem like complete walling off. Perhaps the people who opt to stay on WinXP 17 years after its release can be expected to perform some certificate / service pack installing to keep up their morbid dependency.

**Comment by db81** [comment]
XP users will just have to add exceptions manually like with self-signed certs. People who are too paranoid to do that but don't consider using XP a security risk can be ignored. Also doesn't Chobby fail to work on XP anyway?

**Comment by Licho1** [comment]
Ok https://zero-k.info  now works. There is no redirect.
