### ISSUE TITLE
Wrapper should deploy AIs.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1400]
The wrapper should deploy some AIs, since they are all better than CAI. We could have an AI upload system similar to the engine upload system on the ZK site. Each AI uploaded would have a name, a version and a tickbox controlling whether it should be fetched by the wrapper. We should decide on a formation for the AIs to be uploaded in. I would like to place them in AI/Skirmish/<name>/<version>. The steam package could be done such that the AIs are built in and the wrapper need only check for new ones.

**Comment by sprunk** [comment]
Are they to replace CAI? One useful feature of CAI is that it does not require a host. If we wanted to use the MM interface for bot games we'd have to use LuaAI.

**Comment by Licho1** [comment]
@GoogleFrog  sounds ok
@sprunk  MM with bots? Whaat?  In that case wrapper would make sure all people have all the AIs . .they would simply be part of default installation, like missions.

**Comment by sprunk** [comment]
Yes, but someone still needs to be the host. Skirmish AIs tend to be very CPU intensive so someone will have way higher CPU load than normal for no apparent reason.

**Comment by GoogleFrog** [comment]
MM with bots is not relevant to this ticket since CAI will still exist.

The git formatting ate part of my specifications so here it is again. Each AI uploaded has:
 * A file (7z ok?).
 * A Name.
 * A Version.
 * A tickbox which toggles whether to deploy to users.

The ticked AIs serve as a list of AIs to deploy. Each should be downloaded and up in AI/Skirmish/NAME/VERSION if there is no AI already present matching the Name and Version. The Chobby UI will display only the most recent version by default. This is so we don't end up deleting anything someone is working on.

**Comment by Licho1** [comment]
Does it mean that multiple versions of the AI might be deployed? 
It will also need rules about how/where to deploy them

**Comment by Licho1** [comment]
It does deploy AI, reference them in "LuaMenu/configs/gameConfig/zk/defaultSettings/configversions.json"
