### ISSUE TITLE
Map indexation broken again

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1401]
A bunch of maps was released on December 30th 2016: https://springrts.com/phpbb/viewtopic.php?f=81&p=580695#p580695

None of them are discoverable or hostable in ZK yet.

I tried grepping server trace logs for their names, and found nothing.

**Comment by sprunk** [comment]
ZKI indexes maps correctly as long as SF exposes them properly. https://zero-k.info/Maps/Detail/54528

**Comment by Anarchid** [comment]
The three other maps from this series seem to have not been indexed. I am not certain this is a SpringFiles issue, see the logs in #1405.

If it is a SpringFiles issue, it still could be fixable ZKI-side if the exact nature of improperness of exposure by SF is known.

**Comment by sprunk** [comment]
>The three other maps from this series seem to have not been indexed

As expected. That's because I only inflicted that one and not the others.

**Comment by Anarchid** [comment]
Using remote url workaround?

**Comment by sprunk** [comment]
Remote URL

**Comment by Licho1** [comment]
worksforme now
