### ISSUE TITLE
Deleting sole battle comment does not remove the thread

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1403]
See http://zero-k.info/Battles/Detail/443770 - there is no post (something was posted and got deleted) but the empty thread still shows up on thread list http://zero-k.info/Forum .

**Comment by sprunk** [comment]
@DeinFreund d7490a83bea031e6fc939778791ff163eb0401b9 and 96aff4a6f4013221469621a06e57b8cbc5e0a558 ?

**Comment by DeinFreund** [comment]
Tested. Works now.
