### ISSUE TITLE
Wrapper crash after version check

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1404]
Azur3d said that the wrapper crashes after the version check is complete (so he can see the window). Here is the message.

![rwjsuxet7](https://cloud.githubusercontent.com/assets/1318249/22397081/6ccbd192-e5bd-11e6-976f-91f7f5779ebc.png)

**Comment by Licho1** [comment]
What does it say?

**Comment by GoogleFrog** [comment]
Mantis ticket with a translation: https://springrts.com/mantis/view.php?id=5442

**Comment by Licho1** [comment]
Was it linux? Which user launched the wrapper, did it have permissions to the folder where it was? Did it create engines/version folder with spring in there?
What are permissions of "spring" file there?

**Comment by db81** [comment]
The chat log: http://pastebin.com/ExwkyEp0

**Comment by Licho1** [comment]
fixed
