### ISSUE TITLE
Add wrapper offline mode

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1406]
Players should be able to launch chobby without internet and play everything in the SP menu.

**Comment by Licho1** [comment]
Wrapper wont download anything new with steam, so yeah i think it will be done automagically once we switch to steam. Keeping to verify it works as intended when done.

**Comment by Licho1** [comment]
Wrapper is in pure offline mode if launched from steam folder.
This is detected by a presence of steamfolder.txt
