### ISSUE TITLE
Scary .NET message during install

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1407]
Most users receive a message during install that says "Cannot continue installation, .NEt 4.5.2 or later already installed". This is a scary message that makes them think something is broken. In fact this message is merely thrown by the .NET sub-installer in response to the main installer trying to install .NET. To finish their installation users just need to click "OK" to exit out of the .NET installer and return to the main one.

This is pretty scary, idk how many players have been lost over it. The installer shouldn't try to install .NET when it is already installed. I thought I made a ticket about this a few weeks ago but apparently it was lost.

**Comment by Licho1** [comment]
Detection is there but it fails (was added years ago by xponen), need to re-check.

This is a detection I used in some other recent project:

> reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319\SKUs\.NETFramework,Version=v4.6.1" 2>nul
> if errorlevel 1 (
>     echo Instaluji .NET
> 	dotnet461.exe /q /norestart
> 	
> ) else (
>     echo .NET installed
> )
>
