### ISSUE TITLE
Limit !game and !engine usage in hosts

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1408]
People can !game and !engine to any old broken thing and then cause complaints about bugs. Idk what the best limiting scheme is though.

**Comment by DeinFreund** [comment]
People don't know about !game and !engine. People only use commands that are buttons in chobby.

Everyone else is "Dev"

**Comment by GoogleFrog** [comment]
See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1409

**Comment by Licho1** [comment]
1409 is a bug, it should refuse to change engine and not claim its doing something.

For steam we can consider having stable and beta versions. With stable people would be forced on current defaults synced with server. On beta they would connect to test server and have access to any breaking command they like.

**Comment by Licho1** [comment]
They can also only do so on custom hosts.
