### ISSUE TITLE
Cannont host ZK more recent than v1.5.2.5 in multiplayer

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1411]
Singleplayer games run v1.5.2.7 so the wrapper is downloading the latest game correctly. !game zk:stable in MP rooms sets the game to 1.5.2.5.

**Comment by Licho1** [comment]
Related to unitsync failure due to 64bit engine.

**Comment by GoogleFrog** [comment]
I haven't been uploading 64 bit engines.

**Comment by Licho1** [comment]
They probably infected the registrator thingie, it's using the engine valid when server starts afaik or osmething like that

**Comment by Licho1** [comment]
No, server is fine, it is isuse with pr-downloader used by chobby or with chobby, server can host it and knows those versions. 
You can switch to use wrapper's dl but better to just fix pr-downloader.
