### ISSUE TITLE
Redundancy in JoinChannelResponse

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1412]
JoinChannelResponse {"Channel":{"Users":["GoogleFrog","Test1234"],"ChannelName":"bla","Topic":{"SetBy":"GoogleFrog","SetDate":"2017-02-04T05:45:42.5126703Z","Text":"bla"},"IsDeluge":false},"ChannelName":"bla","Success":true}

ChannelName is sent twice. I guess there is not much to do about it though since non-supported lobbies might break.

**Comment by Licho1** [comment]
inconsistency is because if there is error joining channel, there is no channelheader at all and you need to know which channel join has failed
