### ISSUE TITLE
When are all the initial Users sent?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1415]
Currently I am using MatchMakerSetup to trigger stored steam friend command since by this time all Users seem to be sent. Something less prone to breaking should be arranged.

**Comment by Licho1** [comment]
What would you suggest?

**Comment by db81** [comment]
Initial users could be sent in a single command.

**Comment by Licho1** [comment]
Wait for FriendList
