### ISSUE TITLE
I have not managed to make AIs deploy from luamenu.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1419]
I ran http://test.zero-k.info/lobby/Chobby.exe with no dev parameters and a stable version of luaMenu that has the new deploy profile format. No AIs were added.

**Comment by Licho1** [comment]
Worksforme, however rapid is not deploying some chobby builds correctly. Verify what zkmenu version you are actually running with.
