### ISSUE TITLE
Friends list is now much less interesting

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1423]
Here the friends list of Test1234 <FriendList {"Friends":[{"Name":"Test1234"},{"Name":"Test1234"},{"Name":"Test1234"},{"Name":"Test1234"}]}

Here is my friends lists <FriendList {"Friends":[{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"},{"Name":"GoogleFrog"}]}

**Comment by Licho1** [comment]
friendness reversal fixed in master
