### ISSUE TITLE
Fix letsencrypt https certificate renewal

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1427]
The program "letsencrypt", when it completes check, waits forever for "enter" in console and keeps website disabled.
This happens even if it runs without console.

**Comment by shaun0x00** [comment]
Maybe it's not the right tool for the job?

https://weblog.west-wind.com/posts/2016/feb/22/using-lets-encrypt-with-iis-on-windows#What%27savailableonWindows

**Comment by Licho1** [comment]
We ar eusing lets encrypt simple win.
Issue is on this line, it just needs tweak + recompile:

https://github.com/Lone-Coder/letsencrypt-win-simple/blob/master/letsencrypt-win-simple/Program.cs#L164

**Comment by Licho1** [comment]
some param switch to not wait for key if its renewal run by scheduler and not interactive run by user.

**Comment by Licho1** [comment]
lame fixed by giving the process 1h to exit in scheduler
