### ISSUE TITLE
Updating mission with different map fails to change specified map on site

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1428]
Original versions of the [User Interface Tutorial](http://zero-k.info/Missions/Script/226) used TitanDuel. I changed this to Icy Run in revision 3, but while all content within the mod archive itself and the listed map on mission page were updated to use the new map, http://zero-k.info/Missions/Script/226 and the missions.json entry were not.

Manually updating the script in DB has resolved the immediate issue.

**Comment by Licho1** [comment]
Was revision number bumped by this? How did you change the map?

**Comment by KingRaptor** [comment]
I changed map (among other things) in Mission Editor and then attempted to publish a mission, but there was already an existing mission with the same name so it updated that instead. I don't yet know if updating it "properly" would have the same issue. Revision number was incremented AFAIK.

Another issue was that it didn't seem to update the teams in startscript; see ZeroK-RTS/Chobby/issues/119.

**Comment by Licho1** [comment]
Well is it reproducible?

**Comment by KingRaptor** [comment]
Reproduced with [this test mission](http://zero-k.info/Missions/Detail/164). [This](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/5ddec86591302bf858ac6c2f1e362a46952f0235/Zero-K.info/MissionService.svc.cs#L88)
code function is consistent with observations that it doesn't update any part of the script other than the "game" tag.

**Comment by Licho1** [comment]
I don't understand what is missing from where. There seem to be several copies of script and some stuff only needed for old ZKL.
As far as the code goes, map should update in both DB entry, script entry in DB (if script sent), script entry in mutator (if sent).

So where does it not update? And where does it cause failure?

**Comment by KingRaptor** [comment]
Previously:
- What gets changed: script in .sdz, map name in DB
- What does not get changed: script in DB (I assume this is what is sent to Chobby)

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/734cadcee6c6f2911ac653a23bf0731f0f64313f seems to have fixed it, so closing.
