### ISSUE TITLE
Can't access chobby while the game is running.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#1440]
F11 or clicking on the lobby button doesn't work.

**Comment by Orfelius** [comment]
It works now? It seems to be fixed now, closing.

**Comment by GoogleFrog** [comment]
I noticed this once too, it appears random. I added some logging to try to catch where it fails so attach your infolog from that run of chobby.

**Comment by Orfelius** [comment]
http://pastebin.com/0qXZxgCw
The infolog of that session.

**Comment by GoogleFrog** [comment]
SendLuaMenuMsg showLobby is the only debug output. This implies that the message never reaches LuaMenu.

**Comment by Licho1** [comment]
I dont think that is even possible, could it be old chobby or old engine?

**Comment by Licho1** [comment]
Need enigne/menu versions and ideally reprosteps too. Also does not belong to infra most likely. Closing.
