### ISSUE TITLE
MM 1v1 is always on Obsidian

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1447]
Somehow we just got Obsidian 4 times in a row. Is this intended behaviour?

**Comment by Anarchid** [comment]
I haven't noticed it being only Obsidian. The matchmaker pool for 1v1 seems to be 24 maps, so that's a pretty huge coincidence if so.

Try a couple more times?

**Comment by DeinFreund** [comment]
Is there any chance for the RNG to be initialized/return the same when it's always the same players and only a few minutes time difference? I have no idea how this could happen, but it lead for us to stop playing as this gets boring quickly.

**Comment by Anarchid** [comment]
Hm, so you exited all of those games?

**Comment by DeinFreund** [comment]
Might be related, we played 2 and then exited the rest.

**Comment by Licho1** [comment]
What was the team size?

**Comment by DeinFreund** [comment]
http://zero-k.info/Battles/Detail/446099
http://zero-k.info/Battles/Detail/446100

**Comment by Licho1** [comment]
There is some logic picking map based on team size. Otherwise it seems to work (random is seeded by time)
