### ISSUE TITLE
Very low-level accounts can probably vote in polls

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1449]
_Shaman claimed Chesti used additional accounts (one or more) to make polls pass. I think they were very low-level accounts. Using them in such a manner used to be impossible.

**Comment by Licho1** [comment]
? what polls? Anybody can vote in polls, i dont think any of them were ever restricted.
Tell me what you did and what happened and what you expect to happen.

**Comment by Sgathec** [comment]
Actually I didn't test it (yet). Sorry, I need to go and sleep now.

**Comment by Sgathec** [comment]
Not sure if a level restriction is good way to prevent abuse, but I think it's too easy to illegitimately gain additional influence in a poll.

**Comment by Licho1** [comment]
I still have no answer: what poll is this about? We have lot's of different polls in different places...

**Comment by Sgathec** [comment]
I was talking about any custom room poll.

**Comment by Licho1** [comment]
Anybody can vote there. Expected behavior.

**Comment by Sgathec** [comment]
Please add something to prevent abuse. I think Steam will increase the (potential) amount of it.

**Comment by Licho1** [comment]
We can disable polls then

**Comment by db81** [comment]
If Chesti is abusing polls the solution is not to disable polls, it's to disable Chesti.

**Comment by Licho1** [comment]
What i meant is for host owner to have option to disable it.

**Comment by db81** [comment]
That sounds fine.

**Comment by sprunk** [comment]
I think polls should be disabled by default and enabling would be optional. This is how rooms work in every other game.

**Comment by Licho1** [comment]
Sounds reasonable but might encounter some resistance.. but it could be that way .. and when owner leaves polls would be auto enabled.

**Comment by Licho1** [comment]
But room could become stuck waiting for hos to start...

**Comment by Anarchid** [comment]
No reason to do it immediately imo.

**Comment by sprunk** [comment]
Owner leaves with voting disabled -> close room (like in every other game).

**Comment by Licho1** [comment]
That is the reason why autohosts were invented in the first place. It is very annoying to close running battle or even a lobby with people. But yes it can be done when game is not running. What others think about it?

**Comment by sprunk** [comment]
I didn't say close running battle, just close the lobby room (if voting is disabled, so that "public" rooms won't even close).
