### ISSUE TITLE
Steam login button is missing image

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#1453]
http://i.imgur.com/4UkRB2q.png

Name OR Password?
I suppose this is intended to allow logging in with Steam OR ZK account but I only got this when I mouse overed the two buttons as I was trying to figure out what they do

**Comment by shaun0x00** [comment]
https://www.w3schools.com/tags/att_img_alt.asp
https://www.joedolson.com/2015/03/are-alt-attributes-required-always/

**Comment by Licho1** [comment]
fixed
