### ISSUE TITLE
Nightwatch over-eagerly sets Discord channel topics

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1454]
NW sets server status as topic for #zk, #zkdev, #ai, and #sy.

It only should do this for #zk. The other channels could use proper descriptive topics.

**Comment by Licho1** [comment]
I made it on purpose because i often want to see it in zkdev too.. but it could also copy existing channel topic or show numbers in its own status topic.

**Comment by Anarchid** [comment]
My concern is that because there are only 4 channels, a lot of people join every channel and then,  without the topic to guide them, discuss whatever. For example, Chobby crashes in #ai.

**Comment by Licho1** [comment]
fixed, now channel topic gets into discord
