### ISSUE TITLE
Bad script password.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1455]
See https://github.com/ZeroK-RTS/CrashReports/issues/102

Cannot connect to game due to bad script password.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/101

**Comment by Licho1** [comment]
Cannot imagine how could this happen, needs more feedback if it happens again.

**Comment by GoogleFrog** [comment]
Watch crash reports. Keeps happening.

**Comment by Licho1** [comment]
What password is it? Script password or game password?

**Comment by GoogleFrog** [comment]
Remote requested quit: Connection rejected: Incorrect password

Whatever it is that lets you connect to springie.
