### ISSUE TITLE
Site login UI is confusing.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1460]
It is not clear what the options are and how to do each of them. I'll put screenshots and further explanation in later, if required.

**Comment by Licho1** [comment]
duplicate, its a broken steam image

**Comment by GoogleFrog** [comment]
It's not just that.

**Comment by GoogleFrog** [comment]
I'll comment further when I can see where the steam image goes. I doubt a steam image will fix it though.

**Comment by Licho1** [comment]
as always, you can see the future.
Future is here: http://test.zero-k.info/

**Comment by Licho1** [comment]
fixed
