### ISSUE TITLE
Rejoin button.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#1462]
If you quit the game (but not resigned) for example due to a crash there should be an easy way to rejoin the game without searching it in the room list. The most reasonable way to do this would be adding a rejoin button which would be located in the top part of the Chobby.

**Comment by Orfelius** [comment]
Why close this? This is a real issue even if it might not be of the highest priority.

**Comment by Licho1** [comment]
Because I'm not very interested in implementing this before steam release...

**Comment by db81** [comment]
This can probably be done completely chobby-side (save battle id when starting, delete when exiting normally, if chobby starts with an id saved, prompt user to rejoin).

**Comment by Licho1** [comment]
It can be done by chobby yeah.

**Comment by Orfelius** [comment]
Yes, I misunderstood your intentions in the first place since there was no comment from you why you closed this issue. You already copied it to the Chobby repo so I'm just gonna close this one because of duplication.

**Comment by db81** [comment]
@Licho link to the new issue in chobby repo to prevent Orf confuzzlement when you do that. The syntax is `ZeroK-RTS/Chobby#133`.

ZeroK-RTS/Chobby#133
