### ISSUE TITLE
Update needed on site for commander module tooltips.

### ISSUE THREAD

**Issue by Kingstad** [ZeroK-RTS/Zero-K-Infrastructure#1463]
Shockrifle for guardian com even though it cant get particle beams in the first place.
Probably should be mentioned that moduels like shield and cloak cant coexist
Napalm warhead mentions plasma artillery even though it is no longer available, also it increases blast radius something that isnt mentioned.
Concussion shell is only available to recon com.

**Comment by Anarchid** [comment]
I did the following:
- napalm warhead no longer mentions plasma artillery, instead mentions aoe buff
- removed shock rifle from guardian
- removed concussion from strike and support

It's not convenient for me to edit multiline entries atm. This would be required to add a shield/cloak incompatibility message.

**Comment by KingRaptor** [comment]
I've added a mention of not working with shield to Personal Cloak description.
