### ISSUE TITLE
Redesign new user download

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1467]
The big "Download" button on logged-off zero-k.info should simply download ZK. In other words, it should do this http://zero-k.info/lobby/Zero-k.setup.exe

The giant "Download" button on the main page should instead have the title "Download Zero-K" because often you'll be on a site with ads with several competing download buttons. The button should make it clear that it is an official site element.

Underneath the big "Download" button there should be another button with "Linux Download" written on it. This button should be about half the height of "Download". It should take users to this page: http://zero-k.info/Wiki/Download

The download page should be split into the main page and the alternatives page.

**Comment by Licho1** [comment]
Clicking download leads to DL page which auto starts DL.
DL page extremely simplified.
(DL page allows easier tracking by google analytics)
