### ISSUE TITLE
Put ZK game development on user activity charts

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1468]
I think units, features, factories and general game development activity improve retention because there is new stuff to see. Test this by adding these events to charts.

**Comment by Licho1** [comment]
im not sure how to get this, its hard to estimate rate of evolution even from commit counts.. it needs human brain i fear

**Comment by Anarchid** [comment]
VERSION commits to game repository which are not minor with non-minor digits of the VERSION string different should match ZK releases pretty well where they would impact users. I don't think anyone cares about things committed to github.

**Comment by Licho1** [comment]
VERSION is based on year and month

**Comment by Anarchid** [comment]
Minor digit of VERSION is sequential within the major version. So it should be disregarded.

**Comment by Licho1** [comment]
I think someone would have to define it (feel free to edit the google docs table with events). 
Commit count alone does not mean anything.
