### ISSUE TITLE
ChobbyLauncher detect Java

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1472]
There should be a way to automatically check for a 32 bit JRE and redirect users to the download page when they're trying to use a Java AI in Chobby.

(@Anarchid This is how minecraft does it)

**Comment by GoogleFrog** [comment]
Chobby launcher should not download Java.

**Comment by DeinFreund** [comment]
What then? Spring?

**Comment by Licho1** [comment]
we could distribute java ai that will work for people who have java alreayd installed, is that ok?

**Comment by DeinFreund** [comment]
Then you'd still have to check for Java, or how do you know if it's installed? I don't think Chobby(wrapper) should even auto install java, just tell people if they need it. If you think it's easier to give java ai to people with java than give a pop up to people without java then that works as well I suppose.

**Comment by Licho1** [comment]
Wrapper can detect java, if you want we can send JRE version to chobby to decide further.

**Comment by DeinFreund** [comment]
That'd be all it needs to do. Make sure to check 32 bit versions only (64 when using 64 bit spring, but that's buggy)

**Comment by Licho1** [comment]
Tell me please how to best do it, should i read registry? What about linux?

**Comment by DeinFreund** [comment]
Check environment vars: `JAVA_HOME`, `JDK_HOME`, `JRE_HOME`
Check registry (windows): HKEY_LOCAL_MACHINE\\Software\\JavaSoft\\Java Runtime Environment
Check common locations(linux): https://github.com/spring/spring/blob/d1c40f3b3893fcb90cb492615f216d8a85a0b577/AI/Interfaces/Java/src/main/native/JvmLocater_linux.c#L167

You can find the complete implementation here:
https://github.com/spring/spring/blob/develop/AI/Interfaces/Java/src/main/native/JvmLocater_common.c

**Comment by Licho1** [comment]
Sounds like too much work just to detect java. Feel free to implement and test the needed multiplatform class.

**Comment by DeinFreund** [comment]
Would #1484  help you with that or is the protocol also an issue?
