### ISSUE TITLE
Generalized MM penalty

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1473]
MM Ban should be givable by admins like other penalties and probably include playing in public rooms.

This would allow excluding players from playing while not excluding them from chat which makes everything dev very annoying. It'd also allow Matchmaker to look at previous MM bans to determine the length of next ban.

**Comment by Licho1** [comment]
Banned people should not be able to chat.
We have like 8 types of penalties .. more than offenders.
MM should autoban inactivity though.

**Comment by DeinFreund** [comment]
Anyway MM needs to increase penalties if the previous ban was recent. 

Then it should also be informed on things like quitting before game start, going afk for more than a few minutes and getting kicked from games(log, not punishy).
