### ISSUE TITLE
BotStatus does not support Version

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1479]
Bots can share ShortName and be differentiated by version. The Version key in script.txt enables the version to be set. UpdateBotStatus should allow for setting/getting Version.

**Comment by GoogleFrog** [comment]
It seems that the highest version is used by default but that might just be luck.

**Comment by Licho1** [comment]
What? There is a version? I thought that in our protocol they are discriminated by name. Why to add separate version from name?

**Comment by GoogleFrog** [comment]
Version is how Spring does things for AI updates.

**Comment by Licho1** [comment]
wut? What AI updates? I thought we deploy them.. so you want some optional "version" field in script? Why is it useful?
We control AIs so we will replace existing entry with new one (no point having extra folder and outdated AIs .. we have versioning in json file for that).

So client will always pick the single AI it has.. why do you need versions?

**Comment by Licho1** [comment]
we will override
