### ISSUE TITLE
Error upon starting dev chobby with zkmenu:test

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1480]
I changed the ' dev' argument of my chobby to ' zkmenu:test' and got this error.

![error](https://cloud.githubusercontent.com/assets/1318249/23124983/d91e6928-f7c3-11e6-9bd1-32a3cae01a58.png)

**Comment by GoogleFrog** [comment]
Any attempt to start this chobby has the same error now.

**Comment by GoogleFrog** [comment]
The same error occurs when I copy my main chobby to dev.

**Comment by Licho1** [comment]
delete steamfolder.txt
