### ISSUE TITLE
Transmit donator/contributor info in StartSetup to ingame

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1482]
So player list can display rewards.

Licho also mentioned marking devs/contributors. For that we'd probably need a new bit that can be set in the DB. If implemented this should also be transmitted to the game.

**Comment by Licho1** [comment]
I think we should send "badges" directly so that its more universal.
Server will decide what badges to give and we just send list of icons

**Comment by Licho1** [comment]
done, sending badges.
