### ISSUE TITLE
Steam unable to launch ZK on Linux

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1489]
After launching steam to link account, Steam decided to update ZK. Assuming that this meant it may start working (which it previously didn't) from Steam, i clicked "play" after download completed.

This happened:

![image](https://cloud.githubusercontent.com/assets/3822768/23144963/d06605b0-f7d3-11e6-8f97-55d06db0628e.png)

Suspecting something bad may have happened during update, i then uninstalled ZK and downloaded it fresh. The problem persisted, so i restarted steam and reinstalled again, to no avail.

Linux flavor is ubuntu 16.10.

**Comment by Anarchid** [comment]
Invoking `mono Chobby.exe` from the folder where Steam installed ZK seems to work. So it just doesn't know to use mono / Chobby.exe is not an executable under Linux perhaps?

**Comment by Licho1** [comment]
Executable on linux is set to Chobby.sh 
please verify that the file exists and is launched by steam correctly.

**Comment by Licho1** [comment]
And try executing it in steam folder.

**Comment by Anarchid** [comment]
I've redownloaded everything again. Now this happens:
![image](https://cloud.githubusercontent.com/assets/3822768/23188627/17e6a984-f898-11e6-9497-a610c651b0ba.png)

**Comment by Licho1** [comment]
its fixed in test, switch steam to test branch to test.

**Comment by Anarchid** [comment]
Confirmed, works!
