### ISSUE TITLE
Steam ZK: CircuitAIHard64 not functional on Ubuntu

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1497]
I used the skirmish wizard to create a hard game on Onyx. This set me up against CircuitHard64.

On starting the game, it immediately ended due to AI "resign". There were no crash traces in infolog, however, this seems relevant:

```
[f=-000001] Loading Skirmish AIs
[f=-000001] Error: Unknown skirmish AI specified: 
```

Also see complete [infolog.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/792505/infolog.txt).

**Comment by Licho1** [comment]
please verify local copy with steam and try again, its fixed.
