### ISSUE TITLE
Consider moving steam button to the right and making pressing Enter submit login when focus is on password field

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1499]
User request. See https://zero-k.info/Forum/Thread/23670

**Comment by Licho1** [comment]
Since steam is primary it should probably be the other way around. But currently it isn't very nice ..

**Comment by db81** [comment]
Is steam acc <-> zk acc 1-to-1 or can a steam acc have many zk accs? Do you need to fill the name field if you're logging in through steam? Right now it suggests that.

Ideally you'd do something like "<img sign in with steam> or Zero-K name: [........] password: [........] <log in button>" if you want to convey steam as primary.

It should also create a new zk acc if there's none found linked when you sign in with steam, everyone expects that and no one reads the tooltips about registering ingame. If there's a name collision it should ask "What do you want your zk name to be?" and then the user should never have to enter that name again.

**Comment by Licho1** [comment]
Atm its 1-n ..
1 steam multiple ZK thats why we need login.
But we might also make it 1:1 for better clarity i guess..

**Comment by sprunk** [comment]
Wont "1 steam multiple zk" make it easy to smurf? With 1-1 at least you need to make a new steam account.

**Comment by Licho1** [comment]
done
