### ISSUE TITLE
Steam chobby fails to start on ubuntu

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1500]
Using the test branch, trying to start zk results in the following:
```Chobby.exe Information: 0 : Rapid package appears to be corrupted, please clear the folder```
Deleting rapid and veryfying local files so that steams downloads it again doesn't resolve the issue.

**Comment by db81** [comment]
Fixed, but now the use steam auth checkbox is missing from the login dialog. Maybe just the WIP state of test chobby.

Also yay, I got two zeroes!

**Comment by Licho1** [comment]
Damn that should not happen.. some lib isnt loading i guess :(

**Comment by KingRaptor** [comment]
Also having missing Steam auth checkbox on Linux (including with Steam running and even launching from Steam)

**Comment by Licho1** [comment]
fixed
