### ISSUE TITLE
Reflect inactivity in rank icon

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1502]
Once a player no longer qualifies for the MM rankings, his rank icon should also show unranked status. Otherwise the rank icon may show a completely wrong rating which would be misleading in casual games.

**Comment by db81** [comment]
And once they play a single MM game it's enabled again and still can be completely wrong. Have a confidence parameter that gets reset after inactivity and decreases with games played, and for confidence < X you show a gray icon while still tracking elo?

**Comment by DeinFreund** [comment]
Hm, have a rating system that reflects confidence?

**Comment by db81** [comment]
Nice paper. Can just have confidence only affect the displayed icon at first before/if someone tries to implement that.

We can try to graph elo value together with period of inactivity for people and see how much of an effect rust really has. Maybe the "completely wrong" is actually only slightly wrong.

**Comment by DeinFreund** [comment]
I'll see if I can get an implementation working. Then I'll post comparison with elo to ratings thread.

**Comment by Licho1** [comment]
Implemented elo weight decay now. 50 elo per week in effect up to 250
