### ISSUE TITLE
BB tags don't work inside tables

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1508]
Tags start getting printed as plaintext.

**Comment by sprunk** [comment]
loled

**Comment by DeinFreund** [comment]
How would you be surprised enough to laugh?

**Comment by Licho1** [comment]
Which tables? With html tables it seems to be working.

**Comment by Licho1** [comment]
I would scrap BB really but.. backwards compatibility..

**Comment by sprunk** [comment]
Would it be possible to just replace for example [b] with <b> in all posts globally to solve backward compatibility?

**Comment by Licho1** [comment]
Probably not safely for the same reasons it does not display properly.. i mean to do it we need a way to display properly..
DeinFreund please provide text example of code that is failing.

**Comment by Licho1** [comment]
Faulty report, worksforme. Probably not well-formed table, next time provide replication data.
This works:
||asdsa||[b]asdasd[/b]||
||a[b]sd[/b]as||<b>asdasdad</b>||

With html table too too

**Comment by DeinFreund** [comment]
Ok seems to be all working fine, maybe I had a syntax error. Sorry.
