### ISSUE TITLE
Late joining spectators (always the case in MM) don't have custom player keys (rank, elo, badges)

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1509]
Would be nice if there was a way to add this into the game during run time. 

Currently all these attributes are set in startscript.

**Comment by Licho1** [comment]
There is no easy way to pass that data to client. It would need extra transmit over some external channel so I think its not worth it.
What others think?

**Comment by DeinFreund** [comment]
If Spring doesn't support this when adding players I wouldn't invest too much into this either. This could be used to sort specs by rank or badges in games with many specs(tourney).

**Comment by Licho1** [comment]
Like i would need to send it as lua message in json and lua would need to parse it. If you make the lua part i can make the rest.

**Comment by Licho1** [comment]
Closing unless there is LUA to process it.
