### ISSUE TITLE
Test site uses main site's certificate

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1510]
Untrusted connection when connecting to the test site over https:

 >test.zero-k.info uses an invalid security certificate.
The certificate is only valid for zero-k.info
(Error code: ssl_error_bad_cert_domain)

**Comment by Licho1** [comment]
Hmm does it matter? Probably no point giving it extra cert...

**Comment by sprunk** [comment]
Slight inconvenience, nothing crucial

**Comment by Licho1** [comment]
Probably not worth fixing then. We could disable https on test too but i guess it could be useful in some cases.
