### ISSUE TITLE
Friend list isn't updated

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1511]
Sometimes when setting account relations, there's no freund list in response. Leading to chobby not updating.

> [20:51] >SetAccountRelation {"TargetName":"hokomoko","Relation":0}

**Comment by Licho1** [comment]
Relation 0 is removal

**Comment by DeinFreund** [comment]
It still needs to be removed from friend list..

**Comment by Licho1** [comment]
Oh that would be chobby issue then, friend list is always sent full.

**Comment by DeinFreund** [comment]
But the friend list isn't sent at all after removing friends. So the last friend list still includes the now removed friend.

**Comment by DeinFreund** [comment]
To reproduce, try unfriending an offline person.

I've also noticed this happening when friending an offline person, but in that case it may be intented behaviour.
