### ISSUE TITLE
Test server error on register

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1514]
[f=-000001] Login
[f=-000001] LuaMenuServerMessage, >Register {"PasswordHash":"REDACTED","Name":"FroogleGog"}
[f=-000001] LuaMenuServerMessage, >Login {"LobbyVersion":"Chobby","Name":"FroogleGog","UserID":0,"PasswordHash":"REDACTED","ClientType":1}
[f=-000001] OnConnected
[f=-000001] LuaMenuServerMessage, <Welcome {"Engine":"103.0.1-648-g5775975","Game":"Zero-K test-12490-e85c531","UserCount":0,"Version":"0.0.0.1428"}
[f=-000001] LuaMenuServerMessage, <RegisterResponse {"Reason":"Registered","ResultCode":0}
[f=-000001] LuaMenuServerMessage, <Say {"IsEmote":false,"Place":5,"Ring":false,"Text":"[12 101.167.64.196:51637 ] error processing line Login {\"LobbyVersion\":\"Chobby\",\"Name\":\"FroogleGog\",\"UserID\":0,\"PasswordHash\":\"ejhTuGMjc4wwbGkXn3ZLzQ==\",\"ClientType\":1} : System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at System.Data.Entity.Core.Objects.ELinq.QueryParameterExpression.EvaluateParameter(Object[] arguments)\r\n   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()\r\n   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()\r\n   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)\r\n   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()\r\n   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()\r\n   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)\r\n   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__1[TResult](IEnumerable`1 sequence)\r\n   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)\r\n   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)\r\n   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)\r\n   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)\r\n   at ZkLobbyServer.LoginChecker.<DoLogin>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at ZkLobbyServer.ClientConnection.<Process>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at CallSite.Target(Closure , CallSite , Object )\r\n   at ZkLobbyServer.ClientConnection.<OnCommandReceived>d__9.MoveNext()"}
[f=-000001] [SpringApp::ShutDown][1]
[f=-000001] [ThreadPool::SetThreadCount]

**Comment by sprunk** [comment]
The error has a non-redacted password hash.

**Comment by GoogleFrog** [comment]
It's because it is from the server.
