### ISSUE TITLE
Test server bad login response

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1516]
[f=-000001] Login
[f=-000001] LuaMenuServerMessage, >Register {"Name":"GoogleFrog","SteamAuthToken":"REDACTED"}
[f=-000001] LuaMenuServerMessage, >Login {"LobbyVersion":"Chobby","Name":"GoogleFrog","UserID":0,"SteamAuthToken":"REDACTED","ClientType":1}
[f=-000001] LuaMenuServerMessage, <Welcome {"Engine":"103.0.1-648-g5775975","Game":"Zero-K test-12490-e85c531","UserCount":0,"Version":"0.0.0.1428"}
[f=-000001] ErrorEvent, Name already exists, Info
[f=-000001] LuaMenuServerMessage, <RegisterResponse {"Reason":"Name already taken","ResultCode":2}
[f=-000001] ErrorEvent, Steam not linked, Info
[f=-000001] LuaMenuServerMessage, <LoginResponse {"Reason":"Steam is not linked to any account yet, please provide a valid login name","ResultCode":2}
[f=-000001] LuaMenuServerMessage, >Login {"LobbyVersion":"Chobby","Name":"GoogleFrog","SteamAuthToken":"REDACTED","UserID":0,"PasswordHash":"REDACTED","ClientType":1}
[f=-000001] LuaMenuServerMessage, <Welcome {"Engine":"103.0.1-648-g5775975","Game":"Zero-K test-12490-e85c531","UserCount":0,"Version":"0.0.0.1428"}
[f=-000001] ErrorEvent, Steam not linked, Info
**[f=-000001] LuaMenuServerMessage, <LoginResponse {"Reason":"Steam is not linked to any account yet, please provide a valid login name","ResultCode":2}**
[f=-000001] LuaMenuServerMessage, >Register {"Name":"GoogleFrog","SteamAuthToken":"REDACTED"}
[f=-000001] LuaMenuServerMessage, >Login {"LobbyVersion":"Chobby","Name":"GoogleFrog","UserID":0,"SteamAuthToken":"REDACTED","ClientType":1}
[f=-000001] LuaMenuServerMessage, <Welcome {"Engine":"103.0.1-648-g5775975","Game":"Zero-K test-12490-e85c531","UserCount":0,"Version":"0.0.0.1428"}
[f=-000001] ErrorEvent, Name already exists, Info
[f=-000001] LuaMenuServerMessage, <RegisterResponse {"Reason":"Name already taken","ResultCode":2}
[f=-000001] ErrorEvent, Steam not linked, Info
[f=-000001] LuaMenuServerMessage, <LoginResponse {"Reason":"Steam is not linked to any account yet, please provide a valid login name","ResultCode":2}
[f=-000001] [SpringApp::ShutDown][1]

The bolded login response should say that the password I sent was incorrect. Also, no password seems to be correct for me.

**Comment by Licho1** [comment]
fixed
