### ISSUE TITLE
Wrapper handles text to speech volume incorrectly.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1517]
`"TtsVolume", {Volume = volume}` is sent by chobby to the wrapper. Volume is unaffected.

**Comment by Licho1** [comment]
Tested, it works. It expects volume 0-1, are you sending 0-100?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by Licho1** [comment]
Ok i will change it server side to 0-100
