### ISSUE TITLE
"lobby" part should be removed from the description of this repo.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#1523]
I've already made a mistake of making two Chobby related issues here because of the description. It currently is:
"Website, lobby, .NET based tools and other vital parts of Zero-K infrastructure "
and the "lobby" part should be removed since ZKL is no longer a thing.

Cheers.

**Comment by Licho1** [comment]
there is still a wrapper and big part of it is "lobby" or the lobby server.

**Comment by Licho1** [comment]
Wording got improved.
