### ISSUE TITLE
[ChobbyWrapper] Download clan icon

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1528]
See https://github.com/ZeroK-RTS/Chobby/issues/82

Current way of downloading clan icons is starting ZKL. Something else needs to do that job. New clan icons should also be downloaded without steam update.

**Comment by Licho1** [comment]
Do we need it without steam update? Wrapper could do it but it seems steam update should be fine for it.. we will have time to "police" it too ..

**Comment by DeinFreund** [comment]
Those would be incremental updates only? We would need to do at least daily steam updates for perpetuity. If newcomers create their clan with friends they'll think something is broken because their icon is a white square.

Steam update just sounds misplaced for low bandwidth high frequency updates.

**Comment by Licho1** [comment]
Atm we have like 10 steam updates per day.. so i woudlnt worry that much.

**Comment by sprunk** [comment]
Having to wait 1 day for an icon change looks very bugged (people think icons are simple so they should update immediately).

**Comment by DeinFreund** [comment]
I don't think we should require restarting the game more than once per week. Once per day if we're having major issues.

**Comment by Anarchid** [comment]
Steam updates merely for icons sounds bad. Socket-getting files with the same trick as replays on demand should be doable if other options fail.

**Comment by Licho1** [comment]
Its trivial to add it to wrapper but you are missing the point.
WE DO NOT WANT PEOPLE TO INSTA UPDATE ICONS.
They might upload swastika etc.
And having to wait for steam release gives us admin for icons for free.. we just look at them and delete invalids.

**Comment by DeinFreund** [comment]
If you really want that this needs to be pointed out when uploading a clan image.

**Comment by Anarchid** [comment]
> And having to wait for steam release gives us admin for icons for free.. we just look at them and delete invalids.

Who's going to do this premoderation?

**Comment by db81** [comment]
The sane person's way to do it would be thus:

1. Chobby has a cache. If it encounters an unknown clanpic in the wild, it downloads it and puts it into cache.
2. Clanpics can be vetted by admins. This doesn't impact their availability from site and showing in chobby.
3. When a steam update happens (an actual update, no clanpic updates!), every vetted pic gets included to seed the cache.

> WE DO NOT WANT PEOPLE TO INSTA UPDATE ICONS

I'm pretty sure every site in EU doesn't employ a team of mods to vet every single image from their users to avoid illegal swastikas. Either there are safe harbor laws, or there's a common agreement that the state won't prosecute sites moderating in good faith. I don't see why we, of all people, should deviate from the norm. Correct me if I'm wrong and the norm is actually different.

And people don't like having to see some "your 16x16 pic is awaiting moderation" message, if you want a vision of hell, imagine dozens of [Fx]Drones complaining about "nanny state" over and over for eternity. In all seriousness, it doesn't send a good signal.

**Comment by sprunk** [comment]
People can already upload swastika maps, make swastika forum posts, have swastika usernames and make swastikas out of windgens ingame. A 16x16 clanpic is comparatively harmless.

**Comment by Licho1** [comment]
Ok i will add wrapper function for this.

**Comment by Licho1** [comment]
implemented

**Comment by sprunk** [comment]
4c29a63eeb5a43568ec3e97bbff33ca5553105a5
