### ISSUE TITLE
Decayed rank icons are misleading

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1529]
They show players with completely wrong estimates. If you look at my Elo graphs, you'll see that there is hardly anyone even dropping 50 elons after coming back.

Just displaying inactive players with unranked icon (grey) should be fine for forcing them to play to regain their rank.

**Comment by Licho1** [comment]
I think it's better if its at least partially gradual, so you dont have that massive catching up when it "flips".
I know it's wrong but it also gives player more incentive to play because they will be winning more. 
We should make it more gradual though i guess.

**Comment by Anarchid** [comment]
If it's binary (gray icon when you're not on ladder) there won't be any "massive catching up".

**Comment by db81** [comment]
An advanced approach is to put a grayscale filter on the icon that increases together with decay value and is at 100% at max decay.

If you find doing it on the fly too hard, it's very easy to pre-gen gradual grayscale versions with ImageMagik.

**Comment by Licho1** [comment]
We want to motivate people to play during entire decay period and not once every month to reset grayness.

**Comment by DeinFreund** [comment]
Fix? I just hope we can use something like whr's lower confidence bound eventually. It emulates your actual maximum likely decay closer.
