### ISSUE TITLE
[Site] Swiss flag bork

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1531]
Must be square.

Edit: I'm tired and making wrong issues.

**Comment by Licho1** [comment]
Are native resolutions safe to use? Why not just normalize swiss flag by adding buffer.

**Comment by DeinFreund** [comment]
Original title was to display all flags at native res, but except swiss they already are. A fixed size container with an inner image with auto margin would be an option.

**Comment by DeinFreund** [comment]
Good thing that's fixed, lives were at stake.
