### ISSUE TITLE
Funny decorations

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1532]
![fun](https://i.imgur.com/k0Sk6aD.png)

**Comment by Licho1** [comment]
Unable to replicate/need more info.

**Comment by sprunk** [comment]
@Anarchid seems able to replicate (see last com) https://zero-k.info/Users/LobbyDetail/Anarchid

**Comment by Anarchid** [comment]
Firebug/inspector is all you need. There is no sanitization in the commander form, any unlock can go into any slot, including chassis.

**Comment by DeinFreund** [comment]
No, modules/weapons are checked.
