### ISSUE TITLE
User list: AGS & Ingame sorting

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1542]
The user list: https://zero-k.info/Users

You can sort the list by most fields. AGS and Ingame Time are clickable (and will show the sort direction triangle) but they won't actually be sorted.

AGS doesn't convey anything useful and Ingame Time is already represented by level so I think the best solution would be just to remove them.

**Comment by DeinFreund** [comment]
The problem is the queries running insanely slow, not even sure how it's possible to be that slow. Feels like the server reading all the users from database and then doing a O(n^2) sort on it.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/f737baacf637dbb269414f13ccac3cf53aceed74 User list is now admins only.

**Comment by DeinFreund** [comment]
I looove fixes around here!

**Comment by Licho1** [comment]
Queries being slow is that it had to scan all player-battle entries and do some math over them for every player in database to allow sorting by it.
There is no way around it but the query generated is also very inefficient (can be improved by factor of 30 using temp table as anarchid suggested).
However this is not trivial when using ORM mapper and it would lose type safety/maintainability.
Users section is not very useful one imo so I think, unless someone wants to optimize it, we can hide it (for the love of steam)

**Comment by DeinFreund** [comment]
It would be easy to optimize, but I agree that we don't need it. Sprung's response was just too good.

**Comment by sprunk** [comment]
>Queries being slow is that it had to scan all player-battle entries and do some math over them for every player in database to allow sorting by it.
There is no way around it

Ingame time and AGS only change after a battle so these values could simply be cached and updated/recalculated on battle event.

**Comment by Licho1** [comment]
Of course but that's also whats called bad DB design..
