### ISSUE TITLE
Link Mediawiki accounts to website

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1544]
Needs to support both regular and Steam accounts.

The options I can currently think of are:
- Current MSSQL database auth + OpenID login option with Steam as sole provider (must ensure any accounts created have same username as on zero-k.info)
- Make zero-k.info an OpenID provider and use that as the sole way to login to wiki (will need help with this one)
- Drop account integration with site entirely and just have normal MW registration (+ Steam OpenID)

**Comment by Licho1** [comment]
What would you prefer at this point?  
I think ZK account with passwords + steam open ID is mostly ok.
If wiki stores steam id in db, we could link it "eternally" - by doing a sweep on accounts and renaming it.
Linking is important for giving credits to editors so if we can see steamid in mw db it would all be fine.

Can you check what gets stored?

**Comment by KingRaptor** [comment]
Currently, wiki users who have logged in with their steam ID have it stored in a MySQL table, as the string `http://steamcommunity.com/openid/id/<id>` and mapped to MediaWiki account ID

ZK as OpenID provider is probably the ideal solution from the user-facing perspective, as it eliminates confusion: guaranteed 1:1 account mapping, no option for separate login using ZK passworded account or wiki native account; and no chance of someone making a native or OpenID login whose username conflicts with a ZK-acc login. 
But it's also probably the hardest to do; I tried setting up website as an OpenID provider but it seemed massively complicated.

Hybrid MSSQL + Steam OpenID auth has the advantage of being status quo and easy for both Steam and non-Steam users, assuming we don't run into any conflicts.

Native wiki accounts + Steam OpenID is the functionally simplest solution, at the cost of ease of access for current and future non-Steam users.

If we can't have an OpenID provider, my personal preference is probably to leave it as current. Conflict risk is probably rather low anyway (how many people are going to try logging in to wiki without a ZK account or with a different name?)

**Comment by Licho1** [comment]
Ok I will look briefly into OpenID. If its hard we keep current.

**Comment by Licho1** [comment]
Ok oauth is mildly complicated, we would need to deal with certificate and provide some workflow for ZK site to let people auth using steam and then pass this auth upwards.
It's doable but probably not worth the time atm: https://github.com/DotNetOpenAuth/DotNetOpenAuth/wiki/Security-scenarios#developing-a-user-specific-authorization-server

**Comment by Licho1** [comment]
Yeah ok lets use current state for now. Please do ask people to use same name though and we can resolve conflicts manually if needed. If there are issues (like vandalism) reopen.
