### ISSUE TITLE
Clan descriptions disallow [ ]

### ISSUE THREAD

**Issue by Juletz** [ZeroK-RTS/Zero-K-Infrastructure#1546]
Hi guys,

I got an error when I tried to create a new clan. Everything seems to be fine while filling out the spaces on the /Clans/Create page, but when I hit "Submit", I only get the following message:

![error_clan](https://cloud.githubusercontent.com/assets/26060541/23586744/0c7d5ff4-019c-11e7-9348-aaa11c6211f7.png)

I hope you can resolve the issue or tell me what I did wrong.

**Comment by Juletz** [comment]
Solved it! I just left out the "[]" in the description and I could create the clan without a problem.

**Comment by db81** [comment]
IMO it's still a valid issue because it needs to warn about disallowed characters with a readable message. Also there's no good reason to restrict [ ] in the description.

**Comment by sprunk** [comment]
That commit addressed the user part but not the source of the problem.

**Comment by Licho1** [comment]
I don't think it was [ , ] because there is a specific check in the controller that would block it being submitted to DB in the first palce.

**Comment by Licho1** [comment]
It was description being too long. More readable error now appears
