### ISSUE TITLE
Can't login to zero-k.info with ZK credentials since latest Infra update

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K-Infrastructure#1547]
Trying to log in into zero-k.info. When entering ZK login, password and pressing Enter or pressing a login button, I'm getting redirected to https://steamcommunity.com/openid.....

**Comment by Licho1** [comment]
When do you press enter? If focus is on login or password it should work. Likewise you could click the blue "door' icon (we should probably make that part cleaner)

**Comment by lhog** [comment]
Dammit. Do you think I'm unable to find a proper button?

I'm pressing either Enter or the door button here: https://i.snag.gy/yoc2gQ.jpg and it gets me there: https://i.snag.gy/CsAb1g.jpg

**Comment by Sortale** [comment]
unable to replicate on my comp anything I should do to replicate it?

**Comment by Licho1** [comment]
Disable javascript maybe?

**Comment by Sortale** [comment]
disabled javascript, can not reproduce

**Comment by db81** [comment]
@lhog what browser version are you using?

**Comment by lhog** [comment]
It's re-producible on Firefox. Previously used same browser and environment and it worked flawlessly for many years.

Login works with Chrome though.

**Comment by Sortale** [comment]
confirmed reproduced this bug on firefox and IE

**Comment by lagerspetz** [comment]
Also happens on Firefox on my Linux desktop. Chrome is fine, Chobby home button autologin is fine with Firefox.
