### ISSUE TITLE
Desync detection is oversensitive

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1549]
These logs are claimed to be desync yet they are fine.
 * https://github.com/ZeroK-RTS/CrashReports/issues/290
 * https://github.com/ZeroK-RTS/CrashReports/issues/291
 * https://github.com/ZeroK-RTS/CrashReports/issues/293
 * https://github.com/ZeroK-RTS/CrashReports/issues/295

**Comment by Licho1** [comment]
Suggest better detection pattern..

**Comment by Licho1** [comment]
It's not oversensitive its truncated
