### ISSUE TITLE
Implement "news" for chobby

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1551]
Chobby should get general overview similar to "home" page, with new threads, etc.
Also in real-time when someone posts stuff.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/issues/271

**Comment by sprunk** [comment]
Actually the real-time part would requires the lobby protocol to be able to tell clients about incoming news so there's stuff to be done infra-side as well.

**Comment by Licho1** [comment]
Yes .. also not just news pretty much "home page" stuff that helps community should be real-time transmitted to lobbies for display.

**Comment by sprunk** [comment]
done?

**Comment by Licho1** [comment]
I think so, the community display is not completed, but most of it is in place
