### ISSUE TITLE
Decide what to do about PlanetWars maps

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1553]
We tried starting PW match, but chobby failed to start because it was missing map.
Decide what to do:
 - force people to download the map before letting them to "join" attack or defense?
 - force all PW maps to all PW players?
 - download upon game starting?

**Comment by DeinFreund** [comment]
Only allow PW to players with PW maps.

**Comment by sprunk** [comment]
Ideally only MM maps could be used for PW planets:
 * people will have MM maps predownloaded
 * makes sure only highest quality maps are used

In case the MM pool is insufficient and we have to use other maps, IMO go for 1 or 2. Download upon starting is bad (for same reasons as in MM).

**Comment by Licho1** [comment]
MM maps isnt even technically viable. For some legacy reasons each planet needs unique map and there are way more planets than maps in MM pool.

**Comment by sprunk** [comment]
Steam PW map pack DLC then?

**Comment by Licho1** [comment]
Yeah i will look into DLC and we must make sure download is done before you can join queue in PW.

**Comment by Anarchid** [comment]
A non-Steam way to get into PW would be nice.

**Comment by Licho1** [comment]
Yeah it will...so it's decided now.. just need to make some pack later.. and Gf needs to implement in chobby
