### ISSUE TITLE
Chobby wrapper makes a mess

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#1557]
Following these official instructions ...
```
sudo apt-get install mono-complete
wget http://zero-k.info/lobby/Chobby.exe
chmod u+x Chobby.exe
mono Chobby.exe
```

... will result in all files and folders being downloaded in the same directory as Chobby.exe, and therefore making a mess of whichever directory you downloaded it from:

```
~/Downloads$ ls
cache       engine                                  maps      rapid
Chobby.exe  games                                   packages  temp
demos       google-chrome-stable_current_amd64.deb  pool
```

Solution:
The instructions are missing two commands, for creating a chobby directory and entering it, so the download gets isolated to that single directory.
```
sudo apt-get install mono-complete
mkdir chobby
cd chobby
wget http://zero-k.info/lobby/Chobby.exe
chmod u+x Chobby.exe
mono Chobby.exe
```

**Comment by Licho1** [comment]
Read instructions properly. They mention that

**Comment by gajop** [comment]
Those instructions are poorly written and don't tell you to execute the following commands in the separate folder. 
To me, when I first read it, it seemed that all you needed to ensure was having write permissions.

If you're going the command line route, include everything

**Comment by Licho1** [comment]
fixed
