### ISSUE TITLE
Remove obtrusive news popups

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#1558]
I never liked them and would just kill the popup and read the news as usual if I wanted to.
There are less invasive ways to show that there is something new.
Additionally it's going to be even more annoying if you implement https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1551 , so most people get this popup even after they saw the news ingame or on the forums.

**Comment by Licho1** [comment]
If we add news to chobby then we can nuke popup from site yeah.

**Comment by db81** [comment]
Is it news being in a popup or is it more news being in a massive popup bigger than the sun itself?

**Comment by gajop** [comment]
Yes to both?

**Comment by Licho1** [comment]
Dialogs are now limited too 600px height with scrollbar.
Reading thread counts as reading news.

Whether they appear or not depends on news poster, they are optional so this is now fixed.
