### ISSUE TITLE
[Feature request] Implement prize for planet war

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#1593]
I am willing to donate about 100 steam keys [mostly low value <15USD]  as prize for planet war

I want it to be automated since manual can fail.

Gajop: is mildly disinclined to have it implemented. if it is implemented just have fixed prizes for top 3 players on winning side with highest attack score.

Licho: is interested, but want a draft for implementation. if it is implemented just have fixed prizes for top player on winning side with highest attack score.

Above method: 

pro: easy to implement, can be done manually without additional coding, no need for big upfront cost
Con: feel unprofessional, maybe unscalable, Manual can fail, player can not choose key according to their liking.

Sortale:

-  1st draft: have UI so top player pick then 2nd player allow to pick then, etc for top 10 players
 - 2nd draft:  allow top 3 players of winning faction to pick at end of PW first come first serve, then allow the next top 3 on the next day, etc, until  top 9 players have keys.

May also need a way for me to input/upload key list to server

|ID|Game Name|Steam Store ID|Price|Key|
|---|---|---|---|---|
|1|etc|etc|etc|etc|

pro: Maximum player autonomy, scalable, unlikely to fail long term
Con: need coding, need maintenance, may not have any significant benefit

**Comment by Licho1** [comment]
I would just give it to 1-3 top payers in PW, we can do it manually. 
Giving 100 keys still sounds less work than coding system to give 100 keys 
If it's automated it should still be a rare reward and someone would have to refill the keys basically (to be worth the automation)..
I mean I could give people 100 keys in 100 minutes easilly, to code such system I would need hundreds of minutes.

**Comment by Sortale** [comment]
well automate is only worth it if player can choose key, giving fixed key manual seem to be a better solution given the resource

**Comment by Licho1** [comment]
I would not waste these, they won't spoil. If you have that many, no point giving them all out as a giant prize. I would favor longevity, giving them one by one on special occasions (PW, tourneys).

Some internal list of keys where we could award people key and they could pick could be made.
That is reasonable I think. We would just manually mark player X can pick 1 key.

Is that what you meant?

**Comment by Sortale** [comment]
yes that's what I mean

**Comment by GoogleFrog** [comment]
Don't give a prize. Victory is it's own reward. 
 * Planetwars is a team event so don't give out prizes to some top number of players, it just makes internal competition and issues at the boundaries of prize/no prize. If everyone in a faction gets a prize then you have issues with people in the faction not deserving the prize because they put in almost no work.
 * If you give a prize then some participants that did not receive a prize will look back on planetwars as a waste of time.

**Comment by Sortale** [comment]
so do you want prize for tournament?

auto prize for tournament?

auto tournament?

Manual tournament? manual prize for tournament?

Scrap the prize idea all together ?

**Comment by GoogleFrog** [comment]
Yes, prizes for tournaments. I don't know about automation. 

@Licho1, the problem posed by @Sortale is that he says to the winner "which key do you want" and waits for a response. Then they repeat for all subsequent prize winners. This algorithm can take days to repeat due to decision making and timezones. What he wants is an automated system which tells a user to select a prize, with a time limit, and then automatically offers the remaining prizes to the next in line.

I don't think the site integration is worth the effort. Perhaps require email on signup so you can email them prize choices?

**Comment by Sortale** [comment]
or fixed prize or just let winner have more time to choose

**Comment by Licho1** [comment]
I think such "key selection" automation is reasonable and small if it exists outside site (for example some primitive page without design/direct links), it would just use ZK to authorize the user. 
So yeah i can do that.

I see some other issue though, if people are free to choose it will lead to some games simply being left behind.

I would suggest different way that won't need automation.
For given tourney offer 3 possible keys and player picks one of three which is sent to him.

That is easy to manage even without automation and 3 keys can be set in a way to highlight less (or more frequent) keys.

**Comment by Sortale** [comment]
well the best key would be picked then the other, until no key is left, I mean no point in giving key to people who don't want it.

Keys are left over from humble bundle so unlikely to be multiple key for the same game.

Anyway, the consensus so far to me is that tournament prize only, manual tournament, manual key, fixed prize or prize pool.

**Comment by Licho1** [comment]
Just give one to the best player, ideally we would have them last until steam era when they matter more :)

**Comment by Sortale** [comment]
I'll give you a list then, you can do what you want with it. Compiling will take sometime

all said I don't think there would be a manual tournament in the steam era but what do I know.

**Comment by Sortale** [comment]
here the list about 270 keys most bad, some high value:

[GameList.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/849793/GameList.txt)

**Comment by Licho1** [comment]
I would really suggest waiting with this until steam era. If we do prize now, we may increase player participation by 20% from 4 people to 5.
I would rather do it from 400 to 500.

**Comment by Sortale** [comment]
It shall be done according to your will

**Comment by Licho1** [comment]
Closing this as this requires no coding changes. Price canbe called at any time by sortale himself!
