### ISSUE TITLE
Artefact victory counter is broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1596]
The artefact victory counter is empty.

**Comment by Licho1** [comment]
Because nobody has some so it cannot show which faction leads

**Comment by GoogleFrog** [comment]
The UI looks broken when the victory counter is just a small empty box. Display the artefacts, perhaps say "Two factions tied on 0 artifacts" and then show a picture of 5 unclaimed artifacts.

**Comment by sprunk** [comment]
This counter has been removed. See #2133
