### ISSUE TITLE
The Machines red text colour is slightly too dark

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1597]
The purple of Empire has a good brightness level. Perhaps the site background also has a color-specific effect.

**Comment by Licho1** [comment]
suggest coloring my monitor sux.

**Comment by Licho1** [comment]
no color suggested, closing

**Comment by GoogleFrog** [comment]
The tickets are not just for you. @KingRaptor did a good job with lightening the hegemony colour.

**Comment by Licho1** [comment]
Not for me?  I basically eat those tickets for breakfast... but ok I will share.

**Comment by Anarchid** [comment]
Suggestion: #c11313
I changed header color on screenshot, other text remains old color for comparison.
![image](https://cloud.githubusercontent.com/assets/3822768/23947078/c7e39e7a-0985-11e7-907c-9a34a27ee9e1.png)

**Comment by KingRaptor** [comment]
Changed to #c11313 

(thanks for saving me the trouble of thinking up a new color, ha!)
