### ISSUE TITLE
Can't leave battle while in party

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1600]
```
[22:41] -->LeaveBattle {"BattleID":2}
[22:41] -->LeaveBattle {"BattleID":2}
```

Joining works fine

Maybe also a Chobby display bug. After kicking myself it still showed myself as in the battle without the ability to interact with battle chat.

**Comment by Licho1** [comment]
There is no party at leaving. Should work so chobby bug
