### ISSUE TITLE
No planetwars messages sent from server

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1603]
Qrow is sent no PwMatchCommand or other relevant commands. Here is their infolog http://pastebin.com/50tpfv37. This means the chobby PW UI does not work for them at all.

**Comment by Licho1** [comment]
Message is only sent to people who can play planetwars (are in faciton and meet level limit).
I suggest we send some other marker for example in "welcome" if you want some indication whether PW is running or not.
PwMatchMaker is sent only to those who can actually play.

**Comment by Licho1** [comment]
Oh i found it public const int MinPlanetWarsElo = 1000;
changing to -1000
