### ISSUE TITLE
Percentile ranks

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1620]
WHR directly calculates percentiles so it's very easy to implement percentile ranks as well.

Judging from current percentiles (visible on test server), I'd suggest this:
Red: 75%
Brown: 50%
Orange: 25%
Yellow: 10%
White: 5%
Blue: 2%
Violet: 0.5%

This will be similar to the old 4 icon system (3 ranks for 75% of players) for low ranks, but with the added focus on higher ranks, giving the competitive players some ranks to compete for.

Now that ranks already change when you're away (Elo decay) I don't see much speaking against percentiles. Opinions?

**Comment by Licho1** [comment]
It's easy with elo as well, but we don't really want it (nor WHR).
Simplicity of fixed elo "levels" and rules is preferred. I think that elo decay is much simpler and is based on more important thing (player activity) than percentile (player count).

**Comment by DeinFreund** [comment]
Percentiles would fail due to our small player base. This skews the distribution way too much from a normal distribution.

We'll need a consistent and big enough player base to reduce the noise to an acceptable level.
