### ISSUE TITLE
It's possible to attack own planet

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1627]
If the attack is initiated before the planet is captured. The attack should be aborted as soon as the planet changes ownership.

![img](https://i.imgur.com/3WbG3jN.png)

**Comment by DeinFreund** [comment]
Alternatively, planets that are currently being fought on should probably be locked so there can't be two simultaneous battles on the same planet.

**Comment by GoogleFrog** [comment]
You can't lock a planet, it wouldn't scale.

**Comment by Licho1** [comment]
Attackable planets reflect the state on the start of the round and nothing changes. You can "over attack" the planet but thats not a big issue, good thing is that it scales imo.
