### ISSUE TITLE
Planetwars Design Thinking

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1633]
Consider changing the turn time rule to depend on the current battle length. This is to prevent the attackers from preventing a counter-attack by stalling the game for 30 minutes (even after they have clearly lost).
 * If the attack deadline reaches 10 minutes and the battle that started the round is ongoing then then the countdown should pause until the battle completes.
 * After the battle is over the countdown is resumed.

This could be achieved in the protocol with a DeadlinePaused boolean in PwMatchCommand and the sending of DeadlineSeconds 600 when the pause time is reached.

**Comment by Licho1** [comment]
You cannot prevent counter attack by stalling the game. Even if game is in progress the other faction can attack the same planet (if connections exist).
Attackable planets reflect the state at the start of the matchmaker "round". 
I was instead considering to reduce the timer to 5minutes with 10 minute inactivity grow to make it more reactive.
