### ISSUE TITLE
Attack counts as multiple attacks

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1637]
There was only one attack on colt, but somehow we got messages for a multitude of results

> [13:03] Ready your scrapyards.
> [14:14] Nightwatch It's your turn! Select a planet to attack
> [14:43] Nightwatch Corvus_Corax joins attack on Colt
> [14:47] Nightwatch DeinFreund joins attack on Colt
> [14:57] Nightwatch New Empire won because nobody tried to defend
> [14:57] Nightwatch New Empire attacked Free Machines Colt in  and won. . Empire gained 35 influence (100% from winning flawlessly of 35 base)
> [14:57] Nightwatch New Empire won because nobody tried to defend
> [14:57] Nightwatch New Empire attacked Free Machines Colt in  and won. . Empire gained 35 influence (100% from winning flawlessly of 35 base)
> [14:57] Nightwatch New Empire won because nobody tried to defend
> [14:57] Nightwatch New Empire attacked Free Machines Colt in  and won. . Empire gained 35 influence (100% from winning flawlessly of 35 base)
> [14:57] Nightwatch New Empire won because nobody tried to defend
> [14:57] Nightwatch New Empire attacked New Empire Colt in  and won. . Empire gained 0 influence (0% from winning flawlessly and reduced to 0% because only 0 of 10 ships needed for warp attack got past defenses of 35 base)
> [14:57] Nightwatch All structures have been disabled on New Empire planet Colt. 
> [14:57] Nightwatch New Empire won because nobody tried to defend
> [14:57] Nightwatch New Empire attacked New Empire Colt in  and won. . Empire gained 0 influence (0% from winning flawlessly and reduced to 0% because only 0 of 10 ships needed for warp attack got past defenses of 35 base)
> [14:57] Nightwatch All structures have been disabled on New Empire planet Colt. 
> [14:57] Nightwatch It's your turn! Select a planet to attack
> [14:57] Nightwatch It's your turn! Select a planet to attack

**Comment by GoogleFrog** [comment]
![coltattack](https://cloud.githubusercontent.com/assets/1318249/23952073/523bef56-09e4-11e7-9618-726a4b27e640.jpg)

This caused the planet to be instantly captured, it is now on 100% Empire IP.

![coltevents](https://cloud.githubusercontent.com/assets/1318249/23952215/ce9c4082-09e4-11e7-9932-0dd6546b4f7c.jpg)

The event log says that metal was applied multiple times as well. Also, the log is missing the 100 metal that Machines receive for being in a battle.

**Comment by Anarchid** [comment]
There was no actual battle. I think metal is only given to people, not to factions, as an incentive to play.

**Comment by DeinFreund** [comment]
Check the tracelogs for an exception in TimerOnElapsed(object sender, ElapsedEventArgs elapsedEventArgs)

**Comment by GoogleFrog** [comment]
This still occurs. The issue isn't in reporting multiple times, I think the battle actually happens multiple times. It seems to only occur for defaults.

**Comment by GoogleFrog** [comment]
I think I misread the events list.
