### ISSUE TITLE
Write updated and useful planetwars wiki

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1639]
Put a planetwars explaination on media wiki. The current guide is an outdated design document, leave it as is but unlink it on the site. The user-facing planetwars manual should be a new thing. This should be done by people who know how planetwars works and how to play the metagame. I designed most of it but don't know what is currently implemented or much about what the numbers imply about strategy.

**Comment by Licho1** [comment]
Nobody knows how it works though.. that might be a problem.
But with code reading and science, it can be done.

**Comment by sprunk** [comment]
Anarchid seems to have written this. https://zero-k.info/mediawiki/index.php?title=PlanetWars
