### ISSUE TITLE
Explain increasing attack timer (and maybe remove it)

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1640]
There is a rumor that the time between attacks is increased as one faction is absent. I have never seen this in practice so am not entirely convinced that the mechanic exists. Explain how it is implemented and the progression of the times.

This mechanic should possibly be removed (if it exists) because it discourages playing. Without an attack timer it is generally beneficial to launch attacks (since you can launch them right at the end of the turn) and respond to attacks. However, with timer increasing, players should not play any battles in offpeak times because doing so will merely reset the timer. The timer leads to a faster rate of defaulting. Mechanics which discourage playing games should be removed.

**Comment by Licho1** [comment]
```
            if (missedDefenseFactionID == AttackingFaction.FactionID) extra = Math.Min(missedDefenseCount * GlobalConst.PlanetWarsMinutesToAttack, 60);
            return AttackerSideChangeTime.AddMinutes(GlobalConst.PlanetWarsMinutesToAttack + extra);
```

**Comment by Licho1** [comment]
It increased if faction misses defense repeatedly. Max increase is 60 minutes.

**Comment by GoogleFrog** [comment]
What does it mean that it increases? What do the times look like?
 * A attacks
 * B defends
 * A attacks
 * B misses defense.
 * B now has ??? time to attack?
 * B misses attack.
 * A attacks.
 * B misses defense
 * B now has ??? time to attack?

Why is the timer only for defense? When does it start increasing?

**Comment by Licho1** [comment]
A attacks
B defends
A attacks
B misses defense.
B now has ??? time to attack?  **1:30**
B misses attack.
A attacks.
B misses defense
B now has ??? time to attack?  **1:45 (max = 60 + base)**

It's on defense only because idea is that you can stall with avoiding attacks, but it would be stupid to stall with defense since you auto-lose (and not time efficient at 10 minutes response time).

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/7da7db2114eb31edca956273c0454f0ba92d63a7/ZkLobbyServer/SpringieInterface/PlanetWarsMatchMaker.cs#L372

Looks like this won't work in 3-way PW. However it might be less of a problem since more factions already means things are slower.

**Comment by Licho1** [comment]
it still sort of defends against consequitive attacks against the same inactive faction (faction A and B can both keep attacking C).
But yeah its not a very nice/transparent solution.
Reopen if this mechanics needs fixing.
