### ISSUE TITLE
Have the wrapper detect and inform chobby about ATI

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1642]
According to this https://springrts.com/mantis/view.php?id=5494 bumpmapped water has known crashes with ATI cards and I doubt anyone is going to fix it. The wrapper should detect ATI so that chobby can enable some ATI compatibility setting to set ugly water.

**Comment by ashdnazg** [comment]
Wouldn't it be better to just expose video card info to lua in the engine?

**Comment by Licho1** [comment]
Yeah I think it's easier if card is exposed to lua, since it's already detected. This has to happen before crashy stuff is loaded though.

**Comment by Licho1** [comment]
Yeah we should expose it from engine as @ashdnazg  says. Make a mantis food, it mantis fails to devour it, I will implement it, in that case reopen @GoogleFrog

**Comment by gajop** [comment]
Time travel: https://github.com/spring/spring/commit/960b7a64fe9d0246a0207c8b3c71844c8be9a0b3#commitcomment-21433042

**Comment by gajop** [comment]
Also I think it's unnecessary to provide wrapper functionalities that come from parsing infolog.txt, unless engine crashes when starting the menu. That can be (and already often is) done in Lua.

**Comment by Licho1** [comment]
Wrapper would not parse infolog, wrapper would implement its own detection and possibly change settings so that there are no crashes.
