### ISSUE TITLE
Planetwars change ideas

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1644]
Here are some discussed ideas for planetwars improvements. Don't make changes to the running round. These are worth posting on the forum after the round concludes.
 * Replace the warp core fabricator and warp core stockpile with a 1-use-only Warp Gate structure that has the ability to send 10 Dropships or 10 Bombers to any planet. The structure doesn't work if the faction lacks the required number of ships of the type chosen by the player. The ships are first spent from the players quota but will be taken from the faction even if the player lacks quota. A cost of 500 metal seems like an ok price.
 * Give battles on neutral planets a +20 IP modifier to encourage expansion into unclaimed territory. This modifier is before multipliers.
 * Give each side a homeworld with a headquarters structure. This structure is undestroyable, undisablable, and gives some ridiculous defense bonuses. The bonus would be something like -40 IP, +30 bomber defense, wormhole IP spread blocking and warp blocking. The HQ prevents the creation of other defensive structures, just so it is somewhat assailable in the lategame (or maybe not, since other defensive structures only work for one battle due to disabling. If this requires a new mechanic then ignore it). Losing control of your HQ loses the game.
 * The homeworld exists because it is cool and also for this mechanic: make metal income decrease for battles far from the homeworld. For example battles, could give 5x less metal where x is the distance between the battle planet and the factions homeworld. Metal production per battle could be increased to 120 to compensate.
 * Pre-populate the galaxy to create a wide frontline. For example perhaps leave 25% of the planets neutral in a band across the galaxy. This encourages more fronts.
 * Improve artifact placement to make the victory condition more threatening. Perhaps we could have four artifacts; two in no-mans-land and two relatively safe behind no-mans-land.
 * Make disabled structures unsellable.
 * Add a limit to the number of dropships in a single battle to prevent PW from being unduly sensitive to the result of a single battle with many stacked ships. Pivotal battles are exciting but you shouldn't be able to take a homeworld in one turn by stacking 100 ships. The exact limit will depend on the balance of dropship-inhibiting defenses. A limit of 20 would cap IP gains at 55 which makes the -10 defense effective in that it can stop a planet falling in one turn. Remember that all non-HQ defenses can be disabled by a ground battle so planets can generally be taken in two turns. The first battle could even be a defeat as long as the defense are taken out. A safe limit (in the sense that it likely only plugs unseen problem cases) would be a limit of 30.

Infra tasks:
 - [x] Implement a Warp Gate structure. Costs 500 metal. Powers up in 4 turns(?). Creates 10 Warp Cores and then destroys itself.
 - [x] Implement HQ. This is an undisablable, unconstructable, undestroyable structure that exists at the homeworld of each faction. The structure blocks warp, provides 30 bomber defense and reduces IP gain by 30. If you take the HQ of an enemy faction you win the game (yes, even in FFA, this solves faction elimination issues).
 - [x] Remove Guerilla Jumpgate for being unused and uninteresting.
 - [x] Set a limit of 50 Dropships and Bombers per attack run. This prevents some weird high-end abuses and accidental misclicks. Remove the ability of the factories to increase the per-attack limit.
 - [x] Implement a metal bonus fighting on a planet near your HQ. Attacks at distance 5 from HQ give +5 metal, distance 4 give +10 metal, distance 3 gives +15 metal, distance 2 gives +20 metal, distance 1 gives +25 metal.  Distance is calculated based on owned planets with working wormhole when the battle began. Defenders of neutral planets never receive a bonus.
 - [x] Implement metal cost for fighting on a planet disconnected from your other planets. Connection is calculated as above. Fighting on disconnected planets only gives you 50 metal income from the battle. Defenders of neutral planets always receive 100 income.
 - [x] Implement artifact victory points. Artifacts should have some large power cost, this necessitates the ability to force them to disable via priorities. Active artifacts should generate victory points at 1 per turn. These points are tradable. They should take 10 turns to power up. If a faction reaches 200 victory points then they win.
 - [x] Implement support for structure evacuation. If the attackers win then the battle will send a list of structures that were evacuated, disable all but the structures in this list.
 - [x] Simplify structure disabling rule. Disable all structures if the planet changes ownership. Otherwise, disable non-evacuated structures if attackers win and disable destroyed structures if defenders win.
 - [x] Implement planetwars rank and send it ingame. Offices that can be held should have a rank. If the owner of a structure is not in the game then a random player with the most rank should control the structures. This is to make evacuation decisions as well as to use any structure abilities.
 - [x] Implement sending strings to battles (perhaps in player keys?) to tell players extra objects for the battle. Things like "lose but destroy enemy CC to retain planet".

Initialization tasks:
 - [x] 3 way FFA is possible.
 - [x] Initialize the galaxy with few neutral planets as they lead to weirdness.

Gameside tasks:
 - [x] Implement evacuation. Give structures an ability with 15 minutes cooldown which allows them to be evacuated from the battle.
 - [x] Implement some minor structures bonuses. A little income for econ structures. Defense drones for some others etc...
 - [x] Implement information popup.

**Comment by Licho1** [comment]
HQ is a good idea.
It could also be buildable (at a massive cost) and influience energy upkeep of structures (the further away the higher upkeep).

In general geography based things can be interesting.

Pre-population would mean no planet ownership ..

I don't like warp gate because its not tradable. Other resources are... for better diplomacy. 

Regarding artefacts .. there could justr be factionCount + 1 artefacts. And we could have "channel 5 000 energy to artefact for 100 turns to win" rule.

Looting could be reduced by requiring planet to have 100% influence (hard to achieve in middle of enemy lands) or structure to be active (not disabled).

**Comment by GoogleFrog** [comment]
I don't think HQ should be relocatable because that can easily accidentally destroy a faction or lead to a breakdown of front lines. It should impact metal income instead of energy because metal is more important and variable energy income is hard for players to keep track of since they have to balanced it. Variable metal income is easy.

Pre-population does have ownership problems, however, you could simply give out planets randomly to top players. I think it is far better than the alternative. The current rounds early game expansion into empty territory is the boring part of the game because you are not fighting the opposing faction for control. It also leads to a blobby shape with much of the galaxy unclaimed. There is inevitably a single front.

Tradeable warp cores is not a requirement. Warp gates work significantly better than warp cores. There is a big discussion in the channel to read. The main point is that gates require less spread infrastructure and the one-use nature makes them tied more to the turn timer.

**Comment by GoogleFrog** [comment]
Your looting idea is interesting. I'm not sure that it is required with the proposed change to warp cores. There are potentially three changes:
 * Prevent selling disabled structures.
 * Prevent selling while enemy has IP on your planet.
 * Prevent selling while the planet is not 100% your own IP.

It is hard to get IP on your own planet, you mostly have to wait, and you would often be prevented from selling structures on the frontline due to IP spread. I like disabling selling for disabled structures because it is a simple rule. It is much easier to see when a structure is enabled/disabled than it is to understand how IP relates to looting. I will add it to the list.

**Comment by GoogleFrog** [comment]
> In general geography based things can be interesting.

Is this in response to distance from HQ? Just a note, HQ distance should be calculated at the start of the PW game and then fixed. This way we don't have weird effects from planet busters.

**Comment by Licho1** [comment]
There is a link connector. Can it be used to reduce distances?

I like the variable energy cost, because it means DEFENSES (or future local weapons) are more expensive on far away planets. Which means the more you expand the more expensive it is to protect frontline. And the smaller your territory is, the smaller the upkeep is. 
Equation can be simple enough, like 1 + (links-1)*0.25 and it can be shown in planet info.

With metal you could simply save metal for future expansion, which would lead to angry faction emperors selling people's structure and asking them to not build anything for some time.

**Comment by sprunk** [comment]
>With metal you could simply save metal for future expansion

If you save metal then you get behind on other resources (bombers, warp, defense) so the other faction can take advantage of that. So it shouldn't get degenerate.

**Comment by Anarchid** [comment]
Artifact change idea just discussed:

Instead of controlling all artifacts to win, artifacts are activable structures with high (3000?) energy cost. While active, they produce victory points each turn. Whoever reaches X victory points, wins. Whoever has most victory points when a real-time countdown runs out, wins.

Victory points are permanent and indestructible, so the only way to change the current winner is to get to have more tickets than them: either by destroying their generation ability while keeping yours, or powering up more artifacts in time.

This allows even a single artifact owner to be a credible threat to the galaxy. Someone owning two becomes a menace.

**Comment by Licho1** [comment]
Still don't like the variable metal gain. It can also lead to situation where it pays to talk to a friendly faction and attack planet's of each other next to home to get full metal instead of fighting distant war with the real enemy.

**Comment by GoogleFrog** [comment]
> With metal you could simply save metal for future expansion, which would lead to angry faction emperors selling people's structure and asking them to not build anything (or even to not expand!) for some time.

Metal income does not reduce when you spend metal (except by the current mechanic in which infrastructure drains your energy). I don't see how reduced metal for battles on far planets causes faction leaders to want to stockpile metal.

**Comment by GoogleFrog** [comment]
> I like the variable energy cost, because it means DEFENSES (or future local weapons) are more expensive on far away planets. Which means the more you expand the more expensive it is to protect frontline. And the smaller your territory is, the smaller the upkeep is.
Equation can be simple enough, like 1 + (links-1)*0.25 and it can be shown in planet info.

Variable energy cost is ineffective because defense infrastructure is rarely important on faraway planets. Far away planets do not expect to be controlled for long enough for defenses to come online and be worth the cost. The point of fighting far away is often to disrupt the infrastructure of opposing factions, not to create infrastructure for them in the midst of the enemy planets.

I don't envisage metal costs for far battles being extreme. Getting 100 or 20 metal depending on location is very extreme. I think it would be very rare for a faction to get less than 70% the available metal in a battle. The mechanic is meant as a comeback mechanism that gives the smaller faction slightly more metal so allows them to respond.

> Still don't like the variable metal gain. It can also lead to situation where it pays to talk to a friendly faction and attack planet's of each other next to home to get full metal instead of fighting distant war with the real enemy. The benefit of taking a nearby planet will outweigh the lost ability to fight there for a slightly increased metal income.

These ideas are not based on designing for FFA planetwars.

**Comment by Licho1** [comment]
Another thing regarding variable energy cost is that it makes sprawling empire more expensive or less defensible. It will mean that your core eco has to be next to homeworld or undefeded. Forcing planets without defense makes them more vulnerable which will naturally make you lose them more or be bombed more (fixes both influence/ownership and infrastructure at once).

Another alternative: variable IP gain.
IP already varies a lot and it will naturally lead to less planets conquered and actual planet-comeback.
Having more metal does not mean you can utilize it to win over.

Also I would like different victory.
Artefact on artefact planets can be powered up, using high energy cost (say 2000-3000). Once powered up, each artefact generates one victory point per turn.
Once any faction reaches stockpile of 100 victory points, it wins.
These victory points cannot be destroyed, but can be traded (FFA scenarios).

Having a counter ensures that there is going to be a victory eventually, even if there is no clear planet ownership advantage. 
This means we can use aggressive anti-snowballing features to make the factions artifically more "balanced" and extended the period when it's not clear who wins, without making the game endless like some old planetwars.

**Comment by Licho1** [comment]
evacuation 22e92261748eaf79bea823a97e4df3d7e1022572

**Comment by sprunk** [comment]
This ticket has been implemented and there's #1705 for feedback.
