### ISSUE TITLE
Feature request: admins can kick anyone from any clan

### ISSUE THREAD

**Issue by ashdnazg** [ZeroK-RTS/Zero-K-Infrastructure#1645]
Should allow admins to kick knorke smurfs from clans.

**Comment by DeinFreund** [comment]
In what case would you need that? Why wouldn't the clan leader do so?

**Comment by ashdnazg** [comment]
The administration of this community is not their job, it's ours.

**Comment by DeinFreund** [comment]
Do you actually want permabanned peoplers to be excluded from any clans? That could be done automatically.

**Comment by ashdnazg** [comment]
this is a good addition
