### ISSUE TITLE
Planetwars ingame objectives for losing less

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1649]
Currently, if you win a planetwars game you have won almost as well as you can. There are only two ways for the defeated side to lose less:
 * Destroy the enemy CC.
 * Destroy structures (attack only).

The defenders only have one way to lose less and statistically they are the side that loses more often. Here are three ideas for ingame objectives that allow the losing side to have some benefit:
 * Pickups. Collect pickups to get some bonus in the metagame. I don't really know how to work this in with lore at the moment. Imagine little hovering boxes that instantly give your faction 50 metal when your commander walks over them. This bonus is applied regardless of which side wins (maybe the metal is teleported?).
 * Extraction beacon. Each team could have an extraction beacon that allows for commanders to be teleported out of the battle. This could give some metal bonus if you lose because the commander chassis does not need to be rebuilt. Only works for commanders with Vanguard Economy Packs (since these are clearly the exotic modules that cost the metagame resources to produce).
 * Structure protection (defenders only). The defenders could have the ability to make PW structures immune to destruction. This puts time pressure on the attackers, if they really want to disable the garrison then they need to strike it before it is lifted/teleported away. Merely winning the battle would no longer guarantee structure destruction. Perhaps the defenders get the ability to save one of their structures for every 15 minutes of battle time. Perhaps the defenders must pay ingame resources to do this (supply energy for teleport?). Perhaps a structure saved this way is disabled for one turn (instead of the usual large number of turns) so it is only something to do if you think the structure is in danger.

In addition to this, some (all?) ingame structures could come with basic defenses to allow them to survive early raider raids and Warrior drops.

**Comment by Licho1** [comment]
I think that part of the problem is, that people don't know what CC is and what killing it does.
There should be some info screen at the start of the game and better CC tooltip.

**Comment by sprunk** [comment]
As long as pickups are collectible by both sides and have purely metagame benefit, they probably make the winners win even more.

**Comment by GoogleFrog** [comment]
Structure protection is done. Others are not that important.
