### ISSUE TITLE
Download link for Chobby is empty on mac.

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1657]
I assume it checks useragent and attemps to provide an OS-specific download. 

Since there's no chobby for Mac the correct response is likely to say that there's no download for your system, rather than provide a non-clickable link.

![image](https://cloud.githubusercontent.com/assets/3822768/24097634/6d66f9c2-0d6f-11e7-9be7-ca4e00640bc9.png)
![image](https://cloud.githubusercontent.com/assets/3822768/24097640/73cf00d4-0d6f-11e7-9bf7-6cf532e476bf.png)

**Comment by Licho1** [comment]
Thats curious, nothing changes the link .. it has to be some browser-side filtering.

**Comment by Anarchid** [comment]
I am fairly certain i have no addons that rewrite contents of `<a>` elements.

**Comment by Anarchid** [comment]
Safari with no addons installed at all also has absent href.

**Comment by Licho1** [comment]
And if you do "view source" ?  There is no active code that would remove the href..

**Comment by Anarchid** [comment]
I'll check whether it's client or server.

**Comment by Anarchid** [comment]
Same story when viewing js-unaffected source. It's server!

![image](https://cloud.githubusercontent.com/assets/3822768/24144460/fa65be3c-0e35-11e7-8fd9-d9e28eede419.png)

**Comment by mojjj** [comment]
thats cool.
http://i.imgur.com/HimnCVi.png

the line is, according to github, 2 years old and points to 
http://i.imgur.com/2tyOniD.png
(file: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/Views/Home/Download.cshtml)

seems not to be the correct file, eh?

**Comment by Licho1** [comment]
thanks for finding this mojjj! Fixed

**Comment by mojjj** [comment]
hmm not sure if removing the download file fixes this problem. but you have better insight ;)

**Comment by Licho1** [comment]
Yes because it's actually in the wiki and not in that file.. :)
