### ISSUE TITLE
Fix/clarify StartNewSpring

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1661]
I wired up StartNewSpring but nothing happens. See https://github.com/ZeroK-RTS/Chobby/commit/ef9dbf1621372dceb86682674f869b4975aa6151

```StartNewSpring = {
[f=-000001]     SpringSettings = springsettings_other.cfg
[f=-000001]     StartDemoName = demos/20170322_005957_Crubick Plains v1_103.0.1-697-g918caba develop.sdfz
[f=-000001]     Engine = 103.0.1-697-g918caba
[f=-000001] },```

**Comment by Licho1** [comment]
1) SpringSettings was expected to be a string with actual settings content not a path.
2) Demo is expected to be a demo name, not a path (since you can request download + start of the same demoname in the same startNewSpring request)

Check infolog_full.txt for further wrapper errors.

**Comment by GoogleFrog** [comment]
Sending springsettings as a string is good. I want to be able to specify demo path instead of name because demo downloading already works and local demos need to be supported.

**Comment by Licho1** [comment]
Demo path is always demos/something
as in it automagically prepends "demos" and it assumes it is local.
It will only try to download it if its mentioned in downloads.
Really difference is just in the path.. it does not expect path but filename (also for security reasons, since this thing is part of string that is being executed)

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Chobby/commit/808f87ec4ff738b3b149bdf61a67cecd6874fc5c

chobby.exe Information: 0 : Chobbyla << StartNewSpring {"SpringSettings":"MaxDynamicMapLights = 1\nCamTimeFactor = 1\nLODScale = 1\nBumpWaterDepthBits = 32\nHardwareCursor = 1\nFSAALevel = 2\nBuildWarnings = 0\nGroundDetail = 100\nCamTimeExponent = 4\nInitialNetworkTimeout = 0\nLuaAutoModWidgets = 1\nGrassDetail = 7\nBumpWaterReflection = 2\nLODScaleRefraction = 1\nMaximumTransmissionUnit = 0\nCamMode = 1\nMaxDynamicModelLights = 1\nMiddleClickScrollSpeed = -0.001\nHangTimeout = 0\nWater = 4\nMouseDragScrollThreshold = 0\nLogFlush = 0\nUsePBO = 1\nLuaShaders = 1\nBumpWaterTexSizeReflection = 256\nGroundScarAlphaFade = 1\nVersion = 2\nOverheadScrollSpeed = 50\nEdgeMoveWidth = 0.003\nFontSize = 18\nsnd_general = 100\nBumpWaterBlurReflection = 1\nLODScaleShadow = 1\nUnitLodDist = 9999\nAdvMapShading = 1\nMoveWarnings = 0\nAllowDeferredMapRendering = 1\nAdvUnitShading = 1\n3DTrees = 1\nLoadingMT = 0\nScrollWheelSpeed = -25\nWorkerThreadSpinTime = 5\nVerboseLevel = 10\nDualScreenMiniMapOnLeft = 1\nUnitIconDist = 151\nTreeRadius = 1000\nDisplayDebugPrefixConsole = 0\nGroundDecals = 3\nSmoothLines = 1\nBumpWaterRefraction = 1\nCubeTexSpecularExponent = 100\nReconnectTimeout = 0\nShowClock = 0\nReflectiveWater = 4\nShadows = 1\nBumpWaterShoreWaves = 1\nROAM = 1\nMaxSounds = 32\nMinimapOnLeft = 1\nNormalMapping = 1\nMiniMapMarker = 0\nFPSFOV = 90\nBumpWaterAnisotropy = 2\nMaxParticles = 20000\nLinkBandwidth = 0\nLODScaleReflection = 1\nFSAA = 1\nEdgeMoveDynamic = 0\nAllowDeferredModelRendering = 1\nWindowPosX = 0\nWindowPosY = 80\nXResolutionWindowed = 1920\nYResolutionWindowed = 1000\nWindowBorderless = 0\nFullscreen = 0","StartDemoName":"20170322_013133_ScorpioBattleground_103.0.1-697-g918caba develop","Engine":"103.0.1-697-g918caba"}
chobby.exe Error: 0 : ChobbyLauncher.ChobbylaLocalListener error processing line StartNewSpring {"SpringSettings":"MaxDynamicMapLights = 1\nCamTimeFactor = 1\nLODScale = 1\nBumpWaterDepthBits = 32\nHardwareCursor = 1\nFSAALevel = 2\nBuildWarnings = 0\nGroundDetail = 100\nCamTimeExponent = 4\nInitialNetworkTimeout = 0\nLuaAutoModWidgets = 1\nGrassDetail = 7\nBumpWaterReflection = 2\nLODScaleRefraction = 1\nMaximumTransmissionUnit = 0\nCamMode = 1\nMaxDynamicModelLights = 1\nMiddleClickScrollSpeed = -0.001\nHangTimeout = 0\nWater = 4\nMouseDragScrollThreshold = 0\nLogFlush = 0\nUsePBO = 1\nLuaShaders = 1\nBumpWaterTexSizeReflection = 256\nGroundScarAlphaFade = 1\nVersion = 2\nOverheadScrollSpeed = 50\nEdgeMoveWidth = 0.003\nFontSize = 18\nsnd_general = 100\nBumpWaterBlurReflection = 1\nLODScaleShadow = 1\nUnitLodDist = 9999\nAdvMapShading = 1\nMoveWarnings = 0\nAllowDeferredMapRendering = 1\nAdvUnitShading = 1\n3DTrees = 1\nLoadingMT = 0\nScrollWheelSpeed = -25\nWorkerThreadSpinTime = 5\nVerboseLevel = 10\nDualScreenMiniMapOnLeft = 1\nUnitIconDist = 151\nTreeRadius = 1000\nDisplayDebugPrefixConsole = 0\nGroundDecals = 3\nSmoothLines = 1\nBumpWaterRefraction = 1\nCubeTexSpecularExponent = 100\nReconnectTimeout = 0\nShowClock = 0\nReflectiveWater = 4\nShadows = 1\nBumpWaterShoreWaves = 1\nROAM = 1\nMaxSounds = 32\nMinimapOnLeft = 1\nNormalMapping = 1\nMiniMapMarker = 0\nFPSFOV = 90\nBumpWaterAnisotropy = 2\nMaxParticles = 20000\nLinkBandwidth = 0\nLODScaleReflection = 1\nFSAA = 1\nEdgeMoveDynamic = 0\nAllowDeferredModelRendering = 1\nWindowPosX = 0\nWindowPosY = 80\nXResolutionWindowed = 1920\nYResolutionWindowed = 1000\nWindowBorderless = 0\nFullscreen = 0","StartDemoName":"20170322_013133_ScorpioBattleground_103.0.1-697-g918caba develop","Engine":"103.0.1-697-g918caba"} : Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot implicitly convert type 'void' to 'object'
   at CallSite.Target(Closure , CallSite , ChobbylaLocalListener , Object )
   at ChobbyLauncher.ChobbylaLocalListener.<OnCommandReceived>d__17.MoveNext()

**Comment by Licho1** [comment]
There was a bug, fixed in test. Also @GoogleFrog 
 * please do send file extensions, it changes sdf vs sdfz and who knows what in the future
 * do not forget to request download of map dna game! Unless you are certain they are present. I tried and I was missing some older test version of ZK. 

If it's hard to extract these from changing formats of the local demos, we have online demos...

**Comment by GoogleFrog** [comment]
Does stable wrapper have the fixes?

**Comment by GoogleFrog** [comment]
Fixed.
