### ISSUE TITLE
Integrate Steam Invites into Steam Chobby

### ISSUE THREAD

**Issue by Stuart1998** [ZeroK-RTS/Zero-K-Infrastructure#1669]
Steam invites should be integrated into Steam Chobby so that invites can be sent to friends to get them into the lobby.

**Comment by sprunk** [comment]
Done with coop?

**Comment by Anarchid** [comment]
Inviting into PW could be brutal.

**Comment by GoogleFrog** [comment]
This worked in various permutations when I last tested.
