### ISSUE TITLE
Update PW planet maps to current versions

### ISSUE THREAD

**Issue by Aquanim** [ZeroK-RTS/Zero-K-Infrastructure#1670]
The list of out-of-date PW maps includes but may not be limited to:

Obsidian 0.1 http://zero-k.info/Maps/Detail/31076 to Obsidian 1.3 http://zero-k.info/Maps/Detail/41716
Eye of Horus v2 http://zero-k.info/Maps/Detail/7397 to Eye of Horus v13 http://zero-k.info/Maps/Detail/55647
Comet Catcher Redux http://zero-k.info/Maps/Detail/7251 to Comet Catcher Redux v3.1 http://zero-k.info/Maps/Detail/55646
Barren http://zero-k.info/Planetwars/Planet/3961 to Barren 2 http://zero-k.info/Maps/Detail/55724
Coagulation Marsh 0.6 http://zero-k.info/Maps/Detail/36209 to 0.7 http://zero-k.info/Maps/Detail/46981
Onyx Cauldron 1.6 http://zero-k.info/Planetwars/Planet/3968 to 1.7 http://zero-k.info/Maps/Detail/54054

Maybe Dead Lands http://zero-k.info/Planetwars/Planet/3942 to Living Lands v2.03? http://zero-k.info/Maps/Detail/41686

Other map choices could possibly be improved but that would be a separate issue.

**Comment by Licho1** [comment]
Maps are based on featured list, PW maps is not yet reset/generated.

**Comment by Aquanim** [comment]
I see. The maps weren't updated in the last PW, is this a change that has happened since then?

**Comment by GoogleFrog** [comment]
The galaxy layout is complete. There are 70 planets and a decent number have good maps. Suggest replacements for the poor ones.

**Comment by Licho1** [comment]
done
