### ISSUE TITLE
Send structure owner ingame

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1678]
Structures should have their owner as keys in the PW structure modoption data. The owner should be a playername, if it is missing then someone randomly selected from the team will be the owner. This allows infrastructure to decide who the owner is and keep things up to date. The owner, should be determined by (in order):
 * structure owner.
 * planet owner.
 * rank within faction.

**Comment by Licho1** [comment]
All of this was being sent already
