### ISSUE TITLE
Commander name with special character breaks server when modifying this commander.

### ISSUE THREAD

**Issue by Vistritium** [ZeroK-RTS/Zero-K-Infrastructure#1679]
When commander name contains special character, for example "'" the server will translate it to "&#39 ;" next time you refresh the page. Then you can't modify the commander. The server returns 500:
https://gist.github.com/Vistritium/060a87374ac0877b478cbbe2a43d39b5

**Comment by KingRaptor** [comment]
Fixed, thanks!
