### ISSUE TITLE
Change Structure Names

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1683]
Some structure names need changing and I can't find the DB.
 * Wormhole Generator Beacon  -> Wormhole Generator
 * Improved Wormhole Stabilizer -> Improved Wormhole

The reason is to fit unit names on the space provided by chili selections.

**Comment by Licho1** [comment]
Table is StructureTypes.
I renamed Improved Wormhole, but wormhole "beacon" is not even in DB, it was caleld "Wormhole Generator".
Are you sure you don't get those from unit names ingame instead of server data?
