### ISSUE TITLE
Sign in through steam login failed

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1685]
I attempt to sign in through steam by clicking the "sign in through steam" button on the main ZK page. This takes me to a steam page where I can select my name and click login. Then I am returned to a ZK page with a long URL starting 'http://zero-k.info/Home/Logon?referer=...' which is a blank white page saying "login failed".

**Comment by db81** [comment]
Same here.

**Comment by Anarchid** [comment]
Wary of locking myself out, i fired up another browser and attempted that. Login successful with Mac Firefox 52.0.1 (64-bit)

**Comment by Licho1** [comment]
It works for me. I suspect it was random steam fault (as before). 
If you replicate please specify borwser.
