### ISSUE TITLE
Planet Replacements

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1686]
Here is a list of planet replacements. The maps are sorted by position on the map, either as part of a factions starting territory or the neutral area between two factions. The let column is my knee-jerk rating of the map for planetwars. The center column is a replacement (if required) and the right column keeps track of the type of map.

Here are the things I did:
 * Replaced low scoring maps with better once.
 * Fixed duplicates.
 * Tried to even out small, medium and large maps between the six areas, also evened out occurrence of water maps.
 * Applied large maps for homeworlds and medium-large maps for artifacts.

I'd like comments on map placement design. Should we put maps of particular types in certain areas of the galaxy map? Perhaps small maps in the neutral areas and large maps towards the back of faction territories? Maps at the back of faction territories are less likely to see combat so perhaps we should stash somewhat worse maps there.

This map list could be applied and it would definitely be better than what we have at the moment. If I get the chance to apply it I will likely make swaps to balance some things out. I did not pay as much attention to which types of maps neighbour which sides of neutral territory.

Some technical things:
 * How is the player count required for the planet set? Many of these maps work much better with three players. Quite a few maps only require two so we should seize that oppotunity.
 * Do maps automatically get an appropriate planet image when they are changed?
 * Don't change planet names when applying new maps.

[planets.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/901765/planets.txt)

**Comment by Licho1** [comment]
Player count is set this way - maps sorted by map diagonal size and 15% biggest get 3v3 ..
rule can be changed and we can set it manually too.

Planet image is auto updated based on map.

**Comment by Licho1** [comment]
Ok added planet map and size editing. Please make sure no maps are duplicate.

**Comment by Anarchid** [comment]
Implemented the list, with deviations:
* `3   Small_Divide-Remake-v04    -> Emain Macha v3            : Large`: Skipped because i hate Emain Macha. Used Into Battle instead.
* `4   Terra                      -> Throne v1                 : Large` Skipped because Throne belongs as Empire capital
