### ISSUE TITLE
Treaty list

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1695]
Here is a proposed complete list of treaties and effects.

These treaties add or remove options for attacking or defending.
 - [x] Invasion wormhole access: Gives faction A more places to attack and place dropships. They can attack and place dropships as if they were faction B.
 - [x] Bomber wormhole access: Same as the above but with bomber placement.
 - [x] Ceasfire: Prevents faction A from attacking or placing dropships or bombers on the planets of faction B
 - [x] Influence Freeze: Prevents influence gain through wormholes of faction A on planets of faction B.
 - [x] Defensive pact: Allows players from faction A to join the defense of planets of faction B.

These treaties are identical to the ones above but only for a single planet.
 - [x] Invasion wormhole access from planet: Allows faction A to attack and place dropships as if they owned a particular planet.
 - [x] Bomber wormhole access from planet: Same as above but for for bombers.
 - [ ] Avoid planet: Prevents faction A attacking, dropshipping or bombing a planet.
 - [ ] Influence freeze on planet: Prevents influence spread to planet.
 - [ ] Defend planet: Allows players from faction A to join defense of a planet (complicated one, not needed?).

This is the list of values that can be traded.
 - [ ] Give metal once.
 - [ ] Give dropships once.
 - [ ] Give bombers once.
 - [ ] Give warp core once.
 - [ ] Give victory points once.
 - [ ] Give IP on a particular planet once.
 - [ ] Give metal per turn.
 - [ ] Give dropships per turn.
 - [ ] Give bombers per turn.
 - [ ] Give warp core per turn.
 - [ ] Give victory points per turn.
 - [ ] Give energy per turn.

**Comment by GoogleFrog** [comment]
Probably implemented.

**Comment by GoogleFrog** [comment]
I added this to DB but it requires testing.

**Comment by sprunk** [comment]
Testing has its own ticket #2119
