### ISSUE TITLE
[feature request] clean way to shut down springie

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#170]
is there a way to shut down springie in a clean way?

i.e. that it just waits for all games to end and then finally shuts down?

atm its only possible to kill springie and then wait until all spring-dedicated.exe processes have quit (afaik)

**Comment by Licho1** [comment]
Fixed ending in self update - it wont kill games now and if server restarts it will wait for games to finish to report scores.
