### ISSUE TITLE
Planet buster issues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1703]
Check this out: http://zero-k.info/Planetwars/Planet/4334
 * The planet buster residue image should look more like debris and the underlying planet should no longer be drawn.
 * Planet buster should destroy all structures.
 * All planets adjacent to the destroyed planet should now be adjacent to each other. Otherwise a few well placed planet busters could disconnect the galaxy.

**Comment by sprunk** [comment]
>All planets adjacent to the destroyed planet should not be adjacent to each other.

"should *now*"?

**Comment by GoogleFrog** [comment]
Remove planet buster.
