### ISSUE TITLE
Planetwars mechanics feedback

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1705]
Here are some game mechanics to consider for next round:
 * Make Artifact ingame destroyable and able to be evacuated. This gives attackers the option of destroying the artifact to prevent VP gain for 10 turns.
 * Reduce ingame structure health. Command center is not easily rushable given its large health pool. Some defense around the CC prevents it from being sniped by a losing team. The vast majority of CC destruction that I have witnessed were achieved by an uncontested, fairly static, force (usually a commpush with turrets). This method of destruction does not care how much health the CC has so we may as well lower it as a buff purely to snipes.
 * Consider shorter evacuation time. Perhaps 10/5 to 8/4?
 * Match colours ingame? Players could receive colours close to their faction colour.
 * String connector: It is cool but subverts many mechanics and makes the map ugly. If we want a drawn out multifront war decided mostly by artifact control then the existence of string connector is bad. It has the potential to make the map feel very small (remove some epicness). Perhaps it is better with warp jammer fix (see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1702). It also subverts the defensive metal for distance from HQ mechanic.
 * Consider reducing the energy:metal conversion rate. Currently it is 20 energy for 1 metal, this may be a bit high as it makes the battles less important. Maybe 50 energy for 1 metal?
 * Consider the effect of planet buster and string connector. They bring the game closer to ending in an unstable way. See below.

I dislike planet buster and string connector because they have a permanent effect on the galaxy which is bought about through the actions of few players (the faction leads). Battles should be central to planetwars so I feel like it should focus on battles and fronts, the taking and losing of planets. Every participates in that. The front pushing should also have the opportunity to persist for quite a while, to be solved by diplomacy, coordination and the threat of victory points. Planetwars should be able to support a prolonged struggle otherwise we'll have to run a new one every week.

Here is a way to think about planetwars design: what are the actions that bring the game closers to it's conclusion?
 * Gaining victory points: If 298 victory points are gained then one faction has won.
 * Planet busting: If 69 planets are destroyed then one faction has effectively won.
 * String connecting (sort of). If every planet is connected to every other planet then IP spread will surely overcome the smaller side. More realistically, string connecting cuts off whole swathes of the galaxy from activity.
 * Infrastructure production (somewhat). Infrastructure can be destroyed but it is difficult. Also, things like bombers and dropships that increase aggressive power have defensive counters.

Perhaps that is the wrong way to think about it. Perhaps planet busting is fine but too cheap. Currently the galaxy produces about 700 metal a turn. One planet buster every 3.5 turns. Every planet destroyed in 245 turns. This isn't quite realistic since planet busters are highly disruptive to infrastructure but that is all the more reason to try and make as many as you can. We could also consider some temporary versions of the weapon that involve more player interaction.

Perhaps String Connector creates a link after powering up but then continues to exist. If the String Connector is ever disabled then it would be destroyed. This makes the structure temporary and with high energy drain it would effectively drain metal to keep running. It creates some cool battles because to close the string the defenders simply have to attack the planet back through the string it created and destroy the generator, even if they lose the battle. This would actually be a much cooler replacement for warp cores.

Planet buster could be replaced with a bioweapon that makes chickens. Alternately, planet buster could be a lot more expensive and the bioweapon could exist in its place. This weapon would make a planet neutral and cover it with Hard Chickens (block warp, perhaps some IP gain reduction?). Players could clear the chickens after several battles.

**Comment by GoogleFrog** [comment]
Remove the ability for players or clans to leave a faction. This should be toggleable in the database because players should be able to move around between planetwars. Make admins able to boot people from factions in case someone misclicks or for some other reason. If this is not implemented then people are going to change factions to be 'super allies' and then switch back afterwards. I'm against midgame switching, what do you think @Licho1?

**Comment by GoogleFrog** [comment]
Apparently the Defensive Pact alliance is inoperable. There is a ticket on chobby repo about it.

**Comment by GoogleFrog** [comment]
Charge up times need looking at. Wormhole charge up time should be 3 rounds under the assumption that all factions are taking their turns. Planet buster should be longer under the same assumption.

**Comment by Anarchid** [comment]
Make charge times scale up with faction count?

**Comment by sprunk** [comment]
Artifacts were not used at all, nobody even bothered to capture any artifact planet. I think this was caused by PB though.

**Comment by Aquanim** [comment]
- The HQ-victory mechanic being based on ownership of a single HQ feels strange to me - I think it makes it entirely plausible that a faction which is not 'ahead' by any reasonable definition can steal a win. Something along the lines of 'control a majority of the headquarters' or 'control all of the headquarters', either instantaneously or for X turns, seems more reasonable. 'Control a majority of the headquarters' isn't much harder to accomplish in reasonable usecases (and when HQs cannot be destroyed).

- String connectors and Planet Busters permanently affect the entire game. To me it feels like they should be far more expensive, as a rare and flashy option to break stalemates. (At their present cost it seemed like they invalidated warp cores and bombers, which seemed very silly.) HQ planets and probably artifacts should be immune from such things, but I'm not sure whether ordinary planets should be protectable from them.

> Artifacts were not used at all, nobody even bothered to capture any artifact planet. I think this was caused by PB though.

I can't speak for the other factions, but Empire's opinion was that anybody taking an artifact planet would be dogpiled at best and planet busted at worst.

**Comment by GoogleFrog** [comment]
Two minor things:
 * Send more structure keys ingame to tell the structure spawner about disabled structures and let the tooltip of the structure show player how long they have until they are enabled. I would then make disabled versions of the structures to place ingame which are completely static (no energy, drones, etc..). This allows the structure to be re-destroyed ingame to reset to disable timer or for the defenders to evacuate the structure and allow it to keep powering up unaffected. Ideally the disabled structures would look a bit beaten up, not have glowy bits and would not have any animations.
 * Make planet buster an ingame structure. I think structures are more interesting when they appear ingame. We have two free structure models (double wormhole and small energy) and the Influence Inhibitor is a boring structure that may as well be replaced.

Currently my ideal big changes are as follows:
 * Remove string connector.
 * Add a Warp Gate structure which creates a string between two planets. This does not destroy the Warp Gate but once a string is created it cannot be re-aimed (perhaps this could be technically done with two structures, one replacing the other on activation). If the Warp Gate is ever disabled it is destroyed, this destroys the string that it created (for edge cases, if the string was an original edge then do nothing, if there is an active Warp Gate maintaining the string from the other end then do nothing). This enables the creation of a string but gives the defenders a way to fight back through the opening and close it. Maintaining the string should drain a lot of energy.
 * Possibly reinstate the old Warp Core Fabricator but with a higher infrastructure cost. Warp Cores are tradeable and more flexible than Warp Gate so they should not be much more efficient than it.
 * Fix planet buster by making it destroy all structures and replace the planet image with debris. Perhaps this could be done simply by removing the map associated with the planet and making debris the fallback for when a planet has no map. A planet with no map should not be targetable by anything (Warp gate, ships, invasion etc...). All planets adjacent to a planet with debris should be treated as adjacent (recursively, for multiple debris in a row).
 * Make warpjamming block planet buster and any sort of string connection ability.
 * Make artifacts and HQ have an always-enabled warp jamming ability. A faction should be unable to target their own perma-warp jamming planet as well. HQs and artifacts must be unbustable.

If there is no time for the above then consider these changes:
 * Remove string connector and planet buster.
 * Alternately, replace planet buster with a bioweapon that makes chickens (if the current DB keys support this with no code change).

I don't think string connector and planet buster are vital for the core gameplay of planetwars. They are cool but if they don't work correctly they overpower the game.

Here are some vital changes:
 * Give HQs an ability that prevents the planet from being neutral. The planets with a HQ should only change owner when someone else reaches 50.1 IP. My intention with HQs is that if a faction does not own their own HQ then the game is over. I was implicitly thinking this when I said the wording "you win if you own another factions HQ".
 * Prevent the owners of a HQ planet from trading away IP from that planet. Factions should still be allowed to trade away IP on a HQ planet that they don't own (this could be part of a peace deal).

**Comment by Aquanim** [comment]
I would prefer to see "you cannot win the game if you do not control your HQ" rather than "you immediately lose if you lose your HQ".

**Comment by GoogleFrog** [comment]
My aim with winning if you control an enemy HQ is to remove faction elimination. If two factions gang up on the third then there should be infighting as they approach the HQ, since only one faction can win. A faction should be highly cautious if an enemy has a planet next to their other enemy's HQ. I think there is enough space around the HQ to give mostly defeated factions some ability to impact the game and play the larges ones off against each other.

In short, I want the game to end if one faction is extremely crippled and I want the other two factions to never be motivated to work together to finish crippling a faction. HQ victory seems to achieve this.

I think the volatility is mainly due to the relatively cheap, high powered weapons that we saw this round (connector and buster). Without those cheap options we would have continued to build up economy and could easily afford some defenses to make it much harder to dive in an take planets. A large faction could even donate energy to a small one for the purpose of keeping the small factions defenses running.

**Comment by Aquanim** [comment]
>In short, I want the game to end if one faction is extremely crippled

I suppose that's reasonable.

**Comment by Anarchid** [comment]
> Make warpjamming block planet buster and any sort of string connection ability.

Does this exempt Galaxy Compressor? If it also blocks GC, that's rendering it quite pointless. I think the appropriate change here is to remove GC and PB and replace PB with the bioweapon that neutralizes and chickenizes the planet but retains infrastructure for conquest. At that point it can be even cheaper because it's reversible and blockable. This also dissolves the problem of figuring out a pretty way to connect planets formerly linked through target.

> Possibly reinstate the old Warp Core Fabricator but with a higher infrastructure cost. Warp Cores are tradeable and more flexible than Warp Gate so they should not be much more efficient than it.

I'm pretty sure this will reintroduce the situation where the first faction to obtain enough cores wins.

> Artifacts were not used at all, nobody even bothered to capture any artifact planet. I think this was caused by PB though.
An artifact win costs more than a Galaxy Compressor worth of metal in energy overdrive (artifact converts 2000e into 1 vp, and overdrive converts 50e into 1m, therefore 1 vp costs 100 metal and 100 vp cost 10000 metal), plus at least 4k metal in energy infrastructure (cheapest per cost energy is 100m for 50e, you'll need 40 of those to generate 2k e), and is just as slow (100 turns to power up GC, 100 turns to farm VP's from one artifact). VP's are too expensive.

The full minimal cost of firing the first planetbuster is 2500 (pb) + 1300 (energy) + 325 (overdrive opportunity cost).

> Add a Warp Gate structure which creates a string between two planets. 

This is awesome.

**Comment by Anarchid** [comment]
> I think the volatility is mainly due to the relatively cheap, high powered weapons that we saw this round (connector and buster)

Sparta was conquered without any use of PB or SC; instead it was a massive dropship fleet, Federation's entire government being absent and consequently no metagame attempts to defend (garrison, def grid, etc), and the Defense Pact treaty being dysfunctional.

Dropships were pretty high-powered, though. A single dropship costs two turns of Dropfac operation = 320 energy = 16 metal; you need 42 dropships to capture an intact unfortified HQ in a single attack. This costs merely 714 metal.

**Comment by GoogleFrog** [comment]
Licho and I discussed and think there is a problem with metal sinks. What is metal spent on once infra is built? Two ideas:
 * Free unit spawning ingame for PW metal.
 * Metal cost to rush structure activation.

I think we much prefer the latter. This would allow things such as rushing wormhole or defense activation.

**Comment by Aquanim** [comment]
The latter option appeals to me more as well.

**Comment by GoogleFrog** [comment]
Infrastructure changes:
 * Metal cost to rush structure activation.
 * Send more structure keys ingame to tell the structure spawner about disabled structures and let the tooltip of the structure show player how long they have until they are enabled.
 * Make sure that chickenification works.
 * Reduce overdrive income from 20 to 1 to 50 energy for 1 metal

**Comment by sprunk** [comment]
Everything implementable infraside seems to be done. I've made a ticket for the remaining gameside thing https://github.com/ZeroK-RTS/Zero-K/issues/2891
