### ISSUE TITLE
How many megabytes is all the planetwars maps?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1709]
If we include all 70 maps used for the last planetwars what does the steam package size look like?

**Comment by Anarchid** [comment]
There are 1481 megabytes in galaxy 28.

**Comment by sprunk** [comment]
Including PW maps has recently been tried but reverted in 15 minutes so decisions seem to have already been made.

8cbd3e0ab39ad825a57b833d2829373e78c9eed3
dff7e3820cd83bcedd35eb88bd1cecfac08dcead
