### ISSUE TITLE
springie has no cleanup task (=delete old replays/infolog.txt/old db stuff)

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#171]
imo there should be some cleanup task which deletes old replays / infolog.txt / other old files on server side.

is there any point of keeping these files?

i guess the same applies to database?!

why? reduce backup size, speed things up i.e. currently opening some folders at server side takes ages, chkdsk takes ages as well, server migration will take ages (again)

idk if this applies: spring-dedicated very likely lists all files in its data-dirs (for getting maps/games), if these contains a lot of unused files, its slow at start, too.

there is a reason why there is no full backup of the server (imo because its so huge!)

**Comment by Licho1** [comment]
No longer dumps infolog and demos are glacialized periodically.
