### ISSUE TITLE
Check evacuation mechanics.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1712]
15 seconds ago 	EErankAdminAnarchid changed energy priority of Field Garrison on Radius to High
23 seconds ago 	EErankAdminAnarchid changed energy priority of Planetary Defense Grid on Radius to High
118 seconds ago 	EErankAdminAnarchid has built a Planetary Defense Grid on Dynasty planet Radius.
2 minutes ago 	ILrankAdminhokomoko of Dynasty TheGBC has captured planet Sagan from AUrankAquanim of Empire RSN. B454519
2 minutes ago 	All non-evacuated structures have been disabled on Empire planet Sagan. B454519
2 minutes ago 	Empire structure Field Garrison on planet Sagan has been saved by evacuation. B454519
2 minutes ago 	Dynasty attacked Empire Sagan in B454519 and won. . Dynasty gained 35 influence (100% from winning flawlessly of 35 base)
2 minutes ago 	ROrankSigero gained 16 metal from battle B454519
2 minutes ago 	PLrankzenfur gained 16 metal from battle B454519

The evacuated Field Garrison seems to have been destroyed, it is not on Sagan anymore. Does evacuation actually delete structures? Does it only delete them when the planet changes hands? Is there a bug or was this intended?

**Comment by Anarchid** [comment]
It was destroyed because Sagan was taken, and Field Garrison prefers to self-destruct rather than fall into enemy hands.

**Comment by GoogleFrog** [comment]
Really? In database?

**Comment by Anarchid** [comment]
Yes. The following things have the the `OwnerChangeDeletesThis` flag:

```
StructureTypeID	Name
12	Field Garrison
13	Interception Network
15	Planetary Defense Grid
594	Local Militia
602	Galaxy Compressor
```
