### ISSUE TITLE
There are no battle threads

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1718]
Battle threads are not being generated. There does not seem to be a way to download replays. Also I hear that ELO is not updating.

**Comment by DeinFreund** [comment]
There is no autoregistrator

**Comment by Anarchid** [comment]
Autoregistrator controls discovery of new mods and maps. Not creation of replays, etc.

**Comment by Licho1** [comment]
Its related, without discovery, there is no DB save (cannot link to map/game)

**Comment by DeinFreund** [comment]
This ticket still being open would lead me to believe in your awareness of the server being of reduced functionality. Anyway I've now moved this into #1728.

Lack of replays also means lack of battle thread and lack of elo updates.

**Comment by sprunk** [comment]
Works (recent battle example with downloadable replay, a thread and Elo change: https://zero-k.info/Battles/Detail/460534 )
