### ISSUE TITLE
Site throws Error randomly

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1721]
From time to time, instead of receiving the site I requested, this is served:
`The custom error module does not recognize this error.`

I have yet to find a pattern behind this, it happens randomly on any part of the zk site. It also doesn't seem to appear in the logs. Is there a way to debug this?

**Comment by Licho1** [comment]
It is the "spam" prevention thing. It is expected. 
Code is https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/AppCode/DosProtector.cs

**Comment by DeinFreund** [comment]
Even though you've already relaxed the limits, it keeps happening while I'm just regularly using the site. Are you sure it's working correctly?

**Comment by Licho1** [comment]
I think it is, problem is hovering tooltips, these generate extra request, so if you do a thing like sliding 20 names quickly you can exceed it.
Tooltip widget should be modified to be more sensible.

**Comment by DeinFreund** [comment]
It also happens when using the site search.

**Comment by KingRaptor** [comment]
I think this can be treated as a duplicate of #1778.
