### ISSUE TITLE
Issues with autoregistrator

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1728]
The server seems to be currently using ZK v1.5.4.20 by default. It fails to save any replays with that version of ZK.

Manually setting the game to zk:stable yields ZK v1.5.4.19. This works for replays.

The latest version would be ZK v1.5.4.22.

My assumption is the autoregistrator having failed to automatically update rapid and steam to 22.

**Comment by DeinFreund** [comment]
Might want to add that both 19 and 20 have "game breaking" bugs which is why I'm so stressed out about this.

**Comment by sprunk** [comment]
looks fixed since

**Comment by Licho1** [comment]
it was that rapid failure i think its fixed
