### ISSUE TITLE
please review: forum->new post BB code insertion

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#173]
please review: forum->new post BB code insertion
https://github.com/mojjj/Zero-K-Infrastructure/compare/patch-3?expand=1

as i cannot connect to the DB, i cannot build the page. 

this commit adds to the new-post html snippet a by-click insertion of the BB code into the text area. 

as it would break the forum functionality if its errorous, please someone build the page locally and test it.

**Comment by Licho1** [comment]
can self-review now
