### ISSUE TITLE
Steam-K lacks libsdl2

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1731]
After downloading the game on steam, if I press "Start", nothing happens. Here's the error that occurs when trying to launch it manually:

> Unhandled Exception:
> System.BadImageFormatException: Could not resolve field token 0x040019c2
> File name: 'Chobby.all'
> [ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Could not resolve field token 0x040019c2
> File name: 'Chobby.all'
>

**Comment by DeinFreund** [comment]
Apparently the steam install didn't include libsdl2. If steamers are expected to install this manually, it should be clearly marked somewhere..

**Comment by Licho1** [comment]
@GoogleFrog  do not make engine from portable minimal. We need full version for it to include all libs (also for windows)
