### ISSUE TITLE
Steam-K lacks ZK

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1732]
After installing latest ZK via Steam and joining a Multiplayer game I still had to download the latest version of zk via rapid. Then restart the lobby for it to recognize the newly downloaded game while being spammed with download debug messages.

**Comment by Licho1** [comment]
Was it game of stable zk ?

**Comment by DeinFreund** [comment]
Yes, all defaults.

**Comment by Licho1** [comment]
fixed now
