### ISSUE TITLE
Wrapper error during file deployment

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1738]
See https://github.com/ZeroK-RTS/CrashReports/issues/1056

**Comment by Licho1** [comment]
```The process can not access the file "C: \Users\Knecht\Documents\My Games\ Zero-K\ sqlite3.dll" because it is being used by another process.```

Looks like he started ZK twice at the same moment? I can add a mutex which will prevent it but do we want it?

**Comment by sprunk** [comment]
As long as the other instance runs fine I think it's not needed.
