### ISSUE TITLE
Spec calling !resign insta resigns game

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1739]
If there's only one player left and a resigned player calls !resign the player is instantly force resigned.

http://zero-k.info/Battles/Detail/457169

**Comment by db81** [comment]
sfire must be very happy about this

**Comment by let4be** [comment]
nice feature, pls dont fix

**Comment by Licho1** [comment]
I believe this is correct behavior if there are three people and two vote resign (including if they are specs) its ok to quit.

**Comment by DeinFreund** [comment]
The problem is there is that the resign poll only requires a single vote. This means that a single spectator typing `!resign` already ends the game. There should be at least a second vote required if the poll is called by a spectator, but not when called as the last remaining player.

I think it would be simpler to simply disallow spectators from voting on resign.

**Comment by Licho1** [comment]
Number of votes is 
eligible people / 2 + 1
so if there is 2 players, it should still need 2 votes.. thats how i read the code

**Comment by DeinFreund** [comment]
It is probably because one of the active players doesn't have vote rights. I've experienced this before with more players.

How can this happen besides the active player being afk? In my replay it seems like everybody was using chobby which makes it hard to be flagged as afk while playing.

**Comment by Licho1** [comment]
Probably he was "away" in lobby. That disables vote perms. Why would he be that though?

**Comment by GoogleFrog** [comment]
Away is sent to the server if no mouse movement, mouse clicks or key presses have been registered by Spring for the last four minutes. This is done by a widget in luaMenu so it gets to see key presses before anything in luaUI or ingame. If you want some other detection you will need wrapper support.

**Comment by Licho1** [comment]
Wrapper could send system idle (that monitors system-wide clicks and keypresses). For example each extra minute of idle it could send idle time and let chobby decide what to do.
Is that reasonable?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by DeinFreund** [comment]
Moved to https://github.com/ZeroK-RTS/Chobby/issues/620
