### ISSUE TITLE
make gifv tag autoresize webm format to forum layout

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#1743]
when you add a high resolution webm video to forums it will be left by its size and noone can enjoy good videos. You have to scale video to like 640x480 to fit forum dimensions. Thats odd, noone will have fun watching this.
Example thread:
http://zero-k.info/Forum/Thread/24122?postID=175047

**Comment by db81** [comment]
Dein beat you to it 12 hours ago: #1742.
