### ISSUE TITLE
MatchMakerSetup is out of date

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1747]
I received this message:
[f=-000001] [ServerMessage] MatchMakerSetup {"PossibleQueues":[{"Name":"Teams","Description":"Play 2v2 to 4v4 with players of similar skill.","Maps":["Avalanche-v2","Red Comet","Titan-v2","TitanDuel","Valles_Marineris_v2","Trojan_Hills_v02","Hide_and_Seek_v03","Intersection_v3","Living Lands v2.03","Obsidian_1.3","Isle of Grief 0.2","Fairyland v1.0","Akilon Wastelands ZK v1","Onyx Cauldron 1.7","Calamity 1.1","Adansonia v4.1","Lonely Oasis v1.1","Comet Catcher Redux v3.1","Eye of Horus v13","Wanderlust v03","Vittra v2.1","Into Battle v4","Barren 2","Cold Snap 2","Badlands 2.1"],"Game":"Zero-K v1.5.6.1","MaxPartySize":4},{"Name":"Coop","Description":"Play together, against AI","Maps":["Avalanche-v2","Red Comet","Titan-v2","TitanDuel","Valles_Marineris_v2","Trojan_Hills_v02","Hide_and_Seek_v03","Intersection_v3","Living Lands v2.03","Obsidian_1.3","Isle of Grief 0.2","Fairyland v1.0","Akilon Wastelands ZK v1","Onyx Cauldron 1.7","Calamity 1.1","Crubick Plains v1.2","Adansonia v4.1","La Isla Bonita v1.1","Lonely Oasis v1.1","Comet Catcher Redux v3.1","Eye of Horus v13","Wanderlust v03","Vittra v2.1","Into Battle v4","Barren 2","Chicken Nuggets v5","Cold Snap 2","Badlands 2.1"],"Game":"Zero-K v1.5.6.1","MaxPartySize":5},{"Name":"1v1","Description":"1v1 with opponent of similar skill","Maps":["Avalanche-v2","Red Comet","TitanDuel","Valles_Marineris_v2","Trojan_Hills_v02","Hide_and_Seek_v03","Intersection_v3","Living Lands v2.03","Obsidian_1.3","Isle of Grief 0.2","Fairyland v1.0","Onyx Cauldron 1.7","Crubick Plains v1.2","Adansonia v4.1","La Isla Bonita v1.1","Lonely Oasis v1.1","Eye of Horus v13","Wanderlust v03","Vittra v2.1","Into Battle v4","Barren 2","Badlands 2.1"],"Game":"Zero-K v1.5.6.1","MaxPartySize":1}]}

When I found a match in the 1v1 match maker I got an error that said the game would not start because I don't have Intersection v4.1. The version 4.1 is the version on the site as the version used in matchmaking. Intersection_v3 has supported level 'none'.

**Comment by GoogleFrog** [comment]
I've made the site reflect what is sent to the lobbies for the sake of stability. These maps were affected:
 * Trojan_Hills_v03
 * Intersection v4.1
 * Titan-v2
 * Red Comet v1.3

Also, Fairyland v1.0 was set to supported level 'none' but was still send to the lobbies.

**Comment by Anarchid** [comment]
It [looks](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/47a37d2ca02eba8aaf22c0e83333eef22c5bfb3e/ZkLobbyServer/MatchMaker/MatchMaker.cs#L51) like the queues only read from the database on MatchMaker instantiation = server restart needed to refresh. 

Seeing how all those maps were featured a long while ago and did not end up in the MatchMakerSetup, i guess, suggests that the server has been quite stable.
