### ISSUE TITLE
Commanders stuff (DB text description tweaking)

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1749]
- [x] All chassis say "Metal cost" instead of "Morph 1 cost", the 25m cost is correct.
- [x] Other morphs have correct "Morph X cost" text but wrong cost values:
[2] 150 -> 100
[3] 500 -> 400
[4] 300 -> 200
[5] 400 -> 300

- [x] Site says "Morph 1..5" which corresponds to ingame levels 2..6 - confusing, probably should say Level (or Morph) 1 -> 2 .. 5 -> 6.

- [x] The "minimum morph" stat is off by 1 on all modules except:
	Autorepair
	Companion Drone
	Battle Drone

Everything except these should get +1 to morphLevel.

Other wrongness:

- [x] Beamlaser: cost 25 -> 50, range 300 -> 330
- [x] Heatray: cost 75 -> 50, DPS 410 -> 450, range 320 -> 300
- [x] HMG: cost 75 -> 50, damage 33 -> 30, range 290 -> 285
- [x] Flamer: cost 75 -> 50, range 280 -> 270, damage does not mention multihit
- [x] LPB: damage 41 -> 55, range 330 -> 300
- [x] Lightning: cost 75 -> 50, damage 256 -> 220, emp 640 -> 550, range 280 -> 300, reload 2 -> 1.66
- [x] Missile: cost 75 -> 50
- [x] Riot: damage 240 -> 220, reload 2.2 -> 2, range 270 -> 275
- [x] Shotgun: cost 75 -> 50, range 300 -> 290
- [x] HPB: cost 200 -> 150, reload 4 -> 3.1, max purchase 2 -> 1, range 350 -> 390, icon red -> green (as a conversion)
- [x] Shock Rifle: cost 200 -> 150, max purchase 2 -> 1, icon red -> green (as a conversion)

- [x] Advanced Targeting: range +10% -> +7.5%
- [x] Area Shield: regen 60 -> 50
- [x] Personal Cloak: chassis {all except guardian} -> {all}
- [x] Area Jammer: chassis {all except guardian} -> {all}
- [x] Lazarus: chassis {support, strike} -> {support}
- [x] High Density Plating: limit 7 -> 8
- [x] Flux Amplifier: chassis {support} -> {support, strike, recon}, affected weapons: {LG} -> {LG, Multistunner}
- [x] Companion Drone: cost 400 -> 300
- [x] Battle Drone: cost 600 -> 500
- [x] Disintegrator: cost 400 -> 150, reload 20 -> 30, damage does not mention multihit
- [x] Disruptor Bomb: cost 125 -> 150, slow 1750 -> 2100, reload 12 -> 25
- [x] Hellfire nade: cost 100 -> 150, reload 12 -> 25, napalm dps 20 -> 40, missing aoe: 256 explosion, 128 napalm
- [x] Multi Stunner: cost 125 -> 150, damage 543 -> 550, stun time 6 -> 8, reload 12 -> 25
- [x] SLAM: cost 200 -> 150

**Comment by sprunk** [comment]
More things from recent(ish) ingame patches:
 - [ ] [disintegrator:](https://github.com/ZeroK-RTS/Zero-K/commit/7648710622c203c855055953c401c5d0d1e038c0) [now with waterproof action!](https://i.imgur.com/tGLqJHE.jpg)
 - [ ] [disruptor bomb: does not damage allies](https://github.com/ZeroK-RTS/Zero-K/commit/5d5a0022f6988d7af28160e51d15b560fdd58df5#diff-2e2e08638efc1422a8a0d2a95f6092cd)
 - [ ] [LG reload: 1.66 -> 1.83](https://github.com/ZeroK-RTS/Zero-K/commit/4fcbbec48fb12eb269ad23383c78984832f27c7e)
 - [ ] [flamer: damage 10 -> 11](https://github.com/ZeroK-RTS/Zero-K/commit/4fcbbec48fb12eb269ad23383c78984832f27c7e)
 - [ ] [disruptor ammo: cost 450 -> 300](https://github.com/ZeroK-RTS/Zero-K/commit/4fcbbec48fb12eb269ad23383c78984832f27c7e)

**Comment by sprunk** [comment]
More missed things:
 - [ ] [servos: speed 10 -> 8 %](https://github.com/ZeroK-RTS/Zero-K/commit/44a30e3808983c337f554b083c5213a28bc0a71d#diff-0497c6a05e5a95d7feb4b2b83be3a006R766)
 - [ ] [CR nano: BP 5 -> 4](https://github.com/ZeroK-RTS/Zero-K/commit/90d00bfe6ff0802c893b83af5e7f03042fe00a23)

**Comment by sprunk** [comment]
I wrote some sql. As far as I can tell it covers all remaining inconsistencies.
```sql
UPDATE [zero-k].[dbo].[Unlocks]
SET MorphLevel = MorphLevel + 1
WHERE NOT (Name = 'Autorepair System' OR Name = 'Companion Drone' OR Name = 'Battle Drone');

UPDATE [zero-k].[dbo].[Unlocks]
SET Description = 'Increases movement speed by 8%'
WHERE Name = 'High Power Servos';

UPDATE [zero-k].[dbo].[Unlocks]
SET Description = 'Increases build speed by 4 metal/s'
WHERE Name = "CarRepairer's Nanolathe";
```

**Comment by Histidine91** [comment]
Executed the nanolathe and servo queries, thanks!

Changing the morph level causes no modules to be fittable at level 1 and special weapons to be unusable. Is the issue simply a player-facing UI inconsistency with the comm page displaying "Morph X", where X = ingame level + 1? Could change the .cshtml file in that case.

**Comment by sprunk** [comment]
Alright. In that case the 3 exception modules should get -1 then.
