### ISSUE TITLE
Infrastructure doesn't save some of my replays

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K-Infrastructure#1751]
I set up a custom passworded game with Null-AI as an opponent and I use !cheats in game. Then I quit from the game correctly (i.e. not with !exit)
Such games are not saved in the list of "Last Battles" and therefore I can't reference them when I make bug reports.

**Comment by Licho1** [comment]
In that case you have your demo saved locally. So you can still upload it for bug report. I don't think its worth keeping demos from every game..

**Comment by sprunk** [comment]
I think his point was that it would be good if the rules on which games are saved and which aren't were clear (now it looks like a bug that some aren't saved if someone doesn't know about it).

**Comment by Licho1** [comment]
Desync and cheat arent saved
