### ISSUE TITLE
Tournament status spam

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1756]
This repeats every once in a while and is no longer relevant:
![image](https://user-images.githubusercontent.com/3822768/27557919-14821772-5ac4-11e7-9afa-09171b135f7d.png)

**Comment by Licho1** [comment]
Thats a topic i think.

**Comment by DeinFreund** [comment]
That's the channel topic. It's up to the lobby how to display it.

**Comment by sprunk** [comment]
That's a topic.
