### ISSUE TITLE
MatchMakerStatus never sends more than one InstantStartQueues

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1759]
MatchMakerStatus  is supposed to send every relevant InstantStartQueue to the lobby and let the lobby decide which of them to display. Instead it seems to never send a table of size greater than 1.

I tested on test server.

**Comment by DeinFreund** [comment]
It will try to match you into any battle and then remove you from the list, so only the first match will be returned.

**Comment by Licho1** [comment]
Yeah it cannot guarantee instant start with multiple options..
its basically what-if scenario.
But perhaps some tweaking can be added on the level of queue vs queue priorities

**Comment by DeinFreund** [comment]
So my suggestion wouldn't work? The current what if only seems to consider joining all queues, not each possibility on its own.

**Comment by sprunk** [comment]
I don't see why it couldn't guarantee instant start?

Example:
 * person A is sitting in 1v1 queue.
 * person B is sitting in Coop queue.

Now person C has a guaranteed instant start if he joins 1v1 queue (will create game AvsC).
At the same time - separately - also has guaranteed instant start if he joins coop (will create B+C vs bots). There is a choice between the two and they don't conflict (but currently server only sends 1 offer).

**Comment by DeinFreund** [comment]
Can you tell me what's wrong with doing it like #1760 

If joining queue A makes queue B a non insta-start queue and vice-versa, then queue A and B are still insta start queues.

**Comment by Licho1** [comment]
Yes they are but you can join both at once.. I guess it's irrelevant .. I was wrong, it can work properly from user's perspective.
