### ISSUE TITLE
Manually addable maps that are sure to exixt

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1764]
Currently the wrapper/steam ensures that the maps for featured missions are in the maps folder. I'd like to be able to set this property manually for important maps, such as early campaign maps.

**Comment by GoogleFrog** [comment]
I just want to make arbitrary maps be included in the steam archive and/or downloaded by wrapper on launch.

**Comment by Licho1** [comment]
On github there is a place called steamroot. 
Whatever you put there is being distributed by steam.
You can add VIP items there.

**Comment by Licho1** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/tree/master/SteamRoot
