### ISSUE TITLE
List of channels which are bridged via Nightwatch / Discord

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#1765]
please provide a list of channels which are bridge to discord so a note can be added at the spring lobby server to the channels topic.

please do this within a week or nightwatch will be blocked.

also for the future: if a new channel is added, open an issue at https://github.com/spring/uberserver/issues or nightwatch will be blocked without any further warning.

**Comment by abma** [comment]
https://springrts.com/phpbb/viewtopic.php?f=73&t=36288

**Comment by GoogleFrog** [comment]
Seems to be here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyServer/ZkLobbyServer.cs#L74

"zkdev", "sy", "moddev", "weblobbydev", "ai", "zk", "zkmap", "springboard"

**Comment by sprunk** [comment]
Imparted.
