### ISSUE TITLE
Custom Unit Shaders:, 0(32) : warning C7555: 'varying' is deprecated, use 'in/out' instead

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#1775]
[f=-000001] Custom Unit Shaders:, 0(32) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(40) : warning C7555: 'varying' is deprecated, use 'in/out' instead
0(47) : warning C7533: global function shadow2DProj is deprecated after version 120
0(60) : warning C7533: global variable gl_TexCoord is deprecated after version 120
0(78) : warning C7533: global function textureCube is deprecated after version 120
0(111) : warning C7533: global variable gl_FragColor is deprecated after version 120

infolog.txt: https://github.com/ZeroK-RTS/CrashReports/issues/1484

**Comment by GoogleFrog** [comment]
Duplicate and wrong repo https://github.com/ZeroK-RTS/Zero-K/issues/2375
