### ISSUE TITLE
TOS for Zero-K lobby server

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#1776]
i couldn't find the Terms of Use for the Zero-K lobby. Where are these?

needed for https://github.com/spring/uberserver/issues/217

**Comment by GoogleFrog** [comment]
Looks like you want ToS for a lobby server, not a lobby.

**Comment by abma** [comment]
i want to know the ToS for the Zero-K Lobby server.

**Comment by sprunk** [comment]
This is for what ZK infra does with your content: https://zero-k.info/mediawiki/index.php?title=Zero-K:Privacy_policy

**Comment by abma** [comment]
thanks

**Comment by abma** [comment]
uhm... users can do everything? there are no rules on the lobby server?

so spam, ads, etcetc. is allowed?

**Comment by sprunk** [comment]
Spam and ads warrant moderator response.

**Comment by sprunk** [comment]
There is no explicit "you agree not to spam" as far as I can tell.

**Comment by db81** [comment]
@abma you seem to be treating legal like math. Sprung needs to be more explicit with you. In practice, people can quote things from public channels at will, but if you start disclosing things from private conversations in bad faith, you're likely to see moderator action.

Spamming is actually illegal in many jurisdictions (though enforcement is lacking and the laws are geared towards email).
