### ISSUE TITLE
Make the wrapper generate sdz for improved disk access time.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1781]
> note: the biggest factor may be the pool archive format (sdp) used by ZK, which is great for incremental updates but detrimental to load-time performance since it scatters tons of tiny files all over the disk.

> use the wrapper program to generate sdz's for users after downloading. 

See https://springrts.com/mantis/view.php?id=5662. It sounds reasonable that the packages and pool system would be bad for resource loading speed. Rapid should be able to make sdz packages out of the incremental updates. I think it is worth looking into.

**Comment by Licho1** [comment]
We should actually consider dropping rapid and switching to sdz completely (for steam). It seems that steam has issue with lots of small files too resulting in slow download.. alternatively we would unpack sdz to rapid locally by wrapper.

**Comment by GoogleFrog** [comment]
Sounds good. Here is what I think should be done:
 * Have the steam package only include the latest versions of ZK and chobby as sdz.
 * Have the non-steam wrapper use rapid to download updates for ZK and chobby.
 * Have the wrapper turn the latest chobby and ZK into sdz and use those for launching chobby/ZK.

This means that if chobby downloads a later version of ZK it will be turned into an sdz on the next launch. I am unsure as to whether we are going to remove ZK-downloading capability from steam chobby. Also, I am assuming that incremental rapid downloads can use sdz versions as a base for the download, otherwise nothing I said makes sense.

**Comment by GoogleFrog** [comment]
Most of the crash reports we've seeing now are probably hangs during game loading due to long access times. Since this is the case I'd like to get the wrapper using/generating sdz sooner rather than later so we can see whether these report are due to the many small files created by rapid.

I also expect that sdz would help with micro-freezes that can occur during the game when newly used resources are loaded. See https://github.com/ZeroK-RTS/Zero-K/issues/2427.

**Comment by db81** [comment]
Just don't remove the ability to dl from rapid from steam chobby altogether, we may eventually end up with a bit of a modding scene so it's good to keep functionality that makes that easier. Even if we only lose mainline ZK download capability, that makes it harder to watch old replays.

**Comment by GoogleFrog** [comment]
Could the wrapper be made to download the latest sdz from http://zk.repo.springrts.com/builds/ on startup, if it is not already present. I want to get ZK launching with sdz as soon as possible because it seems like most crashes are during loading time. If the crashes are not related to sdp/sdz then the engine devs need to know.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/1719
https://github.com/ZeroK-RTS/CrashReports/issues/1722
https://github.com/ZeroK-RTS/CrashReports/issues/1724
https://github.com/ZeroK-RTS/CrashReports/issues/1725
https://github.com/ZeroK-RTS/CrashReports/issues/1726

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/1729
https://github.com/ZeroK-RTS/CrashReports/issues/1738
https://github.com/ZeroK-RTS/CrashReports/issues/1741
https://github.com/ZeroK-RTS/CrashReports/issues/1743
https://github.com/ZeroK-RTS/CrashReports/issues/1744

**Comment by KingRaptor** [comment]
For future reference on wrapper implementing .sdz zipping of pool files after startup: https://github.com/spring/RapidTools/blob/master/Tools/MakeZip.cpp
(The Python rapid tool should also have an implementation)

Doing it within Chobby will probably require an engine change.

**Comment by abma** [comment]
FYI: when i see any performance issue on the springrts.com server because of zk-clients mass-downloading the .sdz i'll instantly remove http://zk.repo.springrts.com/builds/

#useyourbrain #ask #talk

**Comment by Licho1** [comment]
Yes wrapper should create sdz from rapid (trivial, like 5 lines of code) OR we should generate sdz on server for steam distribution and download from ZK server (or steam).
I will do it properly.

**Comment by Licho1** [comment]
done, wrapper creates and uses sdz related to #1849
