### ISSUE TITLE
Coop matchmaker uses CAI

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1782]
Ideally it would use circuit. I don't know the logistics of this though.

**Comment by Anarchid** [comment]
Circuit means one or several of the players have to run the AI, so something should decide who does it.

**Comment by GoogleFrog** [comment]
@Licho1 do you think this is fixable? All MM activity should be chobby so we can know that everyone has circuit installed.

**Comment by Licho1** [comment]
Yes but who hosts?

**Comment by GoogleFrog** [comment]
Can each player host one of them? That seems most resilient.

**Comment by Licho1** [comment]
You mean that wastes most cpu? 
Sure tell me what to set in scripts or modoptions..

**Comment by GoogleFrog** [comment]
I think it is resilient because:
- If one player leaves or drops one one of the AIs is lost.
- If one player has a broken circuit only one of the AIs is lost.
- Each AI takes an amount of CPU, although eventually they start merging together. But to give a player 2 AIs we would need to know that they have a stronger computer.

I don't know what to set in scripts. What does springie do when you put an AI in the game? Find that script.

**Comment by Anarchid** [comment]
If Circuit can take units of crashed/dropped ally instances, separately hosted Circuits would work exactly as well as CAI.

**Comment by GoogleFrog** [comment]
Superceded https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2498
