### ISSUE TITLE
Tell crashed users to update drivers

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1784]
If the infolog contains a line "Warning: This stack trace indicates a problem with your graphic card driver. Please try upgrading or downgrading it. Specifically recommended is the latest driver, and one that is as old as your graphic card. Make sure to use a driver removal utility, before installing other drivers." and chobby has crashed then the wrapper should tell the users to update their drivers.

**Comment by CrazyEddieTK** [comment]
It would also be good to include a link to a wiki page providing as much helpful information on how to go about updating drivers as we can produce, including tips for oddball cases gleaned from forum posts where people have struggled to find the right driver but then ultimately succeeded after some esoteric incantations.
