### ISSUE TITLE
New Very Easy CircuitAI config

### ISSUE THREAD

**Issue by CrazyEddieTK** [ZeroK-RTS/Zero-K-Infrastructure#1791]
Per discussion in [this forum thread](http://zero-k.info/Forum/Thread/24239) as well as [this GitHub issue](https://github.com/ZeroK-RTS/Zero-K/issues/2179), I've made a new CircuitAI config which I recommend we adopt as the Very Easy level.

Details are in [this post](http://zero-k.info/Forum/Thread/24239?postID=176190).

Rather than cloning the infrastructure repo and doing a PR, I'm just attaching the new config here for others to review and test.

[circuit-ce-veryeasy.json.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1202856/circuit-ce-veryeasy.json.txt)

**Comment by GoogleFrog** [comment]
Wrong repository. Part of this https://github.com/ZeroK-RTS/Chobby/pull/285/files is what a circuit config changing PR looks like. I'll manually add it.
