### ISSUE TITLE
Chobby is launching games with sdp

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1797]
See this report. https://github.com/ZeroK-RTS/CrashReports/issues/1759

The archive used is sdp.

**Comment by Licho1** [comment]
You said engine will prefer sdz if present.

**Comment by GoogleFrog** [comment]
Apparently that was just a preference of the engine devs. The engine seems to launch with whatever it happens to find first.

**Comment by Licho1** [comment]
ok lets rename/remove sdp then if sdz exists. Wrapper could do it easilly

**Comment by Licho1** [comment]
Or change VFS/engine?

**Comment by GoogleFrog** [comment]
Can you just remove the zk sdp once the sdz is generated? I don't want to remove sdp in general because it is useful to have access to rapid downloads for other things.

**Comment by Licho1** [comment]
oh!! Good point.. we can just remove rapid and keep generating sdz after each download.. as a principle rapid could simply do that always. It wont be able to identify if the sdz is correct though if it gets corrupted. It will also need some proper naming scheme, but perhaps it could name it based on sdp hash name?

**Comment by Licho1** [comment]
It could also delete older copies of the same "tag"

**Comment by Anarchid** [comment]
For non-steam distro, wouldn't deleting the sdp after creation of sdz prevent incremental downloads?

Alternatively, the sdp-indexed ZK can live in a separate content/write directory and then generate sdz from incremental downloads.

**Comment by Licho1** [comment]
This has nothing to do with incremental downloads. Incrementality will be kept. Incremental only uses "pool" folder with files named based on their hash.
This will be kept.
Final step of rapid will just be:
* ~~create SDP file~~
* create SDZ file
* based on known rapid tag, check previous file with the same rapid tag (zk:test, zk:stable) if it exists, delete it (or replace with small SDP )

**Comment by Licho1** [comment]
Basically it will keep "head" of a given tag packed in SDZ, as well as "unpacked" in pool format. It will enver delete from pool

**Comment by sprunk** [comment]
I think it might be best to make engine itself prefer SDZ? Should be just one comparator somewhere that gives SDZ priority and other games will benefit as well.

**Comment by Licho1** [comment]
That's only part of the issue. 
I think we cannot afford to distribute pool files with steam .. at all .. so for steam we might need the reverse function sdz -> pool if we want to support custom mod downloads..

**Comment by GoogleFrog** [comment]
I thought we would distribute sdz with steam and let the rapid downloader download custom mod downloads if they occur.

**Comment by Licho1** [comment]
That is possible however, without first unzipping sdz into pool, download would take hour or so and be done entirely from our server...

**Comment by db81** [comment]
Why can't we afford to distribute pool through steam? Inflated game download size? Too much disk IO to make a steam build for every version?

**Comment by GoogleFrog** [comment]
Pool involves creating many small files. The steam downloader is slow at downloading and tracking many small files. Cache times are increased when there are many small files.

**Comment by Licho1** [comment]
switched to poor sdz for steam, no pool for it.
