### ISSUE TITLE
Singleplayer Custom Commanders

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1799]
If ZKLS would send players the appropriate commander types modoption when they log in or when changes are made then their site-configured commanders could be used in skirmish games.

**Comment by KingRaptor** [comment]
I think it'd be preferable to move comm configs entirely offline, with a configurator widget in Chobby writing a file that ZK reads at start.

**Comment by Anarchid** [comment]
This is also more or less required for campaign.

**Comment by Licho1** [comment]
If you make it entirely offline, then people can entirely hack it. Is it desirable? We can mitigate it in other way, like sending level or xp back from server in MP games to verify that player hasnt cheated too much or something.

**Comment by Licho1** [comment]
Perhaps some sort of hybrid solution would be viable. 
For example:
1) make commander editor entirely in lobby as chobby widget
2) add protocol change to submit and retrieve current commander config - for example in json form
3) allow "whatever" for SP games and only submit changes to server 

This hybrid solution would also let us monitor what modules people use etc and display it on user profile, without having the clunky web edited commander profiles.

**Comment by Anarchid** [comment]
> If you make it entirely offline, then people can entirely hack it.

How so? Commanders are already dynamic, so the game verifies validity of any build.  Contrarily, the illegal battlecom-with-rocket i used to have, and UI-crashing drone module used as chassis, are enabled by site and just required some firebugging.

**Comment by Licho1** [comment]
Oh yeah, scratch what I said, I was living in the past.
We could save profiles on server, but its easier to just write to local file and let steam persist it.
Ability to store current dyncom upgrade path could be handy and easy to code.

**Comment by Licho1** [comment]
Closing, if you want server comms reopen, can be done.
