### ISSUE TITLE
noElo modoption does nothing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1801]
See this game http://zero-k.info/Battles/Detail/466192?ShowWinners=True

**Comment by DeinFreund** [comment]
Could somebody check the database whether noelo was actually registered? I'd assume something failed in the match setup already leading to the value not being set.

**Comment by KingRaptor** [comment]
Database doesn't store noElo state.

Server tries to read noElo state [here](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/1d0753e899ed38ed6711e65a8f31e270e6991939/ZkLobbyServer/SpringieInterface/BattleResultHandler.cs#L100) before deciding whether to apply Elo effects. I am unable to find any indication that the value is actually written in the place the code looks.

**Comment by Sgathec** [comment]
Many, many months or even a year ago, noelo sometimes produced the intended result. Is it now guaranteed not to function? I haven't had it enabled in a long time.

**Comment by Anarchid** [comment]
Is this obsoleted by the post-hoc administration of what counts?

**Comment by sprunk** [comment]
No. Pinging an admin after every no-elo battle is work for both sides.

**Comment by DeinFreund** [comment]
Tags are set automatically, assuming noelo is properly sent to post battle processing.

**Comment by sprunk** [comment]
I did a check and the infra correctly processes `noElo`.

**Comment by Sgathec** [comment]
http://zero-k.info/Battles/Detail/600713
noelo=1, but ratings were changed after the battle.

**Comment by sprunk** [comment]
ZK (as in the game content itself) issue. https://github.com/ZeroK-RTS/Zero-K/issues/3223

**Comment by GoogleFrog** [comment]
This is stupid. Read noElo from the modoptions directly upon game start. Springie sets the modoptions and it is written in the replay.

**Comment by GoogleFrog** [comment]
Exactly this: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/2519/files

**Comment by sprunk** [comment]
d4a1a3894505b09d6630eb2fee68893d6c74021e
