### ISSUE TITLE
The !kick command seems to allow spaces in names

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1805]
For instance, a command such as "!kick Alcur because I'm testing this" appears to try and kick someone called "Alcur because I'm testing this". This can lead to confusion. Please proscribe whitespace or make it possible to include a reason. If you implement the reason functionality, please inform players about it to prevent accidental kicking.

**Comment by Licho1** [comment]
it is using search, multi word search. So you can do !kick mouse fat
to kick [FS!]]FatMouse
