### ISSUE TITLE
Send platform stats to platform stats service

### ISSUE THREAD

**Issue by dansan** [ZeroK-RTS/Zero-K-Infrastructure#1807]
A HTTP-API driven service can help Zero-K gather hardware/OS data about the player base, and later analyze it: 

- https://github.com/dansan/springrts-platform-stats
- https://springrts.com/phpbb/viewtopic.php?f=71&t=36294

The data of the Lua tables 'Platform' and 'Engine' are interesting. The should be collected during game runtime (and not by a  Lua-subprocess of the lobby), to ensure that the library versions are exactly what is used by the engine. The OS-name and CPU-name may have to be read by the lobby (nobody has pointed be to a Lua table for this yet). Resolution, refresh rate and [not] windowed is read by the BA/Evo gadget from the infolog, but I assume this should be possible to read by Lua from ingame.

How it should then be sent to the stats service is not yet clear:
The stats service expects a login (to prevent people with bad intentions to flood the database with wrong data). The login could either be a dedicated one for the zero-k infra (like currently used by the replays site) or a players lobby credentials (not yet implemented).
The first one could be used if the data is first sent from a gadget on the players PC to the zero-k infra, and then forwarded from there to the stats service. (I don't know if there is communication between a running zero-k game and the zero-k infra with which this could be accomplished.) The later could be used to send the data directly from a Lua gadet via HTTP.

On the githubs project page are examples to write to the API with curl (command line), Python and JavaScript. I don't know C# or Lua, but I'll assist however I can.
If you wish to experiment with the API, please send me a forum PM, and I'll send you a login.

**Comment by Licho1** [comment]
Thank you, but we are already gathering extensive data, which include hardware/OS information, using game analytics.
We are also sending in game events to help understand where people get stuck and what are they using.

So it is already easy for us to both gather and visualise stuff.

http://i.imgur.com/eMO1XCX.png

**Comment by Licho1** [comment]
(We also gather opengl version, crashes and lobby GUI events using this tool)

**Comment by dansan** [comment]
Oh, that's nice.
Do the engine devs know about this?

There was some discussion about OpenGL versions, in which I had the impression that they lack that data (https://springrts.com/phpbb/viewtopic.php?f=73&t=36288). That's why I decided to code that site...

Can engine and other game devs have access to the platform data that is collected here?

**Comment by Licho1** [comment]
Sure, we can give access, i just need emails to add more people. 

We do have opengl data too:
http://i.imgur.com/RRVVvOG.png
