### ISSUE TITLE
ZK download error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1808]
https://github.com/ZeroK-RTS/Zero-K/issues/2496

**Comment by Licho1** [comment]
Well check how sdz is done,its some temp hack made by KR?

**Comment by KingRaptor** [comment]
It just has wrapper download from http://zk.repo.springrts.com/builds/

**Comment by Licho1** [comment]
sdz downlaod now offline
