### ISSUE TITLE
Find this replay

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1811]
For Zero-K v1.5.8.3, Torn Islands Remake, 103.0.1-1336-g61d1146.

No replays exist for games with "[f=0011447] Error: [safe_element] index 0 out of bounds! (size 0)" and they are needed for reports.

**Comment by sprunk** [comment]
I believe this was solved. https://zero-k.info/Forum/Thread/24328
