### ISSUE TITLE
"Play this map" button does not work with chobby/wrapper

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1812]
At least two newbs this week claimed that button does not work, tried to download maps manually, got lost and had to ask for help in chat

https://zero-k.info/Lobby/ChatHistory?Place=0&Channel=zk&User=&TimeFrom=09/12/2017&TimeTo=09/13/2017&Text=&grorder=&grdesc=False&grpage=6

https://zero-k.info/Lobby/ChatHistory?Place=0&Channel=zk&User=&TimeFrom=09/15/2017&TimeTo=09/16/2017&Text=&grorder=Tim&grdesc=False&grpage=1

It looks like a thing Wrapper or Chobby should handle.

There's also the design question of whether we want maps to be easily browsable through site at all. On one hand the multitude of maps is a selling point, but on the other anything that isn't featured is typically worthless crap.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/issues/344 link to Chobby ticket if this is not Wrapper's job.

**Comment by Licho1** [comment]
Wrapper does not interfere with this, the command is sent to lobby using protocol.
Lobby is responsible for executing the command. Wrapper does not even see it.

**Comment by sprunk** [comment]
ok
