### ISSUE TITLE
Linux mint spring does not work out of the box

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1816]
Sortale needed:
64bit + still need the 'sudo apt-get install mono-complete libsdl2-2.0-0 libopenal1' line though

Update wiki?

**Comment by Sortale** [comment]
I am confused

which zk version are we talking about? steam? deb file? or just the downloaded chobby.

and which wiki?

and by Jove what can I do to help?

**Comment by Licho1** [comment]
fixed now i think
