### ISSUE TITLE
Add wrapper function CheckFileIntegrity 

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1817]
Bad side data.
https://github.com/ZeroK-RTS/CrashReports/issues/2143
https://github.com/ZeroK-RTS/CrashReports/issues/2144
https://github.com/ZeroK-RTS/CrashReports/issues/2145
https://github.com/ZeroK-RTS/CrashReports/issues/2146
https://github.com/ZeroK-RTS/CrashReports/issues/2147

**Comment by Licho1** [comment]
This appears to be a bug in pr-downloader.
Pr-downloader was downloading server_1.sd7 and then later:

[f=-000001] Error: Error opening "C:\Games\Zero-K\maps\sever_1.sd7": Unexpected end of file (truncated?)
[f=-000001] Warning: [AS::ScanArchive] unable to open archive "C:\Games\Zero-K\maps\sever_1.sd7"

Wrapper rapid and map download does check integrity. If you want you can download maps using wrapper too.

**Comment by GoogleFrog** [comment]
Maps need an integrity check too. I fallback to using the wrapper and it doesn't help. If I am to use the wrapper download exclusively I need extra functions. See https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1826

**Comment by GoogleFrog** [comment]
CheckFileIntegrity will be called on files that are about to be used (maps and games). If they function returns false then chobby will tell the wrapper to download the file (eventually, using its lua implemented download queue). If the file does not exist then CheckFileIntegrity should return false.

**Comment by Licho1** [comment]
Instead we are switching to wrapper downloader (it has progress and abort APIs now). Wrapper makes sure files that are put into games are verified.
