### ISSUE TITLE
Harassment by changing the room name

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1819]
When a room contains spectators but no players, I'm pretty sure anyone could easily change the name of it to something the people inside could find offensive. That seems to have happened already. Perhaps the name change poll should take spectators into account as well by requiring more votes to pass.

**Comment by sprunk** [comment]
Perhaps there should be no name change poll at all and public rooms should have standarized names.

**Comment by Sgathec** [comment]
Not sure. I think users might find being able to personalize rooms nice, but standard naming could help new players find the right room.

**Comment by sprunk** [comment]
If they want personalized names they can host a custom room where they are the boss.

**Comment by Sgathec** [comment]
Oh, I thought you wanted to disable custom names completely.

If only the boss can change the room name then the name could be misleading later if the room type is changed e.g. from Teams to Cooperative and the founder is absent. However, people don't seem to change the name despite being able to, but I find it difficult to say how often that happens. I have personally changed the room name sometimes to reflect the room state (via a poll).

**Comment by DeinFreund** [comment]
I like the idea to have a democracy switch: only allow vote commands on democratic rooms. By default rooms are autocratic.

If the people are offended by the current title/map/mod/... they can just vote against.

**Comment by sprunk** [comment]
After a short discussion it was decided that harrassment by changing room title is not any different from any other harrassment.
