### ISSUE TITLE
While downloading a new Zero-K version the text doesn't fit

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1820]
The text goes partially off the update window area. I suppose the window is not, in fact, part of Chobby. The Chobby I launched was the non-Steam one.

**Comment by Sortale** [comment]
![20171002_233327](https://user-images.githubusercontent.com/14219158/31077557-afa06b52-a7ca-11e7-9a86-be148789a81a.jpg)


like this?

**Comment by Sgathec** [comment]
Yes, that is what I mean.

**Comment by Licho1** [comment]
fixed
