### ISSUE TITLE
Linux install instruction need update

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#1821]
linux installation for zero-k need dependency of:

`libcurl3`

to run on latest ubuntu and linux mint

it is unknown if this is enough to run on other distribution

another list of dependency for spring is:

https://pastebin.com/EtftQV24

as extracted from deb file here: 

https://packages.debian.org/sid/amd64/spring/download

curiously they do not list 

`libcurl3`

either or any curl library for that matter

**Comment by KingRaptor** [comment]
Added `libcurl3` to http://zero-k.info/Wiki/Download

Are any other dependencies missing from the apt-get line?

**Comment by Sortale** [comment]
that should be enough to run on latest ubuntu/linux mint, more than that I am uncertain

**Comment by KingRaptor** [comment]
Thanks!

I'll close this then; reopen if further changes are needed.

**Comment by Sortale** [comment]
for debian 32 bit need further instruction to work

 respond from engine Dev : "<[LCC]jK> 1. he can compile spring for his distro (then he doesn't got that prob) 2. he can use 64bit 3. he can switch to a distro with libunwind.so.7
<[LCC]jK> 4. he can install libunwind on his system, so he got .so.7"

also noted that  solution 4 required you to add the repo for wheezy version of debian then install libunwind7 [not any later version]
