### ISSUE TITLE
Avoid serving unsupported maps

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1822]
When an unsupported map is selected, there should either be some confirmation required "Do you really want to play on a map that might break the game?" or they should require an explicit command(!map "unsupported map names work in quotes only"). Otherwise people still end up on such maps regularly and encounter bugs/glitches.

In this case people were playing on Zed 2.2 which causes graphical glitches and doesn't render cloaked units.

**Comment by The-Yak** [comment]
Seems related to http://zero-k.info/Forum/Thread/24354

**Comment by The-Yak** [comment]
This is still an issue and happening with Otago, as I made the mistake of initial release without a version. I think having an unselectable class of maps would address this.
