### ISSUE TITLE
Lobby needs button to cancel and/or change order of map downloads

### ISSUE THREAD

**Issue by Throwaway3834** [ZeroK-RTS/Zero-K-Infrastructure#1823]
Initial download list is very long. Button to allow current map to come first or to cancel downloads would allow playing to commence sooner. This would improve new and return player experience.

**Comment by The-Yak** [comment]
This is more a problem on larger hosts where !map cycling is often used to decide what to play on. Suddenly the game is starting and you have no hope of getting the map in time because of a large queue to download before you can get current map.

**Comment by GoogleFrog** [comment]
Will be covered here https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/1826.
