### ISSUE TITLE
Lua-based smoothing (tremor, quake etc) can create vertical spires

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#1825]
This is from a Chicken game. One player built a DDM, while the other kept shelling its surroundings with a Tremor. Eventually the originally pyramidal spire became this. 
![image](https://user-images.githubusercontent.com/3822768/31351527-1e8cb458-ad34-11e7-9b25-49c732468c30.png)

**Comment by DeinFreund** [comment]
Yea, it's Nightwatch who is to blame.

Move to Zero-K?

**Comment by Anarchid** [comment]
Oops.
