### ISSUE TITLE
DownloadFileProgress and DownloadFileCancel for wrapper loopback

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1826]
The UI would like to know the progress of current downloads. It would also like to be able to cancel downloads.

**Comment by Licho1** [comment]
added

**Comment by GoogleFrog** [comment]
DownloadFileProgress should send the file size of the file being downloaded.

**Comment by Licho1** [comment]
Progress and time estimates are not based just on download. For example for pool there are multiple steps. Or file can have dependencies.
Or for engine it also expects time to unzip the file. But it can send other data like dl speed.

**Comment by Licho1** [comment]
done
