### ISSUE TITLE
The penalty for muting a user doesn't function correctly

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1827]
On the user page http://zero-k.info/Users/Detail/212163, it currently reads "Muted", but I observed him talk on #zk at around 8:15 o'clock on the 15th of October in 2017 (UTC).

The penalty date and length as shown on his user page at the moment:
"Issued on: 10/15/2017 4:18:29 AM (4 hours ago)
Expires on: 10/16/2017 4:18:29 AM (0d 19h remaining)"

Here's the talk:
[10:24] Zero-K v1.5.9.3 released http://zero-k.info/Forum/Thread/24359
[11:15] Chesti: yup
[11:22] Firepluk: wup
[11:25] Chesti: yepp 
[11:41] DeinVeganer: pleb
The time stamps are the result of the Finnish time zone.

**Comment by DeinFreund** [comment]
I couldn't easily reproduce this on the test server. Possibly it's related to the cache. Any hints?

**Comment by Licho1** [comment]
dunno hard to debug now
