### ISSUE TITLE
old engine/maps taking up disk space

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#1829]
is this avoidable? I just deleted all the old engine for a total of 2GB of free space.

I know we need them for replay but maybe having something deleting really old engine could be nice?

**Comment by sprunk** [comment]
This extends to maps too.

I think this is minor enough that it can wait until Steam distributes stuff for us though; in the meantime it's not unreasonable to have people delete manually.

**Comment by Licho1** [comment]
We dont know what is really old.. it can be old but still used.. we would need to track actual usage which seems extra complexity and risk.
Steam can be used to clean/redownload at any time too .. so yeah lets close it for now..
