### ISSUE TITLE
too easy registration process? spam account potential?

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#1830]
I am uncertain about this but registration process seems too easy to automate. [I could be wrong]

Doesn't this mean it is easy to have spam/troll account flooding the server?

also I don't see the benefit of registration form having autofill function

**Comment by KingRaptor** [comment]
Non-Steam registration should require an email address, and bans should be able to work on email.

**Comment by db81** [comment]
Only if you go on an unending hunt against temp mailbox services. It takes about two seconds to go to https://10minutemail.com

**Comment by Sortale** [comment]
or just limited to major private mail provider [i.e. gmail hotmail yahoo]
like several other web games do

**Comment by Anarchid** [comment]
> Only if you go on an unending hunt against temp mailbox services

A low fence is still a fence, even if low.

**Comment by sprunk** [comment]
Any mail would already be a huge improvement. Currently you can make [20000 accounts in bulk in a few seconds](https://zero-k.info/Users/Detail/384166).

**Comment by GoogleFrog** [comment]
What about a limit on the frequency of account creation per IP? If an IP address has created an account don't let them create another until a second has elapsed.

**Comment by Sortale** [comment]
or max 10-20 account per IP, I remember a web game with 4 account limit [Ogame I think]
I mean realistically can there be more than 25 people playing zk in 1 IP?
this only limit to the registration of course, playing should be a different matter

**Comment by Licho1** [comment]
It is already limited. 
Max rate is now 60 registrations/ hour per IP. 
Meaning if you try to register 61x in one minute you get banned..

It is of course still spammable but not exactly at flood level. 

Email has been considered and is still an option but thats for another ticket..
