### ISSUE TITLE
SetModOptions sometimes sends diffs, sometimes complete states

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1833]
Doing !resetoptions causes SetModOptions from the server with an empty table. Other modoptions changes seem to send diffs from the server. This inconsistency looks unreliable to me, what should the lobby do?

[infolog.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1405009/infolog.txt)

**Comment by sprunk** [comment]
There are no diffs, the server always sends the full table. This is supported by your infolog, lines 31-35:

```
[f=-000001] [ClientMessage] SetModOptions {"Options":{"overdrivesharingscheme":"0","noelo":"0","commends":"0"}}
[f=-000001] [ServerMessage] SetModOptions {"Options":{"overdrivesharingscheme":"0","noelo":"0","commends":"0"}}
[f=-000001] [ServerMessage] User {"AccountID":93464,"Avatar":"corsktl","BanMute":false,"BanSpecChat":false,"BattleID":542,"Clan":"Mean","Country":"NL","Faction":"Federation","IsAdmin":false,"IsBot":false,"LobbyVersion":"Chobby","Name":"swappan","Icon":"7_4","IsAway":false,"IsInBattleRoom":true,"IsInGame":false,"Level":104}
[f=-000001] [ClientMessage] SetModOptions {"Options":{"zombies":"1","noelo":"0","xmas":"1","commends":"0","overdrivesharingscheme":"0","zombies_partial_reclaim":"1"}}
[f=-000001] [ServerMessage] SetModOptions {"Options":{"zombies":"1","noelo":"0","xmas":"1","commends":"0","overdrivesharingscheme":"0","zombies_partial_reclaim":"1"}}
```

Note that the client sends `"noelo" : "0"` twice, and both times the server includes it in the returned table. If it was a diff then it would be omitted the second time because it is already that value.

**Comment by Licho1** [comment]
Confirmed, no diffs, server is just dumb relay (that caches last values for new users, but resets entire table always). 
Logic on client should be - reset table and apply what is received from server.
