### ISSUE TITLE
PRs dont get built

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1836]
PR #1835 hung for a day and there was no automated teamcity build.

**Comment by Licho1** [comment]
seems to be a temporary glitch, it is now building fine.

**Comment by sprunk** [comment]
#1853, #1858, #1860, and #1861 didnt get built either.
#1850 and #1859 are still waiting but also havent been built.

**Comment by sprunk** [comment]
Github doesn't show them but teamcity interface does.

**Comment by Licho1** [comment]
Still counts as a problem keeping open until we know its fixed.

**Comment by Licho1** [comment]
fixed temporarily
