### ISSUE TITLE
Plan a time for steam coop 

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1837]
I think I have a free Sunday. Good times for me are between Saturday 2230 and Sunday 1300.

https://www.timeanddate.com/worldclock/converter.html?iso=20171028T223000&p1=152&p2=tz_gmt

**Comment by GoogleFrog** [comment]
I may only be available from Sunday 700, but as I recall that is Europe sleeping time.

**Comment by KingRaptor** [comment]
If you need me, I should in principle be available any time between 0200 and 1500 (UTC) on Saturdays and Sundays, and 1200-1500 UTC for Friday nights.

**Comment by GoogleFrog** [comment]
There has been no response, so I think I am now busy on Sunday.

**Comment by Licho1** [comment]
On this sunday i have time either since 20:00 of your time, or since 08:00 of your time (for about 2h before i fall asleep)

**Comment by GoogleFrog** [comment]
@Licho1 if you are free can you write down what chobby is supposed to do regarding steam coop and what it expects?

**Comment by Licho1** [comment]
We should design it, original plan is not ideal and i see some shortcomings. 
This is what P2P can do:
 * establish comm channel to a steam friend in any network environment
 * exchange arbitrarily information with friends
 * prepare network for hosting spring (traverse/open ports)

My idea was to basically use the skirmish screen and add some "invite coop partner" button there.
This button open steam overlay with friend list and lets you invite a friend
After friend accepts, when you start a game, you host it and friend gets connectspring to connect to you.
You both commshare.
Locally spring is started as normal, with only slightly modified script to specify hosting port.

This setup could also be used for campaign coop.

**Comment by Licho1** [comment]
we did it somehow
