### ISSUE TITLE
Move planetwars configuration to repository

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1841]
This means the game balance/design is version controlled and accessible to everyone. Making it easier to keep track of changes and to get an overview.

**Comment by Licho1** [comment]
At one point we had it in xml, however it was even more annoying to edit.
Having it in DB has major benefits too - like we can tweak/fix it without rebooting entire infrastructure.

We could perhaps instead generate a proper list of structures etc from the data in DB?

**Comment by GoogleFrog** [comment]
I don't want PW mechanics to change during a round and I don't mind where the mechanics are stored. I like the DB for its ability to change mechanics during PW testing (on test server) and I like git for its version control.

Actually, on that note, I don't know how to change the PW mechanics on the test server or how to copy them over to stable. Perhaps I prefer git in that case.

**Comment by DeinFreund** [comment]
If it remains on database I'd suggest adding a proper interface to access all settings via site.

**Comment by Licho1** [comment]
Well we had exactly this, we had an interface to import/export planetwars structure config to/from file.
It should be somewhere in git history.

**Comment by Licho1** [comment]
Having it in config makes it extra hard to integrate, many things use existing SQL queries to do stuff. 
Admin interface seems like extra thing to maintain that will take more time to code than to use.
Changes to PW are quite rare and can hapepn in table. TAble can be manually exported to CSV for easier browsing and that csv can even be stored in git for archiving.
