### ISSUE TITLE
Add a PW treaty for sending defenders to defend planets

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1842]
Faction A gives faction B the treaty effect "Defensive Aid". This means that players in faction A can join the battles to defend planets owned by faction B. This treaty type should be able to be limited to defending a single planet (with IsPlanetBased) or defending all planets. I thought that EffectBalanceSameSide was intended to have this effect but it turned out not to do anything.

**Comment by sprunk** [comment]
Is this effectively "Fix `EffectBalanceSameSide`"?

**Comment by Licho1** [comment]
According to code this should be possible. Are you sure it does not work? Please note that the treaty is directional.
Code says:
{{{
        private List<Faction> GetDefendingFactions(AttackOption target)
        {
            if (target.OwnerFactionID != null)
            {
                var ret = new List<Faction>();
                ret.Add(factions.Find(x => x.FactionID == target.OwnerFactionID));

                // add allies as defenders
                using (var db = new ZkDataContext())
                {
                    var planet = db.Planets.Find(target.PlanetID);
                    foreach (var of in db.Factions.Where(x=>!x.IsDeleted && x.FactionID != target.OwnerFactionID && x.FactionID != AttackingFaction.FactionID))
                    {
                        if (of.GaveTreatyRight(planet, x=>x.EffectBalanceSameSide == true)) ret.Add(of);
                    }
                }
                return ret;
            }

            return factions.Where(x => x != AttackingFaction).ToList();
        }
}}}
