### ISSUE TITLE
Diplomacy questions/changes

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1856]
First some questions similar to #1844.
- [x] ~~Treaty effects all have the form 'A to B'. Does faction B is this transaction ever lose anything? That is, do they ever have any effect such as the payment of a cost or restriction on their actions? Similarly, does faction A ever gain anything? The answer to both these questions should be no for the sake of consistency.~~
No and no. A always loses, B never loses.

- [x] ~~Can treaties be cancelled? The tooltip for treaty time says "Empty = can be cancelled at any time".~~
Yes, treaties with no turn timer can be cancelled at any time.

- [x] ~~What happens if a faction cannot pay a per-turn treaty cost?~~
Debt occurs

It feels wrong that two factions could make a treaty that prevents them from attacking each other for 10000 turns. The right treaties could effectively turn planetwars into a 1v1 followed by a long wait while the binding treaty wears off. On the other hand there should be something preventing treaties from being broken. Treaties could have collateral but that would be an extra complicated mechanic and both sides could put so much up as collateral that they effectively cannot break a treaty.

At the moment I am swaying towards allowing any treaty to be broken at any time by either party with no mechanical repercussions. Of course, there could be diplomatic repercussions. Under this scheme the only effect of "Treaty time" is it sets a number of turns after which the treaty automatically ends with neither side losing face. In this system the faction diplomats will have to learn not to trade immediate effects for ongoing effects.

Allowing treaties to be broken at any time answers the question of what happens if a faction cannot pay a per-turn cost. The treaty is simply automatically cancelled.

**Comment by GoogleFrog** [comment]
Here is what I would change about treaties:
- Make treaties cancellable at any time.
- Add two number fields called 'Us Collateral' and 'Them Collateral'. Each side pays the amount of metal stated in the collateral when the treaty is made (they have to have enough metal). This metal is temporally lost to both sides. If the treaty has a time limit and it elapses then both sides are refunded the collateral that they originally put in. If a faction breaks a treaty early then the other faction is paid the sum of both collaterals.
- If a faction has a per-turn cost that it cannot make it automatically breaks its treaty.
- Remove debt.

This system has the following motivations:
- Remove debt. This is a secret mechanic that does not make much sense thematically and, as far as I know, there is no way to interact with or view debt. It could also have bugs or abuses since it is so untested.
- Remove unbreakable or practically unbreakable treaties. It feels wrong to me that a game of backstabbing diplomacy would allow for the creation of actually unbreakable treaties. Such treaties might make sense to make at the time but could unbalance the remainder of the game.
- Retain the ability to have a cost for breaking treaties.

**Comment by Licho1** [comment]
diplomacy guarantees implemented
