### ISSUE TITLE
Rename wrapper window name to something less dodgy

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1862]
'chobby.exe' is a poor name for the program which, as far as players should be concerned, is ZK. It should be renamed. "Zero-K.exe" is a good candidate.

**Comment by Oflameo** [comment]
Why does Chobby have an option to launch Evolution RTS in the developer menu?

**Comment by GoogleFrog** [comment]
Because forb half-added an evoRTS game config to chobby. The developer submenu should be hidden without some dev mode flag. The only setting that may be useful to move to lobby is full speed draw updates.

**Comment by Licho1** [comment]
renamed to Zero-K.exe

**Comment by sprunk** [comment]
dc8745e4cdc71a9370f5f5b9e477e7584dcb239b

**Comment by ashdnazg** [comment]
can you also rename the launcher's window name from "ChobbyLaform" to "Zero-K launcher"?
