### ISSUE TITLE
New wrapper download functions seem to do nothing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1863]
I have never received DownloadFileProgress. AbortDownload seems to do nothing too. Fix them or tell me exactly how to get a test wrapper.

**Comment by Licho1** [comment]
Have you started downloading using wrapper? How do i test it?

**Comment by DeinFreund** [comment]
Seems to work since Licho's fix aefed5e6b9f112ae5314f4be0fc008451aa45c7c 

I can cancel downloads and see download progress, is there something else?

**Comment by Licho1** [comment]
It fills log with 70mb of messages under certain conditions atm. But it does something now.
