### ISSUE TITLE
WHR ladder activity

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1866]
Current WHR activity criterion doesn't play well with our inactive player base. There have been different proposals to boost perceived player activity:

 * Manually increase uncertainty to fill ladders
 * Automatically increase maximum uncertainty until ladders are filled, reset it automatically once the game becomes more active
 * Put everyone on the ladders who played in the last X days, even if he only played 1 game.

Is this needed? Which one should I implement? I'd support the second.

**Comment by Anarchid** [comment]
Vote automayor for mayor!
