### ISSUE TITLE
Steam ZK might be broken

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1871]
See http://zero-k.info/Forum/Post/178032#178032

>it does not work out of the box.
>
>here is what i did:
rename Chobby.exe to Zero-K.exe
rename Chobby.sh to Zero-K.sh
>
>and then it works when started by steam

**Comment by Licho1** [comment]
It is waiting for new ZK stable to rebuild steam.

**Comment by Licho1** [comment]
it was broken, it works again now
