### ISSUE TITLE
TitanDuel 2 download fails with recent wrapper and chobby

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1875]
Delete TitanDuel 2 from your maps folder. Launch chobby and connect to the server. This causes titan duel to be redownloaded, since it is a MM map. The download will reach about 22.3MB and then fail.

If you retry this progress then the TitanDuel 2 download will start from 22.3MB and complete successfully (I assume it is using some saved temp file).

Delete Vittra v2.1, TitanDuel 2 and Red Comet v1.3. TitanDuel 2 works in this situation.

**Comment by GoogleFrog** [comment]
Reproduction of the issue is 100% reliable with lone TitanDuel 2. Clicking retry works. Here is an infolog where I click retry.
[infolog.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1463792/infolog.txt)

**Comment by Licho1** [comment]
unable to reproduce so far

**Comment by Licho1** [comment]
will need wrapper log as well start with > out.txt param to get data from wrapper.

**Comment by GoogleFrog** [comment]
Works for me now.
