### ISSUE TITLE
Downloads sit at 0/0 MB for a while

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1876]
With the recent wrapper downloads now sit at 0/0 MB for 10 to 20 seconds before appearing to begin..

**Comment by Licho1** [comment]
Caused by springfiles being down. ZK server tries to ask for springfiles mirrors and this delays the start of actual download.

**Comment by sprunk** [comment]
Sounds bad, what if SF dies at release?

**Comment by GoogleFrog** [comment]
I think a delay of 10 seconds is not great, but it is acceptable if it is the only problem.

**Comment by sprunk** [comment]
>wow it took 30 seconds for FolsomDamDeluxeV4 to find mirror

**Comment by Licho1** [comment]
This issue has been caused by springfiles being down and piece downloader retrying the same mirror optimistically.
I made it pessimistic regarding the chances of mirror going backup during single file download.
