### ISSUE TITLE
Chobby game download is unreliable

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1882]
Game downloads with the in-menu downloads tab sometimes almost complete and then fail. I had this occur, retrying a few times fixed it. There are two ways a game download might occur:
 * ZKLS fails to use zk:stable or some hosts have failed to update.
 * Downloading an old version of ZK to view a replay.

**Comment by Licho1** [comment]
reopen if it sitll happens
