### ISSUE TITLE
Server downtime scheduling/notification

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1883]
If server has to be shut down for any reason users should be notified ahead of time and (if possible/applicable) throughout the downtime. 

This message should be clearly visible in lobby and on website, and include an anticipated start time(stamp) and a custom string describing what is happening. 

An admin interface should be supplied to set the current downtime message and timestamp.

This issue reduces in importance if server restarts have fewer consequences. Currently it causes ongoing battles to not be saved to website, although the play itself is not interrupted.

@DeinFreund's proposed featureset:
- Announcements are broadcasted to all connected users. This could be general and battle chat or even a custom Chobby announcement window.
- No new games can be started during the warning period or they require additional confirmation to be started.
- If any updates to server infra are queued, automatically deploy after the warning period has ended

**Comment by Licho1** [comment]
There is a message that is autobroadcasted via ZKLS. 
Chobby does not implement the popup properly.
The same message can also be sent by admins using lobby protocol.
-> make this issue in chobby
