### ISSUE TITLE
Unitsync issues

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1888]
`System.InvalidOperationException: Sequence contains no elements at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source) at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.b__3[TResult](IEnumerable`1 sequence) at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot) at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression) at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression) at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate) at ZeroKWeb.SpringieInterface.BattleResultHandler.SaveSpringBattle(SpringBattleContext result, ZkDataContext db) at ZeroKWeb.SpringieInterface.BattleResultHandler.SubmitSpringBattleResult(SpringBattleContext result, ZkLobbyServer server) Data: {"ActualPlayers":[{"AllyNumber":0,"IsIngameReady":true,"IsSpectator":false,"IsVictoryTeam":false,"LoseTime":8837,"IsIngame":false,"Name":"rincewind"}],"Duration":8837,"EngineBattleID":"6262085A663D008698764331FCDA2BF2","EngineVersion":"104.0.1-92-g4409317","GameEndedOk":true,"IngameStartTime":"2017-11-12T15:03:08.9085927Z","IpAddress":"37.59.49.101","IsCheating":false,"IsCrash":false,"IsHosting":true,"LobbyStartContext":{"FounderName":"rincewind","Map":"Onyx Cauldron 1.8","Mod":"Zero-K v1.5.11.6","Players":[{"LobbyID":396194,"AllyID":0,"Name":"rincewind","IsSpectator":false,"ScriptPassword":"a732b559d31ba36608623039788c11a1","Clan":null,"Faction":null,"PartyID":null}],"Bots":[{"AllyID":1,"BotAI":"CircuitAINovice32","BotName":"AI: Novice (1)","Owner":"rincewind"},{"AllyID":1,"BotAI":"CircuitAIEasy32","BotName":"AI: Easy (1)","Owner":"rincewind"}],"Title":"rincewind's Battle","IsMission":false,"EngineVersion":"104.0.1-92-g4409317","IsMatchMakerGame":false,"Mode":5,"ModOptions":{"commanderTypes":"ewogIGM1MTA0NiA9IHsKICAgIG5hbWUgPSAiU3VpdGNhc2UiLAogICAgY2hhc3NpcyA9ICJlbmdpbmVlciIsCiAgICBkZWNvcmF0aW9ucyA9IHt9LAogICAgbW9kdWxlcyA9IHsKICAgICAgewogICAgICAgICJjb21td2VhcG9uX2JlYW1sYXNlciIsCiAgICAgICAgIm1vZHVsZV9hZHZfbmFubyIKICAgICAgfSwKICAgICAgewogICAgICAgICJtb2R1bGVfYWJsYXRpdmVfYXJtb3IiLAogICAgICAgICJtb2R1bGVfamFtbWVyIgogICAgICB9LAogICAgICB7CiAgICAgICAgImNvbW13ZWFwb25fc2hvY2tyaWZsZSIsCiAgICAgICAgIm1vZHVsZV9wZXJzb25hbF9jbG9hayIsCiAgICAgICAgIm1vZHVsZV9hYmxhdGl2ZV9hcm1vciIKICAgICAgfSwKICAgICAgewogICAgICAgICJtb2R1bGVfYWR2X25hbm8iLAogICAgICAgICJtb2R1bGVfaGlnaF9wb3dlcl9zZXJ2b3MiLAogICAgICAgICJtb2R1bGVfYXV0b3JlcGFpciIKICAgICAgfSwKICAgICAgewogICAgICAgICJtb2R1bGVfYWR2X3RhcmdldGluZyIsCiAgICAgICAgIm1vZHVsZV9hZHZfbmFubyIsCiAgICAgICAgIm1vZHVsZV9yYWRhcm5ldCIKICAgICAgfQogICAgfQogIH0sCiAgYzUxMDQ3ID0gewogICAgbmFtZSA9ICJDb21tYW5kZXIgMiIsCiAgICBjaGFzc2lzID0gInJlY29uIiwKICAgIGRlY29yYXRpb25zID0ge30sCiAgICBtb2R1bGVzID0gewogICAgICB7CiAgICAgICAgImNvbW13ZWFwb25fbGlnaHRuaW5nZ3VuIiwKICAgICAgICAibW9kdWxlX2Fkdl9uYW5vIgogICAgICB9LAogICAgICB7CiAgICAgICAgIm1vZHVsZV9hYmxhdGl2ZV9hcm1vciIsCiAgICAgICAgIndlYXBvbm1vZF9zdHVuX2Jvb3N0ZXIiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAiY29tbXdlYXBvbl9jb25jdXNzaW9uIiwKICAgICAgICAibW9kdWxlX2Fkdl90YXJnZXRpbmciLAogICAgICAgICJtb2R1bGVfaGlnaF9wb3dlcl9zZXJ2b3MiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAibW9kdWxlX2hpZ2hfcG93ZXJfc2Vydm9zIiwKICAgICAgICAibW9kdWxlX2RtZ19ib29zdGVyIiwKICAgICAgICAibW9kdWxlX2phbW1lciIKICAgICAgfSwKICAgICAgewogICAgICAgICJtb2R1bGVfYWR2X25hbm8iLAogICAgICAgICJtb2R1bGVfZG1nX2Jvb3N0ZXIiLAogICAgICAgICJtb2R1bGVfYXV0b3JlcGFpciIKICAgICAgfQogICAgfQogIH0sCiAgYzUxMDUxID0gewogICAgbmFtZSA9ICJDb21tYW5kZXIgMyIsCiAgICBjaGFzc2lzID0gImd1YXJkaWFuIiwKICAgIGRlY29yYXRpb25zID0ge30sCiAgICBtb2R1bGVzID0gewogICAgICB7CiAgICAgICAgImNvbW13ZWFwb25faGVhdHJheSIsCiAgICAgICAgIm1vZHVsZV9hZHZfbmFubyIKICAgICAgfSwKICAgICAgewogICAgICAgICJ3ZWFwb25tb2RfbmFwYWxtX3dhcmhlYWQiLAogICAgICAgICJtb2R1bGVfYWJsYXRpdmVfYXJtb3IiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAiY29tbXdlYXBvbl9yaW90Y2Fubm9uIiwKICAgICAgICAibW9kdWxlX2RtZ19ib29zdGVyIiwKICAgICAgICAibW9kdWxlX2Fkdl90YXJnZXRpbmciCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAibW9kdWxlX2hpZ2hfcG93ZXJfc2Vydm9zIiwKICAgICAgICAibW9kdWxlX2Fkdl9uYW5vIiwKICAgICAgICAiY29tbXdlYXBvbl9wZXJzb25hbF9zaGllbGQiCiAgICAgIH0sCiAgICAgIHsKICAgICAgICAibW9kdWxlX2Fkdl90YXJnZXRpbmciLAogICAgICAgICJtb2R1bGVfYWJsYXRpdmVfYXJtb3IiLAogICAgICAgICJtb2R1bGVfaGlnaF9wb3dlcl9zZXJ2b3MiCiAgICAgIH0KICAgIH0KICB9Cn0="},"UserParameters":{"rincewind":{"LobbyID":"396194","CountryCode":"US","faction":"","clan":"","clanfull":"","level":"23","elo":"1405","icon":"3_2","avatar":"chickenqueenlite2","badges":"","admin":"0","can_spec_chat":"1","ignored":"","friends":"","commanders":"ewogICJjNTEwNDYiLAogICJjNTEwNDciLAogICJjNTEwNTEiCn0="}},"BattleID":6},"MissionFrame":0,"MissionScore":null,"MissionVars":null,"MyPassword":null,"MyUserName":null,"OutputExtras":["CHATLOG:rincewind I choose: Suitcase!"],"Port":8455,"ReplayName":"c:\\projekty\\springie_spring\\demos-server\\20171112_160154_Onyx Cauldron 1_104.0.1-92-g4409317 maintenance.sdfz","StartTime":"2017-11-12T15:01:54.5275765Z","WasKilled":false}`

**Comment by Licho1** [comment]
this is now fixed
