### ISSUE TITLE
Chobby is not being updated

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1892]
There was a new chobby version released on Sunday, but others including myself haven't received an automatic update when restarting the wrapper.

**Comment by GoogleFrog** [comment]
Are you using the steam version? I wouldn't necessarily trust that to update at the moment. I cannot reproduce with the installer version.

**Comment by GoogleFrog** [comment]
And why do you hate issue searchability?

**Comment by DeinFreund** [comment]
It's installer version. It also denies using new zkmenu after manually downloading it. I'd presume it has to do with broken autoregistrator.

I opened this on my phone, sorry for autocorrect.

**Comment by GoogleFrog** [comment]
Why do you think it has not updated?

**Comment by DeinFreund** [comment]
`[f=-000001] [LuaMenuController::Reset] using menu archive "Chobby v1.5.11.7"`
but
`[f=-000001] [LuaMenu] Error: In Update(): [string "LuaMenu/Widgets/api_download_handler.lua"]:303: attempt to perform arithmetic on a nil value`
