### ISSUE TITLE
Map downloads have been failing for several days

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K-Infrastructure#1893]
Every map queued results in status: failed. Downloads menu has improved looks but still does not grab stuff.

**Comment by DeinFreund** [comment]
Are the downloads actually failing or is the map downloaded but the result not displayed?

**Comment by The-Yak** [comment]
Maps are not appearing in /maps/ folder. Nothing seems to be downloaded.

**Comment by DeinFreund** [comment]
Could you post  your infolog_full.txt? I can't reproduce this.

**Comment by GoogleFrog** [comment]
I cannot reproduce either. It has worked for a while for me and prior to this ticket rumors that it was broken were just rumors. What version are you using?

**Comment by The-Yak** [comment]
infolog_full paste: https://pastebin.com/BC4K2akA

I have no idea how to tell what version of chobby I'm on.

**Comment by GoogleFrog** [comment]
[f=-000001] [LuaMenuController::Reset] using menu archive "Chobby v1.5.11.7"

This is up to date. I think you are having connection issues. The wrapper interface appears to be working.

**Comment by The-Yak** [comment]
Every teamgame I have played multiple people have had the same problem. I may not have quality internet here but I am not the only one with this issue.

**Comment by The-Yak** [comment]
Bitdefender antivirus was blocking chobby from downloading and not reporting it in activity log. Downloads are working and looking great, but now I need a new antivirus.

Closing.
