### ISSUE TITLE
Check whether the matchmaker is making 1v1s with too much difference

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1901]
Look at this game: http://zero-k.info/Battles/Detail/476202. Do the numbers make sense?

My elo: 1911. Malus 3.47781909984983.

Their elo: 1149. Malus 1.49463329233491

Is this within range? If it is within range numbers may need adjusting.

**Comment by DeinFreund** [comment]
This is a real ELO difference of 602. Is this ok?

**Comment by DeinFreund** [comment]
Possible fixes are
 * Don't consider decay as an increase in matching width by either: 
   * Only taking real elo values
   * Only taking decayed elo values
   * Reducing maximum decay
 * Reduce the allowed matching width

The current method actually tries to account for rating uncertainty, which is inaccurate with current elo, but actually makes sense if we move to WHR. Reducing the width would make it near impossible for active players to find matches.

**Comment by Licho1** [comment]
I think it works as designed..
