### ISSUE TITLE
Wrapper fails to download zkmenu:stable

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#1903]
```
Zero-K.exe Information: 0 : Checking for self-upgrade
Zero-K.exe Information: 0 : http://zkmenu.repo.springrts.com/packages/7437bd936b30a092c0fa9e42bc1505b6.sdp Completed - 72.36k
Zero-K.exe Error: 0 : Error downloading zkmenu:stable: System.IO.IOException: Unable to read data from the transport connection: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. ---> System.Net.Sockets.SocketException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
[error message repeats three times]
```
The grouping of the download completion message and error messages repeats several times, until the warning dialog message "Download of zkmenu:stable has failed" appears and the application subsequently closes. Redownloading and reinstalling did not help, neither did deleting up packages and pool.

Win7 Home Premium 32 bit, non-Steam ZK

**Comment by DeinFreund** [comment]
There is no Ram/HDD space issue?

**Comment by KingRaptor** [comment]
> There is no Ram/HDD space issue?

7 GB free on the relevant partition, and physical memory % in Task Manager not exceeding 80% (on a max-for-32-bit RAM system), so it doesn't seem likely.

**Comment by Licho1** [comment]
https://blogs.msdn.microsoft.com/sql_protocols/2009/03/09/understanding-the-error-an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-sufficient-buffer-space-or-because-a-queue-was-full/

**Comment by The-Yak** [comment]
Antivirus?

**Comment by KingRaptor** [comment]
I tried turning off AVG's Web Shield and it was able to download `zkmenu:stable` and `zk:stable`.

Although I forgot to try running wrapper again before making any changes, and haven't been able to reproduce since.

Closing for now?
