### ISSUE TITLE
[Linux] Mono keeps running when the game shuts down

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1905]
See https://github.com/ZeroK-RTS/Zero-K/issues/2606

**Comment by Licho1** [comment]
should be fixed in test

**Comment by sprunk** [comment]
for reference https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/7dc2f2c8648db43f2a3fe0e078c074152343ee99
