### ISSUE TITLE
Wrapper doesn't always close after game ends

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1906]
It sometimes keeps running in the background. Maybe this is related to steam not running.

https://www.reddit.com/r/zerok/comments/7dycoi/process_running_long_after_deletion/

**Comment by sprunk** [comment]
#1905?

**Comment by DeinFreund** [comment]
Windows too

**Comment by Licho1** [comment]
should be fixed in test
