### ISSUE TITLE
Media wiki steam login is broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1908]
Try to login to media wiki using steam

"Server Error
404 - File or directory not found.
The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.
"

**Comment by KingRaptor** [comment]
The OpenID extension is using an incorrect realm `https://zero-k.info/mediawiki/mediawiki`

I don't know why this changed or how to fix it, looking into it.

**Comment by KingRaptor** [comment]
Fixed.
(Stripped the trailing `/mediawiki` from MW config's `$wgServer` and `$wgCanonicalServer`)
