### ISSUE TITLE
Make map rating validity independent of support level

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1909]
Support levels for maps are changed regularly. Whether a map counts for ratings or not should generally never be changed. 

For example if one looks up an old version of a map, it will currently be shown as unsupported and thus doesn't count for elo. Yet if one looks up old games on this map they did count for elo which is impossible to explain solely from the map and game settings.

Thus my suggestion is to have a "rated/unrated" switch on each map that is independent of support level. This could be a replacement for the `special` switch.

**Comment by DeinFreund** [comment]
An alternative approach suggested by hoko would be to add a `deprecated` support level. This is no longer officially marked as support but still counts for ratings.

**Comment by Licho1** [comment]
meh whats the problem of keeping old maps supported and just featuring the "proper" version?

**Comment by DeinFreund** [comment]
That's what I said: http://zero-k.info/Forum/Post/178408#178408

**Comment by Licho1** [comment]
How about calculating elons from everything? Why do we even need "supported"? Perhaps instead we need "not supported".
Which was already have.. its that  is funky indicator..

**Comment by DeinFreund** [comment]
I would agree with that. Who originally disabled that?

**Comment by Licho1** [comment]
notme.. at least i never liked "supported" thingie.. so now supported basically loses meaning?

**Comment by DeinFreund** [comment]
Currently it seems useless as we're just featuring everything that is halfway playable. Yet in the future, I would be interested in reducing the map pool to less, higher quality maps. Then our dozens of currently featured maps could be reduced to supported, with the standard map rotation only containing a dozen or so maps and matchmaker being even fewer maps.

This probably sounds like throwing away all our content, but more isn't always better. 1v1 meta is mostly about units and build orders. This change could turn it into map-specific strategies and expansion orders.

**Comment by db81** [comment]
Just store whether a battle counted for elo/whr in the replay db. Maybe it even already stores that, maybe indirectly, I didn't look. Then you can calculate retroactively and don't have to complicate mapfeaturing.

**Comment by Licho1** [comment]
I think logic should be:
 * isspecial = we dont do elons
 * supported = this is the version that is most likely to work well, if map has multiple versions
 * featured = this is the map that is so good we think you should be playing it and see it in lists
 * matcmaker = this is the map you need to have for mm to work

**Comment by DeinFreund** [comment]
@db81 that needs to be added either way for noelo to work retroactively.

**Comment by Licho1** [comment]
i dont think we need retroactivity.

**Comment by DeinFreund** [comment]
WHR comes with retroactivity by default. Id have to actually implement a workaround to disable it.
