### ISSUE TITLE
Maps distributed to steam contain many duplicates and triplicates

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#1912]
https://pastebin.com/r5W1tnYE

Make sure that missions and "matchmaker" maps contain single version of the map and not many different.

**Comment by DeinFreund** [comment]
Are maps automatically cleared for each new build or could it be that those are simply past MM maps?

**Comment by Licho1** [comment]
They are not cleared, i just clared it and we will see after next stable...

**Comment by GoogleFrog** [comment]
Where did this list come from? There is only one TitanDuel which is featured or above. I intended for only one version should be supported or above. Regardless, I don't think you should include supported maps .in the steam content/

**Comment by Licho1** [comment]
This is the actual steam folder. It gets generated from matchmaker maps + maps needed by missions.

**Comment by DeinFreund** [comment]
So in case it works on next stable the only fix needed would be to simply clear the steam maps folder before each steam update?

**Comment by Licho1** [comment]
titanduel2 a and 2.2 will be fixed soon i assume

**Comment by Licho1** [comment]
always deleting sounds like a waste of SSD lifetime, we shall delete the steam maps folder from time to time..
