### ISSUE TITLE
Create an interface for manual map registration

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K-Infrastructure#1914]
http://api.springfiles.com/files/maps/?C=M;O=D
No maps in the past 2 days have been picked up ZK side. Aether 1.5 was the last.

**Comment by Licho1** [comment]
That is correct, new map registration and springfiles syncing is disabled.

**Comment by The-Yak** [comment]
Okay good talk, renaming issue

**Comment by Sgathec** [comment]
How will users register Zero-K mutators and other games?

**Comment by Licho1** [comment]
Same as now.

**Comment by Sgathec** [comment]
How does one currently make it possible to change to a new mutator in a Chobby room or is there any way at all at the moment? I know !game requires the room to be passworded and the type should be custom.

**Comment by Licho1** [comment]
I think that you can host any game that is downloadable via rapid so you can do !game yourmutator and it will work.
As for maps, i have re-enabled springfiles syncing.
