### ISSUE TITLE
[feature request] Honor system [low priority]

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#1915]
I am uncertain but it seems that in multiplayer games, an honor system can encourage good behaviours

like at the end of a match each players can choose a player to honor with a screen or something

example League of Legends

**Comment by DeinFreund** [comment]
Would it be ok to make this a general system? I.e you can honor any player at any time and at most once? Then honoring could be done during the game, after the game on the website or generally to everyone with a friendly name.

**Comment by Sortale** [comment]
something to compliment our karma system on forum. 

I just need some cut off point to honor [i.e. define action to honor]

e.g. on the forum it would be each post, in my system it would be each game

purpose would be similar to forum karma that is foster good action punish bad, and highlight bad or good players

**Comment by DeinFreund** [comment]
I don't think negative feedback helps anyone. How about turning this into an award if it is on a per-game basis? Then every game one "most helpful player" is selected and awarded. On the ladders you can then see who has collected most "most helpful player" awards.

**Comment by DeinFreund** [comment]
If you want to actually detect trolls this way, we should directly implement a proper rating system. This could for example be measuring troll classification accuracy and a troll rating for every player.

I don't think this is needed currently and we shouldn't give negative feedback, especially publicly, if we aren't completely sure it is correct and appropriate.

**Comment by sprunk** [comment]
Negative feedback with visibility only fuels the cycle.

Negative feedback without visibility already exists, that's the report system. If we want it more accessible then perhaps there could be a report button on the endgame screen, perhaps with some pre-filled categories (teamkill, verbal, etc).

Positive feedback sounds ok but beware that it will easily become meaningless (+ing becomes standard courtesy).

**Comment by Sortale** [comment]
how about positive feedback only on an average per game rating. with some kind of visual indicator for high ranking honorable

even if people mostly do it as courtesy it would separate the chaff from the wheat [I mean troll would receive almost no honor at all I would assume] . and letting people know that most people in their team choose to honor them specifically would give people a sense of fulfillment/satisfaction

**Comment by GoogleFrog** [comment]
How are you linking the word "honour" with your intended concept of honour?

**Comment by Sortale** [comment]
honoring someone? use it that way because it's how LOL call it, karma would do just fine.
beside the name is quite unimportant, what matter is the concept

**Comment by GoogleFrog** [comment]
I mean this: you are giving players the ability to send each other numbers. How do you make the people with the high numbers be the people which you intend to have the high numbers? In a small pond community I can see the system being subverted to mean whatever the big fish find it enjoyable for it to mean. You could end up with a funny troll number.

**Comment by Sortale** [comment]
uhm if that's your concern then no system is good, 

any system can be perverted in a small pool environment as you describe to mean anything. Perhaps best ignore this idea then?

personally, I am just thinking about a simpler method of feedback than the chat

e.g. "gg @[player A] did well but you etc etc" compare to 1 or 2 click.

I feel [not certain] that it's easier and allow for more frequent positive feedback which in turn theoretically increase player enjoyment.

But I can always be wrong.

**Comment by Licho1** [comment]
Postponing this, might be interesting with bigger community.
