### ISSUE TITLE
Discord -> Chobby bridge outputs garbage

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1916]
It seems to have replaced two of sprang's texts with random chat snippets from 2 weeks ago (today is 6 Dec, the old ones are from 18 Nov).

Actual chat:
![actual](https://user-images.githubusercontent.com/2573076/33684903-254ab320-dad0-11e7-86c8-79d8c741cd26.png)

Chobby + random old snippets:
![fail](https://user-images.githubusercontent.com/2573076/33684082-4f0e3d60-dacd-11e7-83f1-de12d75fea69.png)

Later I also said "test" and nothing appeared Chobby-side at all.

**Comment by Licho1** [comment]
We have switched to new API, lets see if that helps
