### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#1917]
I've seen complaints about lag very recently at least on #zk and during a battle. The lag appears to affect multiple people. During the battle, the delay before my orders were executed seemed to be about 0.5 seconds. It was even around a second at times, but that was probably fairly rare. Usually my latency is less than those values. Moreover, about three hours ago I could not log in using my lobby client.

**Comment by DeinFreund** [comment]
There have been a lot of null pointers this evening (6. dec). I couldn't find any OOM, but maybe something else messed up the server? Usually these exceptions are from outdated protocol (i.e. swl ping), yet this time it includes `ChangeUserStatus`

`[2608 37.136.45.151:61036 ] error processing line ChangeUserStatus {"IsAfk":false} : System.NullReferenceException: Object reference not set to an instance of an object. at ZkLobbyServer.ClientConnection.d__11.MoveNext()`

**Comment by sprunk** [comment]
>could this have been a simple network overload/problem?

Licho says `issue seems to be networking, out of our control`.

**Comment by DeinFreund** [comment]
After all these network issues keep happening. Could there be hardware solutions?

**Comment by Licho1** [comment]
I have rebooted the server, the changeuserstatus is something to check though..

**Comment by Licho1** [comment]
i think it was fixed by reboot..
