### ISSUE TITLE
Login is case sensitive

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1925]
I develobbed, login via test site still returns `Invalid login name`. Login should be case insensitive.

**Comment by DeinFreund** [comment]
Is this actually working now?

**Comment by Licho1** [comment]
i assume person who made the PR tested it...

**Comment by DeinFreund** [comment]
It works for Lobby, but still needs implementing for site. That's why I made this issue.
