### ISSUE TITLE
Failed and blocked map downloads

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1932]
Xiniu1 had an issue where they were unable to start matchmaker due to not having any maps. The maps seemed to be in their map folder and had the correct size. Spring VFS.HasArchive would fail to detect the maps as present and this persisted over restarts. Deleting the maps fixed the issue when they were automatically redownloaded.

https://media.discordapp.net/attachments/278805140708786177/390525649149755392/unknown.png?width=1100&height=619
[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1556125/infolog_full.txt)

**Comment by GoogleFrog** [comment]
This sounds like the same issue https://github.com/ZeroK-RTS/Zero-K/issues/2667

**Comment by The-Yak** [comment]
Perhaps the same issue, but for that user it was a campaign map that downloaded then failed to be recognized. This is a bigger problem for campaign because you currently can not easily tell which mission requires what map.

**Comment by Mafiasto** [comment]
I found that deleting  the map and restarting the game fixes it but its hard to know what map is what. I was told to post this info log. 
[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1556830/infolog_full.txt)
