### ISSUE TITLE
Tourney room type

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1940]
add a room type - Tourney. Has user names as arguments, only those users can unspec. Has !setoptions mutelobby=mute,mutespec=mute by default. Closes itself if nobody has been in it for 10 minutes or if there is nobody in it and a game has been started in it. Cannot be created by everyone (needs a permission)

**Comment by GoogleFrog** [comment]
When hosting a tournament room it should take the map and modoptions as arguments.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/892f055ad2f2ecee3354ff14e0c1a6ecc2495c7e#diff-0acfc481015b9608b96df61710c6dad9 et al
