### ISSUE TITLE
Wrapper: list of featured maps (not just MM)

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#1950]
The wrapper should tell Chobby the list of featured maps (similar to how it already tells the MM maps).

**Comment by Licho1** [comment]
wrapper does not do this, its the ZKLS. I am not sure its a good thing to do unless someone wants to add download for it.
It will clog the network and steam already downloads all featured maps.

**Comment by Licho1** [comment]
Hmm steam does not send featured maps. But imo we either 
a) want to distribute with steam
b) want to do on-demand only 

Distributing all via ZK servers seems wasteful
