### ISSUE TITLE
zero-k.info Development Setup and Test-Database

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#196]
In order to build the website, the local db is required for testing if you are not whitelisted to access the live-db. 

i once managed this with another PC (which is no longer available in its configuration) a year ago. I used the old vs2010 express if i recall right. the site was running with an empty local db (not auto-created, that function failed, but handmade, and totally empty and therefore useless). 

now i got vs2013 and i could not get it running with local db. i cannot recall how i made the db connection the last time to work.

my goal is an autocreated a local db, populated with some test data/testuser so other (new) devs may benefit and can start right away.

any guidance on that (eg. where to look for the db table-names, datatypes etc) would be appreciated.

in the end, this could lead to a wiki page how to dev for the website similar to the existing one on googlecode.

side-effect: i can test ;)

**Comment by Licho1** [comment]
ITs now solved. Configure "seed" to add more default data if needed.
