### ISSUE TITLE
Replace visible ratings by rank badges

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#1971]
Numeric ratings aren't easy to interpret and the small changes induced by WHR are not intuitive either. Thus I would suggest replacing the main metric on each profile by simplified (and hopefully nice looking) rank badges. Numeric ratings will persist on the graphing tool and ladders.

The ranks would be taken from the existing electromagnetic spectrum scheme with added rankup/rankdown thresholds. This means, every rank is extended by a certain amount of points in both directions and only going above this threshold will trigger a rank change. Additionally, new ranks can only be gained directly after a victory and lost after a defeat. 

So, assuming a threshold of 20 points, if you wanted to rank up from yellow to blue, you now need to play until you win a game which puts you above 2020 (2000+20) points. 

Because this alone would rob players of their ability to closely track their progression, I would add a progress bar to the rank badge. This will indicate the player's position within the rank's point bracket.

**Comment by DeinFreund** [comment]
The threshold could be defined directly by a player's rating uncertainty. This will assure ranking up isn't unneededly difficult for active players (5-10 threshold) and make sure less active players don't jump around ranks until their rating has settled or they have clearly improved.

This system would guarantee that inactive players can't lose their rank to decay until they actually lose a game. This means that coming back might often be combined with a derank. Thus it might make sense to use raw whr instead of the decayed one, using the decayed rating only for balance (less active players get easier wins).

**Comment by db81** [comment]
I've always had this idea of having a ~2 px wide vertical bar (next to the rank icon?) to display rank.
 * The icons are 16 px by height so you have 16 different gradations. Coarse-grained like the icons.
 * Vertical bars can be compared at a glance, but a 1 px difference is hard to see. This is a feature!
 * Much more intuitive than our color scheme that jumps randomly between hot and cold colors so you have to ask people to figure it out. *Universally intuitive* unlike the color scheme that spawned a lot of bikeshedding.
 * Takes very little space.

**Comment by DeinFreund** [comment]
I don't want more small indecipherable things. The rank is supposed to be something you can show to others and brag with. I would go as far as styling one's entire profile depending on rank.

There is already a game using similar colors for ranks: https://en.wikipedia.org/wiki/Paranoia_(role-playing_game)#Security_clearances
Their naming scheme should be applicable to our system. 

We could probably come up with many more ranking schemes, but I'd rather just stay with this now than start another discussion.

**Comment by DeinFreund** [comment]
I've put a prototype on the test server for now, if you don't think it should be used feel free to revert.

**Comment by Anarchid** [comment]
These stars look pretty bad especially when scaled:
![image](https://user-images.githubusercontent.com/3822768/34381909-34003a08-eb14-11e7-8a71-de109ec77f21.png)
![image](https://user-images.githubusercontent.com/3822768/34381913-3d18e73e-eb14-11e7-9800-00d4751ec465.png)

Unsure if the forum body font change is warranted:
![image](https://user-images.githubusercontent.com/3822768/34381930-4eb6fc60-eb14-11e7-9bb4-3d72527c55b6.png)

My rank progression towards supergiant is having issues:
![image](https://user-images.githubusercontent.com/3822768/34381939-5f9043b6-eb14-11e7-92b8-744e2030186b.png)
