### ISSUE TITLE
Make the linux steam install script explain why it's asking for your password

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#1975]
It looks pretty bad when you click play on a game and you instantly get a password prompt. I want to make it say that you need some deps installed and ask if you wanna run the command. Also I'll make it actually check whether the packages are missing instead of blindly running it like a savage.

This is mostly for myself to remind me I meant to do this.

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/SteamRoot/bin/setup-zerok.sh

**Comment by Sortale** [comment]
we can explain why we need password promp with zenity on debian system. [what I planned to do anyway [long time until I can implement]]

and the dependency request should only appear on fresh install [bad implementation need revise]

**Comment by lagerspetz** [comment]
Simple question in zenity and conditional dep check, replaces line 9 in setup-zerok.sh: 

zenity --question --title "Install Dependencies" --text "Zero-K needs SDL2 and other depdendencies to run.\nCheck for dependencies now?"
answer=$?
if [ $answer = 0 ]
then
  ${pkx} ${pkgmanager} -y install mono-complete libsdl2-2.0-0 libopenal1 libcurl3 zenity libgdiplus sqlite3
fi


setup-zerok.sh is run only once, so that should be fine.

**Comment by Licho1** [comment]
added 91af799

**Comment by lagerspetz** [comment]
Thanks! One issue I just thought about: if Zenity is not installed, the answer becomes nonzero, and the deps are not installed. I could add a check for zenity, but communicating with the user would just get harder... another option is to use a terminal program as a dialog, which is what Steam used to do. I will look for a nicer looking alternative with no deps.

**Comment by Licho1** [comment]
I guess use terminal then.. most important is that it works imo

**Comment by lagerspetz** [comment]
I have attempted to solve this, tested that the three options work on my machine.
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/2039

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/4a83024659f1af7519aecc8606e535864443b356
