### ISSUE TITLE
ZKL packages downloader trying to assassinate rapid server

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#198]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaDownloader/Packages/PackageDownloader.cs#L47
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZeroKLobby/Config.cs#L366

every 2 minutes, server fetches all repos simultanously.
Of course, every ZKL client does it too... resulting in rapid server sending out TCP reset...

Don't fetch everything simultaneously. Don't fetch it that often. In fact, don't poll at all if the user is connected through lobby... it can get trigger through nightwatch. Server overload problem solved.

**Comment by abma** [comment]
great, thanks!

**Comment by gajop** [comment]
Can api.springfiles be used to check for rapid updates?
Example: http://api.springfiles.com/?springname=&filename=&tag=zk%3Astable&sdp=&category=

**Comment by db81** [comment]
If springfiles/upq#41 is fixed.
