### ISSUE TITLE
Cannot connect to multiplayer

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1981]
Host a game, click start. Spring turns into its black "Connecting to server (3s)" screen. Spring reaches 10s and then puts me back in the lobby.

Also, it takes about 20-30 seconds to connect to ZKLS on chobby startup.

**Comment by KingRaptor** [comment]
Server dropped below 1 GB HDD space and Spring refused to start.

I deleted all 103.1.* engines, this freed up about 7 GB.
