### ISSUE TITLE
Chat history is sent every time a player joins

### ISSUE THREAD

**Issue by lhog** [ZeroK-RTS/Zero-K-Infrastructure#1985]
There obviously was a change that made ZK-Infra send a whole history of chat on every channel every time a user joins the server.

Myself and a few other players don't think it was a wise choice due to following:
1) It takes some time for a lobby to receive and process a history of chat. This is especially bad for low end PCs and will become more and more the issue since the length of history is ever growing.
2) If the player name is mentioned it will receive a notification window every time for each mention. At least the case on ZKL.
3) Privacy is compromised. Also there is no available way to erase history.

Please revert to how it used to work before.

**Comment by sprunk** [comment]
Relevant https://github.com/ZeroK-RTS/Chobby/issues/454

**Comment by The-Yak** [comment]
I was surprised to learn this is supposedly a "feature". What good does it do anyone getting notified for the same username ping over and over again?

**Comment by lhog** [comment]
Apparently it's been fixed.

**Comment by lhog** [comment]
Not fixed, just server reset probably cleaned some older chat entries.

**Comment by DeinFreund** [comment]
This  seems to be an issue with setting `Account.LastLogout`. If I logout using the button in Chobby, the chat history isn't resent on the next login. If I logout by simply closing Chobby and terminating the connection, I get all of the messages again for my next login.

**Comment by DeinFreund** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/115a9182dce08b9ae2364d4cfabb42d42a3e0bf4#diff-909210651c4a54b869e31b3ddf38213aR633

This prevents LastLogout from being set.
