### ISSUE TITLE
Error downloading zkmenu:stable

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1995]
Discord user Lubstar#1739 reported this.

chobby.exe Information: 0 : Checking for self-upgrade
chobby.exe Information: 0 : PackageRefresh complete - packages changed
chobby.exe Information: 0 : http://zkmenu.repo.springrts.com/packages/600a34c6a19073226da59b9b166ba721.sdp Completed - 72,88k
chobby.exe Information: 0 : zkmenu:stable download complete - 72,88k
chobby.exe Error: 0 : Error downloading zkmenu:stable System.IO.InvalidDataException: Hodnota Magic number v záhlaví GZip není správná. Ověřte, že předáváte datový proud GZip.
   v System.IO.Compression.GZipDecoder.ReadHeader(InputBuffer input)
   v System.IO.Compression.Inflater.Decode()
   v System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   v System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   v System.IO.Compression.GZipStream.Read(Byte[] array, Int32 offset, Int32 count)
   v System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   v System.IO.Stream.CopyTo(Stream destination)
   v ZkData.Pool.ReadFromStorageDecompressed(Hash hash)
   v PlasmaDownloader.Packages.Sdp2Sdz.GenerateSdz(SpringPaths paths, SdpArchive fileList, String tempSdz, Action1 progressIndicator)
   v PlasmaDownloader.Packages.Sdp2Sdz.ConvertSdp2Sdz(SpringPaths paths, Hash sdpHash, String targetSdz, Action1 progressIndicator)
   v PlasmaDownloader.Packages.PackageDownload.MasterDownloadThread()

**Comment by DeinFreund** [comment]
Could it be that the downloaded file is somehow corrupted?

**Comment by Licho1** [comment]
The message says that magic number in gzip downloaded from springrts.com is incorrect..
All they can is redownload .. its unlikely that the gzip implementation is incorrect, it is one bundled in .NET used in millions of projects.
