### ISSUE TITLE
Ladder ranks are out of order

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#1996]
The colours are out of order.

![image](https://user-images.githubusercontent.com/1318249/34665791-afffc934-f4b5-11e7-9e23-036e78e00a6e.png)

**Comment by DeinFreund** [comment]
This is intentional, the new ranking system requires you to play clearly above your own rank to rank up and clearly below to rank down. Besides that, it is impossible rank up or down in the current stable, I am currently debugging this.

**Comment by DeinFreund** [comment]
Ranking up/down works now on test.
