### ISSUE TITLE
New site font is terrible

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2000]
The font is small, unreadable and has too many serifs. Every ticket about visuals should have a screenshot so here is mine:

![image](https://user-images.githubusercontent.com/1318249/34714506-c429752c-f57d-11e7-9091-7634641d5e7c.png)

**Comment by Licho1** [comment]
Just use the readable font we had before except for key menus. Landing pages has to be nice on eyes.

**Comment by GoogleFrog** [comment]
This screenshot is in firefox. The font is decent in chromium.

**Comment by DeinFreund** [comment]
Just for comparison, this is the intended font:
![font](https://i.imgur.com/1cCEMB5.png)
