### ISSUE TITLE
Disable steam popups from inside lobby

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2014]
The lobby should have settings for disabling "your friend is now playing X" popups from appearing in the ZK steam overlay. I don't know if steam has these settings per-game and whether the wrapper can change these settings but it is worth looking into.

If the wrapper can do this then I would add chobby settings to never show popups, always show popups (as configured by the user in their general steam settings) or automatically disable popups when ingame but show them otherwise.

**Comment by Licho1** [comment]
Wrapper has no direct control over it. It is pure steam business and can be configured inside steam.
