### ISSUE TITLE
Host minimap thumbnails

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2019]
If the site generates and hosts 64x64 thumbnails for maps I will make chobby download and use them. I also want 1024x1024 images hosted but these seem to already have a link.

**Comment by Licho1** [comment]
Why host them and not distribute with steam or even chobby?

**Comment by GoogleFrog** [comment]
They are already distributed with chobby, do you think we should instead try to keep chobby up to date? Can you make the site able to generate a bunch of files for inclusion into chobby?

**Comment by Licho1** [comment]
Well site will definitely:
1) host all minimaps
2) copy selected minimaps to steam 

I think that is enough, if there is download, for non-steamers it wills imply dl.

**Comment by GoogleFrog** [comment]
Thumbnail here http://zero-k.info/Resources/Living_Lands_3.32.thumbnail.jpg
