### ISSUE TITLE
website: add link to tourney archive

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#202]
Would be nice to have archive of played tourneys, to see past winners or find the replays.
Sadly the tourney threads are scattered through the whole forum/news.

This page
https://code.google.com/p/zero-k/wiki/TourneyArchive
is not the nicest but it has list of winners + link to the tourney threads, which usually contain list of replays too.

Might be nice to have it linked somewhere, for example on http://zero-k.info/Ladders or in  "Community" menu.

**Comment by Licho1** [comment]
It's now time to update/edit content in new wiki.
When done it can be linked from some higher level places ..
