### ISSUE TITLE
There have never been any 1v1 matchmaker games on CCR

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2020]
The map is appropriately tagged and appears in MMSetup.

[f=-000001] [ServerMessage] MatchMakerSetup {"PossibleQueues":[{"Name":"Teams","Description":"Play 2v2 to 4v4 with players of similar skill.","Maps":["Hide_and_Seek_v03","Ravaged_v2","Isle of Grief 0.2","Fairyland v1.0","Akilon Wastelands ZK v1","Calamity 1.1","Adansonia v4.1","Lonely Oasis v1.1","Comet Catcher Redux v3.1","Eye of Horus v13","Wanderlust v03","Vittra v2.1","Barren 2","Cold Snap 2","Badlands 2.1","Intersection v4.1","Trojan Hills v03","Red Comet v1.3","Obsidian_1.5","Onyx Cauldron 1.8","Titan v3.1","TitanDuel 2.2","Living Lands 3.32"],"Game":"Zero-K v1.6.1.9","MaxPartySize":4},{"Name":"Coop","Description":"Play together, against AI or chickens","Maps":["Hide_and_Seek_v03","Ravaged_v2","Isle of Grief 0.2","Fairyland v1.0","Akilon Wastelands ZK v1","Calamity 1.1","Adansonia v4.1","Lonely Oasis v1.1","Comet Catcher Redux v3.1","Eye of Horus v13","Wanderlust v03","Vittra v2.1","Barren 2","Chicken Nuggets v5","Cold Snap 2","Badlands 2.1","Intersection v4.1","Trojan Hills v03","Red Comet v1.3","Avalanche v3.1","Obsidian_1.5","Onyx Cauldron 1.8","Titan v3.1","TitanDuel 2.2","Living Lands 3.32"],"Game":"Zero-K v1.6.1.9","MaxPartySize":5},{"Name":"1v1","Description":"1v1 with opponent of similar skill","Maps":["Hide_and_Seek_v03","Ravaged_v2","Isle of Grief 0.2","Fairyland v1.0","Adansonia v4.1","Lonely Oasis v1.1","Comet Catcher Redux v3.1","Eye of Horus v13","Wanderlust v03","Vittra v2.1","Barren 2","Badlands 2.1","Intersection v4.1","Trojan Hills v03","Red Comet v1.3","Avalanche v3.1","Obsidian_1.5","Onyx Cauldron 1.8","TitanDuel 2.2","Living Lands 3.32"],"Game":"Zero-K v1.6.1.9","MaxPartySize":1}]}

**Comment by sprunk** [comment]
http://zero-k.info/Battles/Detail/483859

**Comment by Licho1** [comment]
Sounds like change + not enough samples. Code has been verified, reopen if p < 0.05 after a week or so
