### ISSUE TITLE
Discord messages don't get to the Chat in Chobby

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K-Infrastructure#2025]
![discordbridge0](https://user-images.githubusercontent.com/11136438/35488850-fc8f8e22-045c-11e8-8a85-348a343da80e.png)
![discordbridge1](https://user-images.githubusercontent.com/11136438/35488852-fe4695ee-045c-11e8-8693-73d7b3dbc029.png)

**Comment by GoogleFrog** [comment]
@Licho1 I think this is vital.

**Comment by KingRaptor** [comment]
Works now.
