### ISSUE TITLE
One must restart the campaign in Steam Zero-K

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#2040]
The user "Kingstad" on the #zk chat: "ah I have to restart my campaign when switching to steam".

**Comment by Licho1** [comment]
you dont have to, you can start any mission in coop mode.

**Comment by sprunk** [comment]
I think he means that his progress looks gone because his campaign save is not read from the old non-steam install location.

**Comment by GoogleFrog** [comment]
This is technically unfixable. All we can do is some sort of instructions for copying saves.

**Comment by Licho1** [comment]
Not true, just start the game in your local copy and it will have your local save.
If steam is running in background you can still host coop

**Comment by Sgathec** [comment]
I see. Is this still a very minor problem because people may not realize they can get the Steam benefits by running the old Zero-K installation? Isn't it possible one doesn't realize it can still be run?

**Comment by Anarchid** [comment]
In that case the issue becomes "this is not documented on wiki".
