### ISSUE TITLE
Steam update often breaks sync with old versions

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2046]
I have had issues with steam update and ZK v1.6.2.5, 1.6.2.6 and 1.6.2.7
- Started ZK on steam in some unknown state.
- Attempted to rejoin a MP game with 1.6.2.5. I got a "Game Drawn" screen and was desynced with everyone (https://github.com/ZeroK-RTS/CrashReports/issues/3437).
- Closed ZK.
- Deleted rapid, packages and pool.
- Started ZK.
- Joined and played a game on 1.6.2.5 successfully (http://zero-k.info/Battles/Detail/486276).
- Watched a replay on 1.6.2.5 successfully (http://zero-k.info/Battles/Detail/486271).
- Closed ZK.
- Made 1.6.2.7 and waited for it to build on steam.
- Started ZK, steam updated and now battlerooms hosting 1.6.2.6 show that I no longer have 1.6.2.6.
- Attempted to run the same replay on 1.6.2.5 (http://zero-k.info/Battles/Detail/486271).
- Had a gamedata related Spring crash https://github.com/ZeroK-RTS/CrashReports/issues/3439

My theory is that rapid was using content from the sdz version of 1.6.2.6 as part of the files required to run 1.6.2.5.

**Comment by Licho1** [comment]
Reopen when we get repro steps.

**Comment by GoogleFrog** [comment]
I'm not going to see closed tickets.

**Comment by Licho1** [comment]
this is now fixed (in test)
