### ISSUE TITLE
Add local replay interrogation 

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2050]
I want a wrapper function to get the game, map, engine (anything else?) of a replay. There seems to be no other way to do this. Would solve https://github.com/ZeroK-RTS/Chobby/issues/111 and issues arising from steam deleting old game sdz.

**Comment by sprunk** [comment]
https://github.com/spring/spring/blob/89d5bbc1597337db318e8933522fee731d41689f/rts/System/LoadSave/demofile.h#L53
