### ISSUE TITLE
Whr predict crashes in battle

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#2052]
https://zero-k.info/Battles/Detail/487208

https://i.imgur.com/uWeZLD9.png

**Comment by DeinFreund** [comment]
Could you run
`UPDATE dbo.SpringBattles SET ApplicableRatings=0 WHERE SpringBattleID = 487208`?

**Comment by KingRaptor** [comment]
SQL query executed

**Comment by DeinFreund** [comment]
Reopen if this happens again after next stable. It should now be impossible to change applicable ratings for unratable matches.

**Comment by Licho1** [comment]
Can WHR predict crashes in battle?

**Comment by DeinFreund** [comment]
Nein.
