### ISSUE TITLE
Credits page

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2053]
The wiki entry is being updated very rarely, so I've been thinking about replacing it by an automatically generated credits page. It would simply list anyone with a developer badge and sort into active/inactive via login date. A manually updated list can account for external resources such as Spring or Schneidemesser. Should github account links be stored in the zk profile to allow linking?

**Comment by Sgathec** [comment]
Doesn't the badge require a great amount of work? Do other contributors deserve to be mentioned?

**Comment by Licho1** [comment]
The project is wayy to old for this and many contributions precede github, some contributors now do not contribute by doing github stuff etc..
Most old people never had any developer flag..
Si imo .. no..

**Comment by Licho1** [comment]
As a minimum they should be check of the list..
And idea to connect devs to git isnt bad either  - i might look into this

**Comment by Licho1** [comment]
credits updated
