### ISSUE TITLE
Controlled crash report button

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2057]
Often I want to get infologs from non-crashing users. This proves to be impossible. There should be an easier system. This is what I propose:
- User clicks "send logs" in lobby.
- Popup occurs "Game will close to collect logs, continue?".
- User clicks yes.
- Chobby sends the loopback function that tells wrapper that this system is occurring.
- Wrapper closes Spring.
- Wrapper sends logs to a standard crash report (with a different name).

**Comment by Licho1** [comment]
```    [ChobbyMessage]
    public class SendBugReport
    {
        public string Title { get; set; }
        public string Description { get; set; }
    }
```
