### ISSUE TITLE
The start poll is sometimes difficult to initiate in rooms

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#2058]
Please consider implementing a system that allows a start poll to be active regardless of other polls. Currently polls block other polls which can prevent the game from being started for a relatively long time depending on ordinary users. If there is a grand number of players in one room, it is possible that one has to be really quick in order to be able to initiate a start poll because that requires reacting to the end of the previous poll. Users often start polls successively to change the map which appears to be the main reason the start of the game is sometimes delayed.

**Comment by sprunk** [comment]
1) The MM was created with such issues in mind.
2) Rooms always have a boss with the power to `!endvote` spammed votes or `!start` directly if need be.
3) Simultaneous votes mean the thing you're voting on (ie. start a game on map X) can change mid-vote.

**Comment by Sgathec** [comment]
I came up with an idea. If a poll that changes the settings succeeds while a start poll is active, the effects of the former poll could be queued to take effect after the latter if the start poll doesn't succeed. The users could be told, for example, that the map will change to Icy Run v2 if the start poll doesn't succeed.

**Comment by sprunk** [comment]
Queuing suffers from changing mid-vote meaning as well. You start a vote to "play the next game on map X" but it can become "play not the next game but the one after that on X" if a start vote passes.

**Comment by Sgathec** [comment]
That requires some user experience design. I'm not sure if a verbal note would be enough.

**Comment by Licho1** [comment]
Not really sure how to improve current stuff without breaking it more.
