### ISSUE TITLE
Change PW state without any releases

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2059]
I want to be able to enable and disable PW with no releases, as releases cost more than they used to. 

Lobby server should have some sort of UpdatePlanetwarsStatus that tells the lobby what is going on regarding planetwars. This status should minimally be a boolean state but could also contain an optional UTC time until planetwars begins (purely for UI). This should be sent to everyone on startup and when status changes. If you want, you can put the status in Welcome.

Site should have an admin page to set whether PW is running and to optionally set a timer to enable it.

**Comment by Licho1** [comment]
done

**Comment by GoogleFrog** [comment]
I am not receiving any messages from ZKLS that indicate planetwars state.

**Comment by Licho1** [comment]
Are you eligible for planetwars?

**Comment by GoogleFrog** [comment]
Activation state should be sent to everyone. I want to show tabs and popups that give people the knowledge of how to be eligible.

**Comment by GoogleFrog** [comment]
Is the automated start time with communicated UTC in?

**Comment by Licho1** [comment]
It is done, server sends "PwStatus" 
```
    [Message(Origin.Server)]
    public class PwStatus
    {
        public PlanetWarsModes PlanetWarsMode {get; set; }
        public PlanetWarsModes? PlanetWarsNextMode { get; set; }
        public DateTime? PlanetWarsNextModeTime { get; set; }
        public int MinLevel { get; set; }
    }

```
