### ISSUE TITLE
Steam missing content crash

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2060]
I cannot run this replay with my steam install: http://zero-k.info/Battles/Detail/487380

Crashes:
- https://github.com/ZeroK-RTS/CrashReports/issues/3612
- https://github.com/ZeroK-RTS/CrashReports/issues/3613

It looks like content is missing.

**Comment by Licho1** [comment]
Why do you think something is missing? Looks like normal access violation to me.

**Comment by GoogleFrog** [comment]
[f=-000001] [unitdefs.lua] Error: Bad return table from: units/amphassault.lua
[f=-000001] [unitdefs.lua] Error: removed the "amphassault" entry from the "factoryamph" build menu
[f=-000001] Loading FeatureDefs_posts
[f=-000001] [defs.lua] Error: Failed to load featureDefs
[f=-000001] Error: 2, gamedata/defs.lua, [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/featureDefs.lua, error = 2, gamedata/featuredefs_post.lua, [string "gamedata/featuredefs_post.lua"]:62: attempt to call global 'CopyTable' (a nil value)


[f=-000001] [~ScopedOnceTimer][Game::LoadDefs (GameData)] 4509ms
[f=-000001] Warning: [Game::LoadGame][1] forced quit with exception "Defs-Parser: [string "gamedata/defs.lua"]:38: [string "gamedata/defs.lua"]:26: error = 2, gamedata/featureDefs.lua, error = 2, gamedata/featuredefs_post.lua, [string "gamedata/featuredefs_post.lua"]:62: attempt to call global 'CopyTable' (a nil value)

"

Files are missing or old.

**Comment by GoogleFrog** [comment]
Godde had the same issue https://pastebin.com/ubVDMVN6

"<Godde> Spring crashes when trying to launch an old replay"

**Comment by GoogleFrog** [comment]
I edited my ArchiveCache13.lua to remove the entry for old ZK versions and then chobby successfully ran the replays. Deleting the cache entirely on ZK update is a more reliable method.

**Comment by GoogleFrog** [comment]
Nevermind. The old ZK version doesn't seem to manage to download.

**Comment by GoogleFrog** [comment]
Maybe it still occurs https://github.com/ZeroK-RTS/CrashReports/issues/3724

I tried to run this replay http://zero-k.info/Battles/Detail/489963

**Comment by GoogleFrog** [comment]
I messed up zk v1.6.3.1 with a duplicate commit. I made v1.6.3.3 so this bug should in theory be triggered for replays with v1.6.3.2.

**Comment by GoogleFrog** [comment]
I updated my steam ZK and watched a game (http://zero-k.info/Battles/Detail/490729) so this issue appears to be fixed.
