### ISSUE TITLE
Democracy room toggle

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2066]
Players should be able to set the type of their regime when they host a room. The open battle ZKLS command should have a bool to toggle diplomacy (which will likely be a checkbox in the host UI) and it should be part of a battles status. Non-diplomatic rooms should have no polls and close if the host leaves.

**Comment by Licho1** [comment]
Why? Isn't that what is passworded room for?

**Comment by Anarchid** [comment]
Passworded rooms still allow polls.

**Comment by Licho1** [comment]
Well but they also have despotism, owner can endvote any poll ...
Polls mean nothing they are just "suggestions". Room owner can cancel anything. 

Likewise empty room closes itself... and if there are people and owner left, why closing it?

**Comment by GoogleFrog** [comment]
Ok so perhaps what I need to do is add an endvote button to the UI for room host. This sounds fine.

**Comment by Licho1** [comment]
Yes, just "cancel" poll should be enough. I think ingame this button already exists.
