### ISSUE TITLE
ZKL tooltips show up behind window

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#208]
For some reason tooltips are drawn behind, that is on a lower Z level, than other windows. I'm using win7, another win7 user has the same problem, while a Vista user doesn't.
![zkl tooltips](https://cloud.githubusercontent.com/assets/132906/4919311/30e58cdc-64f9-11e4-8b6d-bd1419828bd6.png)

**Comment by KingRaptor** [comment]
Still happens on Ubuntu 14.04 LTS

**Comment by xponen** [comment]
There are many Linux Window-manager and they interpret the Form-Property (eg: TopMost=true, ShowInTaskBar =false) differently. unlike MS Window which have 1 desktop. This is a problem.

Related case: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/328

To fix it involve trial-n-error (re-shuffling Form-Property, doing in alternate way such as "intercept/send Message" method) and recheck if it still work with multiple Window-Manage (including MS Window).

 It not possible for 1 dev!
Should make ZK/Infra compatible with Linux people instead, so they fix themselves (like you & me did).

**Comment by AppSynergy** [comment]
Any luck, xponen?

**Comment by db81** [comment]
Does this still happen?

**Comment by Skasi** [comment]
Didn't happen for me recently, but I didn't play a lot of ZK. Though still idling in ZKL every now and then.

**Comment by Licho1** [comment]
fixed long ago
