### ISSUE TITLE
Add an admin-UI editable DB key for access to the tournament room spawning UI

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2082]
We really need to be able to make tournament organizers who are not also moderators.

**Comment by DeinFreund** [comment]
Can this be a simple Boolean key for every user or are you planning an actual rights management system?

**Comment by sprunk** [comment]
Just a bool should be fine for now I think?

**Comment by DeinFreund** [comment]
Options are
 * Add a boolean key to each account that decides whether they can access the tournament UI
 * Add another rights level below Moderator that can access the tournament UI and do reversible moderation needed for tourneys (banning, muting, etc..).
 * Split right levels into permissions that can be given for each user. 
 * Only let moderators run tourneys. Consider removing all irreversible moderator actions from normal moderator permissions to make recruitment easier. SuperAdmin remains for those actions.

**Comment by Aquanim** [comment]
Bumping this for the purposes of Shaman's 3v3 tournament.
