### ISSUE TITLE
Obsolete avatars

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2085]
Infra-side part of https://github.com/ZeroK-RTS/Zero-K/issues/2828. Avatars are obsolete, see eg https://zero-k.info/users/lobbydetail/Orfelius who uses ![](https://zero-k.info/img/avatars/logareamine.png) while the unit's current pic is ![](https://zero-k.info/img/avatars/wolverine_mine.png)

There is code to update avatar pictures but since the units were renamed the updates froze. For example when Claw got its new model the `wolverine_mine.png` was correctly updated but that did nothing because people's avatars are still using the old name, `logareamine.png`.

Newly registered people also get the outdated pics because the list of choices hasn't been updated either.

- [x] wait until the gameside ticket https://github.com/ZeroK-RTS/Zero-K/issues/2828 is solved (else any changes cause people to have invalid avatars ingame)
- [x] update the `Avatars` DB table. It contains possible choices for new people - all from before the rename.
- [x] update pre-existing people's `Account.Avatar` field to the new names.
- [ ] insert into Avatars names valid for new units that were not preexisting

**Comment by Anarchid** [comment]
I made a "temporary" `UnitInternalRenames` table which contains the values from KR's renames CSV. 

Now the database stuff should be just a case of two ugly `UPDATE SomeTable SET Avatar = SELECT Replacement FROM UnitInternalRenames WHERE Original = SomeTable.Avatar` (or similar) queries.

**Comment by Anarchid** [comment]
On some further thought, things that were internally renamed before the mass internal rename, like `logareamine`, won't be affected either, and will require manual change.

**Comment by Anarchid** [comment]
I ran the replacement on test site's Avatars table.

These avatar keys remain unaffected:

https://pastebin.com/fGsCNMuD

**Comment by Licho1** [comment]
some people have custom avatars .. non unit but custom..

**Comment by sprunk** [comment]
Yes, the custom avatars are ok and should stay. This is only about old unit avatars.

**Comment by Anarchid** [comment]
I've now run the internal unit renames replacements on live Avatars and Accounts tables.
Additionally i've run substitutions for completely obsolete units (https://pastebin.com/uFwcdLT8) on Accounts.

I can't figure out how to do this for Avatars, however, because it results in duplicate keys. Maybe it's easier to recreate Avatars from scratch, which will also allow it to include units which only became available long after it was first populated.

**Comment by Anarchid** [comment]
I have contrived a scheme to update the Avatars table without completely regenerating it with fresh models.

```
UPDATE  [zero-k_test].[dbo].Avatars
SET AvatarName = (SELECT Replacement FROM [zero-k].[dbo].AvatarRenames WHERE Original = AvatarName)
WHERE AvatarName in 
	(SELECT min(AvatarName) as ToReplace 
	from [zero-k_test].[dbo].Avatars as a 
	INNER JOIN  [zero-k].[dbo].AvatarRenames AS an 
	ON an.Original = a.AvatarName 
	WHERE NOT Replacement IN (SELECT AvatarName FROM [zero-k_test].[dbo].Avatars)
	GROUP BY Replacement)
```
And then
```
DELETE From Avatars WHERE AvatarName IN (SELECT Original from AvatarReplacements)
```

It is truly horrifying. I'm not sober enough to do that yet, but give me half an hour.

**Comment by sprunk** [comment]
Thicket should be removed (copyright).

```sql
UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'chickend'
WHERE Avatar = 'thicket';
```
```sql
DELETE FROM [zero-k].[dbo].[Avatars]
WHERE AvatarName = 'thicket';
```

```
DEL C:\projekty\zero-k.info\www\img\Avatars\thicket.png
DEL C:\projekty\test.zero-k.info\www\img\Avatars\thicket.png
```

**Comment by Anarchid** [comment]
> UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'chickend'
WHERE Avatar = 'thicket';

```
(500 rows affected)
```

> DELETE FROM [zero-k].[dbo].[Avatars]
WHERE AvatarName = 'thicket';

```
(1 row affected)
```

>DEL C:\projekty\zero-k.info\www\img\Avatars\thicket.png
DEL C:\projekty\test.zero-k.info\www\img\Avatars\thicket.png

```
(2 files deleted)
```

Done.

**Comment by Anarchid** [comment]
How about this policy for what avatars should be possible to give:
- All units obtainable in multiplayer
- Including all chicken units (they can be obtained by capture)

Then these could be used for kudos unlocks:
- Campaign units with unique models(Nebula, Sunlance, etc)
- PW structures and units (if such happen to exist)
- Hidden/demonstrator units with unique models (Trisula, Morningstar)

These should never be pickable:
- Units without models (Terraform, Fake Radar Bloop etc)
- Technical purpose units with non-unique models (Empirical DPSer etc)

These lists can probably be generated with very little manual intervention:
1) Default roster: whatever wiki does, or traverse build chain recursively
2) Unused/campaign: just take the list from wiki  
3) PW: `SELECT` from planetwars config table?
4) Rejects: everything that is not in the above lists

**Comment by sprunk** [comment]
#1465 for a policy. This ticket is only about making sure that the current policy does not contain unused / outdated units.

**Comment by sprunk** [comment]
I think this ticket is done, but just to be sure:
```sql
SELECT Avatar, Count(AccountID) FROM [zero-k].[dbo].[Accounts]
GROUP BY Avatar;

SELECT AvatarName FROM [zero-k].[dbo].[Avatars];
```

**Comment by Anarchid** [comment]
```
SELECT Avatar, Count(AccountID) as Users FROM [zero-k].[dbo].[Accounts]
GROUP BY Avatar
ORDER BY Users DESC;
```

https://pastebin.com/ABxX6jvU

```
SELECT AvatarName FROM [zero-k].[dbo].[Avatars];
```

https://pastebin.com/0ubVVnQG

**Comment by sprunk** [comment]
Thanks. To run anytime:
```sql
UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'gunshipkrow'
WHERE Avatar = 'corcrw';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'commstrike'
WHERE Avatar = 'commstrike2_1';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'energyfusion'
WHERE Avatar = 'armfus';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'chicken_listener'
WHERE Avatar = 'chicken_listener_b';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'shieldassault'
WHERE Avatar = 'corthud';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'staticnuke'
WHERE Avatar = 'corsilo';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'striderdante'
WHERE Avatar = 'dante';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'vehcon'
WHERE Avatar = 'corned';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'turretaaflak'
WHERE Avatar = 'corflak';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'shieldscout'
WHERE Avatar = 'corclog';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'turretriot'
WHERE Avatar = 'armdeva';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'turretaaheavy'
WHERE Avatar = 'screamer';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'staticrearm'
WHERE Avatar = 'armasp';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'spideremp'
WHERE Avatar = 'arm_venom';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'jumpcon'
WHERE Avatar = 'corfast';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'commstrike'
WHERE Avatar = 'armadvcom';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'tankheavyarty'
WHERE Avatar = 'trem';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'energywind'
WHERE Avatar = 'armwin';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'cloakbomb'
WHERE Avatar = 'armtick';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'seismic'
WHERE Avatar = 'levelterra';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'commsupport'
WHERE Avatar = 'commsupport1_1';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'shipassault'
WHERE Avatar = 'corcrus';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'commstrike'
WHERE Avatar = 'commstrike1_1';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'chickend'
WHERE Avatar = 'thicket';
```

To run before a server restart (because ZKLS caches the list from `Avatars` and would still give them out, like what happened with the above which all have 1-2 entries):
```sql
DELETE FROM [zero-k].[dbo].[Avatars]
WHERE AvatarName = 'roostfac';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'roost'
WHERE Avatar = 'roostfac';

UPDATE [zero-k].[dbo].[Avatars]
SET AvatarName = 'hoverskirm'
WHERE AvatarName = 'hoverskirm2';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'hoverskirm'
WHERE Avatar = 'hoverskirm2';
```

**Comment by Anarchid** [comment]
I think it may make sense to run these in reverse? 

First running the latter to prevent new wrong avatars to be added after a restart happens

Then running the former to finally erase ones that got through

**Comment by sprunk** [comment]
The former only deals with things that already got removed from `Avatars` some time ago, but which had been done far from a restart so a bunch of `Accounts` still got those names. This query fixes those remnants.

As for the latter: the `Avatars` part can be done anytime, the `Accounts` part needs to be done after a restart.

**Comment by Anarchid** [comment]
I've ran the first query, so now only this remains to run after a restart:
```
UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'roost'
WHERE Avatar = 'roostfac';

UPDATE [zero-k].[dbo].[Accounts]
SET Avatar = 'hoverskirm'
WHERE Avatar = 'hoverskirm2';
```

**Comment by sprunk** [comment]
Apparently there was a(n accidental?) server restart.

**Comment by Anarchid** [comment]
```
(804 row(s) affected)

(453 row(s) affected)
```

**Comment by Anarchid** [comment]
The bug part is done, now the remaining stuff is the policy for selecting new avis.

**Comment by sprunk** [comment]
#1465 for new avi policy.
