### ISSUE TITLE
Wrapper replay reading error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2087]
[infolog_full.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/files/1831812/infolog_full.txt)

What does correct json look like and why does this not break for everyone else?

`Zero-K.exe Error: 0 : ChobbyLauncher.ChobbylaLocalListener error processing line ReadReplayInfo {"RelativePath":"demos\\20180321_012823_TinySkirmishRedux1_104.0.1-313-g3d4f772 maintenance.sdfz"} : System.Exception: Invalid json type PlasmaShared.CommandJsonSerializer : ReadReplayInfo
   at PlasmaShared.CommandJsonSerializer.DeserializeLine(String line)
   at ChobbyLauncher.ChobbylaLocalListener.<OnCommandReceived>d__19.MoveNext()
Zero-K.exe Error: 0 : ChobbyLauncher.ChobbylaLocalListener error processing line ReadReplayInfo {"RelativePath":"demos\\20180320_204749_Porky_Islands_104.0.1-313-g3d4f772 maintenance.sdfz"} : System.Exception: Invalid json type PlasmaShared.CommandJsonSerializer : ReadReplayInfo
   at PlasmaShared.CommandJsonSerializer.DeserializeLine(String line)
   at ChobbyLauncher.ChobbylaLocalListener.<OnCommandReceived>d__19.MoveNext()`

**Comment by Licho1** [comment]
old wrapper .. probably "hacker" user who disabled wrapper updates..

This message just says that wrapper does not know command ReadReplayInfo
