### ISSUE TITLE
Structure types table link

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2088]
https://docs.google.com/spreadsheets/d/1GP58BWQntszIJYyV_s9U6UIf-n0kwyucNoOX8woKDjg/edit?usp=sharing

**Comment by Licho1** [comment]
So many columns...

**Comment by GoogleFrog** [comment]
I've edited the condensed google doc table with some numbers that I think are reasonable. I can edit the DB later. Changes:
 - Economy and production structures have a rush cost of 60% their cost.
 - Wormhole and warpjammer structures have a rush cost of 50% their cost.
 - Defense structures have a rush cost of 40% their cost.
 - Generally increased turns to activate. Turns to reactivate is around 150% to 166% the time it takes to activate.
 - Messed with costs and energy upkeeps.

**Comment by GoogleFrog** [comment]
Backup:

StructureTypeID | Name | Description | Effects | UpkeepEnergy | TurnsToActivate | Cost | OwnerChangeDeletesThis | BattleDeletesThis | IsIngameEvacuable | TurnsToReactivate | MetalToRushActivation | RushActivationTime | Ingame notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | Power Generator Unit | Produces energy each turn | 50 energy/turn | 0 | 2 | 100 | FALSE | FALSE | TRUE | 5 | 60 | 1 |  
3 | Orbital Solar Array | Produces energy per turn; cannot be destroyed in ground battles | 100 energy/turn, immune to battle and bombers. | 0 | 3 | 275 | FALSE | FALSE | FALSE | 6 | 165 | 1 |  
4 | Planetary Geothermal Tap | Produces energy per turn | 250 energy/turn | 0 | 6 | 625 | FALSE | FALSE | TRUE | 10 | 375 | 1 |  
6 | Bomber Factory | Manufactures bombers each turn. Increases deployment capacity by 3. | 0.5 bombers/turn | 200 | 8 | 500 | FALSE | FALSE | TRUE | 12 | 300 | 1 |  
7 | Dropship Factory | Manufactures dropships. Increases deployment capacity by 3. | 0.5 dropships/turn | 150 | 8 | 400 | FALSE | FALSE | TRUE | 12 | 240 | 1 | change to pw_dropfac
9 | Ancient Artefacts | Capture to start generating victory points | not buildable, produces 1 VP per turn (some abilities removed) | 200 | 2 | 600 | FALSE | FALSE | FALSE | 5 | 360 | 1 |  
10 | Warp Gate | Produces single batch of warp cores that let you send ships anywhere | produces 10 warp cores, single use | 500 | 5 | 500 | FALSE | FALSE | TRUE | 8 | 500 | 1 |  
12 | Field Garrison | Reduces enemy influence gain | reduces IP gain by 10 | 150 | 3 | 200 | TRUE | FALSE | TRUE | 6 | 80 | 1 |  
13 | Interception Network | Defends planet against bombers | 10 bomber defense, immune to bombers | 150 | 5 | 250 | TRUE | FALSE | TRUE | 8 | 100 | 1 |  
15 | Planetary Defense Grid | Reduces enemy influence gain and protects against bombers | 16 bomber defense, reduces IP gain by 10, immune to bombers | 250 | 8 | 750 | TRUE | FALSE | TRUE | 12 | 300 | 1 |  
16 | Wormhole Generator | Links planet to neighbours - spreads influence per turn; hardened against bomber attack | 0.3 IP spread, creates out-arc, immune to bombers | 0 | 3 | 150 | FALSE | FALSE | TRUE | 6 | 75 | 0 |  
19 | Improved Wormhole | Links planet to neighbours - spreads influence per turn | 0.8 IP spread, creates out-arc | 100 | 3 | 250 | FALSE | FALSE | TRUE | 6 | 125 | 0 |  
597 | Warp Jammer | Prevents ships from warping to this planet | blocks warp core use | 125 | 5 | 300 | FALSE | FALSE | TRUE | 8 | 150 | 1 |  
600 | Wormhole Inhibitor | Blocks influence spread from neighboring enemy planets | blocks IP spread | 150 | 2 | 300 | FALSE | FALSE | TRUE | 5 | 150 | 1 |  
665 | Faction HQ | The seat of government, capture an opposing HQ to win | 25 bomber defense, reduces IP gain by 25, blocks warp core use, not buildable, immune to battle and bombers, win upon owner change, prevents IP decay below 11 | 0 | 0 | 1000 | FALSE | FALSE | FALSE | NULL | NULL | NULL |

**Comment by Licho1** [comment]
Those % changes can be done with equation .. you can do updater somethign set y=  x*3  where some condition

**Comment by GoogleFrog** [comment]
Edited.
