### ISSUE TITLE
Structure creation error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2091]
http://zero-k.info/Planetwars/BuildStructure?planetID=4334&structureTypeID=1

![image](https://user-images.githubusercontent.com/1318249/37860885-f79b8316-2f82-11e8-9358-8b530ccf2433.png)

I attempted to make a power generator on Throne.

**Comment by KingRaptor** [comment]
278c79b3ee24ebe0244e2fb76e56971121916c83 should fix it.
