### ISSUE TITLE
Remove energy and activation control from no-drain structures

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2093]
You should not be able to manually deactivate your HQ. Upon further thought I decided to extend this to all structures with zero upkeep. Perhaps 'always on' could be a DB tag but for the moment I think it makes sense to check for upkeep in the priority display and deactivationablility logic.

**Comment by KingRaptor** [comment]
e007c586455a8f5b5c8309b42f420fd895741388
