### ISSUE TITLE
Turn is not incrementing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2095]
This battle occurred: http://zero-k.info/Battles/Detail/492340

It is still turn 0:
![image](https://user-images.githubusercontent.com/1318249/37860953-040527e6-2f84-11e8-86e3-b09292888b8c.png)

**Comment by Licho1** [comment]
`

System.NullReferenceException: Object reference not set to an instance of an object. at ZkData.Account.ProduceDropships(Double count) at ZkData.Galaxy.ProcessProduction() at PlanetWarsTurnHandler.EndTurn(String mapName, List`1 extraData, ZkDataContext db, Nullable`1 winNum, List`1 players, StringBuilder text, SpringBattle sb, List`1 attackers, IPlanetwarsEventCreator eventCreator, ZkLobbyServer server) at ZeroKWeb.SpringieInterface.BattleResultHandler.ProcessPlanetWars(SpringBattleContext result, ZkLobbyServer server, SpringBattle sb, ZkDataContext db, StringBuilder text) at ZeroKWeb.SpringieInterface.BattleResultHandler.SubmitSpringBattleResult(SpringBattleContext result, ZkLobbyServer server) Data: {"ActualPlayers":[{"AllyNumber":0,"IsIngameReady":true,"IsSpectator":false,"IsVictoryTeam":true,"LoseTime":null,"IsIngame":false,"Name":"pwFed1"},{"AllyNumber":1,"IsIngameReady":true,"IsSpectator":false,"IsVictoryTeam":false,"LoseTime":3399,"IsIngame":false,"Name":"pwDyn2"}],"Duration":3401,"EngineBattleID":"57D3B55A1F6EE0D2B82C44FC4E5162E7","EngineVersion":"104.0.1-325-g9ad8116","GameEndedOk":true,"IngameStartTime":"2018-03-24T04:29:03.1574446Z","IpAddress":"37.59.49.101","IsCheating":false,"IsCrash":false,"IsHosting":true,"LobbyStartContext":{"FounderName":"PlanetWars #104","Map":"Fairyland v1.0","Mod":"Zero-K v1.6.3.5","Players":[{"LobbyID":398896,"AllyID":0,"Name":"pwFed1","IsSpectator":false,"ScriptPassword":"5355c3ee10f827c489033c07d99f51b6","Clan":null,"Faction":"Federation","PartyID":null},{"LobbyID":398895,"AllyID":1,"Name":"pwDyn2","IsSpectator":false,"ScriptPassword":"e643ddfd73c2de6cb21c4dc3f93245f2","Clan":null,"Faction":"Dynasty","PartyID":null}],"Bots":[],"Title":"PlanetWars 104","IsMission":false,"EngineVersion":"104.0.1-325-g9ad8116","IsMatchMakerGame":true,"Mode":2,"ModOptions":{"mutespec":"mute","attackingFaction":"Federation","attackingFactionName":"Federation","attackingFactionColor":"#55BB55","defendingFaction":"Mercenary","defendingFactionName":"Local militia","defendingFactionColor":"#CCCCCC","planet":"Loki","commanderTypes":"e30=","planetwarsStructures":"ewogIHB3X3dvcm1ob2xlID0gewogICAgdW5pdG5hbWUgPSAicHdfd29ybWhvbGUiLAogICAgY2FuQmVFdmFjdWF0ZWQgPSBUcnVlLAogICAgY2FuQmVEZXN0cm95ZWQgPSBUcnVlLAogICAgbmFtZSA9ICIgV29ybWhvbGUgR2VuZXJhdG9yICh1bm93bmVkKSIsCiAgICBkZXNjcmlwdGlvbiA9ICJMaW5rcyBwbGFuZXQgdG8gbmVpZ2hib3VycyAtIHNwcmVhZHMgaW5mbHVlbmNlIHBlciB0dXJuOyBoYXJkZW5lZCBhZ2FpbnN0IGJvbWJlciBhdHRhY2siLAogIH0KfQ=="},"UserParameters":{"pwFed1":{"LobbyID":"398896","CountryCode":"AU","faction":"Federation","clan":"","clanfull":"","level":"5","elo":"1100","icon":"1_0","avatar":"corbats","badges":"","admin":"0","room_boss":"0","can_spec_chat":"1","ignored":"","friends":"Histidine,Licho,Godde,Shadowfury333,Znack,Aquanim,Istaera","pwRank":"999","canAttackPwStructures":"1","pwInstructions":"WW91IGFyZSBhdHRhY2tpbmcgbmV1dHJhbCBwbGFuZXQgTG9raQpZb3UgaGF2ZSAgb2YgdGhlIDUwLjEgaW5mbHVlbmNlIG5lZWRlZCB0byBjb25xdWVyIHRoaXMgcGxhbmV0LgpJZiB5b3Ugd2luIHlvdSB3aWxsIGdhaW4gMzUuMCBpbmZsdWVuY2UgKDM1LjAgYmFzZSArIDAuMCBmcm9tIGRyb3BzaGlwcyAtIDAuMCBmcm9tIGRlZmVuc2UpCklmIHlvdSBhcmUgbG9zaW5nLCB0cnkgdG8ga2lsbCBlbmVteSBjb21tYW5kIGNlbnRlciBmb3IgNy4wIGluZmx1ZW5jZQpJZiB5b3UgYXJlIHdpbm5pbmcsIHByb3RlY3QgeW91ciBjb21tYW5kIGNlbnRlci4gSWYgeW91IGxvc2UgaXQsIHlvdSB3aWxsIG9ubHkgZ2V0IDE3LjUgaW5mbHVlbmNlIGhlcmUKWW91IGNhbiBhbHNvIGRlc3Ryb3kgZW5lbXkgUGxhbmV0V2FycyBzdHJ1Y3R1cmVzIHRvIGRpc2FibGUgdGhlbSBvbiB0aGUgc3RyYXRlZ2ljIG1hcAo=","commanders":"e30="},"pwDyn2":{"LobbyID":"398895","CountryCode":"AU","faction":"Dynasty","clan":"","clanfull":"","level":"5","elo":"1100","icon":"1_0","avatar":"armartic","badges":"","admin":"0","room_boss":"0","can_spec_chat":"1","ignored":"","friends":"Histidine,Licho,Godde,Shadowfury333,Znack,Aquanim,Istaera","pwRank":"999","pwInstructions":"WW91IGFyZSBkZWZlbmRpbmcgbmV1dHJhbCBwbGFuZXQgTG9raQpBdHRhY2tlcnMgaGF2ZSAgb2YgdGhlIDUwLjEgaW5mbHVlbmNlIG5lZWRlZCB0byBjb25xdWVyIHRoaXMgcGxhbmV0LgpJZiB5b3Ugd2luLCBhdHRhY2tlciB3aWxsIGdldCBub3RoaW5nLCBidXQgdGhleSBjYW4gZGlzYWJsZSB5b3VyIFBsYW5ldFdhcnMgc3RydWN0dXJlcyBieSBkZXN0cm95aW5nIHRoZW0gaGVyZS4KWW91IGNhbiBwcmV2ZW50IHN0cnVjdHVyZSBkZXN0cnVjdGlvbiBieSBldmFjdWF0aW9uIHRoZW0uCklmIHlvdSBsb3NlLCBGZWRlcmF0aW9uIHdpbGwgZ2FpbiAzNS4wIGluZmx1ZW5jZSAoMzUuMCBiYXNlICsgMC4wIGZyb20gZHJvcHNoaXBzIC0gMC4wIGZyb20gZGVmZW5zZSkKSWYgeW91IGFyZSBsb3NpbmcsIHRyeSB0byBraWxsIGVuZW15IGNvbW1hbmQgY2VudGVyLCB0aGV5IHdpbGwgb25seSBnYWluIDE3LjUgaW5mbHVlbmNlCklmIHlvdSBhcmUgd2lubmluZywgcHJvdGVjdCB5b3VyIGNvbW1hbmQgY2VudGVyLiBJZiB5b3Ugd2luIGJ1dCBsb3NlIGl0LCB0aGV5IHdpbGwgc3RpbGwgZ2V0IDcuMCBpbmZsdWVuY2UgaGVyZQpZb3Ugc2hvdWxkIGFsc28gcHJvdGVjdCBQbGFuZXRXYXJzIHN0cnVjdHVyZXMgYXMgaWYgdGhleSBkaWUgdGhleSBnZXQgZGlzYWJsZWQgb24gdGhlIHN0cmF0ZWdpYyBtYXAK","commanders":"e30="}},"BattleID":104},"MissionFrame":0,"MissionScore":null,"MissionVars":null,"MyPassword":null,"MyUserName":null,"OutputExtras":["stats,plist,pwFed1,pwDyn2","CHATLOG:pwFed1 I choose: Engineer!","CHATLOG:pwDyn2 I choose: Engineer!"],"Port":8455,"ReplayName":"c:\\projekty\\springie_spring\\demos-server\\20180324_052559_Fairyland v1_104.0.1-325-g9ad8116 maintenance.sdfz","StartTime":"2018-03-24T04:25:59.1518107Z","WasKilled":false}
--
1734 | 3/24/2018 5:14:33 AM | Error | WHR Casual
`

**Comment by Licho1** [comment]
Is it possible that player without faction played?

**Comment by GoogleFrog** [comment]
All players had faction. Look at the battle.

**Comment by KingRaptor** [comment]
Turns incrementing now. Reopen if any fresh stalling is observed
