### ISSUE TITLE
Treaty guarantee UI is confusing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2096]
The guarantee area shows the icon for the proposing faction and nothing for the accepting faction. It should use faction names for both. It should also give units. I think it should say the following:
 - Empire guarantee : `[entry box]` (metal paid to other party upon cancelling).
 - Other guarantee : `[entry box]` (metal paid to Empire upon cancelling).

![image](https://user-images.githubusercontent.com/1318249/37860989-acd36acc-2f84-11e8-8339-9cc961f624e2.png)

Also guarantee is misspelled.

**Comment by GoogleFrog** [comment]
I suppose it is fine in its completed form.

![image](https://user-images.githubusercontent.com/1318249/37861024-5e4a5626-2f85-11e8-9ac8-5644d46fcceb.png)

**Comment by DeinFreund** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/2110

**Comment by GoogleFrog** [comment]
Showing the image is good. The issue is that at one point only your own image is shown.
