### ISSUE TITLE
Treaty weirdness

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2099]
Empire made a treaty where Empire gives Dynasty 15 VP as a one time payment, guaranteed by Dynasty by 10 metal.

Dynasty did not receive or accept the treaty.
![image](https://user-images.githubusercontent.com/1318249/37861105-c0c0b1b4-2f86-11e8-9ddf-a49d90842a64.png)

If I click on the treaty it looks like it was already accepted.
![image](https://user-images.githubusercontent.com/1318249/37861111-d1ab8c60-2f86-11e8-9262-98cea97c21b5.png)

Is this because the treaty is just a treaty where Empire gives something to Dynasty? I think they should still require acceptance. More things:
 - Dynasty has not paid the 10 metal guarantee.
 - The effect should be an instant 15 VP transfer, which could not occur because nobody has VP.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/37861127-2db43908-2f87-11e8-86dd-21ab531e153c.png)
I cancelled the treaty. Dynasty seems to have lost no metal. Empire has gained 10 metal (I assume the guarantee)

![image](https://user-images.githubusercontent.com/1318249/37861129-453efc20-2f87-11e8-8af9-235f9a934983.png)

**Comment by KingRaptor** [comment]
[Current code](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/Controllers/FactionsController.cs#L238-L250) means the trade effects of a treaty can be implemented even if the guarantees can't actually be fulfilled (it doesn't check the latter until after doing the former).

**Comment by Licho1** [comment]
Check CanAccept, guarantee check is in place there.

**Comment by Licho1** [comment]
If the guarantee or trade fails, there is no db.SaveChanges() so nothing should happen..

**Comment by Licho1** [comment]
I believe its all ok, nothign was transferred anywhere
