### ISSUE TITLE
Invasion staging point effect does not work

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2101]
This treaty exists:
![image](https://user-images.githubusercontent.com/1318249/37861238-94792bec-2f89-11e8-8e36-cf6d749d2887.png)

Haldus is adjacent to Altaris
![image](https://user-images.githubusercontent.com/1318249/37861241-a3419c54-2f89-11e8-9377-8c8cbb474167.png)

Haldus cannot be attacked. Does the effect only work once a turn passes?

**Comment by Licho1** [comment]
It works for dropships, not direct attack

**Comment by GoogleFrog** [comment]
Shouldn't it work for dropships? That was my intention.

**Comment by GoogleFrog** [comment]
Invasion staging point is suggesting planets to attack:
![image](https://user-images.githubusercontent.com/1318249/37861448-f9310948-2f8d-11e8-9ea7-0572bf20c5f9.png)

Perhaps it just needed an economy tick to regenerate the attack targets?

**Comment by GoogleFrog** [comment]
ATTACK PLANET is visible on adjacent planets, but not adjacent to staging point planets.
![image](https://user-images.githubusercontent.com/1318249/37862163-8bec8592-2f9c-11e8-87a8-17cca3c0f0e6.png)

![image](https://user-images.githubusercontent.com/1318249/37862168-99288ee0-2f9c-11e8-8836-ffc32305e915.png)

![image](https://user-images.githubusercontent.com/1318249/37862174-a9ca9b9e-2f9c-11e8-8231-17fa455fc1f2.png)

**Comment by GoogleFrog** [comment]
Neither bombers or dropships use staging points correctly either.

**Comment by GoogleFrog** [comment]
The global dropship access treaty works correctly.

![image](https://user-images.githubusercontent.com/1318249/37872038-1129e0ee-304a-11e8-9482-ea50a5611c59.png)

![image](https://user-images.githubusercontent.com/1318249/37872040-1682ee6e-304a-11e8-9950-2340c9b94c12.png)

![image](https://user-images.githubusercontent.com/1318249/37872041-1c8909b0-304a-11e8-9c39-7833c94a3260.png)

**Comment by GoogleFrog** [comment]
The bug is that the invasion and bomber staging point effects seem to do nothing. These treaties should allow the recipient to attack (in the relevant way) using the specified benefactor planet. The global versions of these treaties function correctly.

**Comment by Licho1** [comment]
This is fixed now
