### ISSUE TITLE
Transfer planet interaction with invasion staging point.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2103]
Federation proposed to trade planets with Empire.
![image](https://user-images.githubusercontent.com/1318249/37861384-9da908b0-2f8c-11e8-8c1a-bfadf751ba2c.png)

Empire accepted. This treaty was not auto-cancelled
![image](https://user-images.githubusercontent.com/1318249/37861392-c03109dc-2f8c-11e8-8f4c-d71471b5fcd0.png)

The planet looks weird. Did this not transfer the planet? Was a battle or economy tick required?
![image](https://user-images.githubusercontent.com/1318249/37861402-de5f9978-2f8c-11e8-8129-f7cdf3bb043b.png)

**Comment by GoogleFrog** [comment]
I just claimed Altais and I have no idea why. This occured about 3 minutes before these state screenshots.
![image](https://user-images.githubusercontent.com/1318249/37862089-77edd0c4-2f9b-11e8-9114-604a373febb5.png)

![image](https://user-images.githubusercontent.com/1318249/37862098-93076d0c-2f9b-11e8-8702-9204638b6d5d.png)

**Comment by GoogleFrog** [comment]
Also, the staging point treaty still holds and it is giving dynasty attack options onto the Empire. A staging point should not be offerable if you do not own the planet. Losing the planet should count as being unable to fulfill the staging point part of the treaty.

![image](https://user-images.githubusercontent.com/1318249/37862117-e09d6eea-2f9b-11e8-8146-152d47c8d824.png)

Can I have clarification as to whether attack targets are supposed to update during turns? There are many things that could update them, such as battles ending or treaty changes.

**Comment by Licho1** [comment]
Ok transfer happens only after game turn end ..  so the first part was expected.
The other check is performed I assume it was the thing where options are selected on MM round start
