### ISSUE TITLE
Edit box focus cycle on register window is wrong

### ISSUE THREAD

**Issue by vladmihaisima** [ZeroK-RTS/Zero-K-Infrastructure#2106]
Open lobby, click Multiplayer, click Register tab, click Username edit box, press "tab", focus moves to "Password" edit box, press "tab", focus moves to "Username" edit box.

Expected behaviour: for last action focus moves to "Confirm" edit box.

A new user tried this without looking at the screen and got confused why he could not register.

**Comment by DeinFreund** [comment]
Lobby issues would be best tracked on the lobby's repository:
https://github.com/ZeroK-RTS/Chobby/

**Comment by vladmihaisima** [comment]
Thanks, miss-read the description "lobby" instead of "lobby launcher". Will fill there after checking is not reported already.
