### ISSUE TITLE
Can attack own planet

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2111]
http://zero-k.info/Battles/Detail/492458

>
46 minutes ago | **Dynasty attacked Dynasty** Maasym in B492458 and won. Dynasty gained 35 influence (100% from winning flawlessly of 35 base)
46 minutes ago | xmariox1990 gained 55 metal from battle B492458
46 minutes ago | maackey gained 55 metal from battle B492458
46 minutes ago | Dynasty metal gain improved by 10 because it is close to Faction HQ. B492458
46 minutes ago | Orfelius gained 55 metal from battle B492458
46 minutes ago | filch gained 55 metal from battle B492458
46 minutes ago | Dynasty metal gain improved by 10 because it is close to Faction HQ. B492458

Attacked own planet. Both teams got same metal since defender == attacker. Haven't yet checked what data was passed to ingame.

Another example http://zero-k.info/Battles/Detail/492471

**Comment by DeinFreund** [comment]
Could it be that the attack was started before Dynasty owned that planet?

**Comment by sprunk** [comment]
Possibly? Even so, it might carry some potential for bugs so it's good to be aware that it's possible in that case.

**Comment by Licho1** [comment]
Yeah it is possible "by design" atm..
