### ISSUE TITLE
Cannot find errors

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2115]
I don't see anything broken in these reports.

https://github.com/ZeroK-RTS/CrashReports/issues/3901
https://github.com/ZeroK-RTS/CrashReports/issues/3903
https://github.com/ZeroK-RTS/CrashReports/issues/3910
https://github.com/ZeroK-RTS/CrashReports/issues/3911

**Comment by sprunk** [comment]
Duplicate of #2051
