### ISSUE TITLE
Per turn treaty test

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2120]
![image](https://user-images.githubusercontent.com/1318249/37872285-2c297566-3050-11e8-8075-9f187aedc155.png)

![image](https://user-images.githubusercontent.com/1318249/37872288-36dbe8fe-3050-11e8-8be8-0e556dd1917b.png)

![image](https://user-images.githubusercontent.com/1318249/37872289-4338349a-3050-11e8-8f7c-3f78febc2824.png)

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/37872363-d1bafc74-3051-11e8-8042-b8d86b39af16.png)
![image](https://user-images.githubusercontent.com/1318249/37872364-d967d9c4-3051-11e8-87a3-1a1802ddf3bf.png)

A turn has passed. Here are the results
 - The metal, dropships, bombers and warp cores appear to have been transferred correctly. This part is simple.
 - None of the structures on any of the Dynasty works are disabled, even though they are reportedly at a deficit. Does energy production have a lag time of one turn?
 - Empire has disabled structures and only one structure which is powering up. Is there a lag on energy income?
 - VP transfer seems to have been done successfully, 
 - Empire now own Maasym even though the effect was set to 10 IP. This is possibly a UI bug and there should just be a treaty that says "Transfer planet X".

The treaty was not archived. Old treaties should exist in some disabled state so people can look at them.
![image](https://user-images.githubusercontent.com/1318249/37872424-59d71c54-3053-11e8-82e6-fb3225bb86ff.png)

![image](https://user-images.githubusercontent.com/1318249/37872426-63682eb6-3053-11e8-89ff-7188399ded3d.png)

**Comment by Licho1** [comment]
Trade transfer happens at the end of turn. So effects are lagged

**Comment by GoogleFrog** [comment]
Some effects lag more than others. Here is what happened:
 - Treaty created.
 - Turn happened. Metal, ships, cores, IP and VP were transfered.
 - Another turn happened. Some Dynasty structures were disabled. All Empire structures started coming online.

The energy effect lags behind the others. However, it is likely too complicated to fix and I don't see energy treaty being used for a single turn in any case.
