### ISSUE TITLE
Consider PW queue

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2123]
maackey does not like how they have to hover over the PW tab to make sure they can get into a battle. Personally I think a queue would be very complicated and we are better off going full async.

**Comment by Licho1** [comment]
It is full async isn't it? Or what do you mean?

**Comment by GoogleFrog** [comment]
Full async is a removal of the initiative system. Anyone can attack any time. The MM would send a list of the planets to defend (with their independent timeout timers) as well as a list of a few planets to attack.

**Comment by GoogleFrog** [comment]
Good version is here #2132.
