### ISSUE TITLE
Consider leet crew database tag for faction roles.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2127]
@DeinFreund is frustrated that random new players get to play important planetwars battles. They want some way for the head of the faction (along with other trusted members) to get the first choice regarding whether to join an attack or defense. Here is the implementation under consideration:
 - Add a DB tag (call it PriorityAttack?) for faction roles.
 - Apply it to the faction leader, the head of military, and the two further military roles (knights and squires).
 - Everyone with a role with this tag sees the attack and defense target exactly the same way as they do currently.
 - Everyone without this role has their attempts to join attack or defenses blocked for the first 15 seconds of every turn. Put a key in PwMatch command to indicate to those that they are not good enough to take the turn immediately. A further server command should be sent to indicate that they are allowed to join attacks.

The 15 delay should be configurable in the DB to allow for quick reconfiguration. The current behaviour should be implemented with a value of zero.

I am conflicted on this mechanic. It seems terrible to allow an inner circle to consistently deny participation to the rest of the faction. I think I would rather do full async initiative.

**Comment by DeinFreund** [comment]
How does full async stop players from randomly joining planned attacks and using up dropships or warp cores?

**Comment by Licho1** [comment]
I dislike this sort of elitism .. but it could gamefied - for example person who has more dropships in orbit can join/replace other person in there.. does not solve defenses though.

**Comment by DeinFreund** [comment]
The problem is that otherwise faction recruitment will be limited to "good" players while trying to keep others out of the faction. With this, the faction officials would have some kind of control over the in game actions of their faction.

**Comment by GoogleFrog** [comment]
Good version is here #2132.
