### ISSUE TITLE
Add max IP to global constants

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2134]
The maximum IP on a planet should be a constant so we can easily scale up PW if required. With more players it would make sense to make them take more time to conquer a planet. I prefer scaling the maximum IP on a planet to scaling the sources of IP gains because we're already at the first decimal place with IP and I don't want to go any deeper.

**Comment by DeinFreund** [comment]
See #2135. This is used in a lot of places though.
