### ISSUE TITLE
Site replays require login

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2152]
Currently watching site replays requires login because the message goes through ZKLS. It could go through the wrapper instead.

**Comment by Licho1** [comment]
Do you know how?

**Comment by sprunk** [comment]
ZKL used to be able to listen to `spring://bla` links, can this be reused?

**Comment by Licho1** [comment]
no it is highly unreliable, requires admin rights and is impossible to setup reliably on linux.
