### ISSUE TITLE
Update media section with steam/presskit material

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2154]
The media section consists mostly of outdated screenshots (one even has old llt model) and trailers. I'd like to replace it with what we are using for Steam and the presskit.

**Comment by GoogleFrog** [comment]
The primary task is to make the trailers in the presskit link to the trailers on the steam page. This is DF trailer (render7 version, lacks youtube upload) and the KR cinematic trailer.

**Comment by DeinFreund** [comment]
I already added the launch trailer youtube version (`pHQkctGTm_A`) before. It has higher quality and the youtube player should be better supported than the steam hax..

**Comment by sprunk** [comment]
Release happened.
