### ISSUE TITLE
Planetwars page keeps refreshing itself

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2171]
This page http://zero-k.info/Planetwars. It is infuriating as it refreshes every few seconds. Makes it impossible to look at.

**Comment by GoogleFrog** [comment]
Not 100% reproducible.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/239fd6f9e27049872b116bd5772e5826ba91aa90

**Comment by GoogleFrog** [comment]
Well, it is infuriating and makes me not keep the page open and then stop paying attention to PW/

**Comment by sprunk** [comment]
I'm just pointing to the commit to revert.

**Comment by Licho1** [comment]
so refresh or not?
people asked for it

**Comment by Licho1** [comment]
feel free to revert galaxy.cshtml

**Comment by DeinFreund** [comment]
30 seconds isn't every few seconds. I suppose your reload was faster?
