### ISSUE TITLE
Send PW information to specs as well

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2174]
The PW information panel that appears for attackers and defenders could also have a spectator version. This would let the spectators know the stakes in the battle and make it more interesting.

**Comment by GoogleFrog** [comment]
This should be implemented as a modoption that contains the string to print, if it should be implemented pre-steam at all. Another benefit is for watching replays or even casts of PW games as the text would set the situation.

**Comment by sprunk** [comment]
I think ideally the modoption would just be a bunch of values such as IP gain numbers and faction names, and adding text around them would be done ingame (because this allows stuff like fancy formatting and localisation). See https://github.com/ZeroK-RTS/Zero-K/issues/2877
