### ISSUE TITLE
Use standard ratio and resolution images on landing page

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2178]
I learnt from the stream review that the landing page images are crazy sizes. Here are the standardized images. https://github.com/ZeroK-RTS/Zero-K-Artwork/tree/ff44771259d6310dd1650c5f9cf6b4337289368d/Steam/screens

**Comment by DeinFreund** [comment]
I don't quite understand the issue. Filesize should be ok, so is aspect ratio a problem? Why would anyone care about the aspect ratio of our landing page images? Are you talking about the media section?

**Comment by GoogleFrog** [comment]
Randomly varying aspect ratio is ugly.
