### ISSUE TITLE
Unsable to set max lobby server players

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2179]
![image](https://user-images.githubusercontent.com/1318249/38535512-331f6672-3cc7-11e8-9ffc-6116c0650ada.png)

This occurs when I enter 17,14,12 or 0 and click Set. Also, the UI should say whether 0 means no limit or absolutely no-one can log on, as setting 0 with this uncertainty is terrifying.

**Comment by Licho1** [comment]
worksforme how were you lgoged in? I set it to 500.. needs superadmin level

**Comment by Licho1** [comment]
need better repro steps, worksforme
