### ISSUE TITLE
Wrapper crash when reporting bug

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2184]
It's unable to connect to github:
http://paste.springfiles.com/view/47e13630

**Comment by DeinFreund** [comment]
I found this https://stackoverflow.com/questions/4926676/mono-https-webrequest-fails-with-the-authentication-or-decryption-has-failed

But it seems there's not much we can directly do about it as it's caused by GithubClient on the .Result query in `CrashReportHelper.cs`:
```client.Issue.Create("ZeroK-RTS", "CrashReports", new NewIssue($"Spring {type} [{engine}] {bugReportTitle}") { Body = $"{bugReportDescription}\n\n```{infolog}```", }).Result;` ``

**Comment by Licho1** [comment]
this is now fixed
