### ISSUE TITLE
Make introductory stickies and set up steam forum

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2186]
If we're linking steam forum it should be made ready for release. Do we have steam forum administrators?

**Comment by KingRaptor** [comment]
- Added a "Help & Bugs" subforum; any others people want to think of? (Could probably remove the trading subforum)
- Added @Anarchid and @Licho1 as "officers", @DeinFreund as "moderator"; would've added @GoogleFrog but he's not listed [here](https://steamcommunity.com/games/334920/membersManage) for some reason
- Stickied [this](https://steamcommunity.com/app/334920/discussions/0/1696044439575619662/) thread

Do we want a link to zero-k.info in its own stickied thread?

**Comment by sprunk** [comment]
Looks done.
