### ISSUE TITLE
Set userCountLimted in community.json

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2190]
Currently, chobby has to connect and get Welcome to figure out whether to automatically. This makes little sense and makes the UI implementation either difficult or confusing. Currently players would see "choose a name for MP" and then have themselves automatically disconnected when they click connect. The connection could be opened secretly but that would be quite a bit of a change to the lobby code that I don't fully understand.

As I understand it, community.json is downloaded and updated on each wrapper launch. Put userCountLimted there so chobby can read whether to attempt an automatic connection.

**Comment by GoogleFrog** [comment]
@Licho1 ticket for you.

**Comment by Licho1** [comment]
So you want this distributed with steam? Cached locally?

**Comment by Licho1** [comment]
stuff has been added to community.json
