### ISSUE TITLE
Do absolutely everything that needs to be done for steam linux or I am unticking it

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2195]
I heard a lot of work and saw a lot of commits about steamOS and linux compatibility/issues but received nothing particularly concrete. We have a long rich history of rumors that linux works when in fact it doesn't work and, worse, someone knew that it didn't work. It is getting late so I am hitting the "Send for review" button tomorrow at local midnight. If there is a lack of agreement that linux works _in this very ticket_ then I am unticking linux. I also need the exact changes that should be applied to any store page info (most likely "Additional notes") and anything that needs writing in the tips for reviewers section.

![image](https://user-images.githubusercontent.com/1318249/38779630-5d7b19b6-410e-11e8-923c-25478eaed08e.png)

![image](https://user-images.githubusercontent.com/1318249/38779623-402becfa-410e-11e8-8c46-98849a471823.png)

**Comment by db81** [comment]
The state of linux is 32 bit doesn't work and steamos big picture view doesn't work (but desktop mode does). The idea was to send that for review, complain that big picture is broken for not detecting the spring window,  and either mention that we're not supporting 32 bit because look even ubuntu doesn't ship 32 bit desktop anymore, or just not say anything because I doubt they test on 32 bit.

**Comment by GoogleFrog** [comment]
Ok, but by the end of this ticket I want a definitive answer on what exact character string to enter into each text box on steamworks.

**Comment by db81** [comment]
Put "32 bit Linux systems are not supported" in the additional notes for sys requirements on linux+steamos.

**Comment by KingRaptor** [comment]
(reopen because this is the most convenient place to put it)

Valve staffer Pierre-Loup provides an explanation [here](https://steamcommunity.com/app/334920/discussions/0/3211505894135630208/#c1696045708654040658):

> The rootcause of the problem isn't the missing X attribute, it's statically linking with Xlib (and a bunch of other libraries, and exporting their symbols globally, which is rather ill-advised) rather than picking it up from the Steam Runtime. This prevents the overlay from being able to attach at all; this will prevent the game from working on SteamOS, but also break Steam Input and In-Home Streaming, as well as various other smaller Steam features that all depend on the overlay functioning properly. When you have a version where the overlay works well when started from Steam, that one should pass content review.
