### ISSUE TITLE
Accounts with no games played have 55% rank-up progress

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2201]
example http://zero-k.info/Users/LobbyDetail/ChanServ

**Comment by DeinFreund** [comment]
What do you expect to see? 54% is a small inaccuracy that can be easily fixed, it should be 50%. This is because the person is far from both up and down ranking, while 0% would imply an impending down rank.

**Comment by sprunk** [comment]
>0 at negative infinity and 1 at uprank

Sounds decent. Ideally the function would result in a similar increase in the progressbar for each game played by a newb.

**Comment by sprunk** [comment]
Seems to have been fixed at some point.
