### ISSUE TITLE
Planet page is broken with non-100 IP

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2206]
We set the IP max to 123. This occurred.

![image](https://user-images.githubusercontent.com/1318249/39054310-a0139aa2-44f4-11e8-8478-94e99484d82e.png)

**Comment by GoogleFrog** [comment]
Works now. Maybe infra was reloading. Still worrying.

**Comment by Licho1** [comment]
This message is spam protector. Anti DOS
