### ISSUE TITLE
Set artefact inactive image

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2209]
I made an infra stable with an inactive artefact image but the PW page does not seem to be able to find the image.

![image](https://user-images.githubusercontent.com/1318249/39079999-2d47c924-4569-11e8-94b0-50a0e2098161.png)

**Comment by Licho1** [comment]
it needs _inactive variant too

**Comment by sprunk** [comment]
407373363c4fdf2f955061af2fd8afc86dcff3e3
