### ISSUE TITLE
ZKL inconsistent error reporting

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#221]
ZKL present some errors to the user, through various GUI means.
Some errors are not reported visually, but are logged.
Some errors are logged to ZeroKLobbyErrors.txt
Some errors are logged to the "Lobby diagnostic log" (or "lobby log history", inconsistent gui too).

Without looking at source code, I have no idea what is the logic... what goes to log file? what goes to log window? Do I have to open both when diagnosing a problem?

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
