### ISSUE TITLE
Planetwars balance tweaks

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2211]
Consider making wormholes cost more metal to rush. Currently they can be rushed quite cheaply and, since they rush instantly, it would make sense for their rush time to be higher.

The round is ongoing so I plan to implement (simple only!) balance changes in the DB after it completes.

**Comment by Licho1** [comment]
yes it is also the structure that is going to be rushed most often.

**Comment by GoogleFrog** [comment]
Changed artifact activation to 600. Increased the rush cost of wormholes and basic defenses.
