### ISSUE TITLE
Don't make any infrastrucure stables.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2214]

**Comment by sprunk** [comment]
augeas is back on the menu boys

**Comment by DeinFreund** [comment]
On that note..

Before making any stables I'd like a Chobby dev to merge https://github.com/ZeroK-RTS/Chobby/pull/635
and then do some extensive testing with it. I'd also test https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/2395 while doing so.

There have been quite a few changes.

**Comment by GoogleFrog** [comment]
You can't expect other areas to do things. Such expectations cause deadlocks.
