### ISSUE TITLE
Site error on rating page

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2220]
https://zero-k.info/Charts/Ratings?RatingCategory=1&UserId=399233

**Comment by DeinFreund** [comment]
Caused by lack of PW ratings. I suggest fix via #2218

**Comment by sprunk** [comment]
Works now (the link is for Casual but I also tried PW and it was also fine).

**Comment by DeinFreund** [comment]
Did you try it after resetting PW ratings (from planetwarsadmin)?

**Comment by sprunk** [comment]
No but it won't be a problem because these are getting removed (see #2218 and the WIP removal branch).
