### ISSUE TITLE
Regular !balance (not MM) screwup

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2248]
http://zero-k.info/Battles/Detail/504642

**Comment by DeinFreund** [comment]
Directly after server reboot I think.

**Comment by sprunk** [comment]
Alright, though I think that's still a problem. Keep some cached ratings so they're available ASAP after reboot? Disallow game starts until the server fully wakes up?

**Comment by Licho1** [comment]
i think its fixed
