### ISSUE TITLE
Big teams balance takes multiple seconds

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2255]
I've seen it take over 6 seconds to execute.

**Comment by Licho1** [comment]
That is to be expected ... it's fairly optimized algorithm already.. unfortunately 32 people is 32 people .. there are four billion ways to split them...

**Comment by DeinFreund** [comment]
Yeah, but I thought the hard limit on the attempts was meant to keep it from torturing the server like this.

**Comment by sprunk** [comment]
@DeinFreund Can be closed? #2368

**Comment by DeinFreund** [comment]
Indeed, might not be optimal yet, but it's down to 32768 iterations for 16v16 :)
