### ISSUE TITLE
Launcher UI layout breaks on low window size

### ISSUE THREAD

**Issue by Palmer--** [ZeroK-RTS/Zero-K-Infrastructure#2273]
You can currently resize the launcher window and make really small. Making it too small breaks UI element layouts.

![broken layout](https://user-images.githubusercontent.com/11057262/39827477-50f66d14-53b8-11e8-92fe-77820b34b1eb.png)

**Comment by GoogleFrog** [comment]
I don't think we can limit the window size. I would recommend not making it this small. Is anything permanently broken by doing this?

**Comment by Palmer--** [comment]
I have not done any extensive testing so I can not answer that with any certainty. From what I know nothing gets irreversibly broken and everything is restored if you resize it back up.

**Comment by sprunk** [comment]
Belongs to chobby repo, moved: https://github.com/ZeroK-RTS/Chobby/issues/584
