### ISSUE TITLE
Battles are aborted before they begin

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2286]
The trace log reports `recieved GAMEOVER before STARTPLAYING!`

**Comment by DeinFreund** [comment]
I've seen this happen far from a server restart. It aborted when a random person quit pre-game, even though there were other people loaded in.

**Comment by Licho1** [comment]
Server tries to avoid reusing ports but it seems to be failing (probably wrong logic). This can cause lots of different issues.

**Comment by Histidine91** [comment]
https://github.com/ZeroK-RTS/Zero-K/commit/e64f2ad971e99fceb035f0102b303d4f76643aa1 fixes the pregame quit case.

**Comment by DeinFreund** [comment]
I have not experienced this for some time. Reopen if you see it.
