### ISSUE TITLE
Update NLog to 4.4.13 or newer to support Mono 5.10

### ISSUE THREAD

**Issue by snakefoot** [ZeroK-RTS/Zero-K-Infrastructure#2288]
See also https://github.com/ZeroK-RTS/Chobby/issues/590

**Comment by se5a** [comment]
More specifically, the chobby launcher project.

**Comment by KingRaptor** [comment]
Updated in ZeroK-RTS/Zero-K-Infrastructure/commit/0d31d4c002c70089be2b4454bef14d68f9bd69f0, thanks!

**Comment by Licho1** [comment]
I think underlying problem is in GA component which uses older nlog ..

**Comment by snakefoot** [comment]
@Licho1 As long one component in the dependency-chain requires an updated NLog, then the entire application will be required to run with updated NLog, thus it will work on Mono 5.10

But if this doesn't hold true, then I have also created an issue for the GA-SDK: https://github.com/GameAnalytics/GA-SDK-C-SHARP/issues/21
