### ISSUE TITLE
Zero-K from itch.io crashes

### ISSUE THREAD

**Issue by Histidine91** [ZeroK-RTS/Zero-K-Infrastructure#2301]
Infolog: https://pastebin.com/ETFDMaC3

Seems to crash when it tries to download and build a new package from rapid. I'm updating itch version with latest ZK/Chobby as a workaround.

**Comment by KingRaptor** [comment]
Searching for ```
`ins->opcode > MONO_CEE_LAST'``` seems to return mainly Xamarin-related results, e.g. [this issue](https://github.com/OmniSharp/omnisharp-roslyn/issues/993)

I might work around it by making it run `mono Zero-K.exe` instead of the custom Linux build, except for #2298.

**Comment by Anarchid** [comment]
Xamarin is pretty much the same as mono. 
Googling further found me this:

> Fixed in mono master/2017-10 branches.

The `mkbundle` needs to be run with a fresher mono - i was generating using my 17.10 install, which presumably doesn't have those fixes. I expect 18.04 to ship them.

**Comment by Licho1** [comment]
this should now be fixed (suspected ilmerge issue)
