### ISSUE TITLE
website: admin clan kick not red bordered

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#2303]
why is this visible to me when i am not in this clan? what happens when i push the link?

https://i.imgur.com/uIlwNDA.png

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/2a04550850b90656510076e6acbb735fe5e40fb6/ZeroKLobby/Resources/police.png?raw=true

**Comment by mojjj** [comment]
so, non-admins dont see this? i thought admin stuff is red-bordered...
