### ISSUE TITLE
MM - add reject button

### ISSUE THREAD

**Issue by Fealthas** [ZeroK-RTS/Zero-K-Infrastructure#2307]
Sometimes you are talking to someone, or watching a game, or something like that and you forget you were in queue. Since you can't reject your whole screen is frozen for 30s, and the other person has to wait this period too.

**Comment by Licho1** [comment]
Perhaps a way to minimize it?

**Comment by sprunk** [comment]
Moved to Chobby repo where it belongs https://github.com/ZeroK-RTS/Chobby/issues/599
