### ISSUE TITLE
!map does not prioritise exact match

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2313]
`!map DeltaSiegeDry`
>Changing map to DeltaSiegeDry Deluxe V3

The version by ID claims to work but actually also sets deluxe.

`!map 7304`
>Changing map to DeltaSiegeDry

DSD is supported so should be able to get picked.

**Comment by DeinFreund** [comment]
Feature

**Comment by DeinFreund** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/cbe8edd91ac53f4212969adf348d6f9639c844b1

**Comment by sprunk** [comment]
That explains why `!map DeltaSiegeDry` doesn't work but not `!map 7304`.

**Comment by Licho1** [comment]
This was changed because people were picking unfeatured maps. 
It should probably order matches by length too (shortest = more accurate match)

**Comment by sprunk** [comment]
Classic `DeltaSiegeDry` is supported so IMO should be pickable by exact match.

`!map 7304` has wrong text response (says it picks classic `DeltaSiegeDry` but actually sets `DeltaSiegeDry Deluxe V3`).

**Comment by GoogleFrog** [comment]
Could we make picking maps by their number unrestricted? Is this too obscure or not obscure enough?

**Comment by Licho1** [comment]
we could i think.
