### ISSUE TITLE
player from same ip got split into opposite team 

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#2314]
as in this battle

http://zero-k.info/Battles/Detail/544872

**Comment by GoogleFrog** [comment]
Same IP was never supposed to do anything to balance iirc.

**Comment by sprunk** [comment]
This is what parties and clans are for, using IP would be quite opaque.

**Comment by Sortale** [comment]
I was informed that this is undesirable due to spec cheating? players could see what the other team doing on computers at the same place?

**Comment by Licho1** [comment]
Same IP means basically same house. It could be a sister upstairs.
