### ISSUE TITLE
should players in the same party be group together in custom room? as in same clan

### ISSUE THREAD

**Issue by Sortale** [ZeroK-RTS/Zero-K-Infrastructure#2315]
I think people would assume this is how it should work

**Comment by GoogleFrog** [comment]
Parties and clans do not set hard limits on who can be on the same team. Keeping them together is preferred up to some level of worse balance.

**Comment by Sortale** [comment]
so is this how it's currently applied?

party would be more likely to be group into the same team in custom room?

I was mistaken then

**Comment by DeinFreund** [comment]
Yes, parties are treated like Clans. If somebody has both a party and a clan, the party takes preference.
