### ISSUE TITLE
Perhaps the top 50 list should be expanded

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#2317]
We have more players now. All the current top 50 players have at least blue ranks. Do we have enough players for a top 100 list?

**Comment by DeinFreund** [comment]
Give the game a few months for the player base to stabilize. I'd recommend to wait at least this long before adjusting ranks/ladders/icons...

**Comment by Anarchid** [comment]
Reopen when playercount stabilizes.
