### ISSUE TITLE
Request: Prevent start votes (but not host start) for private hosts for 5-10 seconds after the game ends

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#2324]
A sizable group of us are frustrated with people "start sniping" games before map can be changed or specafk can be issued. These start snipers sit and wait in open games for them to end and the moment they do end, they start the a start vote before anyone can even do anything to set up the next game.

While this can be remedied by endvote, it's still annoying to have to do it every time someone start snipes (and the frequency of these start snipes is at least once every 3 games it seems).

**Comment by DeinFreund** [comment]
We now have autohosts and with the new start system they'll no longer require users to initiate start votes

**Comment by ArchShaman** [comment]
Closing issue then.
