### ISSUE TITLE
Hosts with the wrong engine fail to start

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2325]
Start a game on a host using an unsupported engine version. You will see the "Connecting 10s" screen in Spring that indicates the host has timed out. The engine version I attempted to start was correctly uploaded to the ZK engines page.

I used WrapperLoopback.StartNewSpring to start the unsupported engine. Below is a screenshot StartNewSpring working on a host running the default engine.
![image](https://user-images.githubusercontent.com/1318249/41212285-216cf91e-6d80-11e8-9a89-2c61e03caf22.png)

**Comment by Histidine91** [comment]
- Issue does not occur with engine version 104.0.1-409-g07c2800 or earlier (although my local copy wouldn't start with 104.0.1-409 in particular
- Issue occurs with 104.0.1-527-gf2536df and 104.0.1-557-g1487736
- It claims it can't find the map, even though spring-dedicated launched with other maps finds them fine
- My guess is this change is responsible https://github.com/spring/spring/commit/19abcddcf3333f2d1702b5d84f2ace135ce85db9#diff-39ff9a80edf05d535fd23200c2edd80b; I'll ask hoko and/or gajop how to turn it off

**Comment by Histidine91** [comment]
Should be fixed in 104.0.1-567-gc484c10, as per commit https://github.com/spring/spring/commit/8c8589be822cc0793c6d08ceb7bec469786f1ad7

(I've uploaded that engine to server, but haven't been able to test yet)

**Comment by Histidine91** [comment]
Works on test server.
