### ISSUE TITLE
Clan shortcut can mess up a clan

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2344]
See https://zero-k.info/Forum/Thread/25747

 Seems to have been manually fixed by @Histidine91 so he should know what the issue was exactly. Apparently it was some sort of illegal character in filename?

**Comment by Histidine91** [comment]
Clan shortcut was something along the lines of `?????`, perhaps from entering non-ASCII characters when setting shortcut

**Comment by Arch-Shaman** [comment]
See: http://zero-k.info/Clans/Detail/494
