### ISSUE TITLE
Steam: Add unlock page to donation DLC + fix grammar

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#2357]
The current description for the DLCs (used for donations) do not tell donators where they can redeem their kudos. It also needs a grammar pass (sorry for grammar nazi-ing).

Current description:

> The Zero-K server runs off generous donations and we hope stay online for many years to come. Bronze supporters receive a bronze forum badge as well as enough kudos to unlock a clan icon or commander skin.

Suggested description:

> The Zero-K server runs off generous donations and we hope to stay online for many years to come. %rank% supporters receive a %rank% forum badge as well as %kudo_amount% kudos, which can be used to unlock commander cosmetics [here](http://www.zero-k.info/my/unlocklist).

Where %rank% is the rank name, %kudo_amount% is the amount of kudos earned by the donation amount.

**Comment by Histidine91** [comment]
Added the URL (although it doesn't work if you don't have an account yet, so I dunno if this is desirable presentation).

The descriptions already differ between the bronze, silver and gold DLCs; dunno if someone changed them after this issue report was made.
> Silver supporters receive a silver forum badge as well as enough kudos to unlock a clan icon and two commander skins

> Gold supporters receive a gold forum badge as well as enough kudos to unlock a clan icon and several commander skins

**Comment by Histidine91** [comment]
Considering this fixed, reopen if someone wants other tweaks
