### ISSUE TITLE
Game can be started with 1 player AFK and 1 not

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#2358]
See:
http://zero-k.info/Battles/Detail/578386
http://zero-k.info/Battles/Detail/578388

>[20:05] needforsleep: have a good one
>[21:39] chrislad42: yo
>[21:39] chrislad42: !start
>[21:39] Nightwatch 2 players balanced Normal to 2 teams ( 1=98%) : 2=2%)). 2 combinations checked, spent 0ms of CPU time
>[21:47] Nightwatch BATTLE DETAILS AND REPLAY ----> http://zero-k.info/Battles/Detail/578386 <-----
>[21:47] chrislad42: !start
>[21:47] Nightwatch 2 players balanced Normal to 2 teams ( 1=97%) : 2=3%)). 2 combinations checked, spent 0ms of CPU time
>[21:59] Nightwatch BATTLE DETAILS AND REPLAY ----> http://zero-k.info/Battles/Detail/578388 <-----

**Comment by ArchShaman** [comment]
This is not expected behavior. As you can see by the battle reports, chrislad42 is *not* the host, yet somehow manages to start the game with me being AFK.

**Comment by DeinFreund** [comment]
This is intended behaviour, see #1832 and #2007 as to why it hasn't been changed.
