### ISSUE TITLE
Allow downloaded maps in multiplayer

### ISSUE THREAD

**Issue by F4Tornado** [ZeroK-RTS/Zero-K-Infrastructure#2375]
I'm a map developer with a map I would like to play with other humans, and preventing non-featured maps from being played in multiplayer is preventing me from doing that. Also, removing this can help maps that otherwise would never get played, get off the ground. If you still want to prevent non-featured maps being played, please give map developers a way to get their maps supported, and tell them when they try to play the map, that the map can't be played in multiplayer instead of saying the map doesn't exist.

**Comment by F4Tornado** [comment]
OK, and you should still change the message so players know that they can't play the map in multiplayer, and that it needs to get featured to be able to play it in multiplayer.

**Comment by DeinFreund** [comment]
It's changed.

**Comment by F4Tornado** [comment]
Ikinz said that you would be a better person to ask to have it featured.

**Comment by sprunk** [comment]
Featuring maps probably involves Licho, GoogleFrog, or maybe Histidine because they need to be put in the Steam distribution which is not doable by regular devs.

**Comment by F4Tornado** [comment]
OK

**Comment by Histidine91** [comment]
Downloaded-by-Steam map list can't be changed, literally nobody is certain how it works. However, if we don't care about the new map being pre-downloaded and just want to make it accessible on autohosts that's not an immediate problem.

Maybe we could make hosts only require `supported` status rather than `featured`.

**Comment by F4Tornado** [comment]
Yeah, I don't care about it being pre-installed, I like that idea.
