### ISSUE TITLE
website - home page is 10 - 12 MB to download

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#238]
logged in: > 130 requests / ~ 12 MB download
as visitor: > 130 requests / ~ 10 MB download

The tiny pictures in the news are not thumbnails, they are full size images.
(slso, some images do not fully specify dimensions, which cause layout to update during download)

Some of the static files are served from googlecode svn web interface (slow and error prone as svn repo is no longer updated).

info about the consequences of a large number of resources per page:
http://latencytipoftheday.blogspot.it/2014/06/latencytipoftheday-most-page-loads.html
http://www.elasticsearch.org/blog/averages-can-dangerous-use-percentile/

**Comment by Licho1** [comment]
its now down to about 7mb. Lots of content appears to be scripts, most of them google scripts including stuff like video player. Not sure what to do next.

**Comment by dansan** [comment]
You should add "Expires" headers to /img or at least some of its subdirectories.
Also on  http://licho.eu/alba/Zero-K/

You can put all flags into one img and use CSS Image Sprites for faster page loading and lower server load (fewer requests).

**Comment by db81** [comment]
It's about 2 Mb logged in / 4 Mb logged out for me now. A good chunk of that is the background image. The background images go from 108 Kb to 3.8 Mb, and 4 of them are PNGs! Logged out, there's a youtube video that takes up about 1.5 Mb with youtube's scripts and a thumbnail.

Once we shrink the background images and maybe some of the pics shown when logged out, this can be closed IMO.
