### ISSUE TITLE
Forum parser: so *bold* and so foolish

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2387]
See https://zero-k.info/Forum/Post/188942#188942

Actual: asterisks are parsed as bold, not part of the link
Expected: asterisks should be parsed as part of the link, not bold

**Comment by sprunk** [comment]
a83f2f6d2ebdb59e3076ed18bedb6b4d79480220

**Comment by Histidine91** [comment]
(For test example, see [here](http://test.zero-k.info/Forum/Thread/24976?postID=182385))

I feel like removing Markdown support from the parser. It's only there as reverse compatibility for avatarwiki pages ported from Github; the few of these that remain should be manually fixed.

Formatting tags should be explicitly tags and not characters used in something else. BBCode fulfills this and Markdown does not.

**Comment by sprunk** [comment]
IMO:

>avatarwiki pages ported from Github; the few of these that remain should be ~~manually fixed~~ moved to mediawiki
