### ISSUE TITLE
!poll setoptions disabledunits=... didn't create a poll

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#2388]
I tried to disable some units in the new autohost room for regular teams. However, the command didn't create a poll but applied the modoption instantly. Does the command work differently if one is an administrator?

**Comment by sprunk** [comment]
It definitely shouldn't. Circumstances would be good to hear though (maybe other people were all afk or something).

**Comment by Sgathec** [comment]
There were about 20 players who weren't completely AFK. I'm pretty sure no poll was active when I tried to start mine.

**Comment by Licho1** [comment]
Permissions screw up @DeinFreund

**Comment by sprunk** [comment]
Read the title, this is explicitly about `!poll setoptions`.

**Comment by DeinFreund** [comment]
```[17:49] DeinSchlumpf: !setoptions noelo=1
[17:49] Nightwatch This command cannot be used on autohosts, either ask a moderator to change the settings or create your own host.
[17:49] DeinSchlumpf: !poll setoptions noelo=1
[17:49] Nightwatch This command cannot be used on autohosts, either ask a moderator to change the settings or create your own host.
[17:50] DeinSchlumpf: !poll title 123
[17:50] Nightwatch This command cannot be used on autohosts, either ask a moderator to change the settings or create your own host.
[17:50] DeinSchlumpf: !poll setoptions disabledunits=cloakraid
[17:50] Nightwatch This command cannot be used on autohosts, either ask a moderator to change the settings or create your own host.```
Seems completely fine for me. Of course an administrator can change the settings. Please don't do that on autohosts.

**Comment by DeinFreund** [comment]
I.e. there are no polls for these commands as they're not supposed to be used on autohosts, except for preset changes by admins. If players want to do things like zombies or disabled units I think it's fine to go to a different host. These settings can otherwise majorly screw up the experience on an official host.

**Comment by Sgathec** [comment]
Ok, but I requested a poll in the command.

**Comment by sprunk** [comment]
A poll was created but it was 1/1 by the virtue of you being the only one eligible to vote.

**Comment by Sgathec** [comment]
Maybe a confirmation query should show up then.

**Comment by sprunk** [comment]
Ideally `!poll` would just fail in such cases (even for an admin).

**Comment by Sgathec** [comment]
Yes, I was going to suggest blocking it altogether.

**Comment by DeinFreund** [comment]
So. Block polls for admin commands?

**Comment by Sgathec** [comment]
Yes, but I think autohosts with rigid rules that can't be changed are not ideal.
