### ISSUE TITLE
Rooms don't limit the number of players to the stated maximum

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#2397]
Screenshot coming later probably.

EDIT: Just for the record, it's an autohost. I may have seen this happen to other rooms as well. I've seen @DeinFreund claim that rooms fail to respect their player maximums.
![image](https://user-images.githubusercontent.com/2042701/44546857-ec98db00-a721-11e8-997e-b24610e27a14.png)

**Comment by DeinFreund** [comment]
This is already fixed on master.
