### ISSUE TITLE
ZK Renegade Trophy Handout

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#2401]
Results:
Gold: DeinFreund/Firepluk/izirayd
Silver: 4hundred/rav/Manu12
Bronze: Anarchid (Subbing for Zenfur) / Hokomoko (subbed for [ffc]) /Dr0ppy

Can I request the Gold trophy be named "Supreme Renegade" ? 
Battles:
http://zero-k.info/Battles/Detail/604990
http://zero-k.info/Battles/Detail/604969

**Comment by sprunk** [comment]
Being called `Gold Cup` is not subject to change for technical reasons.

**Comment by ArchShaman** [comment]
Sad, but acceptable.

**Comment by sprunk** [comment]
I've prepared a query. I chose coins because the tourney had a fairly relaxed ruleset (3v3, less strict map pool) compared to the old regular tourneys and because that lets me get away with putting `Supreme Renegade` as the gold description.

```sql
INSERT INTO [zero-k].[dbo].[AccountBattleAwards]
( [AccountID],[SpringBattleID],[AwardKey],[AwardDescription])
VALUES
( 60947,604969,'bronzecoin','Bronze Coin, August 2018 3v3 Renegade Tourney'),
(169779,604969,'bronzecoin','Bronze Coin, August 2018 3v3 Renegade Tourney'),
(306898,604969,'bronzecoin','Bronze Coin, August 2018 3v3 Renegade Tourney'),
( 77714,604990,'silvercoin','Silver Coin, August 2018 3v3 Renegade Tourney'),
(196461,604990,'silvercoin','Silver Coin, August 2018 3v3 Renegade Tourney'),
(434947,604990,'silvercoin','Silver Coin, August 2018 3v3 Renegade Tourney'),
(185685,604990,  'goldcoin',  'Gold Coin, August 2018 3v3 Supreme Renegade'),
(232028,604990,  'goldcoin',  'Gold Coin, August 2018 3v3 Supreme Renegade'),
(352411,604990,  'goldcoin',  'Gold Coin, August 2018 3v3 Supreme Renegade');
```

**Comment by Anarchid** [comment]
`(9 row(s) affected)`

**Comment by ArchShaman** [comment]
Thanks!
