### ISSUE TITLE
Autohosts can be defaced

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2404]
See https://github.com/ZeroK-RTS/Chobby/issues/639

>Anyone is able to change the map on an autohost to any map. Please change the map automatically to a random featured or supported map after the room has been empty for 30 seconds if the current one is not already. Smurfs could still prevent that so the map could be changed anyway if there's no user activity after 5 minutes. Autohosts and Matchmaker battles are probably more official than other rooms.

IMO disallow unsupported maps, if people start bawwing over yet another speedmetal variante it can get supported.

**Comment by Sgathec** [comment]
Well, disallowing would affect all new maps. Getting someone to support such a map takes some time.
