### ISSUE TITLE
#zk is spamming its channel topic 

### ISSUE THREAD

**Issue by The-Yak** [ZeroK-RTS/Zero-K-Infrastructure#2408]
Channel topic should only be displayed once, as opposed to this:

![zkspam](https://user-images.githubusercontent.com/1368663/45445719-dc6c7f80-b67f-11e8-926a-3aba364d17d0.png)

**Comment by DeinFreund** [comment]
This is a chobby issue. It also gets worse because Chobby often loses connection and has to reconnect to the server. It writes the channel topic into chat on every reconnect.

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/issues/640
