### ISSUE TITLE
MapsController - fail to cache map details, fail to display

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#242]
If an exception is generated while trying to read map details (GetMapDetailData), results will not be cached. This cause a lot of exceptions to be generated in #zkerror... but this is useless because:
- map authors do not know why details are not displayed
- nobody is looking in #zkerror

Errors look like that:

Nightwatch 11/21/2014 1:14:35 PM Warning Failed to get map metedata Complete_Annihilation_test-6680.metadata.xml.gz:System.InvalidOperationException: There is an error in XML document (2, 2). ---> System.InvalidOperationException: <Mod xmlns=''> was not expected.

Maybe the map authors are at fault (I don't know), but ZK infra should at least display errors where people can see them.

I wanted to test more, but the search map function is broken.

**Comment by Orfelius** [comment]
There is no way that the map creator is at fault as they have no influence over map indexing other than making the map compressed in non solid form.
