### ISSUE TITLE
How are maps added to be included in the Steam package?

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2449]

**Comment by Licho1** [comment]
Featuring them for MM will work

**Comment by sprunk** [comment]
Maps included in the steam package are those which fulfil at least one of the following criteria:
 * are support level MatchMaker
 * are manually listed in [campaignMaps.txt](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/77c875474d51c3028c5714dfe9e822c0d9ad10ff/Autoregistrator/Resources/campaignMaps.txt) (for campaign maps)
 * are support level at least Supported and are in top 50 of popularity as measured by player minutes in the last 6 months

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/77c875474d51c3028c5714dfe9e822c0d9ad10ff/AutoRegistrator/SteamDepotGenerator.cs#L231
