### ISSUE TITLE
Wiki out of sync with recent unit changes

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K-Infrastructure#2453]
I just noticed that the wiki is out of sync with the recent unit changes. I noticed that the Kodachi https://zero-k.info/Forum/Thread/27278?Search=&User=&grorder=&grdesc=False&grpage=1 rebalance was newer than is page on the wiki http://zero-k.info/mediawiki/index.php?title=Kodachi&action=history doing a discussion on the Zero-k chat.

If you can push the current stats of all the units that have been changed recently to the wiki, go ahead. Otherwise, I will update them manually.

**Comment by Histidine91** [comment]
Bot-updated, thanks for report!
