### ISSUE TITLE
Allow votekicking people from global chat.

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#2462]
**  evil things were going on

12:51 Pyrostasis: Chesti? your turn
12:52 Firepluk: he kicked u to make u whine, Pyrostasis
12:52 Firepluk: dats fun
12:52 Chesti: I would kick Pyrostasis too. I already read enough  about him
12:52 Pyrostasis: lol
12:52 Pyrostasis: ok I leave this game
12:52 snoke: !kick Pyrostasis
12:52 Firepluk: very kickable
12:52 snoke: !y
12:52 snoke: !y
12:52 snoke: !y
12:52 Firepluk: !y
12:52 Chesti: !y
12:52 Tommyknocker joined
12:52 Pyrostasis left
12:52 Chesti: why kick    does   not work? github report?
12:52 Firepluk: develobs failed
12:52 Firepluk: again

**Comment by DeinFreund** [comment]
Global chat moderation is not meant to work by vote. There's already the option to block and report a user which should fulfill your needs. Why do you think it should be possible to call votes in global chat?
