### ISSUE TITLE
Account rename: can't change case

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2463]
When changing somebody's username to the same name but with different case (eg. `somebody` → `SomeBody`) there's an error that there's a conflict with the same user (eg. can't rename to `SomeBody` because it would conflict with `somebody`).

It can be worked around by temporarily renaming away to something different (eg. `somebody_temp`) and renaming is an admin-only tool so this is low priority.

**Comment by Licho1** [comment]
Is hits caused by DB collation for the given field? It can be set to ignore case.
