### ISSUE TITLE
Clan update failures, invalid headers, headers not showing up, and other bugs.

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#247]
- If one changes the name of the clan or creates a clan (maybe), the information will not update in zkl. Several clans are currently broken because of this.

Example:
http://zero-k.info/Clans/Detail/821
http://zero-k.info/Clans/Detail/819
http://zero-k.info/Clans/Detail/826

However, it seems that in-game the clan registers, but without an associated clan pic. ZKL fails altogether to register the clan.
- If one changes the clan header  to ''Çü fücks wıth yöür héadér. Hæ hæ hæ'' zero-k lobby displays a ''invalid UTF-8 encoding'' header -- this was working before the update to the game list.
- Clan headers do not show up sometimes or sometimes its blanked out for some reason or another. Has nothing to do with invalid UTF-8 header. Example clan: http://zero-k.info/Clans/Detail/820
- Clans cannot be created (apparently) due to this bug. See: http://zero-k.info/Forum/Thread/10123

**Comment by Licho1** [comment]
fixed
