### ISSUE TITLE
Abort MM games with afk people on start

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2473]
See #2432 and https://github.com/ZeroK-RTS/Zero-K/issues/3294

**Comment by DeinFreund** [comment]
Games are aborted and players banned.

**Comment by GoogleFrog** [comment]
What kind of ban? I don't know whether infra ban works correctly.

**Comment by DeinFreund** [comment]
Just infra ban for now. If we can confirm that it's still broken I guess this could be signalized to the lobby somehow.
