### ISSUE TITLE
Make a map ladder

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2477]
Maps should compete with each other, ladder style, when they are offered as options in the PauseMapStart autohost system. The map that wins the vote should be treated as having won a match against the other map(s). I wouldn't use the data to inform map choices, for now.

**Comment by Licho1** [comment]
Maps will only care about their e-peen, might reduce diversity.

**Comment by DeinFreund** [comment]
WHR will be too complex and unintuitive for maps to understand.

**Comment by GoogleFrog** [comment]
> Maps will only care about their e-peen, might reduce diversity.
> I wouldn't use the data to inform map choices, for now.
That is why I would only use the data to learn the rating.

**Comment by Anarchid** [comment]
Pretty sure map skill is in fact static, so naked elo should be plainly sufficient.

**Comment by DeinFreund** [comment]
Classic elo doesn't stay constant. Bayesian elo would be the right tool.
Coincidentally, WHR with constant time is equivalent to Bayesian elo.
