### ISSUE TITLE
website - inconsistent error reporting

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#248]
Some exceptions are fed to #zkerror ... but without context (http request url, parameters, referer), so we can't debug it.

Some exceptions are displayed by the webserver, but website users should not get an "Application error" page, exceptions should be caught, logged and user should get a ZK themed error page or a redirection to a page that include the error message.

There are other log files on the server, but they are not available to people who are focusing on solving existing problems. This is a source of difficulty for those who are trying to explain to users why stuff fail and prevent them from leaving in anger because nobody cares.

**Comment by Licho1** [comment]
All in ZK trace logs now. Some prefixes added where needed.
