### ISSUE TITLE
Chat antispam is too strict

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2484]
CatLady complained. Also, in the past day or so I noticed that some of my messages were dropped and thought it was just a network issue.

**Comment by DeinFreund** [comment]
Agreed. I'll have it only kick in after multiple messages.

**Comment by DeinFreund** [comment]
Please report if there are any other complaints

**Comment by GoogleFrog** [comment]
Changed.
