### ISSUE TITLE
Make a nice lobby poll interface

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2486]
BattlePoll is sent when a poll starts or the number of votes in an ongoing poll changes. If a poll is active when a player joins the room then BattlePoll should be sent to that player. It has the following parameters.
- Topic - The text to display regarding the vote.
- Options - A list of vote options. Each option has an Id and a number of Votes. They may additionally have a Name and a Url.
- VoteToWin - The number of votes required to complete the poll.
- YesNoVote - Whether the vote is a boolean yes/no vote, with 'no' resulting in no action.
- MapSelection - Whether the vote is a vote to select a map.
- Url (optional) - A url relevant to the vote. This should be the map url when the vote is a YesNoVote MapSelection vote.

BattlePollOutcome is sent when a poll resolves. It has the following parameters.
- Message - The message to display regarding the resolution of the poll.
- YesNoVote - Whether the poll was a YesNoVote.
- Success - Whether the poll succeeded.

The server should still send battle chat messages regarding the initiation and resolution of polls. Poll update chat messages are not required.

**Comment by DeinFreund** [comment]
I'm gonna leave in all chat messages for now, unless in-game voting also uses the BattlePoll messages.

**Comment by GoogleFrog** [comment]
More changes to BattlePoll are required.
- Add MapName, which is null or a string containing the name of map poll in a boolean poll.
- Remove the URL from the Topic of the boolean map selection poll.
- Capitalise the first letter of the Topic of a game start poll.
- Add NotifyPoll which is true if the poll is to start the game.

**Comment by DeinFreund** [comment]
Reopen if there are other changes to be made
