### ISSUE TITLE
Auto-starting directly after a map vote results in people without the map.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2487]
Lobbies send whether they have the map, so the server could pay attention to this and delay the autostart vote for a few seconds.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/52907129-08370580-32af-11e9-8b4c-6fe9dc05042a.png)

**Comment by DeinFreund** [comment]
Delaying the vote sounds troublesome, could other votes be called then? If yes, that's certainly going to lead to more map votes.

I could think of adding a delay on start. After a successful start vote (or the host calling !start), if someone is missing the map, the server will call them out and start a 10 second countdown, after which the game starts.

**Comment by sprunk** [comment]
Countdown on start is how rooms work in many other games (eg Star/War Craft) and would solve #1754 so I like the idea.
