### ISSUE TITLE
Manage absent hosted games similarly to autohosts

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2492]
As I talked about in chat, there are three types of teams room
- Autohost.
- Absent hosted battle.
- Present hosted battle.

The incentives of game seeding seem to favour hosting a room over joining an autohost, at least for a significant enough number of players. By itself, this may be fine, as a game with a host can be streamlined with the use of their boss commands. The issue is that hosted battles tend to turn into battles where the host is absent, and then persist for some time. This effectively wastes the work put into improving autohosts.

This idea is to apply some of the autohost management to hosted games with an absent host. On game end, if each of the following is satisfied then a PauseMapStart should be executed.
- The host is AFK or not in the battleroom.
- The battle type is FFA, Coop, Teams or 1v1.
- The battle is not passworded.

I don't know what else distinguishes hosted rooms and autohosts, but additional changes should probably not be applied.

**Comment by Licho1** [comment]
As I see it its just one type of host in two states. 
Eitehr the owner is there or not.

**Comment by DeinFreund** [comment]
I fear this would blur the lines between autohosts and user administered hosts. It's not obvious that the owner appearing/disappearing changes the normal host to an effective autohost. One might think they're on an autohost that suddenly changes when the host comes back.

**Comment by GoogleFrog** [comment]
So? That confusion is far better than the current situation.

**Comment by DeinFreund** [comment]
While we're at this, should polls possibly be disabled entirely while the owner is there?

In #2066 we concluded that !endvote suffices, but it's not visible in the UI so most owners aren't aware of it. Also autohosts now exist as dedicated democratic rooms.
