### ISSUE TITLE
Apparently people are being put into 1v1 MM without consent

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2494]
![image](https://user-images.githubusercontent.com/1318249/53069475-38d9a200-3530-11e9-8f14-e558a7ec3b92.png)

**Comment by DeinFreund** [comment]
I didn't change anything about the the normal MM operation.

**Comment by DeinFreund** [comment]
From what I understand he actually joined 1v1 queue but didn't have to accept the match. One way that could happen is by accepting the quickplay teams invitation. As it's effectively a mm invitation, it'll also make 1v1 games if you happen to be in that queue. I could disable quickplay for those already queued if you think that'd be better.

**Comment by GoogleFrog** [comment]
Why would we think that is what happened? There should be server logs.
