### ISSUE TITLE
Make a more readible rating history page

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2496]
![image](https://user-images.githubusercontent.com/1318249/53680141-02b7d180-3d2b-11e9-9c72-8cfbb9760a03.png)

Nobody knows what a maximum or a 75% confidence interval is. My guess is that almost everyone wants players to have a single history, and for that history to be the ladder rank number. This could be a toggle, or could even automatically toggle when you add more than one player (as the noise is really an issue when you have more than one player).

**Comment by DeinFreund** [comment]
75% confidence interval is the ladder rating, but it's also rather confusing as it'll have drops/noise in it solely due to inactivity (when the player didn't actually get worse). The maximum likelihood rating is much more true to the history. A toggle would definitely make sense.

**Comment by sprunk** [comment]
There's just a single line per player now.
