### ISSUE TITLE
Coop autohosts is on the old ZK version

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2499]

**Comment by DeinFreund** [comment]
Are you asking for an automatic update on autohosts? For now admins have to
run !game zk:stable manually after an update.

**Comment by Licho1** [comment]
What? Why is that
autohosts in the old days were auto doing this. So you made new permanent hosts that dont update?

**Comment by GoogleFrog** [comment]
This ticket is simply asking for someone to do `!game` in the host. Automatic updating would be good too, Licho you are correct that the new automatic hosts were made to not do this.

I did `!game` in the host, so the ticket is fixed. It was still on the old version. The ticket exists because `!game` cannot be done in running hosts.
