### ISSUE TITLE
Game Analytics is broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2501]
As far as we can tell, no messages are being reported from new wrappers.

**Comment by Licho1** [comment]
Simplest fix would be to revert to older GA library. I was having issues with that thing. What is the issue with nlog @Histidine91  ?

**Comment by DeinFreund** [comment]
It might also be a simple misuse of the new API. The changes actually didn't compile after the update, because some API members had been removed.

**Comment by Histidine91** [comment]
Issue with NLog was that older version used by GA makes wrapper hang on Linux: https://github.com/ZeroK-RTS/Chobby/issues/590

**Comment by Licho1** [comment]
Perhaps we could go back + disable GA on linux? This will prevent nlog load and should not freeze..
Btw the freezing was never replicated on my ubuntu

**Comment by Histidine91** [comment]
GA reverted in 0479cb75550d1d7fa16475017e275b9df7341d37, works now.
