### ISSUE TITLE
MM team win rate is broken

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2502]
Archangel sent his standard complaints about the four people in the teams MM not being turned into a game. I tested why the game wasn't created and found that it was the win chance bound, as reducing the bound to 0.0015 created a game. The ingame predict chance was 17%, which is higher than the bound was set (15%).

![image](https://user-images.githubusercontent.com/1318249/53786424-cfb24f80-3f6f-11e9-9347-775f57d83125.png)

Note that Archangel and Nuzzy were a party. I've reduced the win chance to 0.1.

**Comment by GoogleFrog** [comment]
![image](https://user-images.githubusercontent.com/1318249/53787348-b3fc7880-3f72-11e9-8ca1-b96767148008.png)

http://zero-k.info/Battles/Detail/691784

**Comment by DeinFreund** [comment]
That's because the MM uses decayed rating, not true rating. The in-game predictor uses true rating. If MM were to use true rating it'd rate first time players as 1500 instead of 1100 and make their life terrible.
