### ISSUE TITLE
User activity change generates errors

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2503]
https://github.com/ZeroK-RTS/CrashReports/issues/20313

Revert it if no work is going to be done soon.

**Comment by DeinFreund** [comment]
In that report, spring crashed. Then the connection was closed and the wrapper was thus unable to send messages.

**Comment by GoogleFrog** [comment]
Errors occur here too https://github.com/ZeroK-RTS/CrashReports/issues/20519

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/CrashReports/issues/20447
https://github.com/ZeroK-RTS/CrashReports/issues/20460
https://github.com/ZeroK-RTS/CrashReports/issues/20490

**Comment by DeinFreund** [comment]
bd2f0b4ce802e6752782899c709b90553080b817
