### ISSUE TITLE
Steam deploy blocked by broken test site

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2520]
When I tried to rebuild steam on the test site, I was greeted with a mission error.
![image](https://user-images.githubusercontent.com/1318249/54439429-e5542000-478c-11e9-9b23-9b4d5d4556a1.png)

**Comment by Histidine91** [comment]
I haven't uploaded the fixed missions to test server. I think updating test DB from live will fix it.

**Comment by GoogleFrog** [comment]
Shall I just trust that stable deploy works?

**Comment by sprunk** [comment]
blind fix best fix

**Comment by Licho1** [comment]
don't trust, lets do copy from live to test DB first and test deploy

**Comment by GoogleFrog** [comment]
Seemed to work.
