### ISSUE TITLE
Add " daily unique players + spectators" to user charts

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2531]
There is a weird disparity between our analytics. The " daily unique players" chart shows a big drop over the most recent weekend, yet other analytics show little change (thus far). It is important to find the source of the disparity asap. Adding more to the user charts analytics would test how well infra is working.

**Comment by DeinFreund** [comment]
It might be best to count all logged in users, but unfortunately logins aren't all stored in db right now. @Licho1  do you think it would be feasible to do this or would it require too much resources? How big is the AccountUserID table currently?
