### ISSUE TITLE
Prefer different map in subsequent matchmaking

### ISSUE THREAD

**Issue by darloth** [ZeroK-RTS/Zero-K-Infrastructure#2556]
as a nice-to-have feature request: 
Track the last map that each player has played on via matchmaking queues.

When a match is made, attempt to avoid those maps for all involved players.  If this produces a pool of zero maps, fall back to current (presumed random) implementation.

Most valuable for 1v1 where it could add considerable extra variety, but I don't see a problem also applying it to teams or co-op queues, even though they'll fallback more often.

**Comment by dvr333** [comment]
Related to #2554 and #2555

**Comment by sprunk** [comment]
Duplicate of #2555
