### ISSUE TITLE
spring talker - extreme programmer creativity

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#256]
./Shared/LobbyClient/Talker.cs
./Springie/Springie/spring/Talker.cs

I'm not sure why the duplication... but anyway:
Look at how this is closing the connection (with autohost):

    public void Close()
    {
      close = true;
      var udclose = new UdpClient();
      udclose.Send(new byte[2] { 0, (byte)SpringEventType.SERVER_QUIT }, 1, "127.0.0.1", loopbackPort);
      thread.Join(1000);
    }

Yup... thats how ZK does it. It opens a new socket to send packets to "wake up" the receiver. It sends a packet of 2 bytes... but only send 1 of them. What happens next...?

All the code that handle spring start/shutdown is so meaningless I don't know where to start.

**Comment by Licho1** [comment]
Create proper non-event to in close, atm its meant to send SERVER_QUIT instead it trigger SERVER_START (which isnt listened to)
