### ISSUE TITLE
Apparently `!hostsay bla` starts a poll if the caller has no host rights

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2564]

**Comment by DeinFreund** [comment]
That's intentional. If you don't have the right to run a command you might still be able to vote on it. This is needed for cheats.

**Comment by sprunk** [comment]
Allowing people to vote on enabling cheats on autohosts sounds somewhat bad. Even if we want to do that the command is `!cheats` though.

**Comment by DeinFreund** [comment]
Not for globallos, nocost and other synced commands.
