### ISSUE TITLE
Mute should probably disable `!hostsay`

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2565]
Related #2562

**Comment by DeinFreund** [comment]
Mute should be distinct from blocking commands.

**Comment by sprunk** [comment]
I had assumed `!hostsay` is only used for saying stuff (which makes it not a "real" command) but the info from #2564 (i.e. that it's used also for synced ingame stuff) makes me believe this issue is strictly a subset of #2562.
