### ISSUE TITLE
Anniversary tourney results

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2566]
1st place:  Manu12, Sparkles (http://zero-k.info/Battles/Detail/714672 )
2nd place: DeinFreund, hokomoko ( http://zero-k.info/Battles/Detail/714672 )
3rd place: raaar, NorthChileanG (http://zero-k.info/Battles/Detail/714650 )

**Comment by sprunk** [comment]
@Anarchid 
```sql
INSERT INTO [zero-k].[dbo].[AccountBattleAwards]
( [AccountID],[SpringBattleID],[AwardKey],[AwardDescription])
VALUES
(196461,714672,  'gold',  'Gold Cup, April 2019 2v2 Tourney'),
(440239,714672,  'gold',  'Gold Cup, April 2019 2v2 Tourney'),
(169779,714672,'silver','Silver Cup, April 2019 2v2 Tourney'),
(232028,714672,'silver','Silver Cup, April 2019 2v2 Tourney'),
(142479,714650,'bronze','Bronze Cup, April 2019 2v2 Tourney'),
(257950,714650,'bronze','Bronze Cup, April 2019 2v2 Tourney');
```

**Comment by ashdnazg** [comment]
We should really make award assigning interface for admins

**Comment by Arch-Shaman** [comment]
Agreed. Would make this easier.

On Apr 27, 2019 14:38, "Eshed" <notifications@github.com> wrote:

We should really make award assigning interface for admins

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2566#issuecomment-487321874>,
or mute the thread

**Comment by Anarchid** [comment]
```
(6 row(s) affected)
```
