### ISSUE TITLE
Steam update doesn't clear out rapid folder

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#2567]
The rapid folder might still have some old `versions.gz` that contains wrong `zk:stable` versions. Steam update only adds the new files, but doesn't delete older ones if they have different names.

**Comment by Licho1** [comment]
But steam should redeploy vesions.gz so how it can be a problem?

**Comment by sprunk** [comment]
Maybe steam depot builder fetches wrong `versions.gz`?

**Comment by DeinFreund** [comment]
Steam deploys the correct versions.gz but doesn't clean out the rapid folder. So if there exists some old versions.gz in `rapid/foobar/versions.gz` then steam will only add it's on versions.gz to `rapid/repos.springrts.com/zk/versions.gz`. Now spring will scan the rapid folder and find the old versions.gz first and uses that, completely missing the second one provided by steam.

**Comment by Licho1** [comment]
But both steam and zk put it to same location. So what went wrong?

**Comment by DeinFreund** [comment]
In this case they didn't. It just takes the person one run of spring
pr-downloader or some old zklobby/other lobby to screw up their rapid
folder possibly permanently. I wouldn't trust the folder to stay clean by
itself.

**Comment by Licho1** [comment]
We cannot account for people's action outside of our scope, like PR-downloader operations.
We can however have standardized "fix" - "clean up steam folder".

Closing this as this is gamers fault (running third party apps, not cleaning folder)
