### ISSUE TITLE
Block certain usernames from signing up

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2568]
Moved from https://github.com/ZeroK-RTS/Chobby/issues/681

----
There's no reason at all for names like "glownigger" or "JuanIsAFaggot" to be allowed to sign up to begin with. These usernames tend to just be renamed by admins anyways, so why not enforce this unwritten rule with signups?

A valid exception for whatever reason could be approved by moderators (via rename) instead of default allowing anything goes.

**Comment by Licho1** [comment]
It's impossible to auto filter for profanities automatically. They could replace single letter or write them in Finnish.

**Comment by Arch-Shaman** [comment]
Filtering out things like faggot,nigger, n1gg3r, etc would at least show
some precedent that it is not okay. Right now they make these usernames
thinking they can get away with it and get greeted by
Alcur: racism will not be tolerated. You will be renamed.

Almost instantly. Simple filtering would act as a deterrent to the lightly
commited. I'm not looking for 100% filtration. I think we can get by with
the most glaring ones being filtered out. For instance, just the English
variants along with some basic numerisation.

**Comment by sprunk** [comment]
>Right now they make these usernames thinking they can get away with it

As far as I can tell most of those are people getting their Steam name as ZKLS nick. Steam seems lenient.

**Comment by Anarchid** [comment]
> Filtering out things like faggot,nigger, n1gg3r, etc would at least show
some precedent that it is not okay

I don't see the problem with doing this manually once in a while by watching the recent signups. Anything automatic without a human in the loop will likely misfire in most annoying ways.

**Comment by sprunk** [comment]
Looks like the consensus is "not needed".

**Comment by Sgathec** [comment]
What if the infra only showed a list of suspicious user names?
