### ISSUE TITLE
incompatible MS-PL and GPL licenses

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#257]
ionic zip => MS-PL
sharpcompress => MS-PL

BTW, I'm not sure why zk need 2 zip libraries... but thats beyond the point. Licenses are incompatible.

**Comment by Licho1** [comment]
Replace libs with http://icsharpcode.github.io/SharpZipLib/

**Comment by KingRaptor** [comment]
Ionic Zip (DotNetZip) replaced with .NET's own API (System.IO.Compression).

Sharpcompress on GitHub has MIT License (see [readme.md](https://github.com/adamhathcock/sharpcompress/blob/master/README.md), [license.txt](https://github.com/adamhathcock/sharpcompress/blob/master/LICENSE.txt)). Not sure why it's listed as MS-PL on CodePlex, but I figure we can use it safely regardless.

So we just need to make ZKL include the MIT (and GPL) license texts and then we can close this issue.

**Comment by KingRaptor** [comment]
...and it does that now (#788), so closing issue. Thanks for reporting~
