### ISSUE TITLE
Make the ladder show "calculating..." after server restart

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2570]
Set some global flag on server start that makes the ladder page say something along the lines of "recalculating ratings due to server restart, check back in ~15 minutes", then reset that flag when recalculating is done.

See also https://zero-k.info/Forum/Thread/28293

**Comment by DeinFreund** [comment]
Not necessary, the new fake elo is all db based anyway.

**Comment by sprunk** [comment]
Is the real elo visible anywhere? What about the ratings chart? If fake elo is used everywhere then this can be closed.
