### ISSUE TITLE
Check if setting room playerlimits on custom hosts works

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2571]
Somebody wanted to seed a small teams room but apparently the count is stuck at starting value. Could also be a chobby visual issue.

>\<CatLady\> why in seven hells i can't decrease max players limit to 8
\<CatLady\> or anything lower than 16
\<CatLady\> in custom lobby room
\<CatLady\> I specifically set it to 8, and it started with 16... doesn't seem to want to go up or down

**Comment by sprunk** [comment]
>\<CatLady\> stuck at 16 player,s ignoring settings from start of game. Maybe cause i selected "teams"? will try with "custom"
>\<CatLady\> works in custom

This seems to be by design (`NotAutoHost`) https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/7ee28b56c62b95e68711e9ce170e8f07e27ff3c4/ZkLobbyServer/autohost/Commands/CmdMaxPlayers.cs#L12

**Comment by DeinFreund** [comment]
NotAutohost means it should be available on anything that's not an autohost. This includes a self-made teams host.

```
[23:46] Nightwatch Max players changed to 16
[23:46] DeinSchlumpf: !type teams
[23:46] Nightwatch Game type changed to Teams
[23:46] DeinSchlumpf: !maxplayers 10
[23:46] Nightwatch Max players changed to 10
```
I can not reproduce the issue though.
