### ISSUE TITLE
Investigate weirdness in itch installer T&C

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2580]
PorkchopToday at 12:59
Found a random thing to fix on the itch.io installer. The terms and conditions section includes a large copypasted block that probably shouldn't have been included with gems like 
You should also get your employer (if you work as a programmer) or your
school, if any, to sign a "copyright disclaimer" for the program, if
necessary.  Here is a sample; alter the names:

  Yoyodyne, Inc., hereby disclaims all copyright interest in the program
  `Gnomovision' (which makes passes at compilers) written by James Hacker.

  <signature of Ty Coon>, 1 April 1989
  Ty Coon, President of Vice
Though I'm probably the first person to scroll that far in

**Comment by Porkch0p** [comment]
Appears to be here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyInstaller/legal.txt

**Comment by sprunk** [comment]
That text seems to be a part of the GPL itself: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
It's the third section, after the preamble and the actual T&C.

**Comment by Porkch0p** [comment]
Okay, I guess it's a false alarm then. Just looked at how others are using it and Audacity's T&C section includes it there verbatim as well. Was just jarring as a user to see those boilerplate references by scrolling down to the bottom. Might as well close this

**Comment by sprunk** [comment]
Yea, the GPL is pretty obnoxious but we're stuck with it.
