### ISSUE TITLE
Chinese filepath error

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2586]
https://github.com/ZeroK-RTS/CrashReports/issues/22402
https://github.com/ZeroK-RTS/CrashReports/issues/22403

**Comment by Anarchid** [comment]
![image](https://user-images.githubusercontent.com/3822768/59358768-d3572e80-8d35-11e9-9e73-7a04e05036a5.png)

Not a filepath. Network error, nothing to do on our side.
