### ISSUE TITLE
2v2 tournament results

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2600]
https://challonge.com/zk3v3july_19

Since this was 2v2 RR to salvage the tournament, I don't know which game gets what.

**Comment by sprunk** [comment]
I think the gold and silver cup should go to the game in the ultimate round between the overall #1 and #2 teams and the bronze cup should go the game in the penulimate round between the overall #3 and #4 teams. I don't know which battles those are though (looks like the room titles had no `[T]`? At least I can't find them that way). If somebody finds those battles I can prepare the SQL statements.

**Comment by oriongame** [comment]
https://zero-k.info/Forum/Thread/28549

**Comment by sprunk** [comment]
```sql
INSERT INTO [zero-k].[dbo].[AccountBattleAwards]
( [AccountID],[SpringBattleID],[AwardKey],[AwardDescription])
VALUES
(395492, 745429, 'bronze', 'Bronze Coin, July 2019 2v2 Tourney'),
(438381, 745429, 'bronze', 'Bronze Coin, July 2019 2v2 Tourney'),
( 77714, 745406, 'silver', 'Silver Coin, July 2019 2v2 Tourney'),
(391881, 745406, 'silver', 'Silver Coin, July 2019 2v2 Tourney'),
( 86744, 745406,   'gold',   'Gold Coin, July 2019 2v2 Tourney'),
(352411, 745406,   'gold',   'Gold Coin, July 2019 2v2 Tourney');
```

**Comment by Anarchid** [comment]
(6 row(s) affected)
