### ISSUE TITLE
Set engine error on test server

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2601]
I tried to set a new engine to be default. Live server appears to work.

![image](https://user-images.githubusercontent.com/1318249/61346543-8a4a4b00-a89c-11e9-95e8-5391de58bf4c.png)

**Comment by Licho1** [comment]
The failing function is call to steam API:
https://api.steampowered.com/ISteamApps/GetAppBuilds/v001/?appid={steamAppID}&key={webApiKey}
I think it's just a temporary valve thing. Retrying helps.
