### ISSUE TITLE
Ranks Committed A Todd Howard

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2617]
![image](https://user-images.githubusercontent.com/48730089/64300605-500f3880-cf32-11e9-8567-fe995f438b16.png)
![image](https://user-images.githubusercontent.com/48730089/64300610-543b5600-cf32-11e9-9ec9-821a101664a4.png)

I don't remember ranks working like this..

**Comment by sprunk** [comment]
fb4a1978932ee86942f0389c403c9ab6b1f71810
