### ISSUE TITLE
Predict is weird

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2632]
![image](https://user-images.githubusercontent.com/48730089/66712730-e581c180-ed55-11e9-8b3d-1b4b372f2218.png)

**Comment by Arch-Shaman** [comment]
In game, the teams are actually very different than what they are and have different win rates once the game starts.

**Comment by danfireman** [comment]
This game seemed to suffer from particularly bad balancing:
 https://zero-k.info/Battles/Detail/781497

Pre-game !predict indicated a ~35% chance of the losing team winning, but it still picked this combination.

**Comment by sprunk** [comment]
see https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2631#issuecomment-541396227
