### ISSUE TITLE
Bringing back whr malus (at least for newbies)

### ISSUE THREAD

**Issue by sprangg** [ZeroK-RTS/Zero-K-Infrastructure#2635]
Current malus-less balance results in the team with more newbies usually losing, because 1500 whr is generally too high a rating to represent newbie performance.

Here's one example where team 1 has no chance because of this http://zero-k.info/Battles/Detail/782722

Reiterating Licho's points for malus's existence:
- new players balance, to give them higher than expected 0.00001% chance of winning in initial games
- inactive players rank, to make them sink over time and incentivize regular activity
- returning players balance, to make them more likely to win as a reward

In my opinion the only major reason is the first one, to give newbies and their teams a chance. The rest is minor and optional.

**Comment by DeinFreund** [comment]
Malus doesn't actually make you more likely to win. That's only the case if players with malus are stacked on one side of the team. I'd rather see a change to the balancer that actually increases the win chance for players with malus.

**Comment by Licho1** [comment]
Ofc it does increase your win chance. Does lowering your individual Elo not increase your win chance?

**Comment by DeinFreund** [comment]
It doesn't directly. Malus will cancel out if you have the same number of newbies on each team, which is useful, but means that they now have the same win chance. Malus does serve the purpose of giving teams with disproportionate amount of newbies an advantage.

**Comment by Licho1** [comment]
No, malus also works on individual level statistically..
You can never "guarantee" win if you don't know exact skill stats and can predict how players will play.. its just impossible. And statistically it works unless you get into obscure situations .. like too many people with skill numbers that dont reflect actual skills at all in every game.

**Comment by sprangg** [comment]
The perfect situation would be to balance the complete newbies into different teams, so they would have a 50% chance.

But if many of them are put into the same team, like the example game linked in my post, then the newbies need some seriously good players to compensate. Malus would help with this.

**Comment by sprangg** [comment]
Shaman had an idea about players rating themselves the first time they join:

What is your experience level?
- Brand new to RTS -> sets initial malus to 600.
- Some familiarity with RTS -> malus 400
- Very experienced with RTS -> no malus

Would be neat, but 400 for every newbie, like it was for years, would be a good first step.

**Comment by GoogleFrog** [comment]
> It doesn't directly. Malus will cancel out if you have the same number of newbies on each team, which is useful, but means that they now have the same win chance.

@DeinFreund why are you seeming to claim that each side will have an equal number of newbies in most games? If remove the case where each side has no newbies then having an odd number of newbies in the game is clearly going to happen more than 50% of the time!

> Malus does serve the purpose of giving teams with disproportionate amount of newbies an advantage.

This is the goal. Newbies need an advantage so that they win their first few games more often. This is more fun and reduces the chance that their team will take out their frustration on the new player. Just do something simple. Give new players 400 casual game balance malus and reduce it by 40 for each Team game with at least four players that they complete.

**Comment by Licho1** [comment]
Malus is a must. We can always go to ELO if its too complicated or something.

**Comment by DeinFreund** [comment]
Why is it a must? I retroactively calculated the average newbie rating and it is squarely at 1500 (because the prior is set at day 0). The median is a bit lower (1480 iirc), but that's nowhere close to 1100. 

So you want unbalanced games. How unbalanced and how should it relate to level? Level 1 get 70% win chance? 60%? 55%? When does it stop?

**Comment by Licho1** [comment]
I have better way to calculate it.
Look at newbies first games. I want to see win rate >= 50% on non-smurf accounts.

If the win rate is lower we are not hitting target. 
What matter is a subjective experience.

**Comment by DeinFreund** [comment]
Nvm, I don't want to introduce a complicated system that will only make players unhappy. If you want to have a simple malus implementation, please merge #2767. That will balance by ladderelo which starts at 1100 and moves up to the true rating in the first ~15 wins.

**Comment by Licho1** [comment]
Oh I dont want to introduce another system either i just wanted to look at stats. If its really true that newbs are fine at 1500 then they are fine at 1500.  (Its possible if it drifted upwards meanwhile, it wasnt that way when malus was introduced)

**Comment by DeinFreund** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/e1e2ec3e14025a09e5f60e7a61ecca34195d5959
Player starts at -400 malus, goes to 1500 over first 5 levels.
