### ISSUE TITLE
Forum post edit history disobeys {redaction}

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2659]
See eg. https://zero-k.info/PostHistory/Index/202809

**Comment by DeinFreund** [comment]
We can't stop people from writing down usernames..

**Comment by sprunk** [comment]
I think this ticket was more about the inconsistency where you can "look up" a redacted nick for edited posts but not for posts that weren't ever edited (even if edits didn't touch the nick part).

**Comment by DeinFreund** [comment]
I dont understand why we have to hide username references at all. Why is @X redacted but any other mention of X isn't.

**Comment by sprunk** [comment]
We don't but since the account is deleted it should just not me made into a link. Plaintext `Skasi` and not `[austria][purple][policeman][clanpic]<color=dynasty><a href=/users/detail/7198>Skasi</a></color>`

**Comment by DeinFreund** [comment]
Oh I misunderstood. Where does it show the link with flag and such? If I click before/after I only see redacted.

**Comment by sprunk** [comment]
I think you understood correctly the first time?

Raw post: `@Sprung x @Skasi`

Post as it currently appears on the forum thread: `[poland][lobster][cop][sprunk]<a href=/users/detail/4665><color=sprung>Sprung</color></a> x {redacted}`

Post as it would ideally appear on the forum thread: `[poland][lobster][cop][sprunk]<a href=/users/detail/4665><color=sprung>Sprung</color></a> x Skasi`

**Comment by DeinFreund** [comment]
So no more {REDACTED} anywhere
