### ISSUE TITLE
Resign randomly not working

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#266]
Seen two games in a row where !resign would not call a vote to resign, despite being called by active players. Will report other games as they come up.

Affected battles: 
http://zero-k.info/Battles/Detail/311572 - http://pastebin.com/66jghShd
http://zero-k.info/Battles/Detail/311580 - http://pastebin.com/MCqpNwtj

**Comment by Licho1** [comment]
Hmm in that case please report again if it happens. What exactly did it say? There is no "unknown command" string in the springie so its probably from somewhere else...

**Comment by let4be** [comment]
Shit still happen:
[21:49]  * Springiee1 Sorry, I don't know command 'resign'
