### ISSUE TITLE
Steam Download Banner (Web)

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K-Infrastructure#2666]
Minor suggestion for the website - It's pretty easy to add a steam-hosted download banner, which might liven up the Downloads page compared to the "Click Here to get it on steam".

![image](https://user-images.githubusercontent.com/49832728/79936984-ff434600-8415-11ea-9100-d916940ea70d.png)

`<iframe src="http://store.steampowered.com/widget/334920/" width="552" height="190" frameborder="0"></iframe>`

**Comment by Licho1** [comment]
thanks, thats a good idea

**Comment by Porkch0p** [comment]
Looks like this is throwing a mixed content warning when the site is loaded over HTTPS, displaying as a grey rectangle in Firefox. A change from http://store.steampowered.com/widget/334920/ to https://store.steampowered.com/widget/334920/ should correct it.
