### ISSUE TITLE
Wiki Index link is broken

### ISSUE THREAD

**Issue by danylo-dubinin** [ZeroK-RTS/Zero-K-Infrastructure#2668]
Hi, this doesn't work for me suddenly:

https://zero-k.info/mediawiki/index.php?title=Manual

![image](https://user-images.githubusercontent.com/20540273/81594040-fc11f900-93c8-11ea-8796-98d5cbd56685.png)

And looks like no other page can be loaded too.

**Comment by Anarchid** [comment]
![image](https://user-images.githubusercontent.com/3822768/81595261-dd146680-93ca-11ea-8f0b-af45cac6f4e9.png)

There may be some disruptions for a while.

**Comment by Anarchid** [comment]
Seems fixed.

**Comment by Histidine91** [comment]
Note that logging in and editing the wiki are still broken for now.
