### ISSUE TITLE
Wrapper downloads win32 instead of win64

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2671]
- I made an engine called '104.0.1-1510-g89bb8e3_64' and put the win64 link from the spring buildbot in the win64 field. I also filled win32 and lin64 with their usual links.
 - I set my dev wrapper to launch '104.0.1-1510-g89bb8e3_64'.
 - When I ran the wrapper, it said downloading '104.0.1-1510-g89bb8e3_64'.
 - When Spring launched I checked the engine under 'Help -> Report a Bug' and saw that the  spring version was win32.

I have no win64 subfolder in my engines folder. Usually I upload win32 to the win64 field of the engines list because I wanted everyone to use win32.

**Comment by DeinFreund** [comment]
enabled win64
