### ISSUE TITLE
Battle room waiting list

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2675]
Edit: See the comment below for an updated version of the system.

This is a waiting list to generate fairness in joining newly-unmaxed games which also has the potential to make games for large numbers of waiting spectators.

Server-side:
 - Spectators can be in the waiting list, this means they have a new client paramter called `WaitingPosition` set to some positive integer. If they are not in the waiting list then `WaitingPosition` is disabled (setting it to zero works).
 - Waiting players vote like spectators.
 - If the there are free player spots in the room, then the spectator with the lowest positive `WaitingPosition` becomes a player. All the other waiting clients have their `WaitingPosition` decreased by 1.
 - Nobody should be able to manually sneak in an unspec or battle join command before the lowest waiting spectator is set to be a player.
 - Clients can use `SetBattleStatus` to set whether they want to be waiting or not, but no new parameters are required. See use of `SetBattleStatus` below.
 - Clients join rooms attempting to be players, which will automatically put them in the waiting list if the room is full.
 - Rooms can be configured to branch when there are X players in the waiting list. If at least X players are waiting in a non-ingame battle room then all the waiting players are moved to a newly spawned room with the same settings as the parent room.
 - Rooms with common spawn ancestry pool their waiting lists for the purpose of checking if there are enough players in the waiting list to spawn a new room.

UI-side:
 - The Playing/Play button is replaced with 'In Queue'/'Queue' for spectators if the room is at player capacity.
 - If there are waiting spectators in the room then the lower-right spectator list gains a divider called "In Queue to Play" above the "Spectators" divider that lists the people waiting to play. This is sorted by `WaitingPosition`.

Use of `SetBattleStatus`:
 - If a client sets `IsSpectator` to true then they become a non-waiting spectator.
 - If a client sets `IsSpectator` to false, or omits it, and there are free player slots, then they become a player as per usual.
  - If a client sets `IsSpectator` to false, or omits it, and there are no free player slots, then they are set to be a waiting spectator. Clients start waiting with `WaitingPosition` equal to one plus the largest `WaitingPosition` of other waiting clients (one if there are no other waiting clients).
 - If the only result of `SetBattleStatus` would be that a client moves itself to the end of the waiting list, then no effect is applied.

**Comment by Licho1** [comment]
Why not let them join and play directly?

**Comment by GoogleFrog** [comment]
Because there are no free player spots.

**Comment by GoogleFrog** [comment]
Here is an alternate system.
 - Clients have two new parameters, `WaitingBattleID` and `WaitingTime`.
 - Clients can send a command to the server with a `BattleID` that tells the server to start waiting for that `BattleID`, or to stop waiting for anything. This command sets `WaitingTime` to the current time. Commands would not result in a change of `WaitingBattleID` are ignored.
 - If a battle has a free player slot then the oldest waiting player for that `battleID` is forced into the battle room and into the player slot. When this happens the client receives a message containing its old battle room ID (if any) and the new battle room.
 - It should be impossible for other clients to slip in front of the client that is to be forced into the battleroom, essentially bypassing the waiting list.
 - The server periodically sends clients with `WaitingBattleID` their position in the queue, that is, how many other clients have the same `WaitingBattleID` and older `WaitingTime`.

A client also has its `WaitingBattleID` and `WaitingTime` cleared if:
 - It is in a player slot for its `WaitingBattleID` battleroom.
 - Any game starts that has that client as a player.

Generating new rooms.
 - Battlerooms can be configured to spawn new room when they have a set number of players waiting for them.
 - If the required number of clients are waiting, then a duplicate room is created and all waiting clients are moved to that room. The clients receive a message that tells them their old battle room ID (if any) and the new battle room. This message should be distinct in some way from the waiting list message.
 - It may happen that the required number of clients are waiting and already in a duplicate room when a new player joins the waiting list. In this case, the player is moved to the duplicate room.
 - Rooms can have their waiting lists linked for the purpose of spawning rooms. If enough clients are waiting across all lists then a room is created, as above. Rooms that are spawned are linked to their parents.

UI-side:
 - When a user joins a full room they receive a popup asking them if they want to join the waiting list (if not already part of it).
 - The 'Play' button in a full room is instead a button that joins the waiting list.
 - If the user is on a waiting list, then a MM-style status appears at the top of the screen. This status has a 'Leave' button. This status shows them their position in the queue.
 - Clients use the notification of being forced to a battle to send players a popup. This popup is sent if the player is locally AFK, locally ingame, or was in a different battleroom. If the user does not answer the pop in 20 seconds then they are sent back to wherever they came from or spectate. Accepting the popup causes an ingame player to switch to lobby view so they can see the situation.

Notable behaviours:
 - Players can only be waiting for a single battle. This makes the UI and mechanics of the system simpler.
 - Players can be in a different battle that is about to start and still be in a waiting list. This allows people to try to seed a game without giving up their slot.
 - When a duplicate room is spawned, players are not removed from the waiting list until the game starts. Some people who have their heart set on the original room are bound to leave. Hopefully the fact that no cost is paid until a game starts causes enough people to some stick around and try.

**Comment by GoogleFrog** [comment]
New ticket: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2699
