### ISSUE TITLE
Simpler battleroom waiting list

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2699]
Here is a waiting list system.
 - Let every Teams, 1v1 and FFA hosts have an unlimited number of players. I singled out these rooms because they do not have a concept of which team a player is on.
 - Keep track of how long each player has been in the room (ie, when they most recently joined).
 - Transmit the 'most recently joined' timestamp to other clients in the room as a type of battle status.
 - If the player limit of the host is X, then only the X players who have been in the room the longest play when the game is launched.

The lobby UI can use the timestamp information and the room player limit to display a "Waiting" players below a labelled divider in the player list.

This allows people to signal a willingness to play that is distinct from being forced into a spectator slot. Basing the system purely on oldest join time is imperfect, but it is much better than what we currently have. Currently a spectator can wait 30 minutes for a game to end, only to miss the end and have someone else jump in and take a vacated spot.

I think the old ticket is now obsolete: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/2675

**Comment by GoogleFrog** [comment]
The more resilient method of implementing this system would be to have the server send whether a player will play if the game starts now (ie, simply whether they are waiting or not). I still want the timestamp so that the players can be sorted and their waiting time displayed in a tooltip.

**Comment by Licho1** [comment]
What about spectators .. if you switch to spectator and back, do you retain your join time?

**Comment by GoogleFrog** [comment]
Being a spectator should retain your join time.

**Comment by Licho1** [comment]
implemented in test server
