### ISSUE TITLE
Update site screenshots

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2726]

**Comment by GoogleFrog** [comment]
Here is a pack of screenshots I have lying around: https://drive.google.com/file/d/1SCvpTNZu5YI975A63PUuSvCe-zvcDy8p/view?usp=sharing

There are quite a few. I don't know which work best with the layout of the site.

**Comment by Licho1** [comment]
The linmk is not public @GoogleFrog

**Comment by GoogleFrog** [comment]
Fixed https://drive.google.com/file/d/1SCvpTNZu5YI975A63PUuSvCe-zvcDy8p/view?usp=sharing

**Comment by GoogleFrog** [comment]
Try this link https://drive.google.com/file/d/1y63CK5cPJa0dRPLYmN4fQSjyeg_KvKJu/view?usp=sharing

**Comment by Sharkgamedev** [comment]
That link works for me!

**Comment by Licho1** [comment]
done
