### ISSUE TITLE
Use waiting list to enforce even teams when there are few players

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2730]
When there are 3, 5 or 7 players people often sit in the battle room and wait for there to be even teams. This can sometimes cause a spectator cascade as people step out to make the game even, resulting in other people spectating because they have either waited for long enough. One solution is to put one of the players on the waiting list and let a game start in the meantime.
- Add a command called !setminoddplayers X that sets the minimum number of players required to have uneven teams.
- The battleroom needs to communicate X to the lobby so the lobby can place excess players in the waiting list.
- If the game starts with fewer than X people trying to play, have the player at the bottom of the queue be a spectator (most recent join time, just as with waiting lists) if doing so would make the teams even.

**Comment by DeinFreund** [comment]
Just put players in the waiting list when they unspec and the battle is even. Only admit two players at a time into battles. 

So when you have a 4 player game and 1 guy unspecs, they get in the waiting list. Once somebody else unspecs, both get placed in the active lobby immediately. Alternatively, if somebody specs, they are replaced by the guy in the player list.

**Comment by GoogleFrog** [comment]
That amounts to reworking the way timing in the waiting list works. You want the age of the player to be hold long they have been in the battle and not spectating. That sounds fine to me.

**Comment by Sharkgamedev** [comment]
Is anyone else working on this? If not I'm gonna pick it up.

**Comment by GoogleFrog** [comment]
@DeinFreund say which commit fixed it and/or make a ticket on chobby. I am going to forget what you said in discord otherwise.

**Comment by GoogleFrog** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/c6f16ec13d8f2aa715a658a817a2c5b69abda9d7
