### ISSUE TITLE
Old background screenshots are still being served

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2740]
![image](https://user-images.githubusercontent.com/1318249/95669463-b2724800-0bcc-11eb-9951-0c2461ad5d08.png)

These screenshots were deleted from the repository, yet still appear.

http://zero-k.info/img/screenshots/sumo.jpg

**Comment by DeinFreund** [comment]
Fixed manually for now

**Comment by Licho1** [comment]
They just need to be deleted from that folder.. delete what you dont like, but this one is nice i think, lots of flying pieces

**Comment by GoogleFrog** [comment]
This one is ok, but it wasn't in the folder.

**Comment by Licho1** [comment]
ooh i see.. we deploy by not deleting existing stuff so its going to stay there forever.. so yeah its manual action time as DeinFreund found
