### ISSUE TITLE
Allow host to set minelo on sufficiently small hosts

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2742]
If the player limit is low enough, probably something like 6 or 8, then the host should be able to set minelo. It shouldn't be possible to work around this to end up with a large minelo game created by a host. This came up in a thread a while ago but apparently it never made it into a ticket.

**Comment by DeinFreund** [comment]
Hosts can always set minelo now, but it loses its effect as soon as the number of unspecced players surpasses a given limit.

**Comment by GoogleFrog** [comment]
What is the limit?
