### ISSUE TITLE
ZKL icon issue in Windows Volume Mixer

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#275]
http://i.imgur.com/AMYB3eT.png

**Comment by KingRaptor** [comment]
Now ZKL doesn't appear in my volume mixer at all.

Should it? If not we can just close this.

**Comment by KingRaptor** [comment]
I lied, it's there when using ZKL version compiled from master and it's still as huge as ever.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
