### ISSUE TITLE
Fresh Steam install is too large

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2752]
A fresh steam install is 5.1GB.
- 3.22GB of this is maps.
- 950MB is in pool (this seems like a lot when the game and menu are already present in the games directory).

There are 145 maps included in a fresh install. The campaign only uses 71 maps and there are 24 matchmaker maps, a lot of which overlap with the campaign maps. A lot of extra maps are being included from somewhere, perhaps the popularity thing that @DeinFreund added a while ago?

470MB would be saved by removing the following maps:
- https://zero-k.info/Maps/Detail/58856 - Boulder Beach (new giant behe map, only seems to be used for coop?)
- https://zero-k.info/Maps/Detail/19651  - Real Europe (large FFA)
- https://zero-k.info/Maps/Detail/7582 - Mearth (large FFA)
- https://zero-k.info/Maps/Detail/7362 - Dworld (large FFA)
- https://zero-k.info/Maps/Detail/17929 - GRTS messa
- https://zero-k.info/Maps/Detail/14255 - Deadlock
- https://zero-k.info/Maps/Detail/59161 - Twin Lakes Park
- https://zero-k.info/Maps/Detail/58532 - Incandescence
- https://zero-k.info/Maps/Detail/58414 - Leyline
- https://zero-k.info/Maps/Detail/7116 - Aberdeen

I think the inclusion of Twin Lakes Park, Boulder Beach and the large FFA maps shows that the automated popularity system isn't working properly, or I don't know where maps come from. As far as I know maps come from three places:
- Matchmaker maps
- A list in infrastructure somewhere (these tend to correspond to campaign maps)
- Some number of 'popular' maps.

Reducing install size is important because a long install gives potential players more time to forget what they are doing and wander off.

**Comment by DeinFreund** [comment]
I never touched Steam depot generation, but for what I can tell it simply keeps adding maps and never removes the old popular maps, thus ballooning in size.

**Comment by Licho1** [comment]
Deployment is automated and based on map labeling. But I dont think 5gb is much.. just finished downloading 97GB of destiny 2

**Comment by GoogleFrog** [comment]
@Licho1 as far as I know it isn't purely based on map labeling since @DeinFreund added a popularity metric.

**Comment by Licho1** [comment]
Oh I see.. ok..

**Comment by DeinFreund** [comment]
I repeat, I did not touch steam depot generation. Map selection has been untouched ever since its original implementation.

**Comment by DeinFreund** [comment]
Maps should be cleared before generation now, which hopefully fixes this.
