### ISSUE TITLE
Make the wrapper 'decide' to use dedicated graphics cards rather an integrated

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2758]
People with laptops tend to report graphical issues that are solved by telling their graphics card to activate for Zero-K. Apparently the default behaviour of some laptops is to let programs decide individually whether they need dedicated or integrated graphics. There may be something the wrapper can do to request dedicated graphics.

**Comment by Sharkgamedev** [comment]
I had the same thing happen on my new laptop and had to set an override. Potentially this may have answers: https://docs.nvidia.com/cuda/optimus-developer-guide/index.html (Optimus being Nvidia's tech for determining what gpu to use)

**Comment by DeinFreund** [comment]
Can the wrapper tell Spring what GPU to use, or is this something that Spring has to implement first?

**Comment by GoogleFrog** [comment]
@DeinFreund I don't know. The wrapper spawns spring so maybe.

**Comment by Licho1** [comment]
There is/was support for this for linux. You could use optimus command line to specify it.  Not sure what the correct procedure is on windows. Linked article does not seem to show it.

**Comment by Rekojeht** [comment]
This is just a shot in the dark but I found https://developer.nvidia.com/nvapi which may be key to solving this. I think the best approach might be checking if the user has, for example, an NVIDIA graphics card, then programmatically call upon the NVAPI to set the application setting to choose the NVIDIA card making sure to set it to the ZeroK executable.

**Comment by Sharkgamedev** [comment]
If auto switching isnt feasible would it be possible to determine which gpu is currently being used for zk and display a warning if:  
We know it's an apu  
We know there are multiple gpus

**Comment by Licho1** [comment]
Relevant thread 
https://stackoverflow.com/questions/16823372/forcing-machine-to-use-dedicated-graphics-card/39047129

**Comment by Licho1** [comment]
In other words we should add this to spring source:
```
extern "C"
{
  __declspec(dllexport) int AmdPowerXpressRequestHighPerformance = 1;
}

extern "C" 
{
  __declspec(dllexport) unsigned long NvOptimusEnablement = 0x00000001;
}
```

And thats it!

**Comment by sprunk** [comment]
Done engineside
