### ISSUE TITLE
Custom Mode featuring and updating

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2763]
I added custom modes to chobby. They are map/mod/options presets that can be selected when hosting a game or through a menu in Adv Options.

![image](https://user-images.githubusercontent.com/1318249/99132190-6f8f0e80-2669-11eb-97db-dedcfdb793ef.png)

![image](https://user-images.githubusercontent.com/1318249/99132224-8c2b4680-2669-11eb-8883-239b3d728fe5.png)

Most importantly, custom modes don't expose the player to the technical details of what people would usually call "a mod". Zero Wars is a map and Arena Mod is a mutator, yet players don't need to know the difference. A custom mode could even just be a set of modoptions that work well together, since modoptions have become very powerful in ZK.

Custom modes currently live in chobby and are deployed by the wrapper in the usual way. Here is an example: https://github.com/ZeroK-RTS/Chobby/blob/master/LuaMenu/configs/gameConfig/zk/defaultSettings/CustomModes/arenaMod.json

The parameters are described here: http://zero-k.info/mediawiki/index.php?title=Custom_Modes

It would be better if custom modes could be defined by players and featured by moderators for automatic updates and deployment. Doing this would replace the need to create a mod featuring system that just features games and mutators. As an extra features there could be a "download this mode" and "play this mode" button on the site, which sends the player the information through the lobby protocol, much like how "play this map" sends players a command to host and play on a map.

**Comment by sprunk** [comment]
a7dbf0afbe154ea7e87fa17aa77e9c91bf1b8626
