### ISSUE TITLE
Casual team balance brand new players at less than 1500 rating

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2765]
Most brand new players contribute much less to a team than somewhat experienced players with a rating of 1500. I thought we had some sort of system that treated them as 1100 for the purpose of balancing, but an investigation of the balance of https://zero-k.info/Battles/Detail/990767 seems to refute this theory. Apparently "Ladder Rating" starts at 1100, but as far as I know "Ladder Rating" doesn't have any effect on which games or teams are created.

**Comment by Arch-Shaman** [comment]
#2635 ?

**Comment by GoogleFrog** [comment]
Hmm yes, sadly. I guess I will comment there.
