### ISSUE TITLE
Let users send reports to the lobby server

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2774]
Currently clicking on "report player" in the lobby sends the user to the appropriate website report player form. Chobby can take text input and the report form only requires a few bits of information, so there could be a lobby server message for sending reports. This would be a lot smoother and probably result in more reports.

**Comment by maackey** [comment]
Currently "report player" option isn't available on all names in the lobby. That is IMO a worse inhibition for people using the report button -- it may show up for some people sometimes but not others, and the reason isn't clear. Which makes it an unreliable avenue for reporting.

**Comment by DeinFreund** [comment]
`UserReport {"Username": "DeinFreund", "Text": "He called me a lobster."}`
