### ISSUE TITLE
Sorting Ladder by other columns does not work

### ISSUE THREAD

**Issue by Birdulon** [ZeroK-RTS/Zero-K-Infrastructure#2778]
Clicking on the heading does everything you'd expect - makes an up or down arrow next to it, rewrites the url to include `&grorder=Tru&grdesc=True` and refreshes the page. Everything except actually sorting by that column.
![image](https://user-images.githubusercontent.com/5397662/101246252-00857100-3762-11eb-927f-9c1e5a672b33.png)

The same happens with the Player column, and probably Ladder Rating too, though that would be equivalent to Rank anyway for sorting purposes.

**Comment by Birdulon** [comment]
I've checked the other uses of `UniGrid` and all of the ones I can access apart from the Ladder and Map Ladder are perfectly functional. The only common factor I can think of is the True Rating field having a more complex value (two numbers) than any of the other data models contain.

**Comment by DeinFreund** [comment]
I didn't intend for sorting to work here, ladders are usually expected to be in a fixed order. I suppose it would be nice if the UI didn't suggest that it's sortable.

**Comment by Licho1** [comment]
Yeah if you don't set "SetSort" it should not show as sortable by default.
