### ISSUE TITLE
Add RSA key pair to allow login when steam is down

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#2782]
* ServerWelcome sends challenge token to client 
 * client generates priv/pub key pair if it does not have one (chobby decides and stores, wrapper generates)
 * client encrypts/signs the challenge token with priv key (wrapper performs on chobby command)
 * client sends Login as normal but also includes pub key and signed challenge token

Server behavior:
 * On login server always validates pub key and signed challenge token
 * On Login, server validates user using steam and login+pw pair. If all is fine, it stores current pub key.
 * If login has no valid steam token but pub key matches last known pub key of this account, user is accepted.

Bonus goal:
 * Always encrypt password sent from client to server using the priv key. This would require either extra message or pub+signed token also in Register.

**Comment by sprunk** [comment]
cb571eaea81aaabd34d8c432cc108f9ee02c2a49 ?

**Comment by Licho1** [comment]
Looks like it.. it needs implementation on Chobby to do the saving. Is it done? Maybe i created ticket for chobby

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Chobby/issues/784 chobby ticket exists, closing this one
