### ISSUE TITLE
[Feature Request] Flatpak package

### ISSUE THREAD

**Issue by machiav3lli** [ZeroK-RTS/Zero-K-Infrastructure#2785]
The current distribution ways are truly restrained to Steam only. The portable package being so heavy mixing dependencies of Windows and Linux and the simple installation script being unable to follow dependencies changes over a plethora of distros render both ineffective.

Distributing a Flatpak package on Flathub, would solve the installation script issues and would improve the reachability to the majority of modern distros, without the need for multi-distibution channels following the example of 0 A.D. .

**Comment by Licho1** [comment]
this is upt to anyone to make
