### ISSUE TITLE
Implement ladder league

### ISSUE THREAD

**Issue by Legomenon-gh** [ZeroK-RTS/Zero-K-Infrastructure#2796]
I'm going to try to implement a league as described in https://zero-k.info/Forum/Thread/32336?page=2&Search=&User=&grorder=&grdesc=False&grpage=1. This is my plan to minimize risk of breaking things and wasting time, please let me know if anything looks too dangerous or plain wrong.

The first part is to do all the backend work to support leagues but make nothing visible to users. This allows to test that leagues behave correctly and do not break matchmaking before rolling it out. Features required in this step:
- Admins can start a preleague, kick off the league, and end it. Manual action is enough at this point for easy testing, and league state is stored in a simple table.
- MM games increment and decrement user league points correctly based on the higher of their pregame or postgame ladder position. League points will be stored in a database table since they cannot easily be recalculated from scratch.
- The position -> league points configuration will be kept in code unless someone really wants it to be configured dynamically in the database instead (it's more complexity to make an entire table dynamically configurable, and points shouldn't ever change during a league).
- There is a view for admins that show all users in the league, their league points, their current rank icon and their league icon. Also add a league point chart if it's easy to implement based on the rating chart for the ease of debugging.

Once things look good, determine how the league should appear for users and turn it on. This includes the following decisions which don't need to be made until leagues work at all:
- How a new league should impact WHR, if at all.
- How league icons should be displayed (replacing the current icons, additional icons, or a glow).
- If the league ladder should replace the MM ladder or be shown in a separate page.
- If server restarts are too cumbersome, I can stick to testing on the test server and use a DB feature flag to control the feature's availability. This would require more work and doesn't guarantee a hotfix wouldn't be needed.
- The above changes should be fairly simple to implement, and a league can be started once this is live.

The last step is make it easier to go from league 1 to league 2. This includes at least:
- Add possible badge rewards for league winners
- Make any necessary changes to league mechanics based on user feedback
- Potentially make preleague start, league start, and league end automated (since leagues will last for months, leaving this to manual action is fine, but if there's a good way to have cron triggers run, it'd be nicer)

I will start working on the first part (that's the main piece of work) in a few days if nobody objects.

**Comment by Licho1** [comment]
Note that the system already supports separate ranking for planetwars, which is basically similar thing - resetting ranking.

**Comment by GoogleFrog** [comment]
I can have a closer look on the weekend.

**Comment by GoogleFrog** [comment]
I don't know what to do about displaying the rank icons. We already have the casual/MM problem. I'm not sure whether MM WHR should exist separately since the league would be the MM.

> Update the ladder point formula to rating change = 0.5*(clamp(1, 50, whrChange)) + 0.5*(rating change from standard elo calculation). if GoogleFrog still wants to change this formula.

I want the ratings change formula to make sense, but isn't this already the formula?

**Comment by Legomenon-gh** [comment]
Yup you're right, I didn't realize the WHR formula got changed since your post.

Maybe a better approach would be to run a beta league live to get some user feedback on how it should interact with the current MM ladder? Otherwise my inclination would be to keep MM WHR since some users care about it as the measure of skill, but otherwise replace MM ladder points with the league, and punt on ranks.

**Comment by Legomenon-gh** [comment]
I'm going to close this issue since I believe my plan is flawed and isn't ready for implementation, since it adds a lot of complexity and the benefits aren't clear.

The reason to create a separate ladder for the league is to be able to persist the existing MM ladder and WHR since some users have expressed a desire to have an authoritative way to see their skill. The problem with that is it introduces an entire new ladder point system that uses different rules from the other ladders, while still being tied to MM WHR, and it's not clear to me that this is a benefit overall.

After starting some of the implementation work, I cannot justify my plan over a simple reset of the MM ladder points with partial WHR reset.
