### ISSUE TITLE
CW (Curaçao) flag is missing

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2807]
http://zero-k.info/users/lobbydetail/523259

![image](https://user-images.githubusercontent.com/48730089/112038060-c9707b00-8b18-11eb-8de8-0be0cc15acb1.png)

**Comment by Arch-Shaman** [comment]
http://zero-k.info/img/flags/CW.png

**Comment by sprunk** [comment]
ec12409694d9cd55bf8f20d349cc93d3a43359cc et al
