### ISSUE TITLE
"Download sources of mod" is actually a useless JSON

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2818]
This button:
![image](https://user-images.githubusercontent.com/2573076/120110609-7517f600-c16e-11eb-93a8-8fcba2f44a78.png)

Which links to https://zero-k.info/Mods/Download/2

Doesn't actually produce the mod's sources (`.sdz` or even a github link) but just a JSON with pretty much just the name and desc:
```json
{
    "shortName" : "unitlevelups",
    "name" : "Unit Level Ups v46",
    "description" : "The Final Fight, lobster vs lobster. Who will win?",
    "game" : "Unit Level Ups v46"
}
```

Expected behaviour: "Download sources" points to `.sdz` archive, the JSON is accessible via "download metadata" or something.

**Comment by GoogleFrog** [comment]
The unsatisfying answer is that a 'mod' is a description of how to play a particular modification of the game, so can be a lot of things. It could just be a map, a game (mutator) or even just a list of modoptions. It can be a combination of these things too.

Perhaps rename the button?

**Comment by Licho1** [comment]
Yeah it does what it was intended to do..
The server does not actually understand the format, only chobby knows..
