### ISSUE TITLE
Wrapper event for externally launched spring crashing

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2820]
If we are to have general players run s benchmark to test whether the new engine works, then chobby needs a way to detect crashes for externally launched springs. The only non-hacky way I can think of doing this is if the wrapper sends an event upon the externally launched spring closing, with a parameter for whether it has crashed.

Dumping the entire infolog back to chobby via the wrapper when the launched spring closes would be great too, as it would help with finding issues.

I thought I made a ticket for this but can't find it.

**Comment by Licho1** [comment]
crashes are now reported as normal

**Comment by GoogleFrog** [comment]
I don't see the part of the commit where a message is sent to chobby, can you point me to it?

**Comment by Licho1** [comment]
added the message 
```
    [ChobbyMessage]
    public class NewSpringExited
    {
        public string StartScriptContent { get; set; }
        public string StartDemoName { get; set; }
        public string SpringSettings { get; set;  }
        public string Engine { get; set; }
        public string CustomId { get; set;  } 
        public bool IsCrash { get; set; }
    }
    ```
