### ISSUE TITLE
Wiki over HTTPS shows Unit Pics as broken links on Chrome browsers

### ISSUE THREAD

**Issue by Porkch0p** [ZeroK-RTS/Zero-K-Infrastructure#2827]
See here: https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

![](https://cdn.discordapp.com/attachments/432874986064052235/862853506364735510/unknown.png)

Generating and applying a Let's Encrypt certificate for **manual.zero-k.info** might be enough to fix this.

**Comment by sprunk** [comment]
Duplicate of #1795
