### ISSUE TITLE
Zero-K wiki only showing steam login option

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K-Infrastructure#2828]
![Log in - Zero-K - zero-k info](https://user-images.githubusercontent.com/11136438/125986366-d815ffbb-25e1-4177-b9c4-bb41754bc69a.png)

Should be showing steam and internal database as options.

Thread Ref: https://zero-k.info/Forum/Thread/33863

**Comment by Oflameo** [comment]
![Steam Community - steamcommunity com](https://user-images.githubusercontent.com/11136438/125987024-7b30f6bc-5aec-4782-af52-c355b0e750ac.png)

Also take note that there is a disclaimer saying that Zero-K is not affiliated with Steam or Valve still up and that the help logging in link goes to the mediawiki page on logging in mediawiki. 

https://www.mediawiki.org/wiki/Help:Logging_in

**Comment by GoogleFrog** [comment]
As far as I recall the "not affiliated" text is standard for all games. Being on the steam store does not make Zero-K part of steam the company. This is what affiliated means.

**Comment by Histidine91** [comment]
I've reinstated login using wiki's internal database (username + password).
