### ISSUE TITLE
User request: uncompressed map images

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#2837]
Mapper user request. The site already extracts the heightmap etc, but compresses them to jpg (example:  https://zero-k.info/Resources/DeltaSiegeDry.heightmap.jpg ). The request is for there to be some way to access the uncompressed file so that it can be used as a base for further work.

**Comment by GoogleFrog** [comment]
Wouldn't they be too large to store on the server? Why can't they download and decompile the map?

**Comment by sprunk** [comment]
> Wouldn't they be too large to store on the server?

Most likely yes, but confirming that would be a part of the ticket.

> Why can't they download and decompile the map?

They can but "it's inconvenient". Perhaps the real request is for there to just be some easy way to extract heightmaps and the existence of compressed images hinted at this being a low mana solution. Here's the request verbatim:

>  Heya - Was just talking to Aquanim about the jpg versions of the heightmaps we show in our maps section of the site. As a map maker, it would be really helpful if that .jpg thumb could actually click through to the unrasterized png/bmp image for use in later map making. You the right guy for this query? Using PyConv is inconvenient for that trivial re-use of something we already have.

**Comment by Licho1** [comment]
What would be the purpose of this? We could store them in png on server but then ,the maps have the uncompressed image and you can download the map as well.

**Comment by sprunk** [comment]
I think it would just be convenience. So probably not worth the time, maybe can be reopened IF mappers give a more substantial reason.
