### ISSUE TITLE
ChobbyLa under Mono fails to open links

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#2857]
```
Error opening URL http://zero-k.info/mediawiki/index.php?title=Manual : Cannot find the specified file
  at System.Diagnostics.Process.StartWithShellExecuteEx (System.Diagnostics.ProcessStartInfo startInfo)
  at System.Diagnostics.Process.Start () 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process.Start()
  at System.Diagnostics.Process.Start (System.Diagnostics.ProcessStartInfo startInfo)
  at System.Diagnostics.Process.Start (System.String fileName) 
  at ChobbyLauncher.ChobbylaLocalListener.Process (ChobbyLauncher.OpenUrl args) 
```

Likely cause: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/548b4c34d119da21a309e405dbf56f107151c04e/ChobbyLauncher/ChobbylaLocalListener.cs#L160 calls [Process.Start(String)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?view=net-6.0#system-diagnostics-process-start(system-string)) , which mono refuses with a "File Not Found". 

Probably should be `Process.Start("xdg-open", url)` if on Linux.

**Comment by Porkch0p** [comment]
If it clarifies anything, my "hybrid" itch install with both launchers, when started from Zero-K_linux64.sh is still able to open web links in Firefox, but the kickstart throws the above error.

**Comment by Porkch0p** [comment]
That above error was shortened for readability but seems to have lost some important info in the process. The full first line was
`Zero-K.exe Error: 0 : Error opening URL http://zero-k.info/mediawiki/index.php?title=Manual : System.ComponentModel.Win32Exception (0x80004005): Cannot find the specified file`

It might be possible to support opening urls in mono without breaking current systems if [Win32Exception](https://stackoverflow.com/questions/7693429/process-start-to-open-an-url-getting-an-exception) were to be handled and given the suggested Linux parameters.
```
try
{
  Process.Start(url);
}
catch (Win32Exception)
{
  Process.Start("xdg-open", url);
}
```

**Comment by Porkch0p** [comment]
The Win32Exception approach appears to work well. Tested built executable from master, and doesn't appear to interfere with native steam version or windows steam version.

**Comment by mojjj** [comment]
just tried again using steam update to get latest game, but same error again. is this really fixed (and not yet served) ?
