### ISSUE TITLE
404 on trophy on homepage

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#2865]
http://zero-k.info/img/Awards/trophy_economist.png

**Comment by Arch-Shaman** [comment]
Ah, this is from FW. I think there was talk about custom awards being removed or something? Idk. At any rate, attach are the files that I use in FW, no idea how to make a pr for this. Alternatively these can be found [here](https://github.com/Arch-Shaman/ZK-Futurewars-Mod/tree/Stable/LuaRules/Images/awards). I suppose I can also PR the awards at some point, not sure what the best approach is.

![trophy_economist](https://user-images.githubusercontent.com/48730089/155526031-d3f2cf77-4753-42cd-94a9-3807562515d2.png)
![trophy_repair](https://user-images.githubusercontent.com/48730089/155526036-9e25e98f-32ed-43cc-ae82-ee2ee071c68a.png)
![trophy_assistant](https://user-images.githubusercontent.com/48730089/155526038-af9b2fb3-18a6-4567-81ba-fc9b28bdf8bd.png)

**Comment by Licho1** [comment]
fixed .. there should be autoexport buildstep/tool probably broken atm

**Comment by sprunk** [comment]
Probably not broken, these are trophies from some random mod so they aren't included in ZK
