### ISSUE TITLE
Discord bridge no longer relays chat at all

### ISSUE THREAD

**Issue by Arch-Shaman** [ZeroK-RTS/Zero-K-Infrastructure#2920]
![image](https://user-images.githubusercontent.com/48730089/188274679-4637d834-bf74-4cb9-8f71-0d5d6be2a8ba.png)

**Comment by SteelBlueZK** [comment]
https://discord.com/channels/278805140708786177/278805140708786177/1017238546215604305 Therxy said istrolid had this issue a while back, some kind of "message content intent" setting in their bridge. Worth looking into?

**Comment by Porkch0p** [comment]
TIming of Message Content Intent being required and bridge failing seems to line up.

"On September 1, 2022, we will remove verified apps' access to message content if they have not been approved for the Privileged Intent."

https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ

**Comment by Licho1** [comment]
Oh thanks, that will be it!

**Comment by Licho1** [comment]
I ghave the bot intent but it changed nothing, maybe it needs restart?

**Comment by Licho1** [comment]
ok it needed restart, fixed now

**Comment by Arch-Shaman** [comment]
Well this is interesting. Infra repo is using old version but site renders
the modern one.. (see attached issue).

la 10. syysk. 2022 klo 3.54 Licho ***@***.***> kirjoitti:

**Comment by Licho1** [comment]
it needed change on discord side not in code
