### ISSUE TITLE
Screenshot links on media page are dead

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#2932]
https://zero-k.info/Wiki/Media#Screenshots

![image](https://user-images.githubusercontent.com/1318249/220346495-2dd99fe9-427f-4537-8a4a-d673ee3551c8.png)

Perhaps the presskit died. The screenshots are a bit out of date (I have been sending better ones to steam each stable) but they should still be fixed.

**Comment by Licho1** [comment]
fixed
