### ISSUE TITLE
New ZK-Accounts - IP crosscheck and Warning in Chat

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#303]
dont know if such a thing exists yet. as today a user came back again and again with new accounts, trolling the game, acting like a sheep and asking stuff, but then teamkill or ally com nap etc...

so here is it:

before the first game, when new accounts are created, the IPs should automated be crosschecked to a smurf IP list. 

if the new account gets a red flag, it should post in chat a warning, and/or autospec the player before game start, so it needs an active action by an admin to enable the account for gaming.

**Comment by Licho1** [comment]
already implemented - we have warning in caht
