### ISSUE TITLE
website DB migration error - cannot post to battle

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#307]
on battle, says: Cannot post new thread with blank title

**Comment by Licho1** [comment]
unable to replicate, post replication details

**Comment by mojjj** [comment]
was when posting to http://zero-k.info/Battles/Detail/319833 , about 30sec after game finished. cannot reproduce now either.

**Comment by mojjj** [comment]
why is this closed? another error, claimed by Forever, he cannot create new Threads

######
error message:
"Can i ask why i cant make new threads in the forrum? It shows me this:
"You are not a member of T4E, you cannot post in their clan thread"
and this in all types of threads including offtopic"

**Comment by Licho1** [comment]
Cannot replicate. POst replication steps or more info (exception message)

**Comment by mojjj** [comment]
as far as i know, there is no such thing as an exception message. just plain text like

"You are not a member of T4E, you cannot post in their clan thread"

or

"Cannot post new thread with blank title"

just like the response after you submitted a report for a player.

**Comment by Licho1** [comment]
Ok how to replicate? It does not happen for me, it works perfectly

**Comment by KingRaptor** [comment]
I already fixed it in d521d05b2e94fab7f24aa413c9aee26bf8ce38bd
