### ISSUE TITLE
Lichos dev diary thread page=1 every other thread page=2144

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#308]
From Zero-K Issue 476

>Hey,
>click on ZeroK Forums every thread link has page=2144 in the params except:
>http://zero-k.info/Forum/Thread/6692?page=1
>
>this thread is sticky too, maybe it has to do something with that

In other words, clicking on a thread will display a blank page unless you click on the thread name at the top of the screen or enter the desired page itself. It seems to self correct after a second visit to the page. Perhaps its something to do with unread posts?

**Comment by mojjj** [comment]
still an issue with this page=XXX attribute

thread 
http://zero-k.info/Forum/Thread/11225


internal page indexes start at 0, with two pages, so max index is 1. has 2 pages. when coming from main forum view, landed there with page=index attribute  set to 2  => empty page

**Comment by Licho1** [comment]
unable to replicate. Is there any reliable test case to verify?
