### ISSUE TITLE
new players get -480 start elo

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#312]
all new players start with -480 elo.

last userid which started with 1100 elo (default) was: 
346472 13 hours ago. All registrations after him got -480 elo

**Comment by ArchShaman** [comment]
This is an effect of the db upgrade I believe.

**Comment by Anarchid** [comment]
I think this is fixed in 145ce47cf

**Comment by KingRaptor** [comment]
Compiled and deployed now
