### ISSUE TITLE
whitelist flobby for QuickMatch

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#315]
allow flobby for QuickMatch queue please. :-)

**Comment by Licho1** [comment]
What is ID of flobby?

**Comment by cleanrock** [comment]
Why close ? Still not supported:
16:55 ZkTeams1: Sorry, you need compatible lobby to play here (Zero-K lobby or SWL). See https://github.com/spring/uberserver/issues/121

**Comment by Licho1** [comment]
What is the ID?

**Comment by cleanrock** [comment]
http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#LOGIN:client
You may have worse memory than me :) We discussed this extensively.
