### ISSUE TITLE
Critical errors everywhere.

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#317]
Site is completely down, springiee won't change maps, replays not working, nothing works.

I get this error:
Unable to update database to match the current model because there are pending changes and automatic migration is disabled. Either write the pending model changes to a code-based migration or enable automatic migration. Set DbMigrationsConfiguration.AutomaticMigrationsEnabled to true to enable automatic migration.

**Comment by Licho1** [comment]
fixed by  bc85e7097336ab566bf679c19453f7bf4ddfcf76
