### ISSUE TITLE
add some obligatory tutorial / mission / CAI games to prevent smurfing

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#321]
There are kinda a lot of smurfs last days... to prevent such smurfs maybe
- add obligatory CAI battles maybe 5 - 6
- or obligatory missions (could be a problem with non ZKL lobbies)
- or something else what has learning effect and increases time waste for smurfs

**Comment by Licho1** [comment]
we know about that... KR is working on missions.

**Comment by Jamanno** [comment]
*bumb*? :)
