### ISSUE TITLE
Campaign progression error

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#323]
ZKL log: http://pastebin.com/gzGKJ6rG

**Comment by Licho1** [comment]
It seems you have insert wrong combination of planet id and campaign id, what were they?

**Comment by KingRaptor** [comment]
PlanetID = 1, CampaignID = 1 (planet Isis)
There's only one campaign in DB, with campaignID 1

(Relevant function: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/ContentService.asmx.cs#L294)

**Comment by KingRaptor** [comment]
http://pastebin.com/HQFNhcSS

:(

**Comment by Licho1** [comment]
How to easilly replicate locally?

**Comment by KingRaptor** [comment]
Right now I'm testing just by playing Tutorial 1 online, which takes about 5 minutes at a time, then checking lobby diagnostic log afterwards. (Delete your AccountCampaignProgress DB entries for planets 1 and 2 if needed)

Dunno if it'll work correctly on test server.

**Comment by KingRaptor** [comment]
Fixed a couple of months back.
