### ISSUE TITLE
Minor: Fix flags that dont show up (ZKL)

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#324]
Just a minor suggested task to fix flags when possible. Certain countries do not seem to show up correctly in zero-k lobby. It should be a "fix before steam release" thing. It doesn't make a good impression when the first thing you noticed is people are missing flags.

**Comment by Licho1** [comment]
do you know which countries?

**Comment by ArchShaman** [comment]
Iceland, India, Isle of man are some of the ones I've noticed so far.

**Comment by KingRaptor** [comment]
Ought to be fixed in 53703a5025fe7cfed473df16b6139f7fb15e506b

Reopen if issue persists, thanks!
