### ISSUE TITLE
ZKL - fullscreen tooltips

### ISSUE THREAD

**Issue by HisaoNakai** [ZeroK-RTS/Zero-K-Infrastructure#328]
uname -a
Linux localhost 3.16.0-4-686-pae \#1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) i686 GNU/Linux

ZKL version 3.0.1.18594

I use StumpWM, and ZKL tooltips show up as whole new windows, which are naturally fullscreen in a tiling WM. This does not happen with the tooltips in any other application I use.

**Comment by xponen** [comment]
you are right, ZKL tooltip is a window. We put some settings to make it doesn't appear on taskbar as another window. We can draw complex stuff when we make new window.

Its kind of hard to know what setting would work on Linux system, last time I had a hard time to make it not steal input focus in Ubuntu, Xfce desktop.

The code that made Tooltip hide from taskbar is this https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZeroKLobby/ToolTips/ToolTipForm.cs#L29 

I couldn't fix this. It would be better if someone who uses StumpWM attempt to fix it. :(

**Comment by HisaoNakai** [comment]
Hey, xponen.

In StumpWM the ZKL tooltips do appear in the modeline (= taskbar equivalent), and it's partially good that they're treated just like other windows, so they can be closed/switched away from quite quickly, but it's better if the hassle wasn't present to begin with, it's quite distracting and irritates the vision as well.

I wish I could fix it but I'm afraid I have no knowledge of programming as of now.

**Comment by xponen** [comment]
Okay, can be done. Will try add option to disable those tooltips.

**Comment by xponen** [comment]
HisaoNakai,

can't this be fixed in StumpWM? This new option will be only used by you, will look weird.
