### ISSUE TITLE
1v1 queue not starting with many people

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#331]
I joined a 1v1 queue room when it had 3 people in it. In 68 seconds two of them were matched in a game. Myself and the remaining player sat there with the "Game starts in" timer going negative. The queue worked correctly upon rejoining.

**Comment by Licho1** [comment]
Hmm need some better test case .. timer going negative is probably just a visual bug that can be fixed though

**Comment by db81** [comment]
Queues seem to be abandoned with plans for a different matchmaker implementation.
