### ISSUE TITLE
Rapid screen in ZKL is broken.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#343]
![brokenrapidscreen](https://cloud.githubusercontent.com/assets/1318249/5643183/6121738e-96a9-11e4-83bc-3acd43e0ad6b.jpg)

**Comment by xponen** [comment]
I able to replicate, I'll fix this.
Its some sort of asking for a table that is not ready yet (maybe a race condition).

**Comment by xponen** [comment]
Update:
Its JSON deserializer return a malformed table. 

When a "foreach()" loop tries to read a malformed table it say "System.NullReferenceException: Object reference not set to an instance of an object." and point to a line above the "foreach" loop, even if the line was innocent.

**Comment by Licho1** [comment]
I fixed it in next version it should be fine now - swapped to json.net from servicestack (different brand of serializer)
