### ISSUE TITLE
repository still contains some passwords

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#345]
please remove all of them and change all used passwords!

never ever store passwords in a public repository!

**Comment by sprunk** [comment]
noone found them yet -> it is not a real world problem.
people dont steal in civilised countries.

**Comment by KingRaptor** [comment]
Oh Sprung you troll. (It makes sense in context)

abma: Where exactly? If this is about the server access thing, only certain people can log in even if they have the username and password AFAIK. (But yes, should still be changed)

**Comment by Licho1** [comment]
I think its fine now. Dont plan to change conn string pw as it would just make it harder to manage (separate web.config which is not auto deployed  -> possible issue discovered only after release if you touch web.config)
