### ISSUE TITLE
Implement email password recovery

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#35]
1. Add email column to Account table DB
2. Add email field in ZKL registration form
   - ZKL should send this email to uberserver as part of the registration action
3. Add button to site with a password recovery form; generates a random password and sends email to user
   - Form should ask the user for username and email; only send if they match
   - Nightwatch sends uberserver the new password

**Comment by KingRaptor** [comment]
Now that we've moved to our own server this should be easier to do. Any recommendations for implementation method?

**Comment by Licho1** [comment]
It would mean asking users for email. And wont work for existing people. Is it really worth it?

**Comment by KingRaptor** [comment]
Well...
* Password recovery seems like pretty basic (albeit non-essential) functionality
* Email verification and/or bans would add another small hurdle to smurfing

Existing users could have a field to set their email (this would want to be there if we implement this anyway)

**Comment by Licho1** [comment]
How will it work together with steam? Steam won't give you email..

**Comment by Licho1** [comment]
No longer needed, accounts linked to steam can be used using steam online without PW and then to change PW.
