### ISSUE TITLE
wiki/manual: guidelines needed for effective contribution. Also: github OR google?

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#352]
Guidelines are needed for usage of wiki & manual so that people can contribute effectively.
Just like code needs some synthax and style guidelines, so other texts do need planning too.
(Interesstingly the status is so choatic that currently one could not even write guidelines in sensible way, see example 1.)

Three VERY OBVIOUS examples:

1) **google.code OR github wiki?**
In some thread it was written that player manual should remain at google.code's wiki.
But now there are pages appearing at github too.
Pick one!

2) **dead links / dead pictures**
here at bottom: http://zero-k.info/Wiki/NewbieGuide
now-dead images from old caspring site.

http://zero-k.info/Wiki/FAQ#7._I_get_ugly_bubbles_in_the_minimap/the_whole_screen_flashbangs
"Do you get bubbles like this?"
this = http://www.freeimagehosting.net/uploads/dddb74bf69.jpg = third party crap site = dead

Dead pictures are avoidable if there is guideline which reliable host to use.

3) **Same info multiple times in different places**
With code one does not want multiple bloat functions that all do the same thing.
Similiar it is bad to have multiple pages in wiki/manual about same thing.
Three seperate pages have a part about the eco panel. (all have different versions in their picture)
People unknowingly writing the same stuff is not effective.

springwiki has PARTLY solved some of that and imo it was key from "heap of stuff" to somewhat decent docu:
http://springrts.com/wiki/SpringWiki & http://springrts.com/wiki/Help:Editing

**Comment by knorker** [comment]
What does "integrated" mean, integrated into what?

> "The player wiki would use same account data and possibly share markup language with forums."

That together with postings here http://zero-k.info/Forum/Thread/9705?page=1#106877 gives me impression that the idea (whatever that means) is to create new custom wiki. 
As in, instead of using mediawiki or github wiki or whatever, a new implentation of a wiki because *"It would be very hard to make standard off the shelf wiki compatible with ZK accounts, with their displayed style, avatars, tooltips etc"*

Well, wake me up next year when the superduper wiki is functional and actual work on its content can begin.

**Comment by Anarchid** [comment]
> Well, wake me up next year when the superduper wiki is functional and actual work on its content can begin.
Will do.

**Comment by KingRaptor** [comment]
Short term rule: anything that needs to be visible on website goes on Google Code, everything else (e.g. dev documentation) gets put on Github.

Hmm, do we want style manual now, or only after wiki is decided upon?

**Comment by knorker** [comment]
>Short term rule: anything that needs to be visible on website goes on Google Code, everything else (e.g. dev documentation) gets put on Github.

On github wiki exists:
https://github.com/ZeroK-RTS/Zero-K/wiki/Manual & https://github.com/ZeroK-RTS/Zero-K/wiki/Repair
Is that just test stuff or something?
Two wiki is imo not good idea, because things must be done twice. (page templates, images can not be shared between both wikis etc)

>Hmm, do we want style manual now, or only after wiki is decided upon?

wiki sysems are slightly different too (functionality, synthax, how "special pages" (history, file list) work,..) so imo it is obvious what must come first.
About the all-new wiki that people want to implent I do not know anything at all, so can not comment on that.

**Comment by Licho1** [comment]
wiki is now integrated though not yet finished, but we are commited, google code was copied to zk site directly
