### ISSUE TITLE
Autoregistrator not updating mission versions

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#358]
The last instance threw errors about not being able to fetch something (update list?) from packages.springrts.com.

**Comment by xponen** [comment]
Maybe autoregistrator is not using the latest version? because I saw that recently all the web addresses were changed. So the addressed (in code) need to be checked.

**Comment by xponen** [comment]
Autoregistrator do not Auto-deploy, it must be manually copy pasted, so it always out of date

At least this is true in the past. I'm not sure if there's any changes.

**Comment by xponen** [comment]
KingRaptor report this as fixed by overwriting the Autoregistrator
closing.

**Comment by KingRaptor** [comment]
It's back. Apparently DB migration issues are blocking the updates.

**Comment by Licho1** [comment]
hmm right its accessing db directly, it needs to be put to auto deployment too
