### ISSUE TITLE
ZKL: Json couldn't save Hash, ZK redownload everytime ZKL startup

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K-Infrastructure#359]
Here is a crude sequence of event:

1st, ZKL download mod name & Hash as Hex 
2nd Translate hash written in Hex into Byte:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaDownloader/Packages/PackageDownloader.cs#L430
3rd. Compare with cached Hash Byte (which is empty)
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaDownloader/Packages/PackageDownloader.cs#L433
4th trigger download.

Is Empty because JSON doesn't seem to save the Byte. So when its re-read it will always be empty string.

If we fix this we need to redeploy everything again IMO.

**Comment by xponen** [comment]
will try fix soon if nobody tries.

**Comment by Licho1** [comment]
Wow, great catch xponen!

**Comment by xponen** [comment]
wow, this is quite humbling. You seem to solve this flawlessly with just 1 line fix :O
