### ISSUE TITLE
Make friendlist take up less space

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#361]
I suggest adding +/- expand/minimize buttons for the friendlist and splitting online/offline, so for example I can expand the list of online and minimize the list of offline friends.

Another option would be a small "Settings" button on the channel/friendlist and adding things like "hide offline players", etc. there.

**Comment by Licho1** [comment]
Its target of full rewrite so this isnt needed atm
