### ISSUE TITLE
!subscribe circumvents access

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#362]
!subscribe does not check user's access to the channel so you can still read channels you don't have access to.
Affected are #zktop20 and Planet Wars faction channels.

**Comment by xponen** [comment]
found the code to block access here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/NightWatch/OfflineMessages.cs#L153 not sure if I should try do it

**Comment by KingRaptor** [comment]
#zktop20 can probably be left unsecured.

Should clan channels be protected as well?

**Comment by KingRaptor** [comment]
Blocked subscriptions to faction channels in fa08219dc192c6c92b79aaa9efb2117922cc8e7e. Decided not to bother with top20 since read-only there is pretty harmless.

**Comment by Licho1** [comment]
A bit of waste of time, it will go away .. . entire nightwatch will be gone soon...
