### ISSUE TITLE
Account deletion does not stop post search

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#370]
This still works:
http://zero-k.info/Forum/SubmitSearch?username=[AG]abma

**Comment by abma** [comment]
for me it looks like account is just disabled, not deleted :-|

**Comment by KingRaptor** [comment]
Deleting account outright isn't practical I think (leaves holes in all sorts of things like battle records). Stuff like passwords can (and should) be scrubbed though.
