### ISSUE TITLE
forum @-playerID broken

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#372]
see this: http://zero-k.info/Forum/Thread/11419

thats a duplicate account of me from when time began. my alias is not regarded here as fitting the @-ID 

old 
http://zero-k.info/Users/Detail/200661
current:
http://zero-k.info/Users/Detail/201951

**Comment by abma** [comment]
same applies for contributions:
http://zero-k.info/Contributions

i'm pretty sure ChanServ didn't donate ;)

**Comment by Licho1** [comment]
Chan serv is user that wanted to be anonymous...

2015-01-19 18:10 GMT+01:00 abma <notifications@github.com>:
