### ISSUE TITLE
LobbyID and LobbyTimeRank was lost when moving to new lobby server

### ISSUE THREAD

**Issue by dansan** [ZeroK-RTS/Zero-K-Infrastructure#383]
Is there any way to merge the info back into the DB for the existing users, until the old lobby server has an interface the replay site can use for login check?

```
dansan = client.service.GetAccountInfo("dansan", "SECRET")
>>> dansan
(AccountInfo){
   Aliases = "[f6]Dansan,Dansan,LovePeaceAndHarmony,dansan"
   Avatar = "seismic"
   ClanID = 0
   ClanName = None
   Country = "DE"
   EffectiveElo = 1091.98034668
   Elo = 1491.98035
   EloWeight = 1.0
   FactionID = 0
   FactionName = None
   IsLobbyAdmin = False
   IsZeroKAdmin = False
   LobbyID = 0
   LobbyTimeRank = 0
   Name = "dansan"
   SpringieLevel = 1
   ZeroKAccountID = 152636
   ZeroKLevel = 0
 }
```

-->
```
   LobbyID = 0
   LobbyTimeRank = 0
```

**Comment by Licho1** [comment]
sadly time ranks got deleted from zk database so i cannot provide them, but lobby ids were still stored for backup purposes.

**Comment by dansan** [comment]
Cool - thanks - that was fast! Time ranks are not so important.

I have opened a ticket on uberserver, so that it may provide it's own interface in the future: https://github.com/spring/uberserver/issues/133

**Comment by dansan** [comment]
You can close the service if you like. The replay site has switched to a xml-rpc service by official uberserver just now (https://github.com/spring/uberserver/issues/133 , https://github.com/dansan/spring-replay-site/commit/60b7544bf56466d623ee9eb4742dadc00048652e). Thank you for the support.

**Comment by Licho1** [comment]
Ok, thanks!

**Comment by Anarchid** [comment]
The issue was *reopened* on Feb 10th after @dansan reported it as no longer necessary.

Should a new issue be made to shutdown the service, or was this accidental?

**Comment by Licho1** [comment]
closing its fine now
