### ISSUE TITLE
zk lobby server has no default engine set / protocol prompt broken

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#385]
zk server:
TASServer 1.3.1.14  * 8201 0

official server:
TASServer 0.36 98.0 8201 0

already in the first command it breaks spec. lobby protocol 1.3.1.14 isn't defined also empty version isn't defined in spec as well :-|

**Comment by abma** [comment]
hm, side note: is it worth to fix such things to keep compatiblity or better work on sth. like melbot?

**Comment by Licho1** [comment]
These are minor issues i will fix. Stuff I will add in foreseeable future will be additions (to remove need for #extensions) so stuff should not just break...
Also I didnt know 0.36 is protocol i thought its just server version so i let it show build number

**Comment by abma** [comment]
ok, thx.

idk if it was at some point server version, but docs to it are clear:
http://springrts.com/dl/LobbyProtocol/ProtocolDescription.html#TASSERVER:server

i've just noticed because this minor issue because of https://github.com/cleanrock/flobby/commit/cd229f7289e200045067ed9c518f77f8016e3f9d
