### ISSUE TITLE
Springie !spawn is not functioning

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#386]
This prevents all custom games from being started on ZK server.

There is no response from Springie when issuing a correct !spawn; no spawn happens, and no clues i can see pop up in server logs.

**Comment by Licho1** [comment]
Unable to replicate atm, please reopen when it happens again and report host which does not respond to !spawn

**Comment by Anarchid** [comment]
Figured it out, collusion between SWL-side issue (no more Platinum) and slightly incorrect !spawn params with no error return (!spawn mod=zk:stable fails silently, !spawn mod=zk:stable,title=lol works)
