### ISSUE TITLE
VPN bans don't work properly

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#389]
On the ZK administrator channel, the message about a VPN ban thwarting an account was observed. However, it obviously still got through because the user was able to join a battle room. Here's the account in question: http://zero-k.info/Users/AdminUserDetail/348526

**Comment by Licho1** [comment]
what was the vpn message it produced in lobby?

**Comment by Sgathec** [comment]
Yes, in Zero-K Lobby on the admin channel.
