### ISSUE TITLE
Resign vote only requires half of players to vote

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#395]
Should be more than half of players.

Example: http://zero-k.info/Battles/Detail/324729

**Comment by MLanghof** [comment]
Weird.
[this](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/807b06606fd4e96c1004dfd7793dafade0bdc48f/Springie/Springie/autohost/Polls/VoteResign.cs#L29) should already do it correctly, but apparently it counted only one active, non-spec player on your team in that foreach loop right before that line.

**Comment by DeinFreund** [comment]
After seeing this happen a few more times it seems to me like players with springiee rights 1 (== lvl < 20) are not counted but are allowed to vote. If this is right, either these players should be counted or excluded from the vote.

**Comment by KingRaptor** [comment]
There is no check for rights level in the code deciding how many voters are needed.
