### ISSUE TITLE
Make battleroom relay obey mutespec modoption

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#411]
Low priority issue. It is here to remind us what could be done.

There is a modoption called mutespec. When this modoption is enabled Springie should not relay any of the non-player chat to the battleroom. Detecting when it is enabled is not as easy as reading a boolean. It has three states.

If mutespec = 'mute' then it is enabled.
if mutespec  = 'autodetect' and there are at least 3 allyTeams (not counting gaia, but Springie wouldn't know about gaia) then it is enabled.

**Comment by Licho1** [comment]
Im not sure i like such long term, low prio tickets it will end up like google code with hundreds of tickets nobody will look at..

**Comment by KingRaptor** [comment]
Still relevant?

**Comment by GoogleFrog** [comment]
Yes.
