### ISSUE TITLE
Mission editor cannot get mission list

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#418]
When opening the publish menu:
`Could not get mission list: The requested service, 'http://zero-k.info/MissionService.svc' could not be activated. See the server's diagnostic trace logs for more information.`

**Comment by KingRaptor** [comment]
`An error occurred while receiving the HTTP response to http://zero-k.info/MissionService.svc. This could be due to the service endpoint binding not using the HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.`

**Comment by Licho1** [comment]
If you run it locally what is the exception?

**Comment by Licho1** [comment]
Also if you were devving locally as it set GlobalConst.Mode = Live ?

**Comment by KingRaptor** [comment]
GlobalConst.Mode = Live yes

When I tried with Mode = ModeType.Local instead:
`There was no endpoint listening at http://zero-k.info/MissionService.svc that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.`

With test mode the response is just `<HTML></HTML>`

**Comment by Licho1** [comment]
You need to set "startup project" to multiple and also let it start website.

I suspect that the released editor is using "local' or "test" mode instead
of live?

2015-02-17 16:06 GMT+01:00 L.J. Lim <notifications@github.com>:

**Comment by Anarchid** [comment]
`http://zero-k.info/MissionService.svc` suggests it should be Live

**Comment by KingRaptor** [comment]
Earlier, sheep made Sortale try it out while monitoring web traffic. I don't recall the precise details, but apparently the server sends a status code 100 and then the client does nothing instead of proceeding with the request. 

Should we try disabling ServicePointManager.Expect100Continue? ([example](http://stackoverflow.com/questions/15341287/expect-100-continue))

**Comment by Licho1** [comment]
Yeah feel free to disable it, we also have it disabled in ZKL

2015-06-30 11:26 GMT+02:00 L.J. Lim <notifications@github.com>:

**Comment by KingRaptor** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/MissionEditor/MissionEditor2/MainWindow.xaml.cs#L55
```C#
static MainWindow()
		{
			MissionProperty = DependencyProperty.Register("Mission", typeof(Mission), typeof(MainWindow));
            System.Net.ServicePointManager.Expect100Continue = false;
		}
````

Dinnae work :(

`svcutil.exe http://zero-k.info/MissionService.svc?wsdl` gives the following output.config: http://pastebin.com/w2qjf0sZ
(test one is the same except URL goes to test.zero-k.info)

I don't see anything obviously wrong with it...

**Comment by db81** [comment]
Also http://wsdlbrowser.com/p/88a0995f51f41bb247eee9806d8448b2 and http://wsdlbrowser.com/p/e05bfbe3365c91a52ab5162253f77f80.

**Comment by Licho1** [comment]
fixed
