### ISSUE TITLE
LICHO TODO - update data on zkinfo Contributions

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#421]
- cost 2014
- is server data actual? any changes from sping split for server etc
- please verify given information (anything i missed)

**Comment by abma** [comment]
*bump*

http://zero-k.info/Contributions still isn't up to date!

**Comment by mojjj** [comment]
@Licho1

**Comment by abma** [comment]
this isn't fixed yet, still
"2014 	pending"

**Comment by abma** [comment]
http://zero-k.info/Contributions

**Comment by Licho1** [comment]
Yeah its not yet deployed, this ticket reflects state in master, I will deploy to stable today.

**Comment by abma** [comment]
aah, ok. thanks! :)

**Comment by Licho1** [comment]
Its there now
