### ISSUE TITLE
!voteresign didn't work in this game:

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K-Infrastructure#427]
http://zero-k.info/Battles/Detail/327256

me and my ally had !voteresign in ally chat and global chat, but the server just didn't respond. Also, GoogleFrog visited the game briefly, not sure what GoogleFrog saw, but he left early.

**Comment by let4be** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/266

**Comment by xponen** [comment]
Related: http://zero-k.info/Forum/Thread/11659

In my case it didnt respond at all.

Maybe in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/266 Springie forgot all command  because its restart. Just a guess

**Comment by let4be** [comment]
I suspect the reason:
when someone quit the room, voteresign stops working for this team
we had all the evening with this bug yesterday

**Comment by xponen** [comment]
Found suspected code. Will tell it to handle player who quit lobby

For reference: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Springie/Springie/autohost/Polls/VoteResign.cs#L26 

Will go check if all other !vote code is same too...

**Comment by Licho1** [comment]
Just please no more stupid hacks like changing the vote code.. there is a context that contains all the data about game. Whole springie needs rethinkg,redesign also for quickmatch, don't fix this symptom only without looking at big picture.

**Comment by xponen** [comment]
Is not too much hack Licho1, 

The votecode read player list from Spring, but it ask Springie whether player is AFK. IMO this check can be skipped if player disconnect from lobby because no lobby to tell Springie if player is AFK anymore.

**Comment by let4be** [comment]
Good job @xponen :)
I really hope this this will be fixed, it's super annoying
