### ISSUE TITLE
nightwatch "bridge" login spam

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#436]
Nightwatch does a login spam to lobby.springrts.com:

"Failed to log in user Nightwatch: Invalid password", every 5 seconds.

but it is already logged in.

because of test.zero-k.info?

**Comment by Licho1** [comment]
yes because of test zero-k info i will try to change it somehow for test...

**Comment by abma** [comment]
use lobby.springrts.com:7000 (=lobbydev server) maybe?

its not always running, but maybe the better choice.

**Comment by Licho1** [comment]
ok good idea
