### ISSUE TITLE
http://zero-k.info/ContentService.asmx broken

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#437]
because of that TASClient can't download any more and pr-downloader fails in some cases.

did the url change or how to fix the clients?

also http://zero-k.info/ContentService.asmx?WSDL is empty

thats how it looked some time ago:
https://github.com/spring/pr-downloader/blob/master/src/lib/soap/ContentService.wsdl

http://springrts.com/phpbb/viewtopic.php?f=64&t=32978

**Comment by Licho1** [comment]
Its url was changed to http://zero-k.info/ContentService.svc
also return value changed container for download file.

**Comment by Licho1** [comment]
(It was upgraded to more modern .net serice technology
