### ISSUE TITLE
ZKL: Player list scroll issue on Mono

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#441]
> [Anarchblah1] when I scroll down in the player list in chat, I can't get all the way down
> [Anarchblah1] some miscalculation in the playerlist size
> [Anarchblah1] oddly enough it seems to get worse when the window is larger
> [Anarchblah1] when I make the window bigger to see more names, I can't scroll down as far and ironicly see fewer names iirc

**Comment by xponen** [comment]
okay, this is related to this: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/283 

(I thought adding 3 fake name would workaround it)

**Comment by Licho1** [comment]
Thats why its always best to find root cause and fix that...

**Comment by xponen** [comment]
I'll go debug it again, maybe it need to force set the item size or something...
