### ISSUE TITLE
broken !subscribe ordering

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#442]
still happens

**Comment by xponen** [comment]
I did some experiment that could help with debugging.

A sequence of number will:
arrive ordered = if I PM-ed an offline player by typing the number 1 by 1
arrive with some off sequence = if I copied-pasted the numbers instead

PM can be used to verify the bug.

**Comment by Licho1** [comment]
It will most likely fix itself with new server

**Comment by Anarchid** [comment]
This was ZKL side issue (message was received in server tab)

**Comment by Anarchid** [comment]
Server is now upgraded, the issue is still present for both reactSWL and ZKL.

**Comment by cleanrock** [comment]
I am unsure if this ticket is about broken !subscribe command or the order of the messages, i think xponen is talking about the order of messages.
To fix the message order i think adding OrderBy to OfflineMessages.cs will fix it.
Add .OrderBy(x => x.Created) before .ToList(); to the lines (50 and 233) with db.LobbyMessages.Where.

**Comment by cleanrock** [comment]
This is fixed by 42b2693.The last days Nigthwatch subscription messages have been in correct order.

**Comment by Anarchid** [comment]
Closing as such.
