### ISSUE TITLE
numerous new lobby bugs / strange behaviours

### ISSUE THREAD

**Issue by KlonZK** [ZeroK-RTS/Zero-K-Infrastructure#446]
since about a week ago or two:

- when tabbed out, chat directed at me will appear in a bubble window in the windows taskbar as usual. however, upon returning to the lobby that message will not appear in the chat history.

- sometimes i will not sync with the lobby even when map is present. i have seen this with other people,  but it never happened to me once until lately (now every second game or so in team games)

- general laggyness when chatting or entering commands such as votes etc. seems to be much more frequent now

- sometimes it is possible to start/change map etc. without calling a vote. suspect this can only happen in a 2 player game and the reason is that the player count is not properly updated.

**Comment by knorker** [comment]
> "sometimes i will not sync with the lobby even when map is present"
One way to (sometimes) reproduce it:

1) host new private room

2) use !map to change to a map you know you have

3) use !map to change to a map that will need to be downloaded

4) After the download is done, sometimes the map will still not sync 
( https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/752 )

But more: Even if you now use !map to change to the previous map, that map that previously worked will now show as unsynced too.

**Comment by Licho1** [comment]
Unable to replicate..When it happens please check the log, it should look like 
02/02/2016 20:56:14: starting download Zed 2.2
02/02/2016 20:56:14: Download started: Zed 2.2
02/02/2016 20:56:32: Zed2.2.sd7 Completed - 41.30M
02/02/2016 20:56:34: Adding Zed 2.2
02/02/2016 20:56:34: New resource found: Zed 2.2
Post anomalies. This is probably a low priority because we will distribute maps with steam.

**Comment by KlonZK** [comment]
points 1 and 2 of the original report are still there for me. especially the thing with the lost messages is rather annoying.

**Comment by knorker** [comment]
why was this closed?

**Comment by Licho1** [comment]
Ticket should not contain multiple bugs afaik there are other tickets dealing with poi9nts 1 and 2 and those are closed as well.
