### ISSUE TITLE
a typo in ZKL's Post Build Event or is intended?

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K-Infrastructure#452]
I saw postBuildEvent contain text "targetPlatform=v4.5" while other stuff contain text "v4.5.1" 

here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZeroKLobby/ZeroKLobby.csproj#L1653

**Comment by Licho1** [comment]
This is on purpose. Platform is v4.5 - as in "runtime version" and lib version is 4.5.1. Runtime didnt change only libs changed in 4.5.1.
We will also change ilmerge to libz because it works better.
Ilmerge zklobbyserver didnt work.
https://libz.codeplex.com/
