### ISSUE TITLE
a lot of engine downloads by zk-lobby fail

### ISSUE THREAD

**Issue by abma** [ZeroK-RTS/Zero-K-Infrastructure#457]
thats just one example, there are several others:
(removed ip)
 - - [02/Feb/2015:17:44:57 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:17:53:47 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:17:57:14 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 11906400 "-" "-"
 - - [03/Feb/2015:18:00:07 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:18:02:07 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:18:04:25 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:18:09:02 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:18:12:00 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 28245868 "-" "-"
 - - [03/Feb/2015:18:13:27 +0100] "GET /dl/buildbot/default/master/91.0/spring_91.0_minimal-portable+dedicated.zip HTTP/1.1" 200 8447736 "-" "-"

please fix, this costs a lot of bandwith and very likely also causes users to be frustrated.

it seems zkl aborts download. or maybe fails to extract and downloads again? idk the code :-)

also it would be good if zkl sets a proper user-agent with version-number so such issues can be better debugged.

**Comment by abma** [comment]
also: please use .7z file as it is a lot smaller!

**Comment by Licho1** [comment]
Odd are you sure its same client? There is no code that would cacnel download. 
ZKL cannot use 7z because there is no managed 7z library :-(

**Comment by abma** [comment]
yes, all downloads are from the same ip. meh, ok, sad there is no 7z lib. :-|

**Comment by Orfelius** [comment]
It could be just a connection issue. Happens from time to time :)

**Comment by abma** [comment]
in 5 days ~80 ip's with the same problem? imo no. also the download seems to be completed in some cases but it was restarted regardingless of that.

**Comment by Licho1** [comment]
yeah version agent is good idea also maybe ip can be resolved back to player

**Comment by abma** [comment]
please add agent first, contacting people still can be done if no error can be found.

**Comment by Licho1** [comment]
Closing until further data gathered with client name.

**Comment by abma** [comment]
send you an email with access.log.

in ~24 hours again ~20 unique ip's which in most cases seems to have downloaded the engine multiple times sucessfully. some clients already used the user-agent, so happens in current version.

ideas what could fail here? for me this doesn't look like "usual" network problems as the transfer seems to completed but the file is downloaded again from the same ip.

**Comment by Licho1** [comment]
Really odd, i can't imagine the scenario. Every download has pretty visible download bar as well which would alert user if something wasnt right.

Is it possible it also lists HEAD requests?  ZKL first check for file presence using HEAD request.

**Comment by abma** [comment]
no, i've explicitly removed HEAD requests from the access.log.

they would show up as a line with HEAD (vs GET)
