### ISSUE TITLE
Offline singleplayer in ZKL

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#46]
Basic implementation: have a screen that lists all currently downloaded missions (ZKL will need to keep track of these) and displays related stuff (image, author, description, etc.). If connected, also show missions on site with download option; compare with local copies to determine if versions match. 

ZKL should consider automatically fetching and/or updating a selected set of missions (say all featured ones, or just the tutorials).

Basic implementation part 2: Skirmish mode with configurable game, map, bots, teams, modoptions, startboxes and such.

Later versions will also want a "load game" screen.

Campaign system will be left for a later project.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
