### ISSUE TITLE
Unable to load Java-SkirmishAIs using zkl

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#464]
When playing a game against a JavaOONullAI Spring 98.0 crashes when started via zkl, but not via springlobby.

infolog(missing crash :/): http://hastebin.com/siteqidoca.tex
startscript: http://hastebin.com/ridosuburi.avrasm

for comparison startscript when using springlobby(hosting): http://hastebin.com/okarohiquc.hs
what might be the issue is that the AI is missing in zkl's startscript.

**Comment by KingRaptor** [comment]
Was this on Springie? It worked in skirmish mode when I tested it.

**Comment by DeinFreund** [comment]
Yes on Springiee Teams

**Comment by Licho1** [comment]
Springie teams auto removes bots on startup.
Use open own battle

**Comment by DeinFreund** [comment]
Using forcestart of course.

**Comment by Licho1** [comment]
Even with force

2015-02-07 22:10 GMT+01:00 DeinFreund <notifications@github.com>:

**Comment by DeinFreund** [comment]
Tested it twice using "own" Springiee. The startscript is the same as is the crash.

**Comment by Licho1** [comment]
Works fine on 91.0
Please report engine crash to engine mantis, not related to ZK infrastructure.

**Comment by DeinFreund** [comment]
Already reported a similar issue to mantis(when using current develop it crashes with all lobbies)
http://springrts.com/mantis/view.php?id=4665

I reported this here because 98.0 works with springlobby but not with zkl. 
Still I would agree with waiting for the other issue to be fixed first as it might be related.

**Comment by Licho1** [comment]
You mean you tested with spring dedicated and SL? Because what you are
testing is not same. ZK spawns remote springie which has script and you
connect to it. Testing on SL is identical to doing skirmish in ZK

2015-02-07 22:45 GMT+01:00 DeinFreund <notifications@github.com>:

**Comment by DeinFreund** [comment]
Retried using two SL instances on different machines, one hosting the game the other one running the AI and it still works. In this case there is still a difference though, because the host is actually running the game unlike Springiee authosts.

**Comment by Anarchid** [comment]
> Works fine on 91.0

No. Just no. Java AI's don't "work" with 91.0, sorry.
