### ISSUE TITLE
Springiee retains someones' boss status even when boss is no longer present

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#465]
[19:58]  * Scandium Sorry, you do not have rights to execute voteboss, ask boss admin DeinFreund

Well this happened on Team's Bleeding Edge. It used to happen with Silent Shadow as well a couple of months back.

**Comment by Licho1** [comment]
Unable to replicate in tests, added boss clearing on reopen which should fix it

**Comment by Orfelius** [comment]
Nice :+1: 
Weird thing abaut it that it worked most of the time but sometimes it failed :\
