### ISSUE TITLE
AIs' teams can no longer be changed in the lobby

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#466]
To reproduce:
1) Open a room or join an existing room
2) Add CAI or other AI
3) Click on AI -> Ally with -> select any option
4) "Message from server
No permissions to edit bot Bot_1"

**Comment by Licho1** [comment]
worksforme

**Comment by Skasi** [comment]
You are the first person this works for. It does not work for Brynnlow, mojjj, Orfelius and me, we all get the same error message.

**Comment by Orfelius** [comment]
Happens to me as well.
Added AI. Clicked on it. Got popup menu and clicked on "Allywith". Chose "join Team 2".
Window popped out "No permisions to edit bot Bot_1"
Same happens when I want it to join new team

Bot type and boss status doesn't matter it just doesn't let me do anything with it.

**Comment by Skasi** [comment]
[ISP]Lauri reports it works for them. Thus I assume moving bots only works for people who are "more equal" than others (ie admins).
