### ISSUE TITLE
ZKL crashes to desktop without error message or obvious cause

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#469]
Often when I'm doing absolutely nothing (the last time I alt-tabbed away to work on stuff and when I came back it had crashed at some point).

(Win7 with ZKL 1.3.1.50)

**Comment by KingRaptor** [comment]
Just crashed before it even finished loading battle list.

**Comment by Licho1** [comment]
Need to know more, without log or repro step this report is meaningless...  it didnt crash for me yet either..

**Comment by Orfelius** [comment]
Did you have Steam open KingRaptor?
If so then it might be related to this #265 point 3. I have never managed to debug it properly.

**Comment by KingRaptor** [comment]
Steam was on, yes

**Comment by Orfelius** [comment]
The way it sometimes crashed was: ZKL was open. Steam was not. I launched Steam and sometimes it would crash ZKL without posting an error log.

**Comment by Licho1** [comment]
Is zklobbyerrors file empty? No report there?

2015-02-08 11:25 GMT+01:00 Orfelius <notifications@github.com>:

**Comment by KingRaptor** [comment]
This is the only thing I have from the relevant time period, don't know if it's even related to this particular issue.
`2015-02-08 1:21 AM
System.NullReferenceException: Object reference not set to an instance of an object.
   at ZeroKLobby.MainWindow.GetHoveredControl()`

**Comment by Licho1** [comment]
Thats just tooltip but i know what is your error.
Its a feature.
If you run with steam and close steam it closes ZKL, because it assumes ZK is just a steam game. Steam does it, no control over it. Its an ordinary "kill" therefore no log.
