### ISSUE TITLE
Springiees' vote requirements

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#474]
1. When there is only one active player in the room and someone places AI , spectator have a power to start the game regardless of !boss status.
2. When there are only two players in one team the votes required for !voteresign is only limited to one vote meaning that the player who invokes a vote can enforce resign on another player.
3. When there is a !boss in the room, no player other than boss can invoke a !voteresign.

All of these can be quite annoying for one or both parties. Especially when dealing with foul people.

Solutions:
Ad.1 Don't allow specs to invoke a !startvote unless they have! boss status or are an admin. Specs don't need that kind of function anyway as they are not playing the game at the current moment.
Ad.2 Increase of amount of votes needed to two in this instance
Ad.3 This one is quite obvious: just let other people do it when there is !boss around.

That about wraps it up. I hope this will get fixed :)

**Comment by DeinFreund** [comment]
Regarding point 2 you have probably played with Lynx in your team. This has been reported before: #395. If this is the same issue #395 can be closed.
