### ISSUE TITLE
Clean up duplicate accounts

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#485]
There are 516 cases of accounts in the DB having duplicate names due to case insensitivity. The "incorrect" ones should be removed.

Full list: https://www.dropbox.com/s/h3k6nnhxnywx2w1/duplicateaccounts.htm?dl=0
Alternative formats available on request.

After that we can set the name column in DB to case insensitive.

**Comment by KingRaptor** [comment]
Auto-termination code added in 40a2ec1b1f019d39557fec5b150df2994eaca7d6

**Comment by Licho1** [comment]
Probably not as important now. We can run it at any time. I also did significant clewanup (hundred thousand accounts) later
