### ISSUE TITLE
Springiee forcefuly spectacing players

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#488]
I was minding my own buisness and waiting for someone to show up then ivand approached and we meant to just start the game. But suddenly wild Faelthas approached and both me and ivand were forcefully spectated -.-
This has happened before too when I was waiting for someone to join the 1v1 room and when they did it autospectated me. That is a very annoying thing...

**Comment by Licho1** [comment]
need replication steps, not thrilling real life stories
