### ISSUE TITLE
Improved forum post search

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#49]
Basic capabilities: search for keywords, specific user, specific subforums, only look in first post

Advanced features: choose whether to display results as posts or topic; some other stuff I can't think of right now

Also there should be a link on profile page to find all posts by that user.

**Comment by KingRaptor** [comment]
http://zero-k.info/Forum/Search

**Comment by Licho1** [comment]
This will murder server, unless you index it. 
You should either enable fulltext indexes on searchable fields or implement indexing manually (table words - articles)
