### ISSUE TITLE
Connection problems.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#494]
The ZK server seems quite unstable for me. I have just been disconnected from the lobby twice in 20 minutes. The first time was a few minutes long and long enough for me to time out from ingame.

**Comment by Licho1** [comment]
Maybe some transient connection problems? ZK server hasnt been restarted for weeks, its very stable at low memory and CPU footprint. Server is idle. If it wasnt your ISP perhaps something with OVH company hosting.
Next time let me know exact time and i can check for mass disconnecfts if its recent.
