### ISSUE TITLE
Game Details presets set BumpWaterRefraction to 2

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#495]
The higher game details presets (Ultra, and maybe High) set BumpWaterRefraction to 2. This mode causes issues with commander names and can sometimes cause issues with underwater unit visibility as well.

The setting should probably never go above 1 in presets.

**Comment by Licho1** [comment]
Commander names can be fixed then im sure.

**Comment by xponen** [comment]
so, is there any reason against preset 1?
Wasn't BumpWaterRefraction 2 mean't that you can't even see unit underwater? this is bad for gameplay.
