### ISSUE TITLE
 !voteresetoptions have no effect

### ISSUE THREAD

**Issue by cleanrock** [ZeroK-RTS/Zero-K-Infrastructure#500]
I also noticed that help is a bit confusing, host says a setting is MetalMult but it fails, i have to type it in lower case (metalmult) and without spaces around = as help indicates.

**Comment by xponen** [comment]
probably related to https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/427
 
Is waiting for Springie to re-deploy.

**Comment by xponen** [comment]
the MetalMult is ZK setting, will fix it there.

**Comment by xponen** [comment]
should be fixed when Springie deploy later
