### ISSUE TITLE
SetRectangle message unclear

### ISSUE THREAD

**Issue by cleanrock** [ZeroK-RTS/Zero-K-Infrastructure#501]
This may be more of a question and i may be off but here it goes:
If i do !split commands i get more rects, i suspect the "Number" field is a rect unique number and shall replace previous rects with the same number and not the ally team identifier.
If this is the case it seem a bit limiting considering that spring games should support multiple start rects for an ally team.
Btw Licho,
I think you should add clarifying comments to message members in Messages.cs.

**Comment by db81** [comment]
It only supports a single startbox per ally team, and the Number field is the ally team.

Until now I didn't even know having several per ally team was supported. I've never seen that used in practice, sounds like an arcane use case that is not worth implementing.

**Comment by cleanrock** [comment]
I still think current behaviour is bugged:
If you change map you get clear rect messages:
SetRectangle {"Number":0}
I think messages like this should be sent first when you perform !split commands.

**Comment by cleanrock** [comment]
To be more precise this is what i see on map change:
D-15:58:27-Model.cpp:234] message: BattleUpdate {"Header":{"BattleID":1454,"Map":"Chicken_Nuggets_v4"}}
D-15:58:27-Model.cpp:234] message: SetModOptions {"Options":{}}
D-15:58:27-Model.cpp:234] message: SetRectangle {"Number":0}
D-15:58:27-Model.cpp:234] message: SetRectangle {"Number":1}
D-15:58:27-Model.cpp:234] message: SetRectangle {"Number":0,"Rectangle":{"Bottom":200,"Left":0,"Right":60,"Top":0}}
D-15:58:27-Model.cpp:234] message: SetRectangle {"Number":1,"Rectangle":{"Bottom":200,"Left":140,"Right":200,"Top":0}}

**Comment by cleanrock** [comment]
Looking at code i think AutoHost::ComSplit in AutoHosts_commands.cs should call tas.RemoveBattleRectangle for all existing rects before adding new rects.

**Comment by db81** [comment]
If you have 3 rects and do !split you get
```
SetRectangle {"Number":0,"Rectangle":{"Bottom":200,"Left":0,"Right":60,"Top":0}}
SetRectangle {"Number":1,"Rectangle":{"Bottom":200,"Left":140,"Right":200,"Top":0}}
SetRectangle {"Number":2}
```
so it does reset the rects properly.

Keep in mind that
```
SetRectangle {"Number":0,"Rectangle":{"Bottom":200,"Left":0,"Right":60,"Top":0}}
```
is semantically equivalent to
```
SetRectangle {"Number":0}
SetRectangle {"Number":0,"Rectangle":{"Bottom":200,"Left":0,"Right":60,"Top":0}}
```
because SetRectangle is add <i>or replace</i> rect.
