### ISSUE TITLE
Springie did not auto-deploy

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K-Infrastructure#503]
I checked http://zero-k.info:8080/project.html?projectId=ZeroK and the most recent commit weren't registered, and current Springie (I checked using ftp) is dated 13 February, which is older than the fix for https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/427 

need to deploy springie for the fix pls

**Comment by xponen** [comment]
maybe I should do this? https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/504

**Comment by Licho1** [comment]
What do you mean, master => test .. test springie should be deployed and ready for test zkl to play with.
Merging for stable releases it to main environment but you should certainly not release restart of planetwars...
