### ISSUE TITLE
!votemove disregards room passwords

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#509]
!votemove can be used to bypass the password of the target room. Just create a passworded room and execute !votemove \<passworded_room_bot_name\> on another host to test it out.

**Comment by mojjj** [comment]
confirmed. just got moved into a passwordwed game by springiee4

**Comment by Anarchid** [comment]
This is still the case. The goggles, they do nothing.

**Comment by Orfelius** [comment]
looks like it has been fixed. Close please.
