### ISSUE TITLE
Elerium unpredictably forces spectate mode

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#511]
Unspeccing in Elerium when another player is also unspecced will sometimes spectate the player. Additionally, one player is often suddenly spectated after the game completes.

The behaviour is not consistent: every so often it "fails", which allows games to be played between the same pairs of people who were just seconds ago specced by Springie.

**Comment by dvr333** [comment]
It seems to happen whenever a player joins the room. Whoever was in team 2 is usually fine, and whoever was in team 1 is specced.

**Comment by maackey** [comment]
Just happened to me now, I unspecced and was placed momentarily in team 2 - the same team where Saktoth was (although I strongly suspect he was AFK)

I tried to unspec again and was almost immediately set back to spectator. After forcing Saktoth to spectator (!spec Saktoth) I was able to unspec and sit waiting for a game.
