### ISSUE TITLE
BattleUpdate is sent after BattleRemoved

### ISSUE THREAD

**Issue by db81** [ZeroK-RTS/Zero-K-Infrastructure#514]
Occasionally the following can happen:

```
[IN] LeftBattle {"BattleID":2679,"User":"Springiee8"}
[IN] BattleRemoved {"BattleID":2679}
[IN] BattleUpdate {"Header":{"BattleID":2679,"SpectatorCount":1}}
```

**Comment by cleanrock** [comment]
I noticed this now too:
$ grep -w 222 ~/flobby_zk/flobby.log 
D-16:37:11-Model.cpp:239] message: BattleAdded {"Header":{"BattleID":222,"Engine":"98.0.1-398-g80e6cfa","Game":"Zero-K v1.3.3.2","Map":"Small Supreme Islands V2","MaxPlayers":20,"SpectatorCount":2,"Password":"?","Title":"Battle","Port":8759,"Ip":"94.23.171.71","Founder":"Springiee3"}}
D-16:37:11-Model.cpp:239] message: JoinedBattle {"BattleID":222,"User":"Solenostomus"}
D-16:37:11-Model.cpp:239] message: JoinedBattle {"BattleID":222,"User":"Springiee3"}
D-16:39:31-Model.cpp:239] message: LeftBattle {"BattleID":222,"User":"Solenostomus"}
D-16:40:16-Model.cpp:239] message: LeftBattle {"BattleID":222,"User":"Springiee3"}
D-16:40:16-Model.cpp:239] message: BattleRemoved {"BattleID":222}
D-16:40:16-Model.cpp:239] message: BattleUpdate {"Header":{"BattleID":222,"SpectatorCount":1}}
W-16:40:16-Model.cpp:572] failed to process server msg:'BattleUpdate {"Header":{"BattleID":222,"SpectatorCount":1}}' (battle not found:222)

**Comment by Licho1** [comment]
fixed/not relevant?
