### ISSUE TITLE
!voteresign is disabled when there is a boss in the room

### ISSUE THREAD

**Issue by blah1** [ZeroK-RTS/Zero-K-Infrastructure#516]
Steps to reproduce:
-Have a boss in a springiee room that is not yourself
-attempt to !voteresign

Expected Result: A resign vote is started

Actual Result: "You are not allowed to execute voteresign, ask boss admin [USERNAME]" and the boss laughs at you while they take their time finishing off your base

I don't see a practical use for this

**Comment by blah1** [comment]
This is during a match, of course

**Comment by sprunk** [comment]
Fixed
