### ISSUE TITLE
lobby - open local replay

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#524]
lobby shoub be able to open local replay (open file dialog?), look by itself for correct engine and map and start it.

**Comment by Licho1** [comment]
This is a feature request. It's low priority and not on checklist for steam release. If anyone want's to implement this one can with or without this ticket.
Closing.

**Comment by knorker** [comment]
> checklist for steam release

link?

**Comment by Licho1** [comment]
Err...

**Comment by xponen** [comment]
I have it ready, in secret. I worry can't release it yet because problem with merge to new ZKL, and I'm not yet pros at new ZKL.... 

can I add it at mean time? hopefully when merging you can override later?

**Comment by xponen** [comment]
fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/540

**Comment by xponen** [comment]
added it at /extra/history
