### ISSUE TITLE
Setengine kicks everyone from the room without joining them to the new one.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#528]
This is important for current development.

**Comment by db81** [comment]
This should be easy to do, with the new protocol you don't have to close and reopen the battle to change the engine. Same goes for mod updates and the BETA TEST room.

**Comment by sprunk** [comment]
Does this still happen?

**Comment by GoogleFrog** [comment]
Probably. You can check. Rehost for game version also kicks everyone.

**Comment by Licho1** [comment]
fixed
