### ISSUE TITLE
ZKL intermittently starts DefaultOverride engine instead of room specified engine

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#529]
Probably tied to server version somehow. Some chat reports:

```
16:53:37	Svatopluk	now it's starting spring 91
16:53:47		+ now crash
16:54:18		Anarchid infolog.txt useless, it just started wrong spring version
16:54:23	Anarchid	wow that's a serious bug
16:54:45	Svatopluk	now rejoin room + rejoin game = starting correct, 98 spring
```

```
16:55:33	ivand	sometimes it tries to start version of engine you !setengine'd prior to the recent !setengine
16:55:53		like you !setengine 88.0 firstly
16:56:00		then !setengine 91.0 next
```

**Comment by xponen** [comment]
might be problem with ZKL in XP
I just got ZKL-log from Huj, trillion of errors with Async stuff, will have to read slowly
rghost.net/7h5jHc2PC

**Comment by Anarchid** [comment]
This is unlikely to be an XP issue since i'm pretty sure ivand and svatopluk have newer versions.

Additionally, this issue is probably solved and i'm only keeping it open for a couple more days just in case. There have been no recurrent reports of 91.0 being launched since the default version of everything was set to 98.0.1-398 in GlobalConst.

**Comment by Anarchid** [comment]
Hmmm actually if this happens again, it can be reopened. One day is probably enough data to suggest it being fixed, since it was super prominent when it was occuring.

**Comment by Anarchid** [comment]
This still happens, as engine version progresses with new awesome fixes and bugs.

Consequently, people complain about desyncs when they shouldn't.

**Comment by xponen** [comment]
will keep an eye on subtle trigger, this will take some time.

**Comment by Licho1** [comment]
dont bother with subtle trigger, its destined for full rewrite, let me know if you are interested i can explain in chat

**Comment by xponen** [comment]
found it resetting to default in Skirmish tab, is investigating

**Comment by xponen** [comment]
probably only happen to ZKL net4.0
fixed and copy+pasted new build at zero-k.info/www/lobby as  ZKL ver 1.3.2.62 (net4.0)
