### ISSUE TITLE
channel spamprotection

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#530]
people keep pasting texts larger than yo momma in #zk. these can be both chat log reports (when they dont know about report) and infologs (when they crash). these already happen quite a lot and with the clueless steam hordes is going to be even worse.
- spam protection needs to exist
- the automatic spam protection mute message could contain a link to pastebin
- a way to automatically upload crash infologs would be good (steal from SWL)
- manual !mute (not through the site punishment api) could be useful but not that important

**Comment by Licho1** [comment]
Note to implementer, its trivial to throttle on entry point -> simply prevent processing and sleep if threshold is reached.
No mute /kick is needed.
