### ISSUE TITLE
107 000 accounts cannot be used

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#533]
There are over 100k accounts which have no password in the system -> nobody can use them to log in.
Yet many of those cannot be deleted because they have associated records ("games played").

What to do with them?

**Comment by sprunk** [comment]
do they have passwords in the test db or in the old spring uberserver db? if yes then maybe copy passwords from there.

**Comment by abma** [comment]
delete them...

**Comment by db81** [comment]
It would be nicer if the ex-user's name was shown instead of {redacted} so you could at least tell one deleted user from another.

How did the passwords end up being lost in the first place?

**Comment by Licho1** [comment]
They were never known to old ZK infrastructure. 
Deleting is not trivial because they ahve associated data (foreign keys)..
So most of them cannot be deleted ..

**Comment by sprunk** [comment]
Can data be redirected? Make 1 account called "deleted" and change associated data (battles etc.) from the old accounts to point to the new account.

**Comment by Licho1** [comment]
Problem is "name" is unique key (in many places due to legacy stuff still -
like within game, so it blocks possible names .. or you need to rewrite
lots of stuff to make everything strictly numeric id based

2015-03-07 21:57 GMT+01:00 sprunk <notifications@github.com>:

**Comment by Anarchid** [comment]
This is difficult to solve, it seems. However, is it anyhow harmful?

I'll wait a week and close otherwise.

**Comment by sprunk** [comment]
A month has passed. Close?

**Comment by Orfelius** [comment]
I somehow feel like user database should be reset before the Steam launch to make space for new accounts.

**Comment by Anarchid** [comment]
This is stale. There are enough rows.
