### ISSUE TITLE
A bantha and two buildings disappeared until bantha was completed

### ISSUE THREAD

**Issue by christopherreay** [ZeroK-RTS/Zero-K-Infrastructure#534]
![screen00000](https://cloud.githubusercontent.com/assets/239550/6516425/b5598e52-c389-11e4-8727-60de58d761f8.png)

in game: 
http://zero-k.info/Battles/Detail/336402

shadows are still there.

**Comment by Licho1** [comment]
It looks like engine bug please report to mantis here https://springrts.com/mantis/my_view_page.php
along with infolog and engine version.

**Comment by Licho1** [comment]
BtwI had that too at some point on ati in the past

**Comment by Anarchid** [comment]
Also this o rsomething similar was happening on Evo even on nvidias at some point.
