### ISSUE TITLE
zk.info replays - not saved correctly, 0kb file size

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#536]
win8.1

downloaded sdf file has %20 instead of space in the name and file has 0kb, looks not downloaded, only created, so zkl claims not to find the corresponding engine version.
see
http://i.imgur.com/msIYrvm.png
the locally saved copy has some size and a space in the name, the "watch replay->downloaded" copy has %20 instead and size = 0kb

howto reproduce:
goto 
http://zero-k.info/Battles/Detail/336885
click "watch replay"

the button is built at the file 
Zero-K.info/Views/Battles/Detail.cshtml

the button says:
href="javascript:SendLobbyCommand('@start_replay:http://zero-k.info/replays/20150308_010014_Intersection_v3_98.0.1-398-g80e6cfa develop.sdf,Zero-K v1.3.3.2,Intersection_v3,98.0.1-398-g80e6cfa');void(0);"

the engine version is given witht he link, so i assume the problem is with the file download.

----

the problem occurs strangely only with battles i have a local copy (was player/spec), not for battles of other which have also the %20 in the name, but size is > 0kb

**Comment by mojjj** [comment]
a check before the download of the sdf, if the replay file exists, should do the trick i guess.

**Comment by KlonZK** [comment]
http://zero-k.info/Battles/Detail/337426

there is no local copy of it, and it has the 20 in the name.

**Comment by mojjj** [comment]
confirm. also the manually DL (which has not the %20 in the name) has 0kb 

so it is another problem than i suspected above.

**Comment by xponen** [comment]
%20 in filename should still play. Only the 0kb will prevent play IMO

**Comment by KlonZK** [comment]
i dont have original local replay anymore and deleted any 0 kb size copies, but the download button will only produce another 0 kb copy.

**Comment by xponen** [comment]
probably the server didn't save the replay properly. We had same issue long ago but don't remember how it was solved...

**Comment by Anarchid** [comment]
Do you mean the previous issue which was that springie was never sending a /kill event to the game, which prevented replays from ever being written unless written incrementally with game running (e.g. 91.0 behavior) ?

**Comment by xponen** [comment]
yes. I test download it, it is really 0 byte, empty.

**Comment by Anarchid** [comment]
This is a different error mode, then; the file is created, but has zero length.

With the old bug, it would not have been created at all.

**Comment by mojjj** [comment]
bump the priority up on this please. or someone guide me how to research the cause (guide to setup required infrastructure)

tournamennt broken replays:
http://zero-k.info/Battles/Detail/340371
http://zero-k.info/Battles/Detail/340382
http://zero-k.info/Battles/Detail/340381
http://zero-k.info/Battles/Detail/340390
http://zero-k.info/Battles/Detail/340391

**Comment by Anarchid** [comment]
you shuold be able to just checkout Zero-K-Infrastructure, compile it in visual studio, and get a locally running site, lobbyserver, lobby that connects to it, springies, etc.

**Comment by Licho1** [comment]
Replay is generated by spring_dedicated and not touched by other stuff, it looks like engine bug report case.

**Comment by Anarchid** [comment]
The last time it turned out to not be an engine bug. Worth at least checking up under what conditions this happens, before mantising.

**Comment by Jamanno** [comment]
engine change it bug still exists. And it is a really annoying bug.

**Comment by mojjj** [comment]
still open :/

http://zero-k.info/Battles/Detail/371655

**Comment by Anarchid** [comment]
@Jamanno i think you missed a negation in my previous post.

**Comment by Jamanno** [comment]
I see, sorry. Yes. 
Bug still there.

**Comment by mojjj** [comment]
did someone delete the server files with 0kb? because you get not .net error file not found

http://zero-k.info/replays/20150704_181413_Icy%20Run%20v2_99.0.1-20-gc999972%20develop.sdf

Server Error in '/' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly.

Requested URL: /replays/20150704_181413_Icy Run v2_99.0.1-20-gc999972 develop.sdf

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.6.81.0

**Comment by Anarchid** [comment]
A better question: does the 0kb plague still occur? An attempted fix was deployed yesterday.

**Comment by Anarchid** [comment]
Seems fixed; refer to #743 for additional info.
