### ISSUE TITLE
ZeroKLobbyErrors.txt insanely huge

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#537]
https://github.com/ZeroK-RTS/Zero-K/issues/612

**Comment by xponen** [comment]
reported as fixed

**Comment by KlonZK** [comment]
i just deleted a 2.66 gb ZeroKLobbyErrors.txt from my computer, so i wonder if that actually was fixed? i use current lobby.

**Comment by Licho1** [comment]
I would need to see what was inside it .. at least a sample that is :)

**Comment by KlonZK** [comment]
i deleted it and cleaned the trash bin, sorry. the snapshot view showed some error message stuff, so as far as i can tell it was just the accumulated errors of 3 years playing zk.

**Comment by Licho1** [comment]
its fixed in current code (limited to 50mb) maybe you had older ZKL running?
