### ISSUE TITLE
users affected by #512 still have no avatar

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#543]
users who got no avatar on creation (issue #512) still haven't received a replacement.
for example http://zero-k.info/Users/Detail/350532

**Comment by Anarchid** [comment]
You get to pick one avatar for the Lost Generation because i cba to randomized query.

**Comment by sprunk** [comment]
Missile silo (mostly because no regular forum dweller has that)

**Comment by Anarchid** [comment]
(1214 row(s) affected)
