### ISSUE TITLE
a Download form for welcome_screen

### ISSUE THREAD

**Issue by xponen** [ZeroK-RTS/Zero-K-Infrastructure#550]
excerpt from https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/549

Licho: ... dialog which shows all pending downloads and auto hides when they are done and allows. Best in welcome_Screen branch.

current welcome_screen design didn't have space allocated for download bar.

**Comment by db81** [comment]
The wiki seems to be the proper place to put design concepts for welcome_screen. (presumably @xponen made the issue as a reminder for himself, but he seems to have disappeared)
