### ISSUE TITLE
Ubuntu: ZKL lags massively when opening new chat tabs; randomly closes

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#568]
It drops my _desktop UI_ to what feels like 5 FPS. When starting up ZKL this can last for several minutes. 
Also it randomly closes itself (I can't even tell if it crashed or not).

This didn't happen a couple of months back.

Running on Ubuntu 14.04 LTS

**Comment by Licho1** [comment]
probably related to really stupid player list updates...

**Comment by xponen** [comment]
when ZKL close itself in Ubuntu, it meant it crashed. There's no "I have crashed" pop-up in Ubuntu IMO. 
First step is to get ZeroKLobbyErrors.txt and see if it is an easy bug.

**Comment by KingRaptor** [comment]
http://pastebin.com/k7t85zac

(pay attention to the dates, the only ones involved in this issue are the ones from the 30th)

**Comment by xponen** [comment]
FATAL: System.NullReferenceException: Object reference not set to an instance of an object
  at System.Threading.Timer+Scheduler.SchedulerThread () [0x00000] in <filename unknown>:0
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

**Comment by Licho1** [comment]
Find where System.Threading.Timer is used instead of System.Timers.Timer it should be just 2-3 places one of them is it.

**Comment by xponen** [comment]
I found 1 here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaShared/SelfUpdater.cs#L15

**Comment by xponen** [comment]
@KingRaptor  says the "Steam DLL not found" exception still happen to him regularly, I remember @Licho1 said it was fixed.

**Comment by xponen** [comment]
I didn't get Timer error in my Ubuntu 14.04.1 LTS
Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1)

Can't confirm low fps because I don't have good driver in Linux, I always low fps

**Comment by xponen** [comment]
@Licho1 can I copy https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/welcome_screen/ZeroKLobby/Steam/SteamClientHelper.cs#L46 into master?

**Comment by Licho1** [comment]
I think it should be merged somehow im not sure what happens if you do that to auto merge ... no idea..

**Comment by xponen** [comment]
If I copy paste, I will fix conflict manually by updating welcome_screen with master. Like I did before with local_replay!

**Comment by xponen** [comment]
okay merged!

**Comment by xponen** [comment]
I add 2 new commit, hopefully it fix it when deployed later:

fix for steam.dll not found spam
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/c7618d98c84fa2e1da339c5f5b8cb53aa07b8802

fix for Engine & ZK check spam
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/48f97025ebb3d3ae55f22957203c149fdd37b156

**Comment by KingRaptor** [comment]
Tried running from terminal:
"TASC channel joined: <channel>" messages come several seconds apart, even if the channel is completely deserted (and the client is lagging the whole time)

**Comment by db81** [comment]
Is this still a problem?

**Comment by KingRaptor** [comment]
I don't recall any random app shutdowns lately, but the lag was still a thing when I last used it on Ubuntu (within the past month)

**Comment by Licho1** [comment]
This should be fixed by special catches for steam library uncatchable exceptions
