### ISSUE TITLE
While using ZKL's player search the player list is not updated

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#570]
Note how on the left you can see a lot of "xxx joined." messages, but the players don't show up on the right. This happens only when the Search bar on the top right is used. When not searching for any players, the list updates properly.

![zkl playerlist bug](https://cloud.githubusercontent.com/assets/132906/6926288/87b7840c-d7e5-11e4-872a-0ce174d0380d.png)

**Comment by xponen** [comment]
this seem easy to fix, let me do
