### ISSUE TITLE
ZKL doesn't bother downloading correct ZK version when trying to play missions that already exist locally

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#578]
It just lets Spring crash when it tries to load a not-found archive.

**Comment by xponen** [comment]
this will take long time to fix. Unitsync.cs buggy/didn't report "Dependencies" properly (see *1) (its empty for missions) So there's no way to code ZKL to download the Mod (see *2).

*1 : https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaShared/UnitSyncLib/UnitSync.cs#L205
*2 a mod.Dependencies is planned to be read here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZeroKLobby/Notifications/MissionBar.cs#L69

**Comment by KingRaptor** [comment]
It already knows to download the mod if it also doesn't have the mission .sdz, I assume it just needs to be told to do this if it already has the mission.

**Comment by Licho1** [comment]
For the last time, ZKL should not use unitsync!!! 
If ZKL does not use unitsync, its trivial to fix dependencies because they are stored in ZK database.

**Comment by xponen** [comment]
@Licho1  , but database get the dependencies from unitsync :(

**Comment by KingRaptor** [comment]
I tried playing Tutorial 1 (then-latest version of which I already had) without Zero-K v1.3.1.6, it failed.
I tried playing another mission on the same ZK version which I didn't already have, it began downloading Zero-K v1.3.1.6 as it should have.

**Comment by xponen** [comment]
Yay, found it
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Shared/PlasmaDownloader/PlasmaDownloader.cs#L108 
The "HasResource()" didnt bother to check if dependent file exist. 

This will be fixed realllly sooon.

**Comment by xponen** [comment]
okay have commited to master https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/470c60d65a8f56ddee1882be657bfb05eb9be5b3
will pull into stable soon for deploying ZKL

**Comment by xponen** [comment]
this is fixed in 
ZKL ver 1.3.2.62 (Net4.5.1) or
ZKL ver 1.3.2.63 (Net4.0)
