### ISSUE TITLE
Autoregistrator spams errors

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#579]
http://pastebin.com/ff5c1gfU

**Comment by Licho1** [comment]
Its compiled as local debuv instead of live
Dne 5. 4. 2015 3:57 napsal uživatel "L.J. Lim" <notifications@github.com>:

**Comment by KingRaptor** [comment]
Recompiled and restarted a couple of days ago; worked fine at least then.
