### ISSUE TITLE
Replace Facebook Like Box with Page Plugin

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#580]
> With the release of Graph API v2.3, the Like Box plugin is deprecated and will stop working on June 23rd 2015. Use the new Page Plugin instead. The Page Plugin allows you to embed a simple feed of content from a Page into your websites.

Adding Page Plugin is relatively straightforward: see [here](https://developers.facebook.com/docs/plugins/page-plugin/)
However, I couldn't get it to fit nicely in the sidebar box (it overflows horizontally). Make sure to fix that.

User "google" was complaining about home page redirecting him to Facebook login page and this might fix it.

**Comment by mojjj** [comment]
the facebook like button (as well as other social media plugins) tracks every user, beyond the original page, 
no matter if the user is logged in to facebook, 
no matter if the user is facebook user or not
no matter if the user even look at the like button,
and longer than the user is on the page of origin.

there is a need-to-click plugin available to enable the like-button functionalty with all the tracking disabled before the click.
https://translate.google.com/translate?sl=de&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=http%3A%2F%2Fwww.heise.de%2Fct%2Fausgabe%2F2014-26-Social-Media-Buttons-datenschutzkonform-nutzen-2463330.html&edit-text=&act=url

its available at github uses only one click, also under MIT
https://github.com/heiseonline/shariff

Shariff enables website users to share their favorite content without compromising their privacy.
http://ct.de/-2467514

so, if there needs to be refactoring done, maybe the effort for privacy can be added there too.

**Comment by Licho1** [comment]
But does it show the pictures of people? I like the people's images there

**Comment by shaun0x00** [comment]
http://www.net-security.org/secworld.php?id=18395

**Comment by mojjj** [comment]
the article suggests 3 tracking blockers. i tried EFF's Privacy Badger, it shows zero-k.info has 17 page trackers...

**Comment by Licho1** [comment]
we replaced all fb thingies with simple link
