### ISSUE TITLE
kicked player shouldn't be allowed to play on for next 5 min

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#581]
if some player got kicked from host he shouldn't be allowed to play on for next X min. for example some troll gets kicked from all and just joins back and ruins next game. Maybe force him spec instead

**Comment by Jamanno** [comment]
*bump
high lvl player got kicked after game because he didn't want to play as team and could play on which is nonsense imo

**Comment by Jamanno** [comment]
*bump*
there is no way in current setup to deal with trolls except banning them from whole ZeroK.

**Comment by db81** [comment]
#896

**Comment by db81** [comment]
Closed as duplicate.
