### ISSUE TITLE
Friendlist cut off at the border of the window

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#584]
http://i.imgur.com/9XmAW2k.png

For example Lai125, who is on my friendlist, is not visible here.

The friendlist could need a general rework with features like a search function, thus this could be marked as enhancement.

**Comment by xponen** [comment]
omg!

**Comment by Licho1** [comment]
Well he is "YourFriend" after all :-)

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
