### ISSUE TITLE
ZKL: Linux, should be executable

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#586]
The Zero-K.exe file should be made executable (+x). The frequent updates should also make sure it persists the executable flag.

**Comment by Licho1** [comment]
Hm it seems to work fine even without +x ..
I'm not sure how to set this flag using mono in a way that makes the assembly also work on windows.
(Except using shell command). Should we use shell command for this or is this a better way?

**Comment by gajop** [comment]
Normally all executable files require +x. Trying to run such programs gets you this:
```
% ./Zero-K.exe
zsh: permission denied: ./Zero-K.exe
```
Without it you can't execute them directly and have to associate a program with it, which isn't ideal. It's still possible to run them as: 
```
% mono Zero-K.exe                                                                                                                                                                   
Zero-K.exe Information: 0 : Starting with version 1.3.2.105
```

You use the same file for Windows and Linux? In that case it might not be possible to provide a single file, your update tool might have to execute Linux-specific commands, e.g: http://stackoverflow.com/questions/18037587/how-do-i-set-the-executable-file-attribute-in-net?answertab=votes#tab-top

**Comment by Licho1** [comment]
Yes we are using same file for both linux and windows..
Oh so you can just start it directly like if it was a binary file? Didnt know it, i thought you always need mono .. 
So two steps are needed
1) initial file attribute
2) update file attribute

2 can be done from zkl itself. But how do we ensure 1) ?

**Comment by gajop** [comment]
I don't know about 1). It might not be doable with a single file (I haven't investigated).

Just to be clear, it both cases it'll use mono, but if you make it executable, it'll automagically find the correct program to run it. This is similar to executable python/shell scripts that have the [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29) string so they can be run without specifying the interpreter.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
