### ISSUE TITLE
XtC290 player bug

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#587]
His account must be bugged somehow as his name in ZKL is blank. if one hovers over this blank username it shows his name and under it a blank state instead of his current status.
In addition if one hovers over an battle he is in it will show only his blank state in player list in that current battle.

**Comment by cleanrock** [comment]
It may because Country is not sent in User message, just a guess though.
The XtC290 user in flobby is ok, blank country though.

**Comment by Orfelius** [comment]
XtC290 says he is from Romania, connects to game using ZKL and is using proxy to connect into the internet.

**Comment by KingRaptor** [comment]
Flag on zero-k.info is ".png" (no country)

Moot point though, user has been banned for being smurf.

**Comment by cleanrock** [comment]
I am not sure what KingRaptor comment mean but this player have made a problems for zkl users, fix it in some way if you are thinking about a steam launch.

**Comment by xponen** [comment]
need to replicate this to find where it crashed. It is probably just a NULL error.

**Comment by KingRaptor** [comment]
Should be fixed by #590; reopen otherwise.
