### ISSUE TITLE
ZKL tool tips cease to appear after right clicking on a battle icon

### ISSUE THREAD

**Issue by Sgathec** [ZeroK-RTS/Zero-K-Infrastructure#593]
Right clicking on a battle icon disables the hovering boxes that display information about GUI entities under the cursor.

**Comment by xponen** [comment]
is fixed here: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/d2d967c0c86cf97657a4dabb90fd6ac49e5a9895 

ty!
