### ISSUE TITLE
Invalid Salt error when logging in

### ISSUE THREAD

**Issue by blah1** [ZeroK-RTS/Zero-K-Infrastructure#601]
A friend of mine is trying to log in with the account "deathsdelivery101". http://zero-k.info/Users/Detail/266908
Attempting to log in with the lobby just says connecting forever (at least on weblobby, probably the same on ZKL too though) and logging into the website gives this error. http://pastebin.com/iDdc7cuf
The account was last used last summer iirc, before the server change.
In this case a password reset would work fine to fix it, but others might also be having this error.

**Comment by Licho1** [comment]
He nevber logged into site, his password is unset, admin can set a new password for him.
