### ISSUE TITLE
JoinChannelResponse reports absent people for #zkadmin

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#607]
When joining #zkadmin, the users list in the JoinChannelResponse server-message contains people who aren't actually there. Other channels seem fine so this likely happens due to the special handling of that channel.

**Comment by sprunk** [comment]
Duplicate of #609

**Comment by Licho1** [comment]
fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/2ab1d8f819273b44513c53af78d6f0fb527ec70e
