### ISSUE TITLE
#zkadmin does not update userlist

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#609]
I cannot see already joined players, neither I see player who left, but thats for #zkadmin only. Other channels work fine.

**Comment by sprunk** [comment]
Related to #607

**Comment by Licho1** [comment]
fixed in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/2ab1d8f819273b44513c53af78d6f0fb527ec70e
