### ISSUE TITLE
chatbox shows up as gray after switching tabs

### ISSUE THREAD

**Issue by mtroyka** [ZeroK-RTS/Zero-K-Infrastructure#610]
This seems to be a new issue. I can still see the text entry box at the bottom, but the actual channel content just shows up as solid gray and I can't see any text. Sometimes switching tabs gets rid of it, but not always.

**Comment by xponen** [comment]
the channel crashed, can you retrieve ZKL diagnostic log?

**Comment by mtroyka** [comment]
it's no longer current. :| Also, on closer inspection the chat text was still there, just hidden under a gray box that was being drawn over it.

**Comment by xponen** [comment]
its not like this?:
![untitled](https://cloud.githubusercontent.com/assets/2525365/7547998/df0d8a12-f62b-11e4-8384-44402b3f37b8.jpg)

**Comment by mtroyka** [comment]
ah, it was almost just like that, except that I could still see a little text under the 'extras' button.

**Comment by db81** [comment]
> it was almost just like that

I'm assuming that the "was" implies it's fixed by 6214e82.
