### ISSUE TITLE
Some images / webpages are hosted on 3rd party sites

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#612]
All images or websites should be hosted on same server (for ex: github) to prevent images and links going dead and ease maintaince.

Some links/hosts are already dead or will go down soon (google.code)

Private homagepages by project members (licho.eu etc) are not reliable either, in case they one day decide to clean up their webspace and accidently delete something.

For example:
http://zero-k.info/Wiki/EconomyGuide
http://zero-k.info/Wiki/Terraforming
uses http://licho.eu, photobucket.com

http://zero-k.info/Wiki/Manual
http://cdn1.iconfinder.com/data/icons/systematrix/Program.png = random 3rd party website
http://trac.caspring.org/browser/trunk/mods/ca-source/icons/antinuke.png = old CA site = 404

http://zero-k.info/Wiki/Media#Screenshots
uses sites: licho.eu, photobucket.com

**Comment by abma** [comment]
seems licho.eu is completely gone (which hosts the screenshots on the startpage)

**Comment by Anarchid** [comment]
@abma that is an intermittent issue, explored in more detail in https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/673, and reportedly partially fixed.

**Comment by Licho1** [comment]
Now that the wiki is publicly editable again, it can be fixed by willing people..

**Comment by knorker** [comment]
> "Now that the wiki is publicly editable again, it can be fixed by willing people.."

How to upload images to wiki?
On recently edited pages pictures are once again hosted on imageshack.com, imgur.com & co
Soon those images will disappear, again.
Imo the only way that works to prevent perpetual 404s: Hosting images on the wiki itself (like other wiksoftware does)

**Comment by Licho1** [comment]
Maybe the wiki could self download all referenced images for wiki articles. 
Or wheng iven special tag/hint to do so.

**Comment by KingRaptor** [comment]
Could the licho.eu gallery be integrated with ZK infra? Is that even desirable?

**Comment by Licho1** [comment]
Probably ... but do we need it? We can manually copy images we do need to some folder and other might be autofetched if needed.

**Comment by knorker** [comment]
> Some links/hosts are already dead or will go down soon (google.code)

And so it happend. google.code is now no longer hosting images, resulting in many more dead images across wiki.

![zkwikigooglecodeimages](https://cloud.githubusercontent.com/assets/3044855/15414314/c5303da6-1e39-11e6-8f0e-a8ff20b64f59.jpg)

**Comment by knorker** [comment]
> Probably ... but do we need it? 

If there are supposed to be images on the wiki then there should be a way to upload images.
(Such strange question that I ignored it previously because the answer seems obvious.)

> We can manually copy images we do need to some folder 

Who is "we"? What "folder"? A folder on zK-server? Normal users have no access to that.
A folder on github...? So users who want to add images to wiki should register on github, get rights blabla, upload images to zK github..?

> and other might be autofetched if needed.

What does this mean?

**Comment by Licho1** [comment]
Nah I meant copy for key wiki articles. 
Autofetch = make site auto fetch image from url in post and store locally (and adjust url).

**Comment by sprunk** [comment]
Mediawiki accepts image uploads.

**Comment by sprunk** [comment]
Some images on the main site remain hosted on 3rd party sites but there's ticket #1727 for that.
