### ISSUE TITLE
Welcome screen chat tab feedback

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#619]
The text in the window should be black on near-white because that is the most readable. This means that the blue backgrounds will have to be a lot brighter.

The window often flashes when clicking on a different channel to view.

The little magnifying glass icon has a grey background. 

When not in a battle, the battle channel has a grey rectangle in the bottom right. If this channel exists it is just for chat in the current custom room. All battle information and settings would be within the main screen.

**Comment by Licho1** [comment]
fixed/not applicable in main branch
