### ISSUE TITLE
Engine Download folder name "98.0.1-XXX-XXXXXXX develop"

### ISSUE THREAD

**Issue by TurBoss** [ZeroK-RTS/Zero-K-Infrastructure#630]
Hi!,

while pr-downloader downloads spring in the engine folder name "98.0.1-xxx-xxxxxx develop",
ZKL downloads spring in "98.0.1-xxx-xxxxxx" only.
so i end with 2 engines of the same version but in diferent folders
thx

**Comment by Licho1** [comment]
Probably not going to fix it, by design engine name is without spaces and without branch name.
ZKL is not using pr-downloader and whatever is probably knows the difference.

**Comment by db81** [comment]
ZK infra has always used engine names without the branch suffix. This used to work with pr-downloader, but the hack making this possible got removed in springfiles/upq@11c82e0c.
