### ISSUE TITLE
ZKL breaks my computer

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#632]
I started ZKL, my computer froze for about 20 seconds, then unfroze and ZKL did not appear to have started.

I started ZKL again and it took a while to start but managed to start. It crashed within a few minutes.

Subsequent attempts resulted in ZKL freezing everything and then not doing anything.

ZeroKLobbyErrors.txt does not contain any recent errors.

**Comment by KingRaptor** [comment]
Similar behavior reported in #568

**Comment by Orfelius** [comment]
Did you have Steam open GoogleFrog?

**Comment by GoogleFrog** [comment]
Yes.

**Comment by xponen** [comment]
Okay, replicated, will fix

**Comment by xponen** [comment]
ZKL break steam, can't close steam anymore... it says: please wait for Zero-K to shutdown...
but I already close it.
:jack_o_lantern:

**Comment by Orfelius** [comment]
I started to have similar problems lately but it seems like it only happens if I have Steam open.

**Comment by shaun0x00** [comment]
I also had such "hangups".
I do not run steam (never installed it).
I confirmed that cpu was maxed by zero-k.exe during such events, but couldn't find anything in the many incomplete ZKL logs.
I couldn't correlate with network activity either, but I was late to detect it.

Note: this only happened after I played games. I never had such problems before, by only using ZKL to chat.

**Comment by Licho1** [comment]
This should be fixed by special catches for steam library uncatchable exceptions
