### ISSUE TITLE
ZKL - TTS talkative even after spring exit

### ISSUE THREAD

**Issue by shaun0x00** [ZeroK-RTS/Zero-K-Infrastructure#648]
Its annoying to hear TTS proclaiming the name of commanders chosen by the players of a game that has already exit.
Please stop/flush TTS when spring exits.

**Comment by xponen** [comment]
this only happen if Spring haven't exit. It read the output from Spring for this to work.

**Comment by shaun0x00** [comment]
@xponen No. Did you test it? Did you read the code? Did you read the API?
I don't understand, why do you say that?

**Comment by xponen** [comment]
How do you replicate it?

**Comment by shaun0x00** [comment]
unintended: join a 20v20 game and if it is !voteexit soon, you'll hear commander names even after game exit
intended: you can probably just play with an ally vs null ai, have your ally write something long to say (special characters in com names have always been trolls favorites, try that?)... and exit spring before TTS has finished talking.

**Comment by xponen** [comment]
very very likely will be fixed by this commit: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/fb2da9de8aa12b80377624f38734a71f755c9e82
