### ISSUE TITLE
(zkl 1.3.2.65) close-button for news is not reachable (outside screen?)

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#652]
Think this is quite old issue but just saw it again on friend's laptop:

If the pop-up window for news is too large then it does not fit onto screen and the close-button is off-screen.
He tried scrolling but did not manage to close it until I told to try "refresh"
It was this news: http://zero-k.info/Forum/Thread/17388
The screen resolution was 1440×900, win 7 (I think)
Window was "cut off" at top because outside screen, only few bottom pixels of news-image (with lava) were visible.

Needs proper scrollbars or something.

**Comment by knorker** [comment]
same on website, with firefox.

the grey part where it says "News headlines" gets taller on mouse-over.

![bla](https://cloud.githubusercontent.com/assets/3044855/8218599/2aaa755c-1544-11e5-8960-d05b4dd364c6.jpg)

**Comment by knorker** [comment]
with last update the titlebar was completly gone. no close button either.
clicking outside the news-pop-up did nothing.
after restart the pop-up was gone. (this is obv not good fix)

![bla](https://cloud.githubusercontent.com/assets/3044855/9561982/876bc612-4e5e-11e5-83da-b01ba5fc3f08.jpg)

**Comment by maackey** [comment]
This was one of the many reasons I didn't want to add third party themes to the website. I'm guessing it was added because, "look, you just plug it in and it 'works'". I'll look into it.
