### ISSUE TITLE
!endvote own vote

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#656]
Allow !endvote for the player who started the vote. This should be one step towards reducing votes blocking gamestart/other votes.

**Comment by Licho1** [comment]
Thia sounds like a recipe for trolling
Dne 14.6.2015 21:58 napsal uživatel "DeinFreund" <notifications@github.com>:

**Comment by sprunk** [comment]
Why? Any example of trolling use?

**Comment by Licho1** [comment]
Start vote then cancel before it ends or if you dont like result
Dne 15.6.2015 11:22 napsal uživatel "sprunk" <notifications@github.com>:

**Comment by DeinFreund** [comment]
A vote usually either changes something: !endvote would be like spamming useless votes.
Or doesn't change anything: !endvote makes sense if not enough players are voting/speeds things up.
