### ISSUE TITLE
People can join with the wrong engine

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#659]
Players sometimes join game with the wrong engine. This is a very important bug as it can happen to new players which do nothing unusual. Rejoining the battle room seems to fix it for them. Perhaps ZKL needs extra checks to make sure that the engine is right.

Example game http://zero-k.info/Battles/Detail/359478

**Comment by Licho1** [comment]
Need more info.
Was the player desynced in the lobby and it started?
Or was he synced?
If he was synced was the problem corrupted engine/file or missing one?

**Comment by GoogleFrog** [comment]
He joined midgame. The replay should show that.

**Comment by lhog** [comment]
Not sure if related.
If one played in the room and set engine to something else than default (for example 91.0). After in the skirmisher tab, even though another engine is selected (for example 98.0.1-451), then 91.0 gets launched.

**Comment by GoogleFrog** [comment]
It keeps happening. Recently occurred to Garbo and I don't think he has ever joined a host with the engine he connected with.

http://zero-k.info/Users/LobbyDetail/230777

**Comment by sprangg** [comment]
This can be replicated at least by
1. joining multiplayer room
2. changing engine version in "skirmisher" tab
3. when starting/rejoining the multiplayer game, you are using the engine you set in "skirmisher" tab

If you then leave and rejoin the multiplayer room, you connect with the correct engine.

**Comment by Licho1** [comment]
appears to be fixed
