### ISSUE TITLE
Selecting enemy units after resign wont change los

### ISSUE THREAD

**Issue by Licho1** [ZeroK-RTS/Zero-K-Infrastructure#660]
After you resign LOS should be unrestricted if you are spectator with no unit selected.
When you select some unit it should restrict to whatever ally it is.
What i mean is dark/light colors not actual full visibility.

This used to work, now broken with default settings.

**Comment by Licho1** [comment]
http://i.imgur.com/r5DZMSx.png

**Comment by GoogleFrog** [comment]
Those are not the default settings. I just reset and it works for me.

**Comment by Licho1** [comment]
It worked for me and stopped working, how did you "reset" and how did you test?

**Comment by GoogleFrog** [comment]
I removed ZK_data and ZK_order

**Comment by Anarchid** [comment]
review https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/655 for more info

**Comment by Licho1** [comment]
@GoogleFrog  that is hardly a reset.. that's just a reset of ZK game, but who knows what ZKL does with default configs...
It deploys lots of files and alters stuff. Will need to re-test on truly fresh install

**Comment by Licho1** [comment]
fixed
