### ISSUE TITLE
State of the linux VM

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#661]
The Ubuntu machine at licho.eu is currently running a very old and no longer supported version.

Currently it is used only to occasionally run the unitguide generators, as far as i know, but if Turboss installer is to be adopted, ZKI will have to learn how to build stuff under Linux, which would likely also need to fall to that machine's tasks, given that cross-compiling for linux under windows seems to be considered super scary.

Should it be upgraded? Who can do the upgrade? If noone wants to do this, where do i get the power to do that myself?

**Comment by Licho1** [comment]
There is scheduled server swap, when it happens i will notify you and you can "reinstall" needed stuff on new VM.
But atm there is less and less functions of this machine and might not be needed at all (except for cross compiling installer)

**Comment by Anarchid** [comment]
It seems (based on http://steamcommunity.com/app/291150/discussions/0/540741131921165591/) that actually upgrading might be detrimental if it's to be used for building things such as the installer.

Currently the machine already has lib6 2.15, so that's just what would be needed.
