### ISSUE TITLE
Forum freaks out when seeing hashes

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#662]
So while submitting a post with 3#&4# on the forum this error shows up: http://pastebin.com/fRiwmaKe
Then I tried to change it into #3 and #4 but it resulted in the same error page showing up.
Ultimately I typed in 3# & 4# but that broke the [spoiler] tag that I have introduced further in the same line.
link to the post: http://zero-k.info/Forum/Thread/17424#133203

**Comment by Licho1** [comment]
Disable automated checks in web config and instead escape before rendering. Make sure JS is properly blocked.

**Comment by KingRaptor** [comment]
Looks like ee62482db0642e3141647e0590d7867172e35b36 fixed it.

Thanks for reporting!
