### ISSUE TITLE
"Springie rights set to 0" doesn't actually work

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#663]
It does nothing.

Consider replacing any such punishments with the manual rights reduction for the time being.

**Comment by ParzivalX** [comment]
Hmmmm.... looking into this now.
(Sorry, I'm sorta new at this)

**Comment by db81** [comment]
Summary of http://zero-k.info/Forum/Post/133688#133688:

https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyServer/LoginChecker.cs#L241 uses SpringieLevel instead of GetEffectiveSpringieLevel().

**Comment by sprunk** [comment]
ty
