### ISSUE TITLE
Spoiler tags don't work in news popup

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#666]
The URL is just `http://zero-k.info/#` and clicking it does nothing.

**Comment by db81** [comment]
I played with it locally for a bit and here's what I found (every section is a separate news post):
```
[spoiler]
This one doesn't work.
[/spoiler]
```
```
[spoiler]
This one doesn't work.
[/spoiler]

[spoiler]
But this one does!
[/spoiler]
```
```
==Section==

[spoiler]
And this one works too!
[/spoiler]
```

**Comment by Licho1** [comment]
The JS it uses could be redone manually instead of relying on fairly long and opaque existing script. 
Its probably a jquery two liner.

**Comment by Licho1** [comment]
So much for third party solutions..
