### ISSUE TITLE
Welcom Screen transition background flicker

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#668]
The background does not change all at once in welcome screen. This screenshot was taken just after I clicked the multiplayer button from the root of the menu. The screen looks like this for a split second and it is quite disconcerting.

![transitionbackgroundflicker](https://cloud.githubusercontent.com/assets/1318249/8308104/2fb101a8-1a06-11e5-865c-895a1e2afc50.png)

**Comment by ParzivalX** [comment]
Is that new lobby design? And the issue may be something related to lag. Or maybe something with the loadscreen program?

**Comment by Licho1** [comment]
old lobby
