### ISSUE TITLE
mute doesn't work

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#669]
mute someone and it won't work in lobby or game.

:(

**Comment by ArchShaman** [comment]
Do you mean ignore or admin mute? Ignore AFAIK is not supported in game (yet!).

**Comment by Licho1** [comment]
fixed

**Comment by sprunk** [comment]
Reference: https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/b92a5fca8b63f82d0d5a9588b68ff0d720d13594
