### ISSUE TITLE
MonoDevelop fails to load ZK infra

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#672]
It gives an error along the lines of "Unknown ToolsVersion '12.0'". Opening the .csproj files and changing ToolsVersion to 4.0 works around the issue.

Related link: [Unknown ToolsVersion '12.0'](http://forums.xamarin.com/discussion/12066/unknown-toolsversion-12-0)

**Comment by Licho1** [comment]
Make sure it still teamcity builds with toolsversion 4

**Comment by Licho1** [comment]
not mtaintained for mono atm Its recommended to use VS in virtualbox
