### ISSUE TITLE
Unit Guide broken / linux vm offline 

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#673]
Trying to access zero-k.info/Static/UnitGuide throws the following:

```
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 94.23.170.70:80
```

Apparently that is because it tries to fetch content from manual.zero-k.info, which is hosted on the linux VM.

Linux VM seems to be down: 
```
$ ping licho.eu
PING licho.eu (94.23.170.70) 56(84) bytes of data.
^C
--- licho.eu ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3023ms
```

**Comment by Anarchid** [comment]
The server is back up. The issue is closed.

**Comment by Anarchid** [comment]
This is happening again, and seems to be happening repeatedly.

**Comment by Licho1** [comment]
Fixed ESXI failure, need to move to new server but its still being
unavailable ..

2015-07-03 16:27 GMT+02:00 Анархид <notifications@github.com>:
