### ISSUE TITLE
(forum) special chars are broken in title

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#675]
http://zero-k.info/Forum/Thread/17502

Special chars like http://www.degraeve.com/reference/specialcharacters.php work okay in post itself, also work in threads list but break in title when thread is opend.

Firefox, windows

![bla](https://cloud.githubusercontent.com/assets/3044855/8396591/9eb49142-1dac-11e5-95a8-4ea044f63403.png)

Mostly relevant for the quotation marks
http://zero-k.info/Forum/Thread/17498
http://zero-k.info/Forum/Thread/17500
http://zero-k.info/Forum/Thread/17489

**Comment by KingRaptor** [comment]
Fixed and deployed, thanks!
