### ISSUE TITLE
Start votes with 1 yes

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#680]
In-game widget and lobby should start the vote bar with 1 yes for consistency. Currently the votes have 1 yes at the start (the one who started the vote voted yes) but the bar does not reflect this.

**Comment by db81** [comment]
This must be caused by Springie sending [0/N] right after it sends [1/N] when a vote starts. I was under the impression that it didn't affect ZKL.

**Comment by Licho1** [comment]
fixed
