### ISSUE TITLE
spawning new hosts not working again

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#698]
see this 
06:29 Nightwatch: Parameter name: salt
06:29 Nightwatch:    at BCrypt.Net.BCrypt.HashPassword(String input, String salt)
06:29 Nightwatch:    at ZkData.Account.VerifyPassword(String passwordHash)
06:29 Nightwatch:    at ZkLobbyServer.LoginChecker.Login(User user, Login login, ClientConnection client)
06:29 Nightwatch:    at ZkLobbyServer.ClientConnection.<>c__DisplayClass22.<Process>b__1b()
06:29 Nightwatch:    at System.Threading.Tasks.Task`1.InnerInvoke()
06:29 Nightwatch:    at System.Threading.Tasks.Task.Execute()
06:29 Nightwatch: --- End of stack trace from previous location where exception was thrown ---
06:29 Nightwatch:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
06:29 Nightwatch:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
06:29 Nightwatch:    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
06:29 Nightwatch:    at ZkLobbyServer.ClientConnection.<Process>d__24.MoveNext()
06:29 Nightwatch: --- End of stack trace from previous location where exception was thrown ---
06:29 Nightwatch:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
06:29 Nightwatch:    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
06:29 Nightwatch:    at CallSite.Target(Closure , CallSite , Object )
06:29 Nightwatch:    at ZkLobbyServer.ClientConnection.<OnCommandReceived>d__c.MoveNext()

**Comment by Sgathec** [comment]
Currently one can create a room via the !spawn command but doing it though the ZKL GUI results in the following error message: "Unable to locate AutoHost for given game type".

**Comment by Licho1** [comment]
@Sgathec this second issue was fixed yesterday.
@Jamanno  when this happens? It appears to be when password is null but i cannot replicate

**Comment by karamel59** [comment]
Hello. I get the same salt error when trying to connect to the lobby or the website. I can join without problem on springlobby and weblobby but not on Zero-K. My password is not empty, if I rembember correctly I created the account with Zero-K lobby a few weeks ago (but could never log). Is there an IRC channel or something like this to give more info in real time if required?

Invalid salt Parameter name: salt

[ArgumentException: Invalid salt
Parameter name: salt]
   BCrypt.Net.BCrypt.HashPassword(String input, String salt) +621
   ZkData.Account.AccountVerify(ZkDataContext db, String login, String passwordHash) +336
   ZkData.AuthServiceClient.VerifyAccountHashed(String login, String passwordHash) +119
   ZeroKWeb.Controllers.HomeController.Logon(String login, String password, String referer) +344

**Comment by Licho1** [comment]
fixed
