### ISSUE TITLE
Zero-K Lobby crashes if steam is opened after zkl(linux)

### ISSUE THREAD

**Issue by TurBoss** [ZeroK-RTS/Zero-K-Infrastructure#700]
Zero-K Lobby crashes if steam is launched after zkl
http://paste.springfiles.com/view/3a900d52

**Comment by Licho1** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/b6bd59ae9db80f74198ddb72dd6d0a7d3f2ac269
