### ISSUE TITLE
Random ZKL crashes

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#710]
No error written to log.

Found while debugging, can't be sure it's related however: http://i.imgur.com/UL6En5l.jpg

**Comment by Licho1** [comment]
Hmm cannot do much with that if it cannot be catched. I suppose libs can be updated to latest versions

**Comment by Licho1** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/b6bd59ae9db80f74198ddb72dd6d0a7d3f2ac269
