### ISSUE TITLE
feature request: add mumble status chart on zksite

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#715]
How about to see whos in mumble, currently not much players around maybe because noone thinks someone is online.
And remove 10000 channels, it looks more emptry through that.
10 channels maybe enough to meet up for first steps. :)

**Comment by Licho1** [comment]
Channel purge sounds ok. Other than that, ZKL has steam integration with custom written voice chat already implemented. So mumble is obsolete.
