### ISSUE TITLE
Springie uses team elo for 1v1 !predict

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#72]

**Comment by KingRaptor** [comment]
1v1 Elo currently isn't readily accessible to Springie (NW doesn't tag accounts with it, unlike team Elo).

**Comment by Licho1** [comment]
This is already provided in uberserver_final_murder branch

**Comment by Orfelius** [comment]
This is no longer the case. Close?

**Comment by Anarchid** [comment]
ubermurdered.

**Comment by Licho1** [comment]
It's not fixed just springie has 1v1 elo available now.
