### ISSUE TITLE
ChannelUserAdded after UserDisconnected

### ISSUE THREAD

**Issue by cleanrock** [ZeroK-RTS/Zero-K-Infrastructure#720]
Minor problem but i want to report since i saw it now:
D-13:48:57-Model.cpp:240] message: UserDisconnected {"Name":"tap7","Reason":"connection failed"}
D-13:48:58-Model.cpp:240] message: ChannelUserAdded {"ChannelName":"zk","UserName":"tap7"}
W-13:48:58-Model.cpp:573] failed to process server msg:'ChannelUserAdded {"ChannelName":"zk","UserName":"tap7"}' (user not found:tap7)

Server version: 1.3.2.79

**Comment by Licho1** [comment]
hmm probably disconnected during connecting..

**Comment by cleanrock** [comment]
He was online for almost a minute though, all tap7 messages:
D-13:48:02-Model.cpp:240] message: User {"AccountID":187107,"SpringieLevel":2,"Avatar":"capturecar","Country":"FI","EffectiveElo":1603,"Effective1v1Elo":1375,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":23,"ClientType":1,"Name":"tap7","IsAway":false,"IsInGame":false}
D-13:48:03-Model.cpp:240] message: ChannelUserAdded {"ChannelName":"zk","UserName":"tap7"}
D-13:48:17-Model.cpp:240] message: JoinedBattle {"BattleID":34,"User":"tap7"}
D-13:48:55-Model.cpp:240] message: ChannelUserRemoved {"ChannelName":"zk","UserName":"tap7"}
D-13:48:57-Model.cpp:240] message: User {"AccountID":187107,"SpringieLevel":2,"Avatar":"capturecar","Country":"FI","EffectiveElo":1603,"Effective1v1Elo":1375,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":23,"ClientType":1,"Name":"tap7","IsAway":false,"IsInGame":false}
D-13:48:57-Model.cpp:240] message: LeftBattle {"BattleID":34,"User":"tap7"}
D-13:48:57-Model.cpp:240] message: UserDisconnected {"Name":"tap7","Reason":"connection failed"}
D-13:48:58-Model.cpp:240] message: ChannelUserAdded {"ChannelName":"zk","UserName":"tap7"}
W-13:48:58-Model.cpp:573] failed to process server msg:'ChannelUserAdded {"ChannelName":"zk","UserName":"tap7"}' (user not found:tap7)

**Comment by db81** [comment]
Looks similar to #514.

**Comment by Licho1** [comment]
should be fixed
