### ISSUE TITLE
Limit the total number of AI possible

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#725]
Please limit the total number of ai's to 250 - currentplayers. Any more than this is just insanity. LUAUI won't work with more than 255 players (I think) so why allow 800 bots?

Reason 2: A person who adds 800 bots will crash/hang the lobby if kicked as all their bots are removed. Anyone having this ability is just asking for griefing.

**Comment by db81** [comment]
Fixed in 7820f96.
