### ISSUE TITLE
isAway toggle spam (1.3.2.85)

### ISSUE THREAD

**Issue by cleanrock** [ZeroK-RTS/Zero-K-Infrastructure#731]
When dogma is online i often get this away toggle spam which goes on for hours:

D-07:19:27-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-08-02T05:19:33.1692811Z","Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**true**,"IsInGame":false}
D-07:19:27-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**false**,"IsInGame":false}
D-07:19:28-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-08-02T05:19:34.1698639Z","Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**true**,"IsInGame":false}
D-07:19:28-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**false**,"IsInGame":false}
D-07:19:29-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-08-02T05:19:35.1794026Z","Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**true**,"IsInGame":false}
D-07:19:29-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**false**,"IsInGame":false}
D-07:19:30-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-08-02T05:19:36.1897528Z","Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**true**,"IsInGame":false}
D-07:19:30-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Avatar":"mahlazer","Country":"US","EffectiveElo":1582,"Effective1v1Elo":1517,"IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":80,"ClientType":3,"Name":"dogma","IsAway":**false**,"IsInGame":false}

**Comment by Licho1** [comment]
It would be best to verify with dogma whether his client is sending this or
not..
And what client he has..

2015-08-02 7:28 GMT+02:00 Johan Rehnberg <notifications@github.com>:

**Comment by cleanrock** [comment]
Happened again now.
When i wrote this in #zk dogma toggle spam stopped:
08:17 cleanrock: dogma, your client is spamming Away toogle again, please answer Licho question at https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/731
08:17 cleanrock: *toggle

Spam and end of spam:
D-08:18:35-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:36-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:36.587431Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:36-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:37-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:37.5997835Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:37-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:38-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:38.6041817Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:38-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:39-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:39.6184831Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:39-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:40-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:40.6166858Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:40-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:41-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:41.6182143Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:41-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:42-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:42.6312424Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:42-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:43-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:43.6387258Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:43-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:44-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:44.6434498Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:44-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:45-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:45.6477262Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:45-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:46-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:46.6595783Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:47-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:47-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:47.6733093Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:48-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:48-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:48.6894757Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:49-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:49-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:49.6934419Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:50-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:50-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:50.7044131Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:51-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:51-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:51.7119508Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:52-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:52-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:52.712291Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:53-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:53-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:53.7166341Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:54-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:54-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:54.7306109Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}
D-08:18:55-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":false,"IsInGame":false}
D-08:18:55-Model.cpp:240] message: User {"AccountID":109622,"SpringieLevel":2,"AwaySince":"2015-09-26T06:18:55.7413379Z","Clan":"TheGBC","Avatar":"mahlazer","Country":"US","EffectiveElo":1626,"Effective1v1Elo":1517,"Faction":"Rising","IsAdmin":false,"IsBot":false,"IsInBattleRoom":false,"BanMute":false,"Level":81,"ClientType":3,"Name":"dogma","IsAway":true,"IsInGame":false}

**Comment by cleanrock** [comment]
I just heard that you can login with an account simultaneously from different machines, i guess this is what cause this Away spam.

**Comment by Licho1** [comment]
irrelevant/fixed ?
