### ISSUE TITLE
Springie kills game if there are 0 active players in it.

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#732]
Currently Springie instantly killed a 0 active player game. People have a chance to reconnect so I think this time should be increased to a few minutes.

**Comment by Licho1** [comment]
Springie??

**Comment by GoogleFrog** [comment]
Yes. The dedicated server stops if there are 0 active players left in the game. I am fairly sure it is the one which causes this.

**Comment by Licho1** [comment]
Code that did this removed
