### ISSUE TITLE
Add more clan names to player customKeys

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Zero-K-Infrastructure#736]
Currently the short name of a clan is added to a players customKeys. I want more human readable names added to the customKeys. For example someone from GBC http://zero-k.info/Clans/Detail/391 would have
clanName = "TheGBC"
clanNameFull = "The Genetic Benefactor Conspiracy"

**Comment by sprunk** [comment]
Fixed by a1bc5d
