### ISSUE TITLE
AllyNumber can overflow (>= Spring.MaxAllies)

### ISSUE THREAD

**Issue by cleanrock** [ZeroK-RTS/Zero-K-Infrastructure#739]
Server version:  1.3.2.85
I got this message yesterday which triggered an assert in flobby:
UpdateUserBattleStatus {"AllyNumber":16,"Name":"hokomoko"}

Looking at ZK infra code it looks like max AllyNumber should be 15 (Spring.MaxAllies-1).

**Comment by Licho1** [comment]
fixe by zkls/removal of zkl

**Comment by Licho1** [comment]
(Otherwise garbage in garbage out, zkls does not check max alliances)
