### ISSUE TITLE
(homepage) optional spoiler for replay results

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#740]
It is not possible to watch replays without seeing winner on homepage.
Sometimes people put battle-comments in spoiler-tags but it is useless because result is visible anyway. Similiar futile are the attempts to obscure tourney results. (linking non-existing third game in BO3 etc)

Spoiler function for replay existed but was removed:
A setting in profile would be good compromise.

**Comment by Licho1** [comment]
Fixed spoiler is there now for all games not played by the player
