### ISSUE TITLE
Steam API should only see Zero-K as a game when Spring is running

### ISSUE THREAD

**Issue by dvr333** [ZeroK-RTS/Zero-K-Infrastructure#742]
Right now, Zero-K Lobby running causes Steam to see whoever is using it as "In-Game Zero-K". This doesn't show whether or not someone is actually playing, because they could simply be in the lobby chatting or keeping it up in case they want to play. 

Instead, Steam should only see a person as "In-Game Zero-K" when Spring has been launched from Zero-K Lobby. If possible, ZKL should probably check that it is actually Zero-K being played, but that's not a huge concern.

**Comment by Licho1** [comment]
I would like that too but its not technically possible to indicate "running game". Merely linking the library lights the indicator.. Same for launching from steam, dunno how to detect this. Closing until someone figures out.
