### ISSUE TITLE
[admin] battle logs should contain all chat log

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#750]
I dunno how this would make harddisk burst? If not is it possible to record at least votes with it or bad words? :)

**Comment by Skasi** [comment]
What's the "[admin]" thing for?

**Comment by sprunk** [comment]
because only admins can read the battle log from site

**Comment by Skasi** [comment]
Why not everyone?

**Comment by sprunk** [comment]
because they are technical (no chat) and might contain sensitive data

**Comment by Licho1** [comment]
Exists for admins so i think its ok now.
