### ISSUE TITLE
(zKlobby) After map-download map is not recognized until lobby-restart

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#752]
Happens sometimes:
1) Join battleroom
2) map download finishs
3) still shows "red cross" = unsynced
4) restart lobby
5) rejoin room, now is synced

From chat it seem it happens to other players too.
Some say leaving & rejoin room works too. (did not test)
Waiting does not help.

This seems bit similiar:
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/issues/446
"sometimes i will not sync with the lobby even when map is present."

**Comment by knorker** [comment]
Leaving room & rejoin works too, to make lobby "recognize" the map.
This is still nessecary sometimes.

win vista and win 7.

**Comment by Licho1** [comment]
Unable to replicate..When it happens please check the log, it should look like 
02/02/2016 20:56:14: starting download Zed 2.2
02/02/2016 20:56:14: Download started: Zed 2.2
02/02/2016 20:56:32: Zed2.2.sd7 Completed - 41.30M
02/02/2016 20:56:34: Adding Zed 2.2
02/02/2016 20:56:34: New resource found: Zed 2.2
Post anomalies. This is probably a low priority because we will distribute maps with steam.

**Comment by knorker** [comment]
Yesterday in 446 KlonZK posted that this still happens to him.

**Comment by Licho1** [comment]
Need more feedback, requesting logs as mentioned here and version of ZKL

**Comment by knorker** [comment]
Almost a year passed since initial report with reaction. Any logs are long gone.

If this report was not closed then others might notice it and be able to give more details/logs.
Maybe @KlonZK

**Comment by KlonZK** [comment]
cant give any more details, but this is a fairly common problem (several or maybe all people have this on occasion).

**Comment by knorker** [comment]
You could post your file ArchiveCache10.lua
It should be somewhere in folder my games\spring or zK\cache\ 

There is also this issue of map file existing multiple times:
#944 although restarting lobby does not fix that, so maybe it is unrelated.

**Comment by KlonZK** [comment]
map files do definitly exist, once the room is rejoined the sync happens immediately.

**Comment by knorker** [comment]
Here it happend after "Open new Battle"

![unsynced new battle](https://cloud.githubusercontent.com/assets/3044855/13568007/f445549c-e45e-11e5-96cb-8c1593498bd2.jpg)

Actually in this case it is worse because when you open a new battle it picks a new random map.
So restarting the lobby does NOT always fix it in this case!

**Comment by Licho1** [comment]
was fixed
