### ISSUE TITLE
(forum) URL in spoiler tags makes spoiler part of URL

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#753]
![bla](https://cloud.githubusercontent.com/assets/3044855/9336518/4f3a6f82-45da-11e5-9e55-c45ff3bd3ce1.jpg)

**Comment by mojjj** [comment]
use a space before the closing spoiler-selector

**Comment by KingRaptor** [comment]
Still happens with new tags system? (try on test.zero-k.info)

**Comment by Licho1** [comment]
it cannot happen on test if it does reopen
