### ISSUE TITLE
(zklobby/host) Host says "no rights to change map" but then still does it

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#756]
1) Go to a host, be alone in room
2) Click "maps" button in lobby
3) select map, click "Play on this map"
4) The host says:
* Elerium1 Sorry, you do not have rights to execute map
 * Elerium1 changing map to Small Supreme Islands V2

So it first says "No rights" but then still does change map.

**Comment by KingRaptor** [comment]
What happens:
* User clicks "play on this map"
* ZKL sends !map command
* Springie finds user lacks rights for !map (and writes "do not have rights" message), automatically tries !votemap
* Player is alone so vote auto-passes

Related: [Command handling](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Springie/Springie/autohost/AutoHost.cs#L1001), [rights check](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Springie/Springie/autohost/AutoHost.cs#L237)

I'm thinking of solutions to this issue.
* Don't say "do not have rights" if a vote version of the command exists.
    * Might be confusing if the player specifically expects the normal command, not the vote one.
* Treat player as de facto boss if alone in the room (this will give them access to !map automatically).
    * But this lets random people waltz onto public autohosts and do things they shouldn't.
* Special handling for "play on this map" from site (this is what I'll probably do).

**Comment by knorker** [comment]
Seems related I guess:
You do not always get the map that you picked.

1) Log into lobby
2) do not join any room
3) Click maps
4) I picked map "Chicken_Nuggets_v4"
5) I get moved to Springiee102, current map is "Ravaged_v2"
6) map "Chicken_Nuggets_v4" gets downloaded
7) in chat:
[xx:01]  * Springiee102 changing map to Chicken_Nuggets_v4
[xx:01]  * Springiee102 map executed by knorker
[xx:01]  * Springiee102 changing map to Ravaged_v2
8) The map is still (again?) "Ravaged_v2"

**Comment by KingRaptor** [comment]
@knorker: Related issue is fixed in 3df16d33c3bb1ef5f57b30602cc3d65c6a3bab5b (pending deploy)
Thanks for reporting!
