### ISSUE TITLE
!Notify in #zk causes all bots to repeatively spam you

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#758]
Typing !notify in channel #zk causes crazy spam. It also seems to never stop notifying you for some reason. I'm still getting spammed despite typing !notify 9 hours ago.

**Comment by KingRaptor** [comment]
(also things should probably be changed so server doesn't send chatlog to bots)

**Comment by ArchShaman** [comment]
I just logged in today.. wow was I welcomed by a metric fuckton of springiees sending me notifications.

http://i.imgur.com/71MAdj9.jpg
