### ISSUE TITLE
Different installers in circulation

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#760]
Perhaps it is all the same files, but still:

On http://zero-k.info/Wiki/Download there is:
1) http://zero-k.info/lobby/Zero-K.exe
2) http://zero-k.info/lobby/Zero-K_NET4.0.exe
- okay.

Also in circulation:
3) Zero-K_setup.exe  (for ex: http://www.indiedb.com/games/zero-k/downloads/zero-k )
4) setup.exe (for ex: https://springrts.com/phpbb/viewtopic.php?f=42&t=21924 )
linked in various places like forums, yt comments, third party sites and so on...

**Comment by Licho1** [comment]
Recall everything until we have web-downloading qt installer "final" ?

**Comment by KingRaptor** [comment]
Just get Saktoth to replace 3) and 4) with the file from 1) for now

**Comment by knorker** [comment]
Imo instead of uploading new file: Remove it and put note to download from http://zero-k.info/Wiki/Download

http://zero-k.info/lobby/setup.exe could in theory be linked in many places that can not be fixed:
Forums, comments, etc
Merely deleting it = 404 = looks broken.
So if technically possible make http://zero-k.info/lobby/setup.exe re-direct to  http://zero-k.info/Wiki/Download

**Comment by knorker** [comment]
http://download.chip.eu/en/Zero-K_8597434.html - zero-K-M.exe

http://www.chip.de/downloads/Zero-K_49004421.html - links to non-existing Mac-version 
( http://zero-k.info/Wiki/Download#Mac )

There is also downloads with the same filename but different file sizes.
For example both https://springrts.com/phpbb/viewtopic.php?f=42&t=21924 and http://download.cnet.com/Zero-K/3000-7483_4-75450117.html?tag=mncol;1 
offer a "setup.exe" but file sizes differ.

In past different the installers also had different default settings for lobby, depending from where they were downloaded. That made it annoying to figure out player's problems. No idea if that is still true.

**Comment by Licho1** [comment]
That is pretty serious issue.. we should construct lighteight installer using QT (already in git afaik) and distribute that instead.
(Lightweight -> downloads everything from main site)

**Comment by Licho1** [comment]
Everything should be using http://zero-k.info/lobby/Zero-K.setup.exe
or a clone of thereof

**Comment by Licho1** [comment]
I compiled Xponen's NSIS installer for zero-k lobby. It always downloads latest zkl.
Its put into 
lobby/Zero-K.setup.exe
and    
lobby/setup.exe

Howerver i have no idea how to change it on cnet or chip.. if you do please do

**Comment by knorker** [comment]
Another source of old zK lobbies is:
5) Old spring intallers. (for ex. http://zero-k.info/Forum/Thread/22332 )

Those old lobbies are appearently somewhat functional (replays, log in to original spring server) and there is no hint that they are outdated. In this case the old lobby's version number was higher than the "current" lobby.
---
Can the zK website detect the version number of a lobby used to view it?
Maybe that would be a way to display a warning.

**Comment by Licho1** [comment]
It cannot detect its version atm. But we could change something (like url) to detect it.

**Comment by TurBoss** [comment]
sry i miss this

Can I help with the qt installer or is the nsis the one that will be used?

thx

**Comment by Licho1** [comment]
There is already nsis installer created and used by website. Problem is just removing existing installers in circulation.

**Comment by Licho1** [comment]
Unable to remove further, people who have the access need to be bugged.
