### ISSUE TITLE
Startscript rewrite in master breaks startboxes.

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#762]
This makes https://github.com/ZeroK-RTS/Zero-K-Infrastructure/pull/757 impossible for now.

**Comment by KingRaptor** [comment]
VS tells me [this line](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyServer/ConnectedUser.cs#L82) has an ambiguity between PlasmaShared.BattleRect and LobbyClient.BattleRect. May be related.

**Comment by KingRaptor** [comment]
The startscript table for the startboxes turned out to be empty.

**Comment by KingRaptor** [comment]
Should be fixed by 79c291ab9ef2749ee8d4cfa5c177af2d6d0af657

**Comment by Anarchid** [comment]
Yeah, it's an obsolete bug.
