### ISSUE TITLE
(host/lobby/maps) On Chickenmaps players should default to team 1, or they get startboxes w/o metal

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#765]
as first reported in http://zero-k.info/Forum/Thread/19935

1) Log into lobby

2) Maps - Chicken_Nuggets_v4

3) "Play on this map"

4) Host opens - I get put into team **2**

5) Add bot: Normal chicken - Bot gets put into team **1**

6) A random noob joins - team **2**

PROBLEM:
startbox 2 on Chicken_Nuggets_v4 (and other chicken maps) has no metal!

Manual typing !addbox or !balance = not a good fix.

**Comment by KingRaptor** [comment]
*Something* is automatically moving newly joined players from team 1 to team 2 when it shouldn't, and I can't figure out what...
