### ISSUE TITLE
Auto assign bot status to new Springie accounts

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#767]
(and admin status too?)

Though this ought to only apply to the server's own Springies, not anything that someone might create from local host.

**Comment by Licho1** [comment]
There already was code to do that afaik. I think i had removed that because springies are going to be removed too

**Comment by sprunk** [comment]
Does bot status even do anything?

**Comment by Licho1** [comment]
It's just an indication atm. Does nothing.

**Comment by sprunk** [comment]
flobby needs bot status to show correct battle playercount (#977)

**Comment by Licho1** [comment]
springies are dead
