### ISSUE TITLE
Unit Guide generation broken

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#774]
Currently unitguide is served from static files generated while the generator was operational.

The generator itself, however, is broken: the lua component *as well* as bash script expects linux commands and linux os utilities. While msys allows the bash script to work reasonably, the critical part is that the lua script does not seem to be able to use that.

Possible solutions:
- figure out how to make lua work with msys or whatever is that thing that allows unix stuff to work under windows (probably nicest)
- obtain a new linux VM (probably easiest)
- rewrite (who's gonna do it)
- assimilate kaen unitguide instead

**Comment by Licho1** [comment]
You dont need to rewrite lua part just rewrite the 5 line shell runner

**Comment by Anarchid** [comment]
Unfortunately, that is not entirely accurate: https://github.com/ZeroK-RTS/SpringRTS-Tools/blob/master/unitguide/make_unit_guide.lua#L90

**Comment by Licho1** [comment]
Fixed generator, not commited to repo (dunno wher eit is) not wired to teamcity stable. But works and can be manually run at any time.
