### ISSUE TITLE
(zKl) Needs way to place startboxes pregame

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#776]
without text and coordinate guessing.
and a way to remove them.

**Comment by Anarchid** [comment]
There are workarounds:
- use weblobby
- you're probably going to use weblobby anyway

**Comment by Licho1** [comment]
And boxes probably wont be configurable in lobby at all..they are map specific..

**Comment by henczati** [comment]
Other map options can be edited using a GUI, too.
A graphical front-end for the springie command, that needs e.g. entering 1-2 numbers or clicking on a map image. I don't see why this would be a problem.

**Comment by henczati** [comment]
Or is weblobby going to replace ZKL?

**Comment by db81** [comment]
The design docs for new UI seem to gravitate towards less customization, so even if zkwl is realized, drawing startboxes will be an obscure option, if present at all. With @spunk's new boxes this seems even less necessary.
