### ISSUE TITLE
New maps are not "downloadable" despite mirrors working?

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#778]
Example: http://zero-k.info/Maps/Detail/49814
Excerpt from api.springfiles.com:
```
mirrors:
		0:http://springfiles.zebar.de/maps/fairyland_v0.02.sd7
		1:http://spring1.admin-box.com/maps/fairyland_v0.02.sd7
		2:http://api.springfiles.com/files/maps/fairyland_v0.02.sd7
```
The file `http://api.springfiles.com/files/maps/fairyland_v0.02.sd7` is downloadable, and the `maps` directory is listable.

**Comment by Licho1** [comment]
It checks file length check db if it knows about mirrors.

**Comment by Anarchid** [comment]
The file on api.springfiles.com seems to be a `Spring Archive (10,9 MB)`, so filesize is not it.
`LastLinkCheck` field in database is null, so it should have been downloadable.

(as evidenced in it being automatically mirrored by wget for indexing)

**Comment by Anarchid** [comment]
`LinkCount` is however zero.

**Comment by Anarchid** [comment]
Apparently the following can make a 'not downloadable' map downloadable:
```
!map fair 2
!maplink
```

Closing until further incidents.
