### ISSUE TITLE
ZKL chat scrollbar is *over* text in Mono

### ISSUE THREAD

**Issue by henczati** [ZeroK-RTS/Zero-K-Infrastructure#780]
Under linux (Lubuntu 14.04/Trusty) using mono (installed by mono-complete 3.2.8+dfsg-4ubuntu1.1) the scrollbar in ZKL chat is *over* the chat textbox, covering the last cca. 3 characters on every line.

**Comment by Licho1** [comment]
ZKL discontinued, chobby is the savior.
