### ISSUE TITLE
ZKL Battleroom "Add AI" button stretch (ubuntu,mono)

### ISSUE THREAD

**Issue by henczati** [ZeroK-RTS/Zero-K-Infrastructure#781]
The "Add AI" button is stretched to cca. 4-5 times the width of the other buttons (Options, Maps, Teams), and if the ZKL window is not wide enough, the button is partially not visible (with no scrollbar).

Problem observed under:
* Lubuntu 14.04/Trusty
* mono (installed by mono-complete 3.2.8+dfsg-4ubuntu1.1)

In windowed ZKL battleroom:
![zkl_battleroom_map fullscreen](https://cloud.githubusercontent.com/assets/5007476/9705021/a80f0262-54b7-11e5-9d85-5073aaecd7fc.png)
In fullscreen ZKL battleroom:
![zkl_battleroom_map windowed](https://cloud.githubusercontent.com/assets/5007476/9705022/a813687a-54b7-11e5-98aa-fdfe2bae6648.png)

**Comment by Licho1** [comment]
fixed
