### ISSUE TITLE
forum search bugged

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#787]
search something like "sfireman krow skuttle"

google search finds no results:

"
        results for: fireman krow scuttle
        search instead for: sfireman krow skuttle
"

if you click "search instead for: sfireman krow skuttle"

you get 2 pages of results.
then you click page 2, it again shows the results for 
"fireman krow scuttle"
which are empty list

it should display page 2 of search for "sfireman krow skuttle"

there is no way to display this second page that i found. the suggested autocorrected search term overlays this usecase. is there any way to override this?

**Comment by KingRaptor** [comment]
Should just fix the "real" forum search (#49) so it's guaranteed to work properly; then link it somewhere visible and make Google search not find forum posts

**Comment by KingRaptor** [comment]
http://zero-k.info/Forum/Search

**Comment by Licho1** [comment]
fixed
