### ISSUE TITLE
chesti and his abusive behaviour

### ISSUE THREAD

**Issue by Dr0ppy** [ZeroK-RTS/Zero-K-Infrastructure#790]
chesti offends me today so i express my opinions about him he mutes me for a week then i rename my coms because screw him honestly he commanderbans me. f i would offend ANYONE else i bet he wouldnt do this. his behaviour needs rewieving.

**Comment by Dr0ppy** [comment]
he also specced me for no reason

**Comment by Skasi** [comment]
Please make a pull request.

**Comment by Dr0ppy** [comment]
how to recreate:say cheshit to chesti express your opinions about him rename your coms to have cheshit in them and it happens. plz patch it out

**Comment by CarabusX** [comment]
Sounds like driver issue. Try updating your drivers.

**Comment by Orfelius** [comment]
Have you tried turning it on and off?

**Comment by ArchShaman** [comment]
Have you tried reinstalling?

**Comment by sprunk** [comment]
Probably an engine bug, mantis your infolog

**Comment by mojjj** [comment]
this is a bug tracker. use it for bugs only.

**Comment by Dr0ppy** [comment]
it is a bug mojjj it is not eltting me speak/choose commander/use forum :( i need help

**Comment by KingRaptor** [comment]
Working as intended.
