### ISSUE TITLE
Can't edit the title of a thread without editing the body

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#794]

**Comment by KingRaptor** [comment]
It works for me on the test forum (open edit page, change title without touching body, submit). Do you see something different?

**Comment by ArchShaman** [comment]
It doesnt seem to work for me. (I created this post:
http://test.zero-k.info/Forum/Thread/19728?postID=138109 ) and tried to edit it. It didn't change anything oddly.

I think it may be because you have administration rights which allows it to happen without changing the body.

**Comment by ArchShaman** [comment]
Try to replicate using a non-admin account?

**Comment by KingRaptor** [comment]
[Okay, fixed](http://test.zero-k.info/Forum/Thread/19729).
Commits: bb28fa499413713887686734286506fe39e4f016, 1ec618784968a1c672ba986b505b1f38df9716f9

Maybe I should also make it not make an edit history entry if only the title is changed?
Anyway, thanks for reporting!

**Comment by ArchShaman** [comment]
Awesome, thanks for fixing!
