### ISSUE TITLE
[feature] seperate elo for single FFA

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#796]
add seperate elo for FFA and put it into ladders... I bet many will be below good. :)
start value should be 1400
cons:
- more diskspace

pros:
- FFA way different to 1 vs 1, teams or even small teams.

there will be much different elo.

**Comment by Licho1** [comment]
Elo is not really good for FFA because in FFA you also have order of rankings (who dies first and who last).
Furthermore if we only had FFA elo it would take AGES to converge to meaningful results.
You need some 30-100 wins for elo to convertge, imagine that in FFA...

**Comment by sprunk** [comment]
FFA also has tons of randomness (eg. pros can eliminate each other and noob wins) and empirically it seems it would converge to Team elo because it requires similar skills (porc, eco, striders).

**Comment by Licho1** [comment]
Closing unless more  specific proposal is put in place

**Comment by Licho1** [comment]
ELO wont work well because elo is only given to winners. You will need to win like 30 FFA for ELO to get some results..
