### ISSUE TITLE
[vid] broken in test forum

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#798]
See: http://test.zero-k.info/Forum/Thread/19719

**Comment by Licho1** [comment]
[vid] does not work with https://www.youtube.com/watch?v=C5e6eG6bXAQ&feature=youtu.be&t=31
its coded to only work with mp4 etc file names. This link does not contain file name it wont work.

**Comment by ArchShaman** [comment]
Ah, thanks for the clarification.
