### ISSUE TITLE
Improved Ignore

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#799]
Currently ignore only blocks in-lobby communications from undesired elements. Ignore could be expanded to block in-game and Springiee communications (game<->lobby transmissions) from ignored players.

This could also reduce administration load by providing players with an effective "mute" button for players they are tired of hearing passive-aggression, insults, or abusive language from or are being harassed by.

**Comment by Licho1** [comment]
implemented
