### ISSUE TITLE
feature request: tell NW about next tourneys

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#805]
so !tourney in chat will return next tourney time or how long until next tourney

**Comment by Licho1** [comment]
best to show it somewhere in lobby itself. Perhaps we can use topic for that?

**Comment by Jamanno** [comment]
Don't you know IRC bot style,
!time
!meetings

**Comment by Licho1** [comment]
Unclear how this is meant to work
