### ISSUE TITLE
zero-k autohost on spring server?

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#814]
discussion about running an zK autohost on spring server:
https://springrts.com/phpbb/viewtopic.php?f=16&t=33907

yay / nay / wuiii

**Comment by Licho1** [comment]
I think its fine, as long as the game itself does not crash there etc :)

**Comment by Licho1** [comment]
Nothing to do on our side, it's good to have some extra external autohost as long as its clear its not the official one.. if there is need for some assistance/tech help reopen.
