### ISSUE TITLE
exited/desynced matches give no replay link = no way to report

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#818]
1) Have teamkiller
2) Vote to exit match
3) Match exits
4) No replay. (at least no link link to replay given in chat)
5) Hard to report teamkiller without link to replay

**Comment by Licho1** [comment]
Dunno sint storing all matches excessive?

**Comment by knorker** [comment]
imo the teamkilling/trolling is more excessive

**Comment by let4be** [comment]
we could store ALL matches, hdd storage is DIRT cheap nowday anyway
you can easily have 3tb for like 200$ this would be enough for years of recording zk games

**Comment by Licho1** [comment]
Put it online, on some fast line and code a syncing then :)

**Comment by Licho1** [comment]
desynced now appear on website, exited no (by design)
