### ISSUE TITLE
Teams room: don't create FFAs

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#827]
Some maps work for both 2teams and FFA and so they have 3+ boxes. Small Teams, Large Teams rooms should only create 2 teams always even if map has more boxes.

**Comment by Licho1** [comment]
Dislike this change, playing team FFA on "all welcome" should be an option!!
Where else can you play team FFA? FFA host wont allow team FFA, reverting.

**Comment by sprunk** [comment]
What happens if there are eg. 8 people on 4-person FFA map in FFA host? Won't it create team-FFA with 4 teams 2 people each?

**Comment by Licho1** [comment]
It will and I think that is correct... Better than 2 teams if its an ffa map..

**Comment by sprunk** [comment]
So people can move to FFA host for team FFA? That would mean large teams room can stay as 2 teams.

**Comment by Licho1** [comment]
There is no team FFA, and there is no way to play team FFA on FFA host.
Team FFA is more similar to teams than to FFA and its natural to use "all welcome" host for it, since you can control it by choosing map.

**Comment by sprunk** [comment]
I'm not sure what you mean by "team FFA".

If you have eg. 12 people in FFA room and pick a map with 4 boxes, it makes a "team FFA" with 3 people in each team, no?

Or do you mean something else by team FFA?

**Comment by Licho1** [comment]
Yes thats team ffa.. basically team game with more than 2 teams.
