### ISSUE TITLE
Wiki should not be too forumlike.

### ISSUE THREAD

**Issue by Anarchid** [ZeroK-RTS/Zero-K-Infrastructure#837]
Currently wiki articles:
- show up in new forum posts when commented on
- can be commented on 

Both of these seem to be none too good. At the very least,  the "thread" OP should be editable for most people, and there should be clear disambiguation (in style maybe) between the actual wiki page entity and its comments.

**Comment by Anarchid** [comment]
Oh i've just realized the wiki "release" was accidental? Nevermind then.

**Comment by Licho1** [comment]
Wiki will look like wiki + comments below. Similar to how maps work. But im first upgrading every component, because that was my planned strategy. Release was accidental
