### ISSUE TITLE
Platinum doesn't spawn

### ISSUE THREAD

**Issue by KingRaptor** [ZeroK-RTS/Zero-K-Infrastructure#847]
May be related to #830 

Possibly relevant log from test server: http://pastebin.com/PVKCiv0D
(maybe spring is null [here](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Springie/Springie/autohost/AutoHost.cs#L600)?)

**Comment by KingRaptor** [comment]
9e1d06d30a5d1554c9183a5eb5045d8d5df1ce5c does not fix it

**Comment by Jamanno** [comment]
can someone fix that please, since some are going again for newton ramps in  4 vs 5 or such...
Also requests are high for "normal games" :)

**Comment by KingRaptor** [comment]
Never did figure out why Platinum doesn't spawn when told to, but Rhodium has been created to take its place.
