### ISSUE TITLE
(autohost) NullReferenceException on !map

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#849]
!map
* Elerium Sorry, you do not have rights to execute map
* Elerium System.NullReferenceException: Object reference not set to an instance of an object.
* Elerium    at Springie.autohost.Polls.VoteMap.PerformInit(TasSayEventArgs e, String[] words, String& question, Int32& winCount)

the next !map commands worked normal

**Comment by Licho1** [comment]
Unable to replicate..

**Comment by db81** [comment]
The same happened to me as well. Most likely it only happens when springie rolls a particular map for the next one.

**Comment by Licho1** [comment]
Hmm I checked the code but only way i could imagine it is when you have a host with 0 players or when next possible map list is empty.. Dunno how that can happen on live host..

**Comment by ArchShaman** [comment]
It's an individual map that's causing this.

It was a known issue at one point. We tried to hunt for it.

**Comment by Skasi** [comment]
This happened to me twice yesterday within a few minutes when I was alone in the small teams room. Licho, if you want to replicate it just spam !map a hundred times.

**Comment by knorker** [comment]
imo tbugs should not be closed just because it is hard to reproduce or only happens sometimes..

**Comment by Skasi** [comment]
Isn't there some "feedback needed" tag or such?
