### ISSUE TITLE
(homepage) replay search has false results for player names

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#855]
It seems in replay search one can enter total gibberish for playernames and it will still return results.
Example: enter playername "dfghdfhdrthdrhtdfgh" and it will return same results as if you left the field empty.

![bla2](https://cloud.githubusercontent.com/assets/3044855/10558223/c77dddae-74c8-11e5-92e7-eddea2a769b3.jpg)

Or more real world example which is more confusing:

1) Want to search replays of [Fx]Drone http://zero-k.info/Users/Detail/169802

2) enter "drone" into filter

3) Lots of results, but the "real Drone" is not in any of them

![bla2](https://cloud.githubusercontent.com/assets/3044855/10558204/0785a6f8-74c8-11e5-9a77-62ae1e5f61eb.jpg)

**Comment by Licho1** [comment]
Because there would be many false positives with 'substring' player search (licho can be part of any number of other names like lichosux lichosux2 etc) it needs exact match. i will add autocomplete for this though

**Comment by knorker** [comment]
Yes, but that is something different...
(would be nice feature too, way to reliably search battles by a player, maybe by ID?)

There exists no player "dfghdfhdrthdrhtdfgh", so the search should just come up empty.
(as it does when searching for a map "dfghdfhdrthdrhtdfgh")
