### ISSUE TITLE
Preview window not closing properly

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#857]
When pressing "Close" on the lower right on a forum post's preview a "Loading..." window pops up and remains in the middle of the screen.

When pressing "X" in the upper right the same "Loading..." window pops up and in addition the "Preview" button next to "Submit post" does not reappear.

![zk](https://cloud.githubusercontent.com/assets/132906/10576437/8798bc58-7663-11e5-9c88-b5eb24cbd72d.png)

**Comment by Licho1** [comment]
Unable to replicate, maybe connection problem for you?
http://i.imgur.com/ZX5CSrB.png
button is missing because preview auto refreshes..

**Comment by Skasi** [comment]
Missing button was fixed. Problem of "Loading..." window still persists. Whenever closing the preview window (either by top-right "X" or by "Close" at the bottom) the "Loading..." bar pops up. Using Firefox 43.0b1

**Comment by Aquanim** [comment]
I can recreate the "Loading..." bar in Firefox but not in Chrome.

**Comment by Licho1** [comment]
fixed by auto refresh removal
