### ISSUE TITLE
Linebreak in forum ignored

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#858]
The linebreak inside the following code is not drawn on the actual post, here's the forum post http://zero-k.info/Forum/Thread/20471?postID=144920#144920

Here's the post's code:

>There'll still be a bit of inconsistency because :visited "Post comment" buttons - being links and all that - have a slightly darker font color. All in all inconsistency is to be expected when trying to give `<input>`s the same style as `<a>`s.
>
>What's funny is that there's yet another set of `<input>` and `<a>` styles used..

The empty line between the two paragraphs is missing.

**Comment by Licho1** [comment]
Its because it is inside <a> which is then unclosed..

**Comment by Licho1** [comment]
fixed
