### ISSUE TITLE
Do something to wiki _ tag

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#865]
_ is used in a lot of names for widget files and code vars but on forum it works like < i >.

For example there's a gadget called "start_unit_setup.lua" but it cannot be written like that because it ends up as "start<i>unit</i>setup.lua", this makes documenting stuff harder. 

_ is not used much and < i > already exists so it is more annoying than helpful.

**Comment by Licho1** [comment]
only allow it if before or after the symbol is a space.

**Comment by db81** [comment]
What if the variable starts with _? It's better to have a &lt;code&gt; tag. And I agree it's just an annoyance for little gain given that &lt;i&gt; exist.
