### ISSUE TITLE
maplist & replays list do not load more results when scrolling down

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#867]
Both http://zero-k.info/Maps & http://zero-k.info/Battles only show "one page" of results, no new results are loaded when you have scrolled down to the end. (as it used to)
This makes it impossible to look at full map list or look at older replays.
Firefox 41.0.1
http://zero-k.info/Forum/Thread/20478

**Comment by Aquanim** [comment]
This appears to be a Firefox-specific issue. I have the same problem with Firefox 41.0.2 but it appears to work correctly with Chrome v46.0.2490.71 m.

**Comment by knorker** [comment]
it does not work on Internet Explorer 9 either.

**Comment by knorker** [comment]
Are fixes to website instantly or do they have to be "deployed" in some way?
I ask because it behaves the same still..

**Comment by Licho1** [comment]
All thats in master is on http://test.zero-k.info/
Later I push it to "stable" branch and then its on live site as well.
