### ISSUE TITLE
Protect Critical Wiki Pages

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#874]
Currently there is a certain wiki page that displays for newbie players ("Newbie Intro"). A vandalizer can change this to display anything he/she may want.

Such as:
![epicwin](https://cloud.githubusercontent.com/assets/7841201/11164149/883269a6-8aa5-11e5-96e4-7dc496e9a69e.JPG)

While yes the revert button does help, it can still scare off potential newbies if they bare witness to such an attack.

For proof, try logging into the test site with a newbie account.

**Comment by Skasi** [comment]
All critical wiki pages could probably use a white list. Or perhaps some very simple automated protection. Iirc wikipedia has lots of bots that can detect and revert vandalism, spam and similar.

**Comment by ArchShaman** [comment]
Well.. pretty much everything in Site should be protected. Most notably:
* Features
* Links
* COC (duh)
* Probably some other things I couldn't find.

**Comment by Licho1** [comment]
Imo only things that are directly exposed to newbies/external views should be. Features, new games and maybe links or download page.
Rest is non essential and we can go with 99.99% reliability and quick revert such changes.
As this is not a coding ticket (anyone can lock those) closing.

**Comment by Skasi** [comment]
It **is** a coding issue. Locking wiki pages means they can't be improved, so something else is needed.
