### ISSUE TITLE
(forum/lobby) more contrast for the map category icons

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#878]
When scrolling  http://zero-k.info/Maps the category icons look very similiar.
Hills / Flat / Mountains all have greenish color with yellow sun in the corner and white clouds.
The actual relevant part of the icons is only a small part of already small 32x32 pixels graphic.

The sea rating icons could be more different/clearer too.

**Comment by Licho1** [comment]
Can you support some icons please? Also peple asked for "cliffs" icon.
