### ISSUE TITLE
Maps: add a new "Cliffs" terrain label

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#880]
See http://zero-k.info/Forum/Thread/20641

**Comment by Licho1** [comment]
Will do, provide icon please.

**Comment by sprunk** [comment]
Mountains
![mountains](https://cloud.githubusercontent.com/assets/2573076/12961607/bfc002fc-d041-11e5-82c9-f6263d8633a2.png)
Cliffs
![cliffs](https://cloud.githubusercontent.com/assets/2573076/12961609/c091d1a6-d041-11e5-8f86-81e91f2ac7f1.png)
Hills
![hills](https://cloud.githubusercontent.com/assets/2573076/12961610/c0b9191e-d041-11e5-991b-a5a7039887c3.png)
Flat
![flat](https://cloud.githubusercontent.com/assets/2573076/12961611/c0db49c6-d041-11e5-99d6-c9674380aa7c.png)

These are very simple but much clearer than current icons.

**Comment by Licho1** [comment]
Also uglier and not matching to other categories (like sea coverage). It might also look like a sea due to  too deep blue and missing sun.

**Comment by sprunk** [comment]
I could improve these (add sun, make sky brighter) and also create matching ones for other tags but they would all be the same ugly paint style. Is that ok or do they have to look good?

**Comment by Licho1** [comment]
No art provided, closing. Reopen if you get a decent good looking art.
