### ISSUE TITLE
Skirmisher doesn't work when offline

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#881]
It works when zkl isn't connected to the server, but doesn't even bother launching Spring when being offline. (It says "Launching Spring..." but no process is spawned)

Occurs on Win7 64 bit.

**Comment by Licho1** [comment]
provide repro steps/logs. Tested it, after logging out, going to skirmisher and picking map and adding AI it works.

**Comment by DeinFreund** [comment]
Did you actually go offline? To reproduce all I have to do is disconnect Internet, add AI, try to start game.

If you still can't reproduce I'll happily provide a video or logs.

**Comment by DeinFreund** [comment]
Here is the zkl log if that helps: http://paste.springfiles.com/view/e5a0bc5e

**Comment by DeinFreund** [comment]
Skirmisher has ceased existance.
