### ISSUE TITLE
Remove Ninja voting rights

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#888]
Ninjas have no rights to interfere with votes that do not concern them

**Comment by sprunk** [comment]
It's not possible to know in advance who will spec

**Comment by db81** [comment]
What if we discount the vote when the voter specs?

**Comment by sprunk** [comment]
Then people just wait with respeccing until the vote passes.

**Comment by db81** [comment]
Yeah you're right, that would only help with !start votes.

**Comment by KingRaptor** [comment]
Closing since this is a wontfix anyway.
