### ISSUE TITLE
votemove poll should not be displayed ingame

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#891]
Very often, room is full. Some playing FFA (mostly) and someone calls a votemove vote to join e.g. Springiee.
Ingame players see this poll and vote automatically "no". 
-> Vote was adressed to wrong group....
Those who start this vote just want to get another game running because normally, FFA takes ages.
Perhaps try to not display move votes into battle chat. Just leave it in lobby. And players already playing shouldn't be allowed to vote maybe.
Please do not come up with this evertaking QuickMatch will solve all this stuff.

**Comment by sprunk** [comment]
Belongs to ingame
https://github.com/ZeroK-RTS/Zero-K/issues/1327
