### ISSUE TITLE
Repurpose All Welcome

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#898]
Currently the all welcome host is being used as a general big teams room. It would be nice to see it have autobalance remove bots (such as in small teams) and branded a general pvp room (since we already have a COOP room, why do we need 2?)

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/c1ab8d42b468a4a88456e07c4234c2195397755e
