### ISSUE TITLE
passwords can be stolen from user-posted error messages.

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#905]
visible md5-hash plus weak passwords (common in games) = lol.
players should be told to change their password and to be more careful

**Comment by db81** [comment]
Another way for people to compromise their passwords is to post a link from ZKL that contains "asmallcake" GET parameter with the password. I've seen this happen twice.

**Comment by knorker** [comment]
"asmallcake" happend even to admins.I thought it was fixed, that is at least 2,3 years old.

**Comment by Licho1** [comment]
Chobby fixes this by redacting stuff.
