### ISSUE TITLE
lobby stores password in cleartext

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#908]
...since years.
problem is when players share config files to help with some bug (either on their own or by being asked)
or people who use same PC.

**Comment by KingRaptor** [comment]
Which one, ZeroKLobbyConfig.xml? It no longer contains password in current lobby version. 
At least I opened mine and didn't see it, and ZeroKLobby.Config.cs says it stores in an isolated location (though still presumably in plaintext).

(catch me on lobby if you know of it being stored somewhere visible and don't want to say here)

As for shared PCs, there are options to not remember the username/password, though they might need to be more visible (and set to forget by default).

**Comment by knorker** [comment]
> "...no longer..."
Since when?
I had downloaded zK lobby just prior to posting that.

yes ZeroKLobbyConfig.xml
Of course it needs the "remember password" thing checked in options.

**Comment by KingRaptor** [comment]
I'm not getting it in ZKL 1.3.2.101 with`<DiscardPlayerName>false</DiscardPlayerName>`

Will try with a fresh download. Does the download link point to an old version, or is this the .NET 4.0 version?

**Comment by KingRaptor** [comment]
Did a fresh download from http://zero-k.info/lobby/Zero-K.exe to a separate folder (and specified a separate datadir on first run) and ran. Then noticed the config was still copying some settings from my normal one, so backed up and deleted my usual ZeroKLobbyConfig.xml and repeated the above steps. No password stored in the new config .xml.

**Comment by Licho1** [comment]
Yeah its stored in secure system storage now.
