### ISSUE TITLE
No server? Website / IRC, maybe others?

### ISSUE THREAD

**Issue by amkeyte** [ZeroK-RTS/Zero-K-Infrastructure#911]
Sorry, I don't have a better place to put this. I'm not seeing any notices on the FB page or here, so it's probably on my end. Everything worked for a few days, then it quit last night.

I am unable to access any online assets from within the Zero-K lobby, also in Firefox Zero-K.info gives 404 error. Ping and tracert work as expected, however. I'm not experiencing any other access issues to normal browsing for other web servers.

Again, I would post this on the forum or something, but I cant get to it.

Any ideas?

Thanks
Aaron

**Comment by db81** [comment]
Just brought it back online.

**Comment by amkeyte** [comment]
Awesome thanks!
