### ISSUE TITLE
double login / password reset

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#912]
Not sure if this is valid, but it should be tested.

I used #905 to steal someones password. I pm'ed him in lobby that he should change his password.

He said he could not change pw because of some error-message.
I logged out of his profile (browser) and then he could change password.
If this was NOT general server-failures from past days and NOT player-side problem, then it is imo a security problem.

Imagine an attacker who does not have the pw but only manages to steal a temporary login. (like hijacking a session or something)
Usually the user would now log in too, and since orginal user knows the password he can set a new password and lock out the attacker.
Problem is that in zK it does maybe not work.
Also logins to same account from seperare IPs are somewhat strange?

**Comment by Licho1** [comment]
login should not be possible without a password (stealing session should not be possible)
