### ISSUE TITLE
ability to kick bots

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#913]
some funny people add bots to a public games host all welcome. kick bots would be useful.

**Comment by db81** [comment]
I think no one gave admins that ability because you can always kick the owner. Is it true that someone is able to spam unowned bots?

**Comment by db81** [comment]
On investigation, it turns out an admin can actually [kick any bot](https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/ZkLobbyServer/ConnectedUser.cs#L565), so it's an UI problem (and ZKLS allowing you to specify arbitrary owner for bots you add).

**Comment by knorker** [comment]
the solution to "people add bots to games where it is not wanted" is not a kick-bot-button. 
the solution are properly configured autohosts.

**Comment by db81** [comment]
Don't PvP springies remove them when autobalancing?

**Comment by knorker** [comment]
Does it matter? Adding them in first place should be blocked.
Also go to replays-list, put filter "bots=yes" and see that on "All Welcome" there are indeed matches with bots.
It already was annoying that whenever you join a normal-looking host there was the chance that it would turn into a 10v10 clusterfuck on some silly tiny joke-map. Now another mix has been invented, add bots to the clusterfuck. http://zero-k.info/Battles/Detail/391691
The hosts suck and a kick-bot-button only fights symptoms.

**Comment by db81** [comment]
df42b46 makes sure you can always kick bots by kicking the owner, making the ability to kick individual bots pretty unimportant. I'm assuming @mojjj's issue was about someone spamming rooms with non-removable bots, closing since that's fixed.

**Comment by mojjj** [comment]
well. the point why i wrote this is, the owner was not in the room, but the bots remained. so kicking nobody would result in having still the bot. dunno if this is a bug too. !rehost does the trick, but disconnects everyone.

**Comment by db81** [comment]
That's what df42b46 fixed.
