### ISSUE TITLE
since newest ZKL random bots get added by some players

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#914]
after new update some player add countless bots (CAI) to team games. :(

**Comment by db81** [comment]
#913

**Comment by db81** [comment]
This report is pretty unclear. Users adding unwanted bots has been happening every now and then since forever. What does it have to do with the ZKL update?

If this is about bot owner spoofing (allowing to add bots that don't disappear when you kick the offender), df42b46 fixes that.
