### ISSUE TITLE
zkl breaks when adding 9001 bots at once

### ISSUE THREAD

**Issue by mojjj** [ZeroK-RTS/Zero-K-Infrastructure#920]
i suspect anteep smurf there. suddenly, room is filled with more bots than the screen is long. zkl freezes, needs win task manager to kill. happend to everyone in the room (as we just started game we talked)

http://imgur.com/6infjPm

restrict adding bots to a reasonable number per second.

**Comment by Sgathec** [comment]
Yes, adding a lot of bots through a script causes too much lag.

**Comment by db81** [comment]
Limiting the maximum number of bots in a room is probably simpler.

**Comment by DeinFreund** [comment]
Would it be enough to just add a check(counter) here?
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/b710abb422136951445cb1323695b0133ee14ada/ZkLobbyServer/ConnectedUser.cs#L545

**Comment by db81** [comment]
Fixed in 7820f96.
