### ISSUE TITLE
ZKL Totally unstable

### ISSUE THREAD

**Issue by ArchShaman** [ZeroK-RTS/Zero-K-Infrastructure#925]
Keeps blinking out, chat greys out, panel breaks, userlist breaks.

errorlog:
http://pastebin.com/atNCwN0F

**Comment by Anarchid** [comment]
Does this still happen?

**Comment by ArchShaman** [comment]
Restarting fixes it it seems.

**Comment by Licho1** [comment]
It seems lobby was missing image. ITs meant to DL it but perhaps network failed temporarily? Reopen if it occurs again
