### ISSUE TITLE
Mute punishment prohibits playing 1v1s and 1 player PvE games.

### ISSUE THREAD

**Issue by Orfelius** [ZeroK-RTS/Zero-K-Infrastructure#926]
Springiee operates on plain text commands which makes it impossible for a muted person to vote or issue any votes including resign, start etc. That basically unables a muted person to play a 1v1 game (and to some extent 2v2 games) because it requires a muted person to start a game which is impossible since all text imputs are simply ignored.

Edit: Correction all Springiee imputs are ignored, I can still use server commands such as /join

**Comment by Skasi** [comment]
What about private messages to Springiee?

**Comment by sprunk** [comment]
Change title to "Mute prevents 1v1 games"? Blocking text input is what mute is supposed to do.

**Comment by Orfelius** [comment]
Ok so apparetly I am able to vote resign trough in game though the message gets blocked.
But I cant vote for anything which enables me to play properly. Isn't mute just supposed to make people not able to communicate?

**Comment by Licho1** [comment]
will be fixed by mm in the future.

**Comment by Orfelius** [comment]
But mm and singeplayer are not fixes.
Being muted is fine - it means a person can't interact with the rest of the community. But at the same time it also wont let them play the game since they cannot !start a game because Springiee commands are written in a plain text.
Its shadowbanning people, not muting them and imo its not ok.

**Comment by sprunk** [comment]
You won't need !commands to use the MM.

**Comment by Orfelius** [comment]
But I need !commands to play custom games.

**Comment by Licho1** [comment]
During the process springie services will be moved directly to ZKL server and thus will be able to skip mute and work as normal.

**Comment by Orfelius** [comment]
Alright, that seems reasonable.
