### ISSUE TITLE
(site) Latest Maps

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#927]
Latest maps (http://zero-k.info/Maps) does not actually sort maps by date.
Not sure what it's sorted by actually.

**Comment by Licho1** [comment]
The order of maps is based on featured order number (set by admins). 
I dont see any "latest maps" there .. and yeah its a feature to add!

**Comment by gajop** [comment]
Check http://imgur.com/Lxur0Vj

**Comment by Licho1** [comment]
Oh, its a wrong label then..
