### ISSUE TITLE
http://zero-k.info/Users - average teamsize is actually playercount

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#929]
I think on http://zero-k.info/Users ATS (tooltip=average team size) actually means the total count of players in the match, not per team.

For example this player http://zero-k.info/Users/Detail/222617 is on second position with ATS of 30.0 

He only played one match http://zero-k.info/Battles/Detail/72663 which was 15v15

**Comment by db81** [comment]
I think that's fine as long as it doesn't count spectators.

**Comment by Skasi** [comment]
Simply rename it to "average game size"?
