### ISSUE TITLE
(lobby) Unhandled Exception with mono

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#930]
player wrote:
" I am trying to run the lobby in Mono, nothing appears, and I get the following text, help anyone?"

post contains a log:
http://zero-k.info/Forum/Thread/20880?postID=149913#149913

**Comment by Licho1** [comment]
User PC is missing library System.ServiceModel.dll  . it needs to be added to mono, perhaps upgrading mono should help (it does contain it).
