### ISSUE TITLE
Site is clueless about com modules

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#935]
Allows a lot of invalid setups, does not allow some valid ones.

**Comment by KingRaptor** [comment]
Is there a handy list somewhere of the following?
* Modules that can be installed on chassis X on site but not ingame
* Modules that can't be installed on chassis X on site, but can be ingame
* Modules with wrong stats (cost, min level, prerequisites, etc.)

Maybe I can figure out a solution for site letting the user install modules earlier in the sequence than their prerequisites. (Don't count on it though... ...)

**Comment by KingRaptor** [comment]
First level morph is listed as costing 0 metal, should be 25

**Comment by KingRaptor** [comment]
Recom having the wrong weapon 2 options can be fixed with a DB change after infra merge. Other issues still need listing.

**Comment by Licho1** [comment]
fixed afaik
