### ISSUE TITLE
joining disbanded clan is not possible after recreating

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#936]
http://zero-k.info/Clans/Detail/1893
never left this clan and clan got disbanded...
never recreates this clan and it :
- does not appear in clan search neither clan list
- joining this clan leads to this error:

> Sequence contains no elements
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.InvalidOperationException: Sequence contains no elements
> 
> Source Error: 
> to be continued ...

**Comment by KingRaptor** [comment]
Note: I've also manually undeleted that clan, but later clans will still have the problem if recreated before next site deploy.

Thanks for report!
