### ISSUE TITLE
(forum/wiki) wiki:toc links break (or should not exist in forum?)

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#939]
A variante of #938 but maybe different enough:

1) go to http://zero-k.info/Forum/Thread/2424
2) Go to page 4, see my test posts
They look like this:
![anchorlinksforum](https://cloud.githubusercontent.com/assets/3044855/12871408/1aae7f52-cd79-11e5-99d4-fddb3133a100.png)

3) Press F5

4) Now the links look like this:

![anchorlinksf5](https://cloud.githubusercontent.com/assets/3044855/12871410/26241f5e-cd79-11e5-9698-d937bc79afee.png)
---

On this thread the same posts always looks correct:
http://zero-k.info/Forum/Thread/20993

---
Not sure what the bug is:
a) wiki:toc is not supposed to work/happen in the first case
b) wiki:toc should work but sometimes it does not

**Comment by Licho1** [comment]
It is functionally incapable of generating that section without links.
If it ever happens again, please check HTML source code of that TOC section.
It seems to me as some random browser quirk. Clsoing

**Comment by knorker** [comment]
It reproduces every time for me. firefox, win 7
http://pastebin.com/Z7qGfER2

**Comment by Licho1** [comment]
Please try on test site now. Could be fixed by other TOC fix.

**Comment by Licho1** [comment]
http://test.zero-k.info/
