### ISSUE TITLE
ZKL joins new players as player and not as spec

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#940]
It would be better that if you join you are spec and have to unspec to play not the other way.
Maybe some newbies do not know what happen... what is so bad if they automatically watch first game?
Many normal players need to press spec button first. (please do not come up with speccing is bad)

**Comment by Licho1** [comment]
This is intended. Not going to fix it. People dont know how to "unspec" and very often they initially play with friends etc.

**Comment by Jamanno** [comment]
If they do not know how to unspec should they play a complex game like ZeroK?

**Comment by sprunk** [comment]
Yes because live spectating is actually a relatively uncommon feature and people definitely don't expect it to be default.
