### ISSUE TITLE
(lobby) gamestart disabled despite/because multiple copies of map are downloaded

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#944]
No idea what to title this. 
Interpretation of http://zero-k.info/Forum/Thread/21035

Player can not play map Titan Duel.
It downloads but the start-button is dark color and not working. (disabled)
Other maps work.
Watching a replay of that map works.

From player's posted archivecache10.lua file one sees the same exists, as multiple copies:
TitanDuel(1)(1).sd7
TitanDuel(1)(2).sd7
TitanDuel(1)(3).sd7
TitanDuel(1).sd7

The actual filename (TitanDuel.sd7) does not appear in player's archivecache10.lua

**Comment by Licho1** [comment]
fixed
