### ISSUE TITLE
clan balances fail due to minimal elo gaps

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#948]
when playing like 7 vs 7 or 4 vs 4. Clan balance often fails.
e.g. clan has following elos:
1) 1955
2) 1842
3) 1515
4) 1480

other players:
5) 1920
6) 1850
7) 1510
8) 1470

it would make team sometimes like that:
2,6,7,8

It would be nice if clans get hard teamed until there is a gap from more than 100 elo to other team or such. Of course other team should have high elo players as well. But mostly it could switch clanplayer with 1800 elo and other player with 1800 elo.

**Comment by sprunk** [comment]
100 elo difference means 36:64 % win chance, too much.
Currently it's max 40 (44:56 %)

**Comment by Jamanno** [comment]
But as I said sometimes it  just changes 1850 elo with 1832

**Comment by Licho1** [comment]
Hmm oh right 36% feels low.. well revert at will!

**Comment by sprunk** [comment]
70 elo diff gives 60:40%, how about that?

**Comment by Licho1** [comment]
sounds good to me

**Comment by Jamanno** [comment]
like this game:
http://zero-k.info/Battles/Detail/402416
Elos:
Firepluk: 2160
Dancer: 1720
Denzen: 1466

AveragePlan: 1890
Chesti:1872
Indaled 1612

no point to be in same clan if you do not get balanced into it.

**Comment by sprunk** [comment]
change has not been deployed yet?

**Comment by Jamanno** [comment]
well this what strange to in my opinion:
http://zero-k.info/Battles/Detail/409290
seems like no then?

**Comment by sprunk** [comment]
not yet
