### ISSUE TITLE
leaving clan while having active poll for clan roles leads to error

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#949]
start a poll like nominate for clan leader and then try to leave clan

> [InvalidOperationException: Collection was modified; enumeration operation may not execute.]
>    System.Collections.Generic.Enumerator.MoveNext() +4358725
>    ZkData.DbExtensions.DeleteAllOnSubmit(IDbSet`1 dbSet, IEnumerable`1 toDel) +160
>    ZeroKWeb.Controllers.ClansController.PerformLeaveClan(Int32 accountID, ZkDataContext db) +865
>    ZeroKWeb.Controllers.ClansController.LeaveClan() +21
>    lambda_method(Closure , ControllerBase , Object[] ) +62

**Comment by Licho1** [comment]
should be fixed
