### ISSUE TITLE
(lobby) wrong password saved for auto login

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#950]
http://zero-k.info/Forum/Thread/21077

> Hello,
> i have a problem.

> Every day i login in game manual becouse ZK save wrong password
> https://yadi.sk/i/SbKQoQzPpTvMU

> rewrite password in settings not work
> https://yadi.sk/i/O_zYrn1UpUFD7

> How i delete wrong password and write my password?

**Comment by Licho1** [comment]
fixed
