### ISSUE TITLE
Make the "Open a new battle" dialogue password text hidden

### ISSUE THREAD

**Issue by gajop** [ZeroK-RTS/Zero-K-Infrastructure#951]
The text in the password field should either be invisible or alternatively have *** symbols as replacements. Helps against people behind you or, more likely for most of us loners out here, people watching your stream.

**Comment by Licho1** [comment]
What??? You want this password to be visible so that you can verify its text for friends..
it makes no sense to hide it

**Comment by gajop** [comment]
Safety first (it was also rather amateurish to show it). 
If you see a reason for it to be shown *sometimes* then maybe it should be possible to preview it by selecting a checkbox: "Show password"

**Comment by Licho1** [comment]
afaik its standard not not hide this password in other games .. its inconvenient and leads to errors because you have to type in blind and tell it to friends.
