### ISSUE TITLE
Lobby: add reset settings button

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#956]
Resetting widgets/hotkeys is hard to discover, it involves deleting some files manually. It would be good if it was a button.

**Comment by Licho1** [comment]
Button already exists in ZKL

**Comment by sprunk** [comment]
Just found it. It says just "clear" which is bad for discoverability and could imply it's for setting lobby settings instead of ingame.

Is the name on the button a part of the image? I wanted to change it to something better ("reset ingame settings") but couldn't find anything.

**Comment by Licho1** [comment]
Text is stored as a string, not image, it should be somewhere..
