### ISSUE TITLE
News posts cannot receive html tags

### ISSUE THREAD

**Issue by sprunk** [ZeroK-RTS/Zero-K-Infrastructure#959]
Try making a news post with any html tag (for example \<br/>). Preview works fine but posting causes an error:

> A potentially dangerous Request.Form value was detected from the client (Text="bla
> \<br/>
> bla").

**Comment by sprunk** [comment]
fix didnt actually work

**Comment by Licho1** [comment]
fix did work as planned, deployment failed, teamcity is down
