### ISSUE TITLE
(lobby) white page after first lobby start

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#960]
1) download lobby/installer

2) see this:

![2](https://cloud.githubusercontent.com/assets/3044855/13553300/0ffa6f86-e385-11e5-980d-c18fa3fe3524.png)

3) Is there supposed to be just a white background? Looks bugged/boring/ugly

**Comment by Licho1** [comment]
What windows do you have?

**Comment by knorker** [comment]
7 64bit

**Comment by Licho1** [comment]
Is the build in browser otherwise working for you? Are other pages loading there? Like maps list?

**Comment by knorker** [comment]
All other pages in the build in browser are working. But after lobby-start the login screen always looks like that, with white background.
(I thought it is only after first start after fresh install, but actually is at every start)

What it is it supposed to look like?

**Comment by Licho1** [comment]
There should be special wiki page on background with some "tutorials" and generic intro...
 But im working on removing that too so this is a temp issue

**Comment by knorker** [comment]
But while the log-in dialog is displayed it is not possible to click anything else?

**Comment by Licho1** [comment]
Click not but:
1) it should be visible (the message)
2) there should be no download during login dialog
3) there actually isnt any download or download failure in steam version
