### ISSUE TITLE
(installer) no way to install installation path, files simply explode into dowload folder?

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#963]
1) start installer

2) Message box: Create desktop icon? Yes / No

3) Installation begins.

4) There was no option to select an installation path or even chose the hard-disk.

5) The installer simply exploded its files over the directory where it was downloaded to!
In my case that was C:\Users\otte\Downloads
So when I download the installer to desktop or accidently download it to my music folder or elsewhere, then the installer would just fill those folders with its stuff?!

![lol installation](https://cloud.githubusercontent.com/assets/3044855/13553378/bd377ab6-e387-11e5-9199-3be7a5eb65b0.png)

**Comment by Licho1** [comment]
Which isntaller? There shoudlnt be one atm..
 Just .exe download

**Comment by knorker** [comment]
Zero-K.exe from http://www.moddb.com/company/0k-development-team/downloads

**Comment by Licho1** [comment]
This should be removed.. we don't have any "download" or "installer" pack afaik. 
It should be replaced by link to ZK site which will cotnain direct link and link to steam store.

**Comment by knorker** [comment]
So you are saying it is yet another case of #760 ?


Both zero-k website and moddb offer a while named "zero-k.exe"
Both files have same filesize and claim to be same version.
(I am not going to compare file hashes or whatever for such mess)

![installers_moddb_zerokwebsite_same](https://cloud.githubusercontent.com/assets/3044855/13563909/f8c0f260-e445-11e5-82a0-a9405b08cc30.png)

![installers_moddb_zerokwebsite_same_properties](https://cloud.githubusercontent.com/assets/3044855/13563983/6d437126-e446-11e5-9286-732256444cb7.png)



> afaik

You are lead developer of game/lobby. Of all possible people you should be the one to know for sure..

> This should be removed.. 

Please tell people to do so. Because when I tell people to update/kill old download links (or to stop spraying new soon-to-be-broken links around internet) it does appearently not work.

**Comment by Licho1** [comment]
Yeah its the current "portable" exe of zero-k ..
It should be put into destination folder, it does not ask because its already being prepared for steam distribution.. sigh..

**Comment by knorker** [comment]
just lol
