### ISSUE TITLE
(lobby) map downloads not working - System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#965]
http://zero-k.info/Forum/Thread/22137
> i cannot play a game and i cannot see a game in multiplayer

From de channel chatlog:

> giuseppe: hi  falls jemand hier ist hab ein problem download von maps bricht  einfach ab .kann mir weder ein spiel anschauen oder eins spielen.

-> Map downloads stop. He can neither spectate a match or play.

Restarting lobby """solved""" it.

06.03.2016 20:26:50: Closing current battle
06.03.2016 20:26:50: Closing current battle
06.03.2016 20:33:59: Joining battle 288
06.03.2016 20:34:01: Download started: Zero-K v1.4.3.1
06.03.2016 20:34:01: http://zk.repo.springrts.com/packages/d3f01fa1cd76ef767e062f667eb1e74f.sdp Completed - 213,05k
06.03.2016 20:34:06: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: Error downloading Zero-K v1.4.3.1: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: Error downloading Zero-K v1.4.3.1: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: Error downloading Zero-K v1.4.3.1: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:06: Error downloading Zero-K v1.4.3.1: System.IO.IOException: Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. ---> System.Net.Sockets.SocketException: Eine vorhandene Verbindung wurde vom Remotehost geschlossen
bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
bei System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
--- Ende der internen Ausnahmestapelüberwachung ---
bei System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
bei PlasmaDownloader.Packages.StreamExtension.ReadExactly(Stream stream, Byte[] buffer, Int32 offset, Int32 count, Int64& valueToIncrement)
bei PlasmaDownloader.Packages.PackageDownload.LoadFiles(SdpArchive fileList)
06.03.2016 20:34:48: Closing current battle
06.03.2016 20:34:48: Closing current battle

**Comment by Licho1** [comment]
This sounds like a network problem ...
Not much we can do about that...
Btw if you want I can give you steam version (working mostly on that now) to test stuff there instead.

**Comment by knorker** [comment]
Well, he could still chat so not sure if it is network problem.

But if it is a network problem:
Display a message/icon, so users knows what is going on?

**Comment by Licho1** [comment]
He could even download part of the mod but not all of it.. it should tell him that the download failed, its unexpected thing though..
Also with steam there isnt any download of mod..

**Comment by knorker** [comment]
just lol

**Comment by Licho1** [comment]
Cannot fix "An existing connection was forcibly closed by the remote host".

**Comment by knorker** [comment]
Instead of just stopping to function most programs display some error message or icon when something with network goes wrong.

https://www.iconfinder.com/search/?q=disconnect&price=free

**Comment by Licho1** [comment]
Yeah thats what happens here too, you have this bar at bottom that shows "download failed". What else do you suggest?

**Comment by knorker** [comment]
I suggested a network-failure-icon. Downloads can fail for many reasons. (full HDD etc)

If restarting the lobby is really what makes it functional again (and not just the time passed) then ideally lobby would somehow reset its stuff itself, without user turning it off & on.
