### ISSUE TITLE
(lobby) changed password does not update saved password

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#966]
I changed password under account details.

In settings - 'Lobby Password' I also entered the new password.

On every start lobby still has the old password filled in.

**Comment by knorker** [comment]
actually: Having the password/username under settings is strange.

The usual way is to have a checkbox in the login-dialog: 
[x] remember login data

**Comment by Licho1** [comment]
agreed
