### ISSUE TITLE
(website) better handling of non-downloadable maps

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#968]
There are hundreds of non-downloadables maps.
Peoplepersons like to dig in maplist and post "Look at this!" or "Why can this not be downloaded?"

There should be a note about this. Suggestion:

> **This map Is not downloadable. This map WILL never be downloadable. This map probally never WAS downloadable.**
Please do not spam the forum with comments about this map unless it is something genuinely interessting.
This entry exists because the system has picked it up when someone was hosting the map, perhaps for testing. Most likely this map exists nowhere else outside of the computer of its creator. There might be a released version of this map, but it is not this one.

**Comment by lhog** [comment]
Indeed. !map and !listmaps should filter such maps out. Maybe introduce !mapforce or something to override filtering (although I see no use case).

**Comment by knorker** [comment]
#968 = lobby
#969  = website

**Comment by sprunk** [comment]
the other way around
