### ISSUE TITLE
(lobby) errorspam when joining battleroom: error processing line JoinBattle

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#970]
when trying to join battleroom.
spam until the lobby window was completed covered with the message boxes.

![zkl join error](https://cloud.githubusercontent.com/assets/3044855/13637017/4c5e8d4a-e605-11e5-9cb8-62583d0bb167.png)

**Comment by Licho1** [comment]
yeah i did but 971 also got fixed meanwhile
