### ISSUE TITLE
(lobby) Login/Register dialog is not fixed size

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#971]
![zkl resizeable dialog](https://cloud.githubusercontent.com/assets/3044855/13637190/4a6ba6e8-e606-11e5-9b99-32366a2a4334.png)

**Comment by Licho1** [comment]
current dialog looks like this http://i.imgur.com/ZF1fZ8G.png

**Comment by knorker** [comment]
dl link?

**Comment by Licho1** [comment]
http://test.zero-k.info/Zero-K.exe but do not try yet, its in a state of mess atm, working on restyle
