### ISSUE TITLE
Show Kudos on unlock page and donator star tooltip

### ISSUE THREAD

**Issue by Skasi** [ZeroK-RTS/Zero-K-Infrastructure#972]
Players can no longer see how many Kudos they have on http://zero-k.info/

There used to be a number displayed in the bar where playername, clan, faction, planetwars info and the logout button were. Chances are a PW info removal also removed the Kudos number.

![](http://i.imgur.com/06YODV8.png)

**Comment by Licho1** [comment]
Kudos were removed on purpose from there..why did you readd them?

**Comment by sprunk** [comment]
It looked like they got accidentally removed alongside PW stuff like bombers. Why were they removed?

**Comment by sprunk** [comment]
Currently there is no place where you can see your kudos (not even on the page where you buy unlocks for kudos).

**Comment by sprunk** [comment]
https://github.com/ZeroK-RTS/Zero-K-Infrastructure/commit/6dde62df08140d07d083b4df93ceffd72280457e

**Comment by Licho1** [comment]
Idea was to give people donator stars, which, when you hover them, show actual kudos.
Also unspent kudos should be visible in unlocks section.

**Comment by Licho1** [comment]
I guess that my deletion was uncomplete (no proper stars) so your fix was good one.
