### ISSUE TITLE
(commanders) If a chasis is required then the player should be required to first unlock a chasis

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#973]
1) Acquire unlock points

2) Spend unlock points on modules

3) Can not configure a Commander because:
> You need to unlock some chassis before you can start customizing commander

4) All unlock points are already spent

To avoid this newbtrap it should not be possible to unlock modules until a chasis has been unlocked.

Modules that only work on certain chasis should not be unlockable until that chasis is unlocked.

(There might be text or guides that explain this stuff but it is better if no explaining is nessecary)

**Comment by GoogleFrog** [comment]
The entire module unlocking system is slated for removal.

**Comment by KingRaptor** [comment]
Unlocks removed.
