### ISSUE TITLE
(lobby) [Play on this map] -> "Unable to locate Autohost.." when not logged in

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#974]
1) Start lobby

2) Be not logged in

3) Browse maps, pick map, click "Play on this map"

4) 

> "Unable to locate Autohost for given gametype"
> ![play on this map unable to locate autohost](https://cloud.githubusercontent.com/assets/3044855/13719300/04b654b4-e7f4-11e5-96ac-50bbabbd562a.png)

It should tell player to log in, in more nicer way. Or start a singleplayer battle on that map.

**Comment by Licho1** [comment]
old lobby and zkls
