### ISSUE TITLE
current ZKL on linuxmint 17.1

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#978]
cannot install ZeroKLobby
> Unhandled Exception:
> System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
> File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
> [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
> File name: 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
mono --version
3.2.8

**Comment by db81** [comment]
Try ```apt-get install mono-complete```.

**Comment by Licho1** [comment]
yeah this is not a complete mono, you need windows.forms section of it too

**Comment by Jamanno** [comment]
yeah that worked... maybe it should be as info on wiki or download page
