### ISSUE TITLE
(chesti) multiple login dialogs appear during registration

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#982]
In the process of registering an account multiple log-in dialogs popped up with some seconds delay inbetween.
Note in the picture the most bottom dialog is at 'Register' tab while the popped up dialogs are at 'Login' tab.

![four logins after ban](https://cloud.githubusercontent.com/assets/3044855/13730051/72694470-e944-11e5-9284-af265c0cc9a8.png)

**Comment by Licho1** [comment]
fixed
