### ISSUE TITLE
(lobby) more meaningful text for votes, better autohosts name

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#984]
> Springiee Poll: Do you want to join Hydrogen? [!y=1/23, !n=9/23]

The polls in lobby are bad because:
-> no idea what a "Hydrogen" is. (Is it a clan I can join? Is an autohost? Small teams? FFA? )
-> no idea what will happen if vote succeds (all get moved? all who voted 'yes' get moved?)

Better texts would be like:

> Poll: Do you want to distribute players in this battleroom into two smaller battlerooms?

or

> Poll: Do you want to move yourself to the FFA room?

**Comment by Licho1** [comment]
fixed by obsoletion
