### ISSUE TITLE
let players announce their games

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#986]
add an option to announce a game which you have started. (should be forbidden if more than 6 players around, not specs)

**Comment by Licho1** [comment]
what do you mean "announce" ?

**Comment by knorker** [comment]
SomePlayer: !promote

triggers channel message:
_Why morph a peewee when you can morph the Commander? SomePlayer needs [4] more players on map [WinniePooh]! Join now!_

**Comment by Licho1** [comment]
That does sound a bit silly... they could as well press ctrl+v .. and spaem less

**Comment by sprunk** [comment]
Yeah posting a message in the chat is something any player can do, makes no sense to involve springie
