### ISSUE TITLE
Locked out of ZK client and site

### ISSUE THREAD

**Issue by SnuggleBass** [ZeroK-RTS/Zero-K-Infrastructure#995]
Hey there,

I've been locked out of ZK for maybe 5-6 days now? I lost access just prior to the 2v2 tourney (sorry anarchid). I assumed at the time that the server was down, but then SF333 posted videos on youtube from the tournament that I thought would be canceled. 

http://i.imgur.com/J1hQha9.png

http://i.imgur.com/zSeVR8R.png

This is the only site that doesn't work, in addition to the client. I've used the internet extensively in the meantime and that is not the issue. SF333 says I'm not banned, and there's been a lower turn out recently, suggesting I might not be the only one affected. I can't think of anything on my end that would have changed my access to ZK, though admittedly, I leave all that stuff to a housemate so it's possible they did something without me knowing. 

Thanks.

**Comment by db81** [comment]
@wagonrepairer had a similar problem and it turned out his antivirus or firewall blocked zero-k.info, so check for that. Maybe we got blacklisted somewhere, zero-k installer tends to trigger false positives.

**Comment by SnuggleBass** [comment]
Thanks. I'll check it out once I've got time later today.

**Comment by Aquanim** [comment]
I had the same problem at the same time. I believe it was caused by some permutation of DNS issues since I solved the problem by using 8.8.8.8 (the google dns) as a secondary dns thingy.

@SnuggleBass is your isp TPG by any chance?

**Comment by SnuggleBass** [comment]
That's too many aquanims for me. I'll need to refer your post to my tech guy when he gets home. If you had the same problem at the same time, I'm pretty happy assuming that you've got the right of it and once someone capable of understanding wtf your acronym tech speak means is here, the problem will be resolved in short order. 

Much obliged <3

**Comment by Licho1** [comment]
Saktoth also had a similar problem. Switching DNS server to 8.8.8.8 fixed it to him. I have no idea what causes this. DNS was timing out..

**Comment by Anarchid** [comment]
> Last update of WHOIS database: 2016-04-06T16:48:50Z <<<

Date seems to coincide?

**Comment by Licho1** [comment]
For some reason DNS times out in certain places, Pakistan, Thailand and Australia (some providers)
https://www.whatsmydns.net/#A/zero-k.info

DNS health check indicates DNS records are correct. Do you have any other idea?

**Comment by Licho1** [comment]
No blacklist for email .. all is ok.. sigh..

**Comment by Aquanim** [comment]
I'm afraid I don't really know all that much about how the DNS system works, beyond the basic principles. It's possible that given time the problem will correct itself.

**Comment by Anarchid** [comment]
The disruption of communications can only mean one thing, invasion.

**Comment by Licho1** [comment]
Please try (in cmd) to ping or traceroute our dns servers.

tracert ns.web4u.cz
tracert ns2.web4u.cz

Problem could be that the name servers aren't accessible and domain isn't cached in your DNS chain. 
(And no domain wasnt altered/renewed for many many months).

**Comment by SnuggleBass** [comment]
I woke up this morning hungover, but also with ZK working. Don't recall talking to by guy about it (though admittedly it could have happened?), I assume something changed server side? Either way, it's a big win, thank-you.

**Comment by sprunk** [comment]
>I woke up this morning hungover, but also with ZK working.

Now we know what to do when server breaks!
