### ISSUE TITLE
(site) test.zero-k.info gets overwritten, breaking download link to test-lobby

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#996]
(No idea how relevant this is with the various lobby versions and downloads)

Appearently on http://test.zero-k.info/ the download page is meant to offer a test-version of lobby.
However it offers the same lobby-version as normal site because the test-site DB gets overwritten sometimes.

http://zero-k.info/Forum/Thread/21049?postID=151941#151941

> Test version of lobby can be downloaded from test site.
> There is a test site:
> http://test.zero-k.info/
> and test lobby here:
> http://test.zero-k.info/lobby/Zero-K.exe

http://zero-k.info/Forum/Thread/21049?postID=151987#151987

> The download page of http://test.zero-k.info/ does not give that downloadlink.
> It points to normal downloads.. 

http://zero-k.info/Forum/Post/151989#151989

>  Fixed wiki there, but it will get overwritten (from time to time test site DB is cloned from real one) 

This overwritting seems to have happend again since then, because http://test.zero-k.info/Wiki/Download does not link to test-lobby-download anymore.

**Comment by Licho1** [comment]
Hmm not sure how to fix that, since its based on wiki and wiki is copied from live. I guess its best to just use manual link for download or just post the http://test.zero-k.info/lobby/Zero-K.exe  link into some dev wiki page/forum?

**Comment by sprunk** [comment]
Make Downloads a hardcoded page? It doesn't need to be wiki because random people don't have much to add there.

**Comment by Licho1** [comment]
does not feel right just for the purpose of test downloads. Instead maybe i can add some sort of download tag into wiki - which translates to correct url. Or even automated URL translator zero-k.info -> test.zero-k.info for test site (that might be simplest, its in one spot in wiki parser)

**Comment by knorker** [comment]
again appearently untested updates broke lobby.
http://zero-k.info/Forum/Thread/22683
http://zero-k.info/Forum/Thread/22683?postID=160355#160355

**Comment by Licho1** [comment]
fixed by automated download on dl page + fix in wiki
