### ISSUE TITLE
(site) replays older than circa Jan 2016 are not downloadable

### ISSUE THREAD

**Issue by knorker** [ZeroK-RTS/Zero-K-Infrastructure#997]
Some examples:
http://zero-k.info/Forum/Thread/22276

http://zero-k.info/Battles/Detail/389066#149070
>  I think old replays were moved to a separate drive, should look into symlinking them or something.

**Comment by Licho1** [comment]
They are moved to D: drive where there is filesystem compression. Logic needs to be changed to search all possible places for them.

**Comment by db81** [comment]
This looks trivial to fix, just add "d:\demos" and "d:\demos-server" to https://github.com/ZeroK-RTS/Zero-K-Infrastructure/blob/master/Zero-K.info/Controllers/ReplaysController.cs#L19.

**Comment by Licho1** [comment]
fixed by ikinz

**Comment by Anarchid** [comment]
NB: fix is untested, and both that and the PR openly mentions that being blind.

**Comment by Licho1** [comment]
You can test it on test site, it looked correct.

**Comment by db81** [comment]
Yeah it works on test.
