### ISSUE TITLE
[minor]Neptunium uses \n in Welcome message.

### ISSUE THREAD

**Issue by DeinFreund** [ZeroK-RTS/Zero-K-Infrastructure#998]
> Neptunium Hi DeinFreund (rights:2), welcome to Springie 1.3.2.112, automated host. For help say !help\n>>> No Trolling!! <<< 

It should probably send two messages instead.

**Comment by sprunk** [comment]
Looks like the config currently doesn't have a newline character but a backslash character and an n character. Changing the config should do the trick but I have no control over that.
