### ISSUE TITLE
not possible to votemap on serious host 

### ISSUE THREAD

**Issue by Jamanno** [ZeroK-RTS/Zero-K-Infrastructure#999]
noone can vote for map on serious host.
It is not good when host decides what map... you should can do "!votemap red comet" 
all the time.
Now you can do only !votemap and it random picks some...
Why it cannot be the same like on springiee?
Svatopluk said he is getting "no rights to execute votemap"

**Comment by sprunk** [comment]
fixed already, wait till deploy
